### ISSUE TITLE
API changes report for Neo4j kernel

### ISSUE THREAD

**Issue by lvc** [neo4j/neo4j#10447]
Hi,

I'd like to share report on API changes and backward compatibility for the Neo4j kernel library: https://abi-laboratory.pro/java/tracker/timeline/neo4j-kernel/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Hope it will be helpful for users and maintainers of the library.

Please review the report and request any other Neo4j modules to be included to the tracker if you are interested.

Thank you.

![neo4j-kernel-1](https://user-images.githubusercontent.com/1517837/32821249-71f81652-c9e3-11e7-9ae5-62d24f0d2d6d.png)

![neo4j-kernel-2](https://user-images.githubusercontent.com/1517837/32821248-71daf356-c9e3-11e7-8e69-071aed70be18.png)

**Comment by chrisvest** [comment]
We are already tracking API compatibility with clirr (and investigating revapi), which integrates with our existing Maven based build setup. Because of this integration, I don't think there are compelling arguments for us to use japi-tracker instead. In case you are using this data for research, we are not considering `org.neo4j.storageengine` to be public API, so the reports in those packages are false positives. Generally, if it's not mentioned in our javadocs https://neo4j.com/docs/java-reference/current/javadocs/ then we don't consider it public API.

**Comment by lvc** [comment]
The report has been fixed according to docs. Non-public packages have been excluded from the report: https://abi-laboratory.pro/java/tracker/timeline/neo4j-kernel/

Thank you.
