### ISSUE TITLE
Doc error on https://boltprotocol.org/v1/

### ISSUE THREAD

**Issue by zorgnax** [neo4j/neo4j#10446]
On the page at https://boltprotocol.org/v1/, it provides an example for sending an init message to bolt like this:

```
Client: INIT "MyClient/1.0" { "scheme": "basic", "principal": "neo4j", "credentials": "secret"}

  00 40 B1 01  8C 4D 79 43  6C 69 65 6E  74 2F 31 2E
  30 A3 86 73  63 68 65 6D  65 85 62 61  73 69 63 89
  70 72 69 6E  63 69 70 61  6C 85 6E 65  6F 34 6A 8B
  63 72 65 64  65 6E 74 69  61 6C 73 86  73 65 63 72
  65 74 00 00
```

shouldn't that third byte be B2 not B1 since it is a structure containing two arguments? or am I following this wrong?

**Comment by technige** [comment]
Hi @zorgnax. Thanks for pointing this out but unfortuantely _boltprotocol.org_ is a fan site rather than an official Neo4j website. To that end, we can neither vouch for the accuracy of the information there nor make changes to fix any problems.

Your best bet for low-level protocol details is the demo driver in the boltkit repository:
https://github.com/neo4j-contrib/boltkit/blob/master/boltkit/driver.py

Obviously the source code of the official drivers may also be useful.
