### ISSUE TITLE
GoogleVis or GGVis, build graphs with different database structure

### ISSUE THREAD

**Issue by johnpatil** [neo4j/neo4j#10696]
I'm a statistician in pharmaceutical industry. In my free-time I'm trying to learn some Shiny R programming and I would like to build something on some clinical research data (the main reason is that I understand the domain and I have a lot of data).

We usually work on **[SAS](https://tekslate.com/sas-clinical-training/)** datasets and I managed to import them in R as dataframe.

I'm in front of a limit and really don't know how to get rid of it, the dataset structure.

The usual dataset structure I have is this one:

PT   VISIT    VAR1
001  Visit 1  100
001  Visit 2  120
002  Visit 1  110
002  Visit 2  90
I managed to setup the code to run my first linechart but I noticed that both GGVIS and GOOGLEVIS are meant to work on a database of this kind

VISIT    PT001  PT002
Visit 1  100    110
Visit 2  120    90
And this is more than a problem to me, because I don't want to transpose all the datasets and also I don't want to create one variable for each patients because they are usually dinamic (the number of patients usually changes over time).

Do you know if there is a way to handle my usual dataset structure, grouping on the value of the Patient variable?

I would include my code but it is pretty basic and totally useless in this case, but if you want, just ask and I will include it.

Thanks in Advance For your answer
Johny

**Comment by craigtaverner** [comment]
Hi @johnpatil. Sorry this issue has not received a response. I think it is because the github issues are usually where people report problems with the database, and questions like yours, data modeling questions, are usually handled in the community forums. Recently we created a new forum for community discussion, and I welcome you to ask any data modeling questions there. 

See https://community.neo4j.com/
