### ISSUE TITLE
bug: order of optional match's affecting result

### ISSUE THREAD

**Issue by jorroll** [neo4j/neo4j#10717]
## Bug Report

It is my understanding that 
```
MATCH (a)
OPTIONAL MATCH (a)-[:A]->(b:Something)
OPTIONAL MATCH (a)-[:B]->(c:SomethingElse)
RETURN b, c
```
and
```
MATCH (a)
OPTIONAL MATCH (a)-[:B]->(c:SomethingElse)
OPTIONAL MATCH (a)-[:A]->(b:Something)
RETURN b, c
```
should return the same result (i.e. the order of `OPTIONAL MATCH` clauses is irrelevant). For a specific query in my database, the order of the `OPTIONAL MATCH` clauses affects the return.

- Neo4j version: Community 3.3.1 & 3.1.5
- Operating system: Ubuntu 16.04
- API/Driver: The built-in web app running over bolt

### Expected Behavior

That these two queries return the same result:
```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(p)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(b)
RETURN l
```
and
```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(b)   // <- CHANGE
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(p)   // <- CHANGE
RETURN l
```
Return the same result

### Actual behavior

This version of the query returns ```(:Current:`List::Current`:List {uuid: '03ecd5ba-912a-442a-96b9-897af10fb2f2'})``` (which I think is correct)
```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(p)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(b)
RETURN l
```
and this version of the query returns `null` (which I think is incorrect)
```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(b)   // <- CHANGE
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(p)   // <- CHANGE
RETURN l
```

### To recreate:

1. Create a new 3.3.1 database.
2. Add constraints:
```
CREATE CONSTRAINT ON (l:List) ASSERT l.uuid IS UNIQUE
CREATE CONSTRAINT ON (p:Person) ASSERT p.uuid IS UNIQUE
CREATE CONSTRAINT ON (o:Owner) ASSERT o.uuid IS UNIQUE
```
3. Create pattern:
```
CREATE (:Current:`Person::Current`:Person {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})<-[:OWNER_CURRENT]-(:Current:`Owner::Current`:Owner {uuid: 'dd51fc3b-3476-4b73-b136-4864a3ef58f9'})<-[:OWNER_CURRENT]-(:Current:`List::Current`:List {uuid: '03ecd5ba-912a-442a-96b9-897af10fb2f2'})
```
4. Run the queries:
```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(p)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(b)
RETURN l
```
Returns ```(:Current:`List::Current`:List {uuid: '03ecd5ba-912a-442a-96b9-897af10fb2f2'})```
```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(b)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (l:`List::Current`)-[:OWNER_CURRENT*2]->(p)
RETURN l
```
Returns `null`

### Additional Information

I also experience into this problem using Neo4j Community 3.1.5.

**Comment by InverseFalcon** [comment]
Okay, I see what's going on. This isn't a bug. I'll explain.

The problem is in your last set of 3 OPTIONAL MATCHes. Note that you are using the same variable, `l` for each of these, and that this is the first introduction of the variable in the query.

If the first OPTIONAL MATCH succeeds, then `l` will be bound to a node, and it will continue to be reused in the subsequent OPTIONAL MATCHes (which won't actually be useful at all, since none of the OPTIONAL MATCHes introduce any additional variables, they're all effectively no-op). Whichever node `l` was bound to from that first OPTIONAL MATCH will be the node returned.

However, if the first OPTIONAL MATCH fails, then `l` is bound to null, which automatically means the subsequent OPTIONAL MATCHes will fail (null can't be a node), so the null value of `l` will be returned at the end. 

Going back to your original example, it is true that these two are equivalent, and that the order of the optional matches doesn't matter:

```
MATCH (a)
OPTIONAL MATCH (a)-[:A]->(b:Something)
OPTIONAL MATCH (a)-[:B]->(c:SomethingElse)
RETURN b, c
```

and 

```
MATCH (a)
OPTIONAL MATCH (a)-[:B]->(c:SomethingElse)
OPTIONAL MATCH (a)-[:A]->(b:Something)
RETURN b, c
```

However, this only works because `a` has already been bound to a variable from the first match. As long as `a` exists, both OPTIONAL MATCHes can execute, and the result of either of them does not affect the other.

Your concrete examples don't follow this pattern. An equivalent query for that might be something like:

```
MATCH (a)
OPTIONAL MATCH (a)-[:A]->(b:Something)
OPTIONAL MATCH (a)-[:B]->(b:Something)
RETURN b
```

In this one, order is important and definitely matters. 

Why does it matter? Because you're using the same variable `b` in both of them, and the first usage of the variable is in these OPTIONAL MATCHes. If there are :A relationships in graph (going to a :Something node), but no :B relationships in the graph to a :Something node, that's fine. The first OPTIONAL MATCH will succeed, bind `b` to the node that matches, and the next OPTIONAL MATCH will fail (which is fine because it's effectively a no-op since no new variables introduced), and the `b` from the first OPTIONAL MATCH will be returned.

But if the order is flipped, there is no `b` node which fits the pattern (no :B relationships exist), so `b` is null. That null value gets used in the subsequent OPTIONAL MATCH, which fails (though this doesn't matter anyway, same result whether or not that OPTIONAL MATCH is in the query), and the null value for `b` is returned.

Close if you are satisfied, otherwise I can clarify further if needed.

**Comment by jorroll** [comment]
Oooo, _great_ explanation @InverseFalcon!!!

So, if I understand you correctly...

### Example 1

Updating my query like so is a solution to the issue:

```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (list_1:`List::Current`)-[:OWNER_CURRENT*2]->(p)
OPTIONAL MATCH (list_2:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (list_3:`List::Current`)-[:OWNER_CURRENT*2]->(b)
RETURN list_1, list_2, list_3
```

This is fine, and I can certainly work with that, but _ideally_ `list_1`, `list_2`, `list_3` would accumulate and return in just a `list` variable. ~~I imagine one way of accomplish this would be to use an apoc procedure like `apoc.coll.union(apoc.coll.union(list_1, list_2), list_3) as list`~~  In testing, this method doesn't work because `list_1` etc are not `List` objects (and `apoc.coll.union` accept list objects). I could also handle it in my app, of course.

Is there a better method?

### Example 2

What if ```(list:`List::Current`)-[:OWNER_CURRENT*2]->(b)``` exists, and ```(list:`List::Current`)-[:OWNER_CURRENT*2]->(o)``` exists, and ```(list:`List::Current`)-[:OWNER_CURRENT*2]->(p)``` exists. 

Previously, I thought that each query would accumulate in `list`. But now it's sounding like `list` will be set after the first `OPTIONAL MATCH`, and then subsequent optional matches would try and find a path from that _specific_ set of `list` to `o` or `b` (and, since a path would not exist, the subsequent `OPTIONAL` will return `null`). This will result in only the first `OPTIONAL MATCH` having a return. Is this understanding correct?

```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
OPTIONAL MATCH (list:`List::Current`)-[:OWNER_CURRENT*2]->(p)
OPTIONAL MATCH (list:`List::Current`)-[:OWNER_CURRENT*2]->(o)
OPTIONAL MATCH (list:`List::Current`)-[:OWNER_CURRENT*2]->(b)
RETURN list
```

### Example 3

More generally, it sounds like, once a variable is bound, it is immutable. Is this correct? If so, this helps to clarify a difference between `MATCH (a)<--(b), (a)<--(c)` and `MATCH (a)<--(b) MATCH (a)<--(c)`.

I'm also _guessing_ that, if a variable is bound to an object (like a node), the _object_ could still be mutated (such as with a `SET` clause) and accessing that object within the variable would reflect that change. Though I can't immediately think of an example demonstrating this concept.

### Example 4

Based on my understanding, _this_ part of my query will work, but the order of the `OPTIONAL MATCH` clauses is important (though actually, if my _previous_ understanding of variables & `OPTIONAL` was correct, this wouldn't have worked 😖 )
```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH b, o, p
```
This is because `p` will be bound in the first `MATCH` and used in the first `OPTIONAL MATCH`. The first `OPTIONAL` will bind `o`. If `o` is `null`, the second `OPTIONAL` will fail, as it should. If `o` isn't `null`, the second will run and may or may not return any `b`.

## Finally

Before creating this issue, I searched through the Neo4j developer manual for information relating to `OPTIONAL MATCH` clauses, as well as variables. My guess was that, if this was user error, the issue was probably with my understanding of variables (looks like I was correct). I didn't find much information in the developer manual about variables (entries I found are: [3.2.3 Variables](https://neo4j.com/docs/developer-manual/current/cypher/syntax/variables/), [3.3.1 MATCH](https://neo4j.com/docs/developer-manual/current/cypher/clauses/match/#match-on-rel-type-use-variable), a sampling of other, _small_, references when searching for "variables"). Maybe there's more in-depth information I didn't find, but this discussion has already been _super_ helpful for me.

If I clean this issue up a bit. For example, changing ```(l:`List::Current`)-[:OWNER_CURRENT*2]->(b)``` to ```(l:List)-[:OWNER]->(b)``` and ```(p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})``` to ```(p:Person {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})```, etc. Is there somewhere I could submit a PR to add an example like this to the variables section of the developer manual? It seems like a great example as it touches upon a number of concepts (though I am biased, since it's definitely a great example for _me!_).

Thank you so much!

**Comment by InverseFalcon** [comment]
### For Example 1

That's almost correct, though that return would get you all possible combinations of list_1 matches and list_2 matches and list_3 matches. Also, using that variable name probably isn't such a good idea, since a node variable is not a list, you would need a `collect()` in there for it to be a list/collection.

Since you're using the same pattern to match from all 3 of those node variables, it's probably easiest to get all of those nodes referenced by a single variable, then perform the match on all of them. We can do that by combining the collections of all `o` and `b` and add in `p`, then we'll unwind all of them under the same variable and match from that.

```
MATCH (p:`Current`:`Person::Current`:`Person` {uuid: '49bf9a34-2480-42d4-86db-e7ad492b6286'})
OPTIONAL MATCH (o:Current)-[:STAFF_ACCOUNT_CURRENT*2]->(p)
OPTIONAL MATCH (b:Current)-[:BRANCH_CURRENT*]->(o)
WITH p + collect(o) + collect(b) as nodes
UNWIND nodes as node
WITH distinct node
OPTIONAL MATCH (list:`List::Current`)-[:OWNER_CURRENT*2]->(node)
RETURN list
```

### For Example 2

You're correct that your previous approach will not accumulate the results. 

OPTIONAL MATCH only has meaning when new variables are being introduced. If you're using previously bound variables and not introducing any new ones, then your OPTIONAL MATCH should never change your results, as OPTIONAL MATCH never filters out results the way MATCH does when the match isn't found (it only binds any newly-introduced variables to null). 

When the second OPTIONAL MATCH is reached, `list` is already bound to either a node (if the previous OPTIONAL MATCH succeeded) or a null value, so whatever `list` was bound to will be used in subsequent matches or optional matches.

### For Example 3

The results of matches or optional matches are streams of records, with each part of those records addressable by a variable. Or put another way, a stream of result rows with column variables. So After the first 3 lines, you have a stream of result records with variables `a`, `b`, and `c`. 

Typically at this point you would perform additional filtering, either through using WHERE clauses or additional MATCHes, constraining the stream of records to only those where the match exists, and possibly introducing new variables into your result stream (possibly increasing the number of result records, but never introducing any new values for previously bound variables). Some exceptions are UNION and UNION ALL. 

Looking at the differences between these two queries:

`MATCH (a)<--(b), (a)<--(c)` and `MATCH (a)<--(b) MATCH (a)<--(c)`
The main difference is actually on relationship uniqueness in a match. Cypher uses RELATIONSHIP_PATH uniqueness: a specific relationship can only occur once in a path within a MATCH. Without this restriction, more complex pattern matches (like variable-length relationship paths using -[*]->) could fall into an infinite loop if there's a loop in the graph, as the same relationships would be traversed over and over.

This means that in the first query, the relationships represented cannot refer to the same one, there must be at least two separate relationships to `a` for the match to succeed (whether they're from the same node or different nodes). If there are only two nodes in the graph and only a single relationship between them, then the first match won't return anything; the relationship used in the first pattern can't be used for the second. However, in the second query, given that same 2-node 1-relationship graph, the query will succeed. The second MATCH is independent from the first, so the exact same relationship and start node would be reused, and if queried further you would see that `b` = `c`.

### For Example 4

Your analysis is correct, this part of your query is fine.

**Comment by Lojjs** [comment]
@thefliik Like @InverseFalcon has explained above this is not a bug. However it is a tricky case so we will try to add some more documentation around it in the Cypher docs (https://neo4j.com/docs/developer-manual/current/cypher/)

**Comment by jorroll** [comment]
@InverseFalcon & @Lojjs thank you!!!

**Comment by jorroll** [comment]
Actually, I'm not sure if you want this closed or not. Feel free to close if you do.

**Comment by Lojjs** [comment]
@thefliik I will keep it open until we have updated the docs. Thanks for reporting.

**Comment by Lojjs** [comment]
@thefliik As part of our effort to clean up old Github issues, I'll close this one now since we have separate tracking for the documentation card and you seemed happy with the explanation above.

**Comment by Lojjs** [comment]
@thefliik As part of our effort to clean up old Github issues, I'll close this one now since we have separate tracking for the documentation card and you seemed happy with the explanation above.
