### ISSUE TITLE
Expose Hazelcast's setPublicAddress settings

### ISSUE THREAD

**Issue by frant-hartm** [neo4j/neo4j#11018]
## Cannot setup causal cluster where nodes are behind nat or similar network settings

In a deployment where node's public ip address doesn't match any of the machine interfaces it is not possible to setup causal cluster because hazelcast erroneously connects to itself.

Seems like discovery advertised address is not used to set Hazelcast's setPublicAddress settings
http://docs.hazelcast.org/docs/latest-development/manual/html/Setting_Up_Clusters/Other_Network_Configurations.html

**Neo4j Version:** 3.3.2
**Operating System:** CentOS 7.2
**API:** Docker

### Steps to reproduce

3 hosts with
public-ip-1, public-ip-2, public-ip-3

Neo4j running inside docker, the network type is not host, so the container has different ip address.

Setup CC with following:
```
2018-02-14 13:09:24.383+0000 INFO  My connection info: [
	Discovery:   listen=0.0.0.0:5000, advertised=public-ip-1:5000,
	Transaction: listen=0.0.0.0:6000, advertised=public-ip-1:6000, 
	Raft:        listen=0.0.0.0:7000, advertised=public-ip-1:7000, 
	Client Connector Addresses: bolt://public-ip-1:7687,http://public-ip-1:7474,https://public-ip-1:7473
]
2018-02-14 13:09:24.384+0000 INFO  Discovering cluster with initial members: [public-ip-1, public-ip-2:5000, public-ip-3:5000]
```

### Expected behavior
Advertised discovery address should be used for hazelcast setPublicAddress.

### Actual behavior

Getting this exception and startup fails:

```
Exception in thread "hz._hzInstance_1_dev.cached.thread-1" java.lang.RuntimeException: Connecting to self! [172.21.0.2]:5000
at com.hazelcast.nio.NodeIOService.shouldConnectTo(NodeIOService.java:187)
at com.hazelcast.nio.tcp.TcpIpConnectionManager.getOrConnect(TcpIpConnectionManager.java:401)
at com.hazelcast.nio.tcp.TcpIpConnectionManager.getOrConnect(TcpIpConnectionManager.java:393)
at com.hazelcast.nio.NodeIOService$ReconnectionTask.run(NodeIOService.java:388)
at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76)
at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92)
```

**Comment by IkKan** [comment]
+1 

Having the same issue with docker and causal cluster setup

**Comment by martinfurmanski** [comment]
We have looked into these issues before, but not really found a good solution using hazelcast. I will try to bump the priority of finding another solution though. We have an old PR which we couldn't merge because it was causing other issues: https://github.com/neo4j/neo4j/pull/10017

**Comment by eastlondoner** [comment]
I have found a workaround for this _if you are able to set up dns entries_ for each of your cluster members.

1) set up DNS A records to give each causal cluster member a unique hostname:

```
core1.mydomain.com -> public-ip-1
core2.mydomain.com -> public-ip-2
core3.mydomain.com -> public-ip-3
```

2) On each member change the advertised address and discovery members to use the member's hostname:

```
dbms.connectors.default_advertised_address=core1.mydomain.com
causal_clustering.initial_discovery_members=core1.mydomain.com:5000,core2.mydomain.com:5000,core3.mydomain.com:5000
```

3) On each causal cluster member modify the `/etc/hosts` file so the advertised name points to the host's private ip address (generally `hostname -i` will return this but you may need to hard-code it):

```
sudo echo "$(hostname -i)       core1.domain.com" >> /etc/hosts
```

Now Hazelcast will propagate hostnames instead of ip addresses and each member is able to recognise which is its own hostname (because of the `/etc/hosts` change).

**Comment by moxious** [comment]
I have run into the same issue, but found a similar workaround to @eastlondoner 's.

Similar because it relies on DNS.  I have found that the node doesn't have to have `dbms.connectors.default_advertised_address` attached to any network interface.  The node will effectively parrot whatever it's told here, even if it can't prove it owns that address.

As a result, my work-around is to make `dbms.connectors.default_advertised_address` the externally valid IP address, and then use the DNS entries for initial cluster members.  I tend to use private DNS inside of cloud environments, so a config looks something like this:

```
dbms.connectors.default_advertised_address=1.2.3.4
causal_clustering.initial_discovery_members=node0.neo4j:5000,node1.neo4j:5000,node2.neo4j:5000
```

Note that because default_advertised_address is provided to clients and drivers, when using private DNS one **cannot** set the default_advertised_address to a DNS entry as @eastlondoner  did, since that isn't routable externally.

So since either will work, it will I suppose tend to depend on whether your DNS is public or private.

**Comment by RagnarW** [comment]
Closing due to unsupported version
