### ISSUE TITLE
Upgrade path from the latest Neo4J 2.0.x to 3.x is not supported

### ISSUE THREAD

**Issue by deemeetree** [neo4j/neo4j#11057]
### Bug description

I discovered that the upgrade path from the latest 2.0.x to 3.x is not supported even though it is claimed otherwise on http://neo4j.com/docs/operations-manual/3.3/upgrade/#upgrade-planning

**Neo4j Version:** 2.0.4 
**Operating System:** Mac OS X  10.12.6

### Steps to reproduce
1. Download neo4j community 2.0.4 
2. Create a database
3. Download neo4j community 3.3.3
4. Follow the procedures outlined http://neo4j.com/docs/operations-manual/3.3/upgrade/#upgrade-planning

### Expected behavior
The upgrade should happen smoothly

### Actual behavior
1. Settings migration tool doesn't run properly unless Java 1.8 is installed
2. Settings migration tool creates incompatible settings in the conf file and even if those are deleted the fact that it creates an outdated settings file breaks everything. So the settings have to be transferred manually despite what the upgrade guide says. There's the same problem for 2.3.8 version it's not only the 2.0.x issue.
3. The database will not be imported from 2.0.4 because the storage 0.A.1 is not compatible with 0.A.8 (error message). So one has to upgrade the DB to 2.3.8 first and only then upgrade it to 3.3.3 using the neo4j-admin import tool as outlined in the upgrade guide.

The complete upgrade process (what works and what doesn't) is described here: https://github.com/noduslabs/infranodus/wiki/Upgrading-Your-Neo4J-Database-from-2.x-to-3.x

**Comment by chrisvest** [comment]
Hi @deemeetree. The manual page you link to says that upgrade from _2.3.latest_ is supported, not _2.0.x_. The upgrade document it links to is wrong in stating that this is possible. So "The database will not be imported from 2.0.4 because the storage 0.A.1 is not compatible with 0.A.8 (error message). So one has to upgrade the DB to 2.3.8 first and only then upgrade it to 3.3.3 using the neo4j-admin import tool as outlined in the upgrade guide." is expected behaviour, and how you do this upgrade.

The `config-migrator` is part of the 3.x software package, so that's why it requires Java 8.

It would be good if you could open another issue specifically about how the config-migrator produces broken settings. It shouldn't do that.
