### ISSUE TITLE
webadmin.js doesn't work behind proxy

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#112]
@shining4u: 'Description:
Hi, I'm running neo4j server on 7474 port and apache on 80 port.
I set proxy setting to expose neo4j server with url, "http://domain/neo4j"
Other things seem to works fine but webadmin.

When I open the url "http://domain/neo4j", it runs following steps.
1. GET /neo4j/webadmin/
2. GET /neo4j/webadmin/css/style.css
3. GET /neo4j/webadmin/js/require.js
4. GET /neo4j/webadmin/js/webadmin.js
5. GET /neo4j/webadmin/js/lib/arbor.js
6. GET /?_=1338775347645
...
And on step 6, it should be GET "/neo4j/?_=1338775347645", NOT "/?_=1338775347645"
I guess, that's why webadmin doesn't work properly.

Here is my running environment:

Neo4j version : Neo4j - Graph Database Kernel 1.7-SNAPSHOT (revision: jenkins-community-1418)

Settings on apache,

[Location /neo4j]
        # Proxy to localhost:7474
        ProxyPass http://localhost:7474
        proxyPassReverse http://localhost:7474

```
    # Substitutes
    AddOutputFilterByType SUBSTITUTE application/json
    AddOutputFilterByType SUBSTITUTE text/html
    AddOutputFilterByType SUBSTITUTE */*
    Substitute "s|localhost:7474|<DOMAIN>/neo4j|n"

    # Authentication
    AuthType Basic
    AuthName "Neo4j"
    AuthUserFile /var/lib/neo4j/conf/.htpasswd
    Require valid-user
```

[/Location]'

**Comment by dellelce** [comment]
Why was this closed? 3 Years later I cannot find anyway to disable the redirect... wasn't the best practice to not put the full url in everywhere? Manipulating the headers to "trick" neo4j is a "kludge" / "worst" workaround. Hopefully I am missing something from the documentation.

**Comment by chrisvest** [comment]
Probably because the webadmin isn't part of the product anymore.

**Comment by jakewins** [comment]
@dellelce like @chrisvest; and to the point that the code discussed above no longer is in use at all. Eg: this bug does not exist anymore, because the code that caused it has been removed; this is why the ticket was closed.

However - that is not to say the new code base does not suffer from a similar problem. If you are having an issue combining proxying and the Neo4j Browser, consider opening a ticket on the Browser issue tracker here: https://github.com/neo4j/neo4j-browser
