### ISSUE TITLE
set password twice while creating new graph/database

### ISSUE THREAD

**Issue by kdwykleingeld** [neo4j/neo4j#11406]
When you create a new database using Neo4j Desktop (3.3.4 in my case) you must set a password.

Since you only have to enter the password once there is a possibility for typos / mistakes.

I would suggest that the password must be entered twice to prevent this.

Regards Koen

**Comment by oskarhane** [comment]
Since you have full control over the local database and can reset the password at any time I don't think it's necessary.
That being said, it's something people are used to, so we might consider that in coming versions.
However, since this issue is opened in the neo4j repo rather than https://github.com/neo4j-apps/neo4j-desktop I'm going to close this.
If you want to track the state of this I suggest you open a new issue in the repo I linked to above.
