### ISSUE TITLE
Cypher Querry (Problem) for relationship

### ISSUE THREAD

**Issue by eayan** [neo4j/neo4j#11535]
Hi,

I am just trying to use cypher query to visualize existent relationship but continuously have "error" message. Can someone look/check up my query?

![selection_054](https://user-images.githubusercontent.com/5304822/38684921-1080df8c-3e71-11e8-9e82-4a4871aa4281.png)

![selection_055](https://user-images.githubusercontent.com/5304822/38684928-16fbfdf6-3e71-11e8-9886-832ac583cd7e.png)

Best...
Erdal Ayan, M.A.-M.Sc.

**Comment by Lojjs** [comment]
@eayan Which version of Neo4j are you using? In 3.3, I can run your query without error message.

Best regards Louise, Neo4j Cypher team

**Comment by eayan** [comment]
Dear @Lojjs thank you for your response. I was using desktop version 1.0.21 and now installed server version 3.3.5 and imported my .rdf. I tried my query again and it is still the same error. 1st and 2nd querries do not work but 3rd one works. I did not get the difference between them since I am just trying to get the same output.

1.query-> MATCH p=(n:ns3__Object)-[r:ns4__P102_has_title]->(n:ns4__E35_Title) RETURN p LIMIT 25
![selection_059](https://user-images.githubusercontent.com/5304822/38800914-c2566da4-4168-11e8-8601-d9da76beea0e.png)

2.query-> MATCH (n:ns3__Object)-[r:ns4__P102_has_title]->(n:ns4__E35_Title) RETURN n:ns3__Object,r,n:ns4__E35_Title LIMIT 25

![selection_057](https://user-images.githubusercontent.com/5304822/38800900-bb7ffff4-4168-11e8-9f58-858afd19775e.png)

3.query-> MATCH p=()-[r:ns4__P102_has_title]->() RETURN p LIMIT 25
![selection_058](https://user-images.githubusercontent.com/5304822/38800955-d74119bc-4168-11e8-9d95-93e470a922c2.png)

**Comment by SaschaPeukert** [comment]
Hi @eayan ,

Please correct me, if I am wrong, but looking at your queries, it wasn't intended that you assign the variable n to both nodes, correct? If that is the case, then this is your problem. The way that the first query, for example, is currently formulated, you are asking for this structure in the graph:
`(n:ns3__Object:ns4__E35_Title)-[r:ns4__P102_has_title]->(n)`
Since I don't see that in your last image, returning nothing is actually the correct behavior. 
Does that help your problem?

Cheers,
Sascha
Neo4j Cypher team

**Comment by SaschaPeukert** [comment]
I'll close this issue now because it does not seem to be an issue with Neo4j

**Comment by eayan** [comment]
Dear @SaschaPeukert ,

you can close it. thank you for your informative explanations.
best...
