### ISSUE TITLE
Neo4J gets corrupted when runs out of disk space, no way to fix it.

### ISSUE THREAD

**Issue by deemeetree** [neo4j/neo4j#11573]
- Neo4j version: 3.3.3
- Operating system: CentOS 7

I ran out of disk space and as a result the database got corrupted (it looks like).

It won't restart. 

When I run neo4j-admin check-consistency it says only that:

unexpected error: null. At position LogPosition{logVersion=250, byteOffset=198709181} and entry version V3_0_10

So probably some transaction logs got corrupted.

I tried to run store-utils but it gives compile errors and doesn't work

I posted more info about the issue here: https://stackoverflow.com/questions/49866342/neo4j-3-3-3-database-got-corrupted-as-there-was-not-enough-disk-space-and-no-way

It would be good to have a guide on what to do in situations like that because so far there's only this but it's not working https://github.com/neo4j/neo4j-javascript-driver/issues/300

**Comment by chrisvest** [comment]
This will be fixed in 3.4 by #9956 — I see you already noticed this on StackOverflow. If you have a support contract, then that's the way to go. Truncating the log file manually is very risky, but if that's your only option then it boils down to `head -c 198709181 log.250.copy > log.250` or something like that. Finding the exact byte position to cut at is the hard part.

**Comment by deemeetree** [comment]
@chrisvest thanks! and what would be the right way to look for where to cut the file?

**Comment by chrisvest** [comment]
You can run the `dump-logical-log` tool with the `--lenient` flag to see if there's any garbage at the end after a cut. Then it's just trial end error.

https://github.com/neo4j/neo4j/tree/3.3/tools
