### ISSUE TITLE
Can't start 3.4.0-rc01 on macOS High Sierra : (Too many open files)

### ISSUE THREAD

**Issue by amadfida** [neo4j/neo4j#11739]
- Neo4j version: /neo4j-community-3.4.0-rc01
- Operating system: macOS High Sierra 10.13.4
- Actual behavior

```
/usr/local/neo4j-community-3.4.0-rc01/data/databases/graph.db/neostore.transaction.db.0 (Too many open files)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:69)
	at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:54)
	at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFiles.createLogChannelForVersion(TransactionLogFiles.java:249)
	at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFile.start(TransactionLogFile.java:78)
	at org.neo4j.kernel.impl.transaction.log.files.TransactionLogFiles.start(TransactionLogFiles.java:87)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
```

the output of ulimit

```

$ launchctl limit
	cpu         unlimited      unlimited      
	filesize    unlimited      unlimited      
	data        unlimited      unlimited      
	stack       8388608        67104768       
	core        0              unlimited      
	rss         unlimited      unlimited      
	memlock     unlimited      unlimited      
	maxproc     1418           2128           
	maxfiles    64000          64000     
```

**Comment by klaren** [comment]
Hi @amadfida!

Does this happen on an empty database?

The new index implementation in 3.4 can use a lot of file descriptors so if you have a lot of indexes you have to increase the limit.

**Comment by amadfida** [comment]
No it only happens on an existing db and we did have to increase the default limit to significantly higher number i.e. 60K -> 400K for it to work.

**Comment by klaren** [comment]
That sounds way off the charts. Do you have a rough estimate of how many indexes you have?

**Comment by amadfida** [comment]
We have 1320 indexes (the number of rows from CALL db.indexes())  and our default index is lucene+native-1.0

**Comment by klaren** [comment]
As I mentioned earlier, the new index implementation uses a lot of file descriptors and for your high number of indexes (1000+ is more than avarage) hitting 60K is very likely. We are aware of this drawback and are working on a solution that will lower the resource usage.

In order to optimize I/O performance, we open multiple channels to all the files. The impact of this is highly depending on the OS and hardware. If you're not comfortable with the 400K limit you can try and tweak the striping factor with an undocumented feature flag, e.g.
```
-Dorg.neo4j.io.pagecache.impl.SingleFilePageSwapper.channelStripePower=2
```
This value has to be one of 1, 2, 4, 8, 16, 32 and 64. The default value is calculated from the number of available CPU cores, rounded up to the closest number of the ones listed above. Lowering this setting might impact performance, especially on Windows, but since your running macOS, you can probably get away with lowering it. You have to experiment with what works for your hardware setup.

In addition to that, the `lucene+native` combo, actually have to create files for both index engines to be prepared to handle both, even if you don't use one of them. While the consumed disk space is negligible, it's still a couple of extra file descriptors, per index, that gets used there. Currently, there is no way to toggle this off but we plan to have a pure `native` index in the future that will address this.

And as an additional side node; the number of file descriptors will spike during high load, so even if the database manages to start it can still fail during runtime due to that limit. So I recommend that you will keep a margin there. This is because the index creates a lot of smaller files during transaction execution, which is then merged to a single large file in a background thread. Generally, this merging is faster than the rate of transactions, but there is still a bit of lag before those files get merge and this temporarily increase the number of open files.

**Comment by chrisvest** [comment]
> This value has to be one of 1, 2, 4, 8, 16, 32 and 64.

No, the number is the exponent to which 2 is raised.
So if `channelStripePower` is 5, then you'll get 2^5 = 32 stripes aka. file descriptors for every individual mapped file.
You can set it to 0 to have only one file descriptor per mapped file. Setting it to 1 will open 2 file descriptors, 2 will open 4, 3 opens 8, and so on.

**Comment by vigorouscoding** [comment]
I believe I found a solution for this. I also experienced this and the switch 
`-Dorg.neo4j.io.pagecache.impl.SingleFilePageSwapper.channelStripePower=0` did not help even though my open file limit was very generous (see below).

There seems to be a limit to `10240` files for Java in Mac OS X. You need to supply a JVM option `-XX:-MaxFDLimit` (see https://www.oracle.com/technetwork/articles/java/vmoptions-jsp-140102.html) to bump this to the max. For me max means around `255000` files - even though my limit is way bigger. But 255k files will suffice for my neo4j needs.

```
$ launchctl limit maxfiles
	maxfiles    524288         524288
```

For further information and a test class see: https://stackoverflow.com/questions/16451343/java-file-limit-on-osx-lower-than-in-bash


EDIT: For me it was `-XX:-MaxFDLimit` - even though the provided documentation link states it should be `-XX:+MaxFDLimit`. Feel free to test this and comment.

**Comment by chrisvest** [comment]
Turns out this is MacOS specific. When `MaxFDLimit` is enabled, the JVM will query the OS for the maximum file descriptor limit, and request that it's current limit be set to that. On MacOS, the max limit can be _infinite_, and this is an invalid value to the current limit. So the JVM instead relies on an `OPEN_MAX` define, which is probably where that `10240` comes from. When you disable `MaxFDLimit`, you bypass this entire machinery, and the existing high limit will be left alone.

Again, this only happens on MacOS. For all other systems, enabling `MaxFDLimit` looks like it will always do the right thing.

**Comment by vigorouscoding** [comment]
I can not confirm this 100% - I have set multiple different open file limits because I was running into this issue. I tried `40000`, `64000`, `524288` and even `2524288` because the neo4j java process kept crashing with `Too many open files`. So I have never set this to `unlimited` (or `infinite` as you called it).

The only solution I found was what I wrote above. Maybe there is something else at play but I for one am really glad that I have a working setup now to work locally.
Maybe this will help other Mac users or at least point them into the correct direction.

**Comment by chrisvest** [comment]
We'll add some text about this to the operations manual, so I'm closing this.

One more thing: setting `channelStripePower=0` can have a performance penalty, which is why it's not the default.

**Comment by chrisvest** [comment]
@vigorouscoding I use the word "infinite" as a reference to `RLIM_INFINITY`. The details are here: http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/hotspot/os/bsd/os_bsd.cpp#l3312

**Comment by vigorouscoding** [comment]
Oh, my bad! I thought you meant with respect to `launchctl limit` where you can set limits to `unlimited`. Thanks for the clarification and sorry for the confusion!
