### ISSUE TITLE
Unexpected result with overlapping match clauses

### ISSUE THREAD

**Issue by ctytgat** [neo4j/neo4j#11814]
- Neo4j version: 3.3.4
- Operating system: MacOS
- Steps to reproduce

Create following nodes:

```CREATE (ann:Person {name:"Ann"})-[:KNOWS]->(john:Person {name:"John"})-[:KNOWS]->(jeff:Person {name: "Jeff"})```

And execute this query:

```MATCH (a:Person)-[:KNOWS]->(p:Person), (a:Person)-[:KNOWS]->(:Person)-[:KNOWS]->(p2:Person) return a, p, p2```

- Expected behavior

3 nodes are returned

- Actual behavior

Nothing is returned.

I'm aware of the fact that the 2 matches can be written as 1, but we dynamically generate our queries which can sometimes lead to this kind of construct. 
I can't see why this wouldn't work...

**Comment by InverseFalcon** [comment]
Hello,

The reason why this doesn't work is due to [cypher's inherent uniqueness](https://neo4j.com/docs/developer-manual/current/cypher/introduction/uniqueness/#cypherdoc-uniqueness) when it comes to matched patterns:

> While pattern matching, Neo4j makes sure to not include matches where the same graph relationship is found multiple times in a single pattern. In most use cases, this is a sensible thing to do.

Within a matched pattern, relationships must be unique, they cannot be reused. This is often very useful, and inherently it prevents infinite loops for variable-length match patterns when a cycle is present.

Because of this, once the first :KNOWS relationship from the `a` :Person node is matched, any subsequent attempt to match to a :KNOWS relationship (of which there is only one) from that same `a` node in the same match pattern will fail.

Breaking up the match into multiple MATCH clauses will work as expected, however.

**Comment by ctytgat** [comment]
Ok thx for the info.
