### ISSUE TITLE
Neo4j Enterprise 3.3.5 : runtime issue

### ISSUE THREAD

**Issue by protheusfr** [neo4j/neo4j#11938]
- Neo4j version: neo4j:3.3.5-enerprise
- Operating system: Ubuntu 16.04
- API/Driver: Cypher
- Execution of specific cypher request.
- Expected behavior : use COST planner with COMPILED runtime
- Actual behavior: use COST planned but fail back to INTERPRETED runtime after 10 seconds

Accordingly to the official documentation (https://neo4j.com/docs/developer-manual/current/cypher/cypher-query-options/) Neo4j Enterprise doesn't use INTERPRETED runtime.

In facts, our query execution time varies between 10228 ms and 35ms with same data and same parameters.

**Comment by protheusfr** [comment]
Hello team,

Any update regarding this issue ?

**Comment by SaschaPeukert** [comment]
Hej @protheusfr !

In Neo4j 3.3 falling back to the interpreted runtime is allowed and intended, depending on the query you are running. Generally speaking, the compiled runtime does not support all kinds of queries, thus this mechanism is necessary. If you look at the 3.3 version of the developer manual ( https://neo4j.com/docs/developer-manual/3.3/cypher/cypher-query-options/ ) it states the following 

>  In Enterprise Edition, the query execution engine’s fallback mechanism is to try the compiled runtime first, and if it does not support the query, to then try the slotted runtime, and if that also does not support the query, to finally fall back to the interpreted runtime, which supports all queries.

If you share your query and some sample dataset with us, we could try to find out why your execution times vary that much. 
In case it's only the first run, that seems slow that might be because we cache previously seen query plans. This allows us to skip a lot of the planning work for subsequent queries that get recognized by the cache and we can go directly to executing it.

**Comment by protheusfr** [comment]
Thanks you Sascha.
Can I sent you request sample directly on a Neo4j support address ?

**Comment by SaschaPeukert** [comment]
For normal support cases, raising a ticket in https://support.neo4j.com/hc/en-us would be the right thing to do but you can also just send it to me for now ( sascha.peukert@neo4j.com ) :-)

**Comment by craigtaverner** [comment]
The query is parameterized using `{UUID}` which will cause it to search different parts of the graph for different parameters. It is entirely possible that these have very different performance characteristics. You should run `PROFILE` for the query for paramters that perform well, as well as for parameters that perform badly, and see what the difference is. In cases like this is it likely that for some parameters the UUID id results in zero rows for part of the query, making subsequent parts very fast.

In order for us to reproduce this issue we would need the query and the parameters used (the list of UUID's).

**Comment by CelineLeduc** [comment]
Hi there,

The thing is that running the query with the SAME `{UUID}` parameter results in very different execution times. 
With the dataset and the query I provided via mail you can use 'e6e6499d-85f0-4485-915a-0969660864b8'. On my local machine, here are the results:
 - First execution: `Started streaming 3 records after 7527 ms and completed after 7533 ms.
`
 - Second execution: `Started streaming 3 records after 26 ms and completed after 27 ms.`

**Comment by SaschaPeukert** [comment]
Hi,

I run the query with the uuid @CelineLeduc provided and got similar execution times but the important part is, that those times were quite stable after the first execution. 
Afterward, I tried to run `apoc.warmup.run` after starting the DB for the first time and then running the query. This got the execution times to 
`Started streaming 3 records after 89 ms and completed after 95 ms.` for the first run and 
`Started streaming 3 records after 22 ms and completed after 24 ms.` for the second run (and similar for any next run) 

What does that mean? Firstly, Caching is at play here, like I suspected before
> In case it's only the first run, that seems slow that might be because we cache previously seen query plans. This allows us to skip a lot of the planning work for subsequent queries that get recognized by the cache and we can go directly to executing it.

Secondly, you tested it on a DB das has just been started, right? Of course, this is fine but it means that the pagecache is not yet fully loaded. Running something like apocs warmup procedure loads all record in the pagecache for you (if pagecache is big enough that is) and makes it so that we don't need to access the disk afterwards. 
So I recommend one of those things: Either use [apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures) [warmup procedure](https://neo4j-contrib.github.io/neo4j-apoc-procedures/index33.html#_warmup) or update to `3.4` since 
`Neo4j 3.4` has a built-in warmup as part of the server startup.

Does that help you or are you seeing execution times that are actually going up although the query is already in the cache?

**Comment by protheusfr** [comment]
Hello Sascha,

Thank you for your response.
This make sense except we didn’t meet the issue only on fresh started DB.
We got the same issue on production DB which is run since weeks or months.
Maybe page cache is too small then, how ca we check that?

Regards,

Bastien

**Comment by SaschaPeukert** [comment]
Hej Bastien,

This site should have the answers you seek (including examples how to configure your page cache to the right size): https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/

**Comment by sherfert** [comment]
@protheusfr Did the page cache configuration help to alleviate the problem?

**Comment by protheusfr** [comment]
Nop, same results.
I guess we had no options to rewrite entirely the request (and maybe the model)

**Comment by mnd999** [comment]
This issue has been inactive for some time, and relates to an unsupported version of Neo4j, so I will close for now. If it's still something we need to work on, please feel free to reopen.
