### ISSUE TITLE
Cypher does not use NodeIndexSeekByRange with projection

### ISSUE THREAD

**Issue by algarsi3** [neo4j/neo4j#11944]
- Neo4j version: 3.4.0
- Operating system: Debian 8 (Jessie)
- Cypher version: 3.0

When executing:
```
match (p:Person)
where 1 <= p.pos_abs <= 140000000000
return v
```
The following plan is executed:
![image](https://user-images.githubusercontent.com/14314257/41403667-b742323c-6fc5-11e8-86a4-db89b27d7129.png)

But when executing:
```
with 1 as start, 140000000000 as end
match (p:Person)
where start <= p.pos_abs <= end
return v
```
The following plan is executing:
![image](https://user-images.githubusercontent.com/14314257/41403781-039925d2-6fc6-11e8-888f-c921281b0033.png)

I expected that Cypher used NodeIndexSeekByRange instead of NodeByLabelScan. Trying to use using hint throws an error:
```
with 1 as start, 140000000000 as end
match (p:Person)
using index p:Person(pos_bas)
where start <= p.pos_abs <= end
return v
```

**Comment by SaschaPeukert** [comment]
@algarsi3 Thanks for reporting this. I have successfully reproduced this problem and we will look into it

**Comment by fickludd** [comment]
Hi there @algarsi3, 

This query is just a you say something that should be index backed regardless of whether the predicate is specified in the `WITH` clause or directly in the `WHERE`. However, the planner is not always very clever about this, mostly because the semantic analysis which happens before planning has some architectural issues which are quite costly to fix. So unfortunately the short answer here is that we have to help the planner by putting predicates directly in the `WHERE` clause, because the fix to this behavior would be too invasive to put into the ´3.4´ series. 

I cannot promise in what version this will finally be addressed, but we are aware of the issue and would also like it solved!
