### ISSUE TITLE
[Feature request]Terminate query when HTTP request is aborted / timeout

### ISSUE THREAD

**Issue by Antti-Kaikkonen** [neo4j/neo4j#11973]
For example when using /db/data/transaction or /db/data/transaction/commit for a long-running query, it would be nice if the query was terminated when the HTTP request is aborted or times out.

I know it might be possible to achieve this using CALL dbms.listQueries(); and CALL dbms.killQuery(id); but I'm worried that it might not be possible to always determine which query to kill if there are multiple instances of the same query.

Does this functionality exist when using the bolt driver or are there any other ways to achieve this?

**Comment by Antti-Kaikkonen** [comment]
I figured I might be able to do what I want like this:

1) Create transaction with no statements
POST /db/data/transaction  (statements: [])

2) Add a long running query to transaction
POST /db/data/transaction/[transaction id from step 1] (statements: [statement:"match ..."])

3) Terminate the query by rolling back the transaction before step 2 is completed. Hopefully, it will terminate the query started in step 2.
DELETE /db/data/transaction/[transaction id from step 1]

Previously I submitted the statement in step 1, so I wouldn't get a transaction id to rollback before the query has executed. I will try this method and let you know if it works.

**Comment by lutovich** [comment]
Hi @Antti-Kaikkonen,

Bolt connections are persistent TCP connections and database can detect their failures. Ongoing transaction will automatically be terminated. There is currently no such mechanism for the transactional endpoint. Your approach feels good to me.

**Comment by Antti-Kaikkonen** [comment]
I think a TCP connection always persists during a single HTTP request so it should be possible to do the same thing with the transactional HTTP API. 

I implemented the workaround that I described and it seems to work.

**Comment by technige** [comment]
Hi @Antti-Kaikkonen 

We have discussed this feature internally and have decided not to go ahead with an implementation. While it may seem like a straightforward request, there are complexities and inconsistencies that it would introduce.

We do not want to bind the database state to the communication channel for HTTP. While this does make sense for a stateful protocol, such as Bolt, it does not make sense for a HTTP, which is stateless. With the HTTP interface, a transaction potentially takes place over multiple connections in the normal case, i.e. you can call `/transaction/N` multiple times while retaining server state in `N`. If one of the connections used to perform an action within that transaction were to fail, a full rollback of transactional state would be unhelpful. Rollback should be explicitly triggered through `DELETE`.

Of course, you do not get a transaction ID if you are using the `transaction/commit` endpoint. But this should be considered a helpful shortcut or "syntactic sugar" for the main endpoints. To that end, it should not exhibit different behaviour, lest it exhibit surprising behaviour.

So you have several options with the interface today. To use "longhand" HTTP transactions, to use Bolt instead of HTTP, or to kill a long-running query via the `killQuery` procedure, if you are in the situation where you've started something that you can't terminate.

Nigel
