### ISSUE TITLE
Incompatible point types are not rejected

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#11976]
### Actual behavior

```
neo4j> CREATE (n:TEST {p: point({latitude:56, longitude:12, x:22, y:44})});
Created 1 node, set 1 property, added 1 label
0 rows returned in 9ms (rendered after 13ms)
```

### Expected behavior

This should be an error, as incompatible positions have been specified using both latitude/longitude and x/y (which also should result in points from different coordinate systems).

**Comment by SaschaPeukert** [comment]
Thanks for pointing this out. Currently, we allow those maps to have any number of keys, which might be useful in certain situations. But you are right - we need to find a solution for conflicting keys. 
For your example, `cartesian` will always win at this moment.

**Comment by Lojjs** [comment]
Sorry for the very delayed response. This was considered too much of an edge case to be worth changing backwards compatibility for. Internally, x & y are treated as the primary parameters, while latitude and longitude are aliases, so x and y are preferred in case of conflicts. As far as I know, nobody else have had issues with this during the years since the feature was released. In case it is brought up again, we might reconsider doing something about it.

Best regards Louise, Neo4j
