### ISSUE TITLE
Distance between incompatible points is not an error

### ISSUE THREAD

**Issue by cleishm** [neo4j/neo4j#11979]
### Actual behavior

```
neo4j> RETURN distance(point({ x: 23, y: 45 }), point({ longitude: 128, latitude: 54 }));
+------------------------------------------------------------------------------+
| distance(point({ x: 23, y: 45 }), point({ longitude: 128, latitude: 54 }))   |
+------------------------------------------------------------------------------+
| null                                                                         |
+------------------------------------------------------------------------------+
```

```
neo4j> RETURN distance(point({ longitude: 128, latitude: 54, height: 100 }), point({ longitude: 128, latitude: 55 })) AS dist;
+------------------------------------------------------------------------------+
| dist                                                                         |
+------------------------------------------------------------------------------+
| null                                                                         |
+------------------------------------------------------------------------------+
```

### Expected behavior

An error, as the points are from different coordinate systems (example 1), or of different dimensions (example 2).

**Comment by cleishm** [comment]
When comparing a 2D point with a 3D point, both from the same CRS, it _may_ make sense to assume a hight of zero rather than returning an error.

**Comment by SaschaPeukert** [comment]
I agree with you, that errors would be nice to have here. But at this point, it is a known limitation of our error handling system which won't be changed soon.

**Comment by cleishm** [comment]
Hi @SaschaPeukert! Thanks for taking a look at this!

I'm not sure it's a "limitation" however. This situation is handled explicitly in the function code, where it returns `NO_VALUE` rather than throwing an error: https://github.com/neo4j/neo4j/blob/3.5/community/cypher/runtime-util/src/main/java/org/neo4j/cypher/operations/CypherFunctions.java#L352-L355

Changing that line to throw an `InvalidArgumentException` or `CypherTypeException` would solve it.

E.g.:

```
diff --git a/community/cypher/runtime-util/src/main/java/org/neo4j/cypher/operations/CypherFunctions.java b/community/cypher/runtime-util/src/main/java/org/neo4j/cypher/operations/CypherFunctions.java
index 778799c118a..65bfb1e45ad 100644
--- a/community/cypher/runtime-util/src/main/java/org/neo4j/cypher/operations/CypherFunctions.java
+++ b/community/cypher/runtime-util/src/main/java/org/neo4j/cypher/operations/CypherFunctions.java
@@ -351,7 +351,7 @@ public final class CypherFunctions
         }
         else
         {
-            return NO_VALUE;
+            throw new IllegalArgumentException( "Cannot calculate distance between points in difference coordinate reference systems" );
         }
     }
 
diff --git a/community/cypher/interpreted-runtime/src/test/scala/org/neo4j/cypher/internal/runtime/interpreted/commands/expressions/DistanceFunctionTest.scala b/community/cypher/interpreted-runtime/src/test/scala/org/neo4j/cypher/internal/runtime/interpreted/commands/expressions/DistanceFunctionTest.scala
index 5c1a2ffe540..956f7c4d3b4 100644
--- a/community/cypher/interpreted-runtime/src/test/scala/org/neo4j/cypher/internal/runtime/interpreted/commands/expressions/DistanceFunctionTest.scala
+++ b/community/cypher/interpreted-runtime/src/test/scala/org/neo4j/cypher/internal/runtime/interpreted/commands/expressions/DistanceFunctionTest.scala
@@ -19,6 +19,8 @@
  */
 package org.neo4j.cypher.internal.runtime.interpreted.commands.expressions
 
+import org.neo4j.cypher.InvalidArgumentException
+import org.neo4j.cypher.internal.runtime.interpreted.{ExecutionContext, QueryStateHelper}
 import org.opencypher.v9_0.util.test_helpers.CypherFunSuite
 import org.neo4j.values.storable.CRSCalculator.GeographicCalculator.EARTH_RADIUS_METERS
 import org.neo4j.values.storable.{CoordinateReferenceSystem, PointValue, Values}
@@ -44,6 +46,12 @@ class DistanceFunctionTest extends CypherFunSuite {
   def distance(p1: PointValue, p2: PointValue): Double =
     p1.getCoordinateReferenceSystem.getCalculator.distance(p1, p2)
 
+  test("should throw when incompatible coordinate reference systems") {
+    val p1 = Values.pointValue(CoordinateReferenceSystem.WGS84, -179.99, 0)
+    val p2 = Values.pointValue(CoordinateReferenceSystem.Cartesian, 179.99, 0)
+    an [InvalidArgumentException] should be thrownBy DistanceFunction(Literal(p1), Literal(p2)).apply(ExecutionContext.empty, QueryStateHelper.empty)
+  }
+
   test("should calculate correct bounding box for WGS84") {
     testBoundingBox((x, y) => Values.pointValue(CoordinateReferenceSystem.WGS84, x, y))
   }
```

**Comment by SaschaPeukert** [comment]
It not quite as simple as that sadly. If we were to throw an error at this point, imagine the consequence on people running large complex queries on datasets that don't have a rigid schema. In this scenario, we'd throw and abort the whole query for one value that doesn't fit the others. Not a nice thing to do, right? The current solution works a bit better than that but can and will be improved in the future.

**Comment by cleishm** [comment]
@SaschaPeukert While I have some sympathy for that argument, it is inconsistent with all other cypher functions.

E.g.:
```
neo4j> CREATE (a {foo:1}), (b {bar:"test"}) RETURN a.foo * b.bar;
<interactive>:0:0: error: Don't know how to Multiply(NodePropertyLate(0,foo),NodePropertyLate(1,bar)) `String("test")` with `Long(1)`
neo4j> 
```

Indeed, a quick review of https://github.com/neo4j/neo4j/blob/3.5/community/cypher/runtime-util/src/main/java/org/neo4j/cypher/operations/CypherFunctions.java shows this is the _only_ function that, rather than an error, returns `NO_VALUE` for incompatible arguments.

**Comment by craigtaverner** [comment]
The reason for this choice in behaviour is not arbitrary, but strongly tied to indexing. We want Cypher to behave the same with and without an index. The index will not contain entries for null properties, as null implies the property does not exist. This also means that `exists(n.prop)` can be solved by index scans. At the same time, we now have type specific indexes (Numerical indexes introduced in 3.3, and spatial and temporal indexes in 3.4). The type specificity is taken down to all non-comparable types. For example, temporal has six types (Date cannot be compared to Time, etc.) and spatial has an arbitrary number of types (one for each CRS, and 2D is in a different CRS than 3D). So the fact that a 2D point cannot be compared to a 3D point is strongly tied to the fact that a 2D point is stored in a different index than a 3D point.

I note that in a previous comment you say:
>When comparing a 2D point with a 3D point, both from the same CRS, it may make sense to assume a hight of zero rather than returning an error.

However, a 2D point and an 3D point are _not_ in the same CRS. They may be in a related CRS (eg. WGS84 versyus WGS84-3D), but they are not the same. Currently Neo4j has no knowledge of the meaning of the CRS other than whether it is geographic or cartesian (which influences default CRS bounds and distance functions), but nothing is know about CRS heirarchy, or functions for mapping points in one CRS to another. A complete GIS is capable of transforming data from one CRS to another, but that is way out of scope for Neo4j, and also a very non-trivial problem (with singularities and asymmetric transformations, etc.).

When it comes to CRS transformations, I can imagine three levels of support, where Neo4j is at the first:

* No support
* Explicit transformations (provide a function library, for example in your case a function allowing comparison of 2D to 3D by defining a default height or z)
* Automatic transformations (real GIS systems have libraries of supported transformations between CRS)

It would be interesting to take a step to the second level, but even that is non-trivial because we would want the new statements (using these functions) to be index backed.

**Comment by cleishm** [comment]
> Currently Neo4j has no knowledge of the meaning of the CRS other than whether it is geographic or cartesian (which influences default CRS bounds and distance functions), but nothing is know about CRS heirarchy, or functions for mapping points in one CRS to another.

Yup, you're right @craigtaverner. If that hierarchy isn't added, then you can't do transformations. For example, you can't assume that WGS84 can be converted to WGS84-3D by assuming a height of zero, as I suggested might be possible. So until then, I guess you'd just make it an error whenever they are mixed, as proposed.

(Note that the patch above doesn't try to do any transformation - it just returns an error when incompatible types are used to calculate distance, in the same way that all the other functions return errors for incompatible types).

**Comment by craigtaverner** [comment]
@cleishm  Foolishly I deleted my first paragraph which deals with answering your original request, since it was off topic from the rest of my answer. But basically it described the fact that Cypher is, in most, but not all, places returning null instead of an error from situations like this. This is a deliberate direction taken years ago, but unfortunately not 100% consistently implemented in all places. We had a few issues over the years with this, and in general the move is towards returning null. However, I understand your concerns and will take this up with the language group, because it would be best to get their final position on this.

**Comment by cleishm** [comment]
> The fact that Cypher is, in most, but not all, places returning null instead of an error from situations like this.

@craigtaverner What are other examples? I'm looking at the code, and trying examples, and it seems this is the only function returning null for incompatible arguments. Certainly not "most"!

Which would make sense. I recall the discussion years ago about null, and recall that the decision was to return null _when null is supplied as an input_. I.e. null in, null out.

I do agree that blowing up the query when encountering a single "bad" value is a poor experience. If that is to be solved, I'd suggest adding an error type which would be the result of functions that encounter errors during application. This would be different from null, and could be highlighted by the UI.

**Comment by craigtaverner** [comment]
@cleishm The other situations are inequalities. For example, the query: `MATCH (n:User) WHERE n.id > 1000 RETURN n`. The predicate is actually three predicates on User nodes:

* User must have an `id` property (users without `id` property are ignored, with no error, the same behaviour as if n.id is null)
* The `id` property must be a Number (users with `id` properties that are strings are ignored, just as if `string > 1000` evaluated to null)
* The `id` property Number value must be greater than 1000

This query will behave identically with and without an index. This allows us to have type specific indexes, and when the `User(id)` index is queried with the `> 1000` condition, the type of the operand will cause the query to be directed to a type-specific sub-index (the new native GBPTree index) for numbers only. This means that the sub-index containing strings will not even be asked, which is very good for performance reasons.

Now getting back to _points_ and the `distance(a,b)` function. It was designed primarily to be used as a predicate. For example `MATCH (n:User) WHERE distance(n.location,$here) < 1000 RETURN n`. Where `$here` is a `Point` in some CRS, this predicate is actually four predicates on User nodes:

* User must have a `location` property (users without `location` property are ignored, with no error, the same behaviour as if n.location is null)
* The `location` property must be a Point (users with `location` properties that are strings, eg. addresses, are ignored, just as if `distance(point, string)` evaluated to null)
* The `location` property must be in the same CRS as the `$here` parameter.
* The `location` property must be within 1000m of the incoming parameter point `$here`

The CRS is treated as a characteristic of the type because for the purpose of comparability it has exactly the same behaviour. Different types cannot be compared. Two points in different CRS cannot be compared. Comparisons (inequalities, equalities, distance function) all return null when comparing points of different CRS (just as they would for comparing variables of different types).

This behaviour is identical whether there is an index or not. As with the type-specific indexes described before, this allows for points in different CRS to be stored in different indexes. This is actually not a design choice, but something we have no choice in because it is not possible to store, for example, WGS84 in the same _space_ as cartesian, or 3D in the same space as 2D, without doing some strange internal implicit conversions (which we discussed in the previous answer).

**Comment by cleishm** [comment]
Hey @craigtaverner,

In the case of:

> The id property must be a Number (users with id properties that are strings are ignored, just as if string > 1000 evaluated to null)

You're right:

```
+------------------------------------------------------------------------------------+
| a.foo < b.bar                                                                      |
+------------------------------------------------------------------------------------+
| null                                                                               |
+------------------------------------------------------------------------------------+
Created 2 nodes, set 2 properties
```

I'd disagree with null being returned in this case also. Especially given:

```
neo4j> RETURN 1 < "test"; 
<interactive>:1:12: error: Type mismatch: expected Float or Integer but was String
```

It seems numeric comparison and the distance function are two examples inconsistent with other functions, that should be changed to return an error (either immediate or an error object). Any others?

**Comment by cleishm** [comment]
Hey @craigtaverner,

In the case of:

> The id property must be a Number (users with id properties that are strings are ignored, just as if string > 1000 evaluated to null)

You're right:

```
neo4j> CREATE (a {foo:1}), (b {bar:"test"}) RETURN a.foo < b.bar;
+------------------------------------------------------------------------------------+
| a.foo < b.bar                                                                      |
+------------------------------------------------------------------------------------+
| null                                                                               |
+------------------------------------------------------------------------------------+
Created 2 nodes, set 2 properties
```

I'd disagree with null being returned in this case also. Especially given:

```
neo4j> RETURN 1 < "test"; 
<interactive>:1:12: error: Type mismatch: expected Float or Integer but was String
```

It seems numeric comparison and the distance function are two examples inconsistent with other functions, that should be changed to return an error (either immediate or an error object). Any others?

**Comment by craigtaverner** [comment]
Just a small update. I believe the cypher language group have been discussing the idea of allowing functions to behave differently when in predicate context and when not, so that they can, as you suggest, always generate null in predicate context, but errors in non-predicate context. For now, however, it is inconsistent, with the official position that they behave the same (as the distance function does), while there being some cases where they do not.

**Comment by cleishm** [comment]
This doesn't seem like a valid analysis. As far as I can see, with the exception of the _two_ cases we've identified, functions used in predicate context also cause failures. E.g.:

```
neo4j> UNWIND [1, 'c'] AS x WITH * WHERE x * 1 > 0 RETURN x;
+------------------------------------------------------------------------------+
|                                                                              |
+------------------------------------------------------------------------------+
| 1                                                                            |
<interactive>:0:0: error: Cannot multiply `String` and `Long`
```

It seems that there are "some cases" where they are consistently returning `null` in predicate or non-predicate position (two cases identified so far). All other functions consistently cause an error in either position.

I do like the idea of having them behave differently in predicate vs non-predicate, as that would be a necessity to allow them to fail in predicate and return an error type in non-predicate.
