### ISSUE TITLE
Load CSV didn't complete even after 2 days or longer

### ISSUE THREAD

**Issue by zhizh** [neo4j/neo4j#11986]
### Environment

    neo4j-enterprise-3.4.1-windows.zip & neo4j-enterprise-3.4.4-windows.zip
    neo4j.conf
        dbms.memory.heap.initial_size=5g
        dbms.memory.heap.max_size=5g
        dbms.memory.pagecache.size=7g
        # dbms.directories.import=import
    PC:  Surface Pro 4
    OS:  Microsoft Windows 10 Professional 64bit 10.0.15063 
    CPU: Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz 2208Mhz, 2 cores, 4 logic processors
    HD:  1 TB SSD + 1 TB SSD
    RAM: 16 GB 
    Data Source:
        https://snap.stanford.edu/data/twitter-2010.txt.gz
        twitter-2010.txt.gz (5,501,785,223 bytes, 1,468,365,182 lines)

### Steps to reproduce

    Step 0:
        CREATE CONSTRAINT ON (person:Person) ASSERT person.id IS UNIQUE

    Step 1: (did complete in 8,210,673 ms)
        USING PERIODIC COMMIT 1000
        LOAD CSV FROM "file:///C:/poc/import/twitter-2010.txt.gz" AS line FIELDTERMINATOR ' '
        WITH DISTINCT toInt(line[0]) as id
        MERGE (n:Person {id:id})
        ON CREATE
        SET n.name = toString(id),
            n.sex = ["Male", "Female"][(id % 2)],
            n.age = (id % 50) + 15,
            n.country = ["China", "U.S.A", "France", "Britain", "Russia", "Canada", "Germany", "Japan", "Italy"][(id % 9)]

    Step 2: (did complete in 3,803,455 ms)
        USING PERIODIC COMMIT 1000
        LOAD CSV FROM "file:///C:/poc/import/twitter-2010.txt.gz" AS line FIELDTERMINATOR ' '
        WITH DISTINCT toInt(line[1]) as id
        MERGE (n:Person {id:id})
        ON CREATE
            SET n.name = toString(id),
            n.sex = ["Male", "Female"][(id % 2)],
            n.age = (id % 50) + 15,
            n.country = ["China", "U.S.A", "France", "Britain", "Russia", "Canada", "Germany", "Japan", "Italy"][(id % 9)]

    Step 3: (didn't complete even after 2 days or longer with no error report either)
        USING PERIODIC COMMIT 1000
        LOAD CSV FROM "file:///C:/poc/import/twitter-2010.txt.gz" AS line FIELDTERMINATOR ' '
        WITH toInt(line[0]) as id, toInt(line[1]) as id1
        MATCH (n:Person {id:id}), (n1:Person {id:id1})
        MERGE (n)-[r:FOLLOWS]->(n1)
        ON CREATE
        SET r.degree = (id+id1)%100

### Actual behavior

Step 0, 1, 2 proves to be successful where step 1 took  8,210,673 ms, step 2 took 3,803,455 ms, but step 3 **didn't complete even after 2 days or longer with no error report either**.

### Expected behavior

Step 3 are exprected to be complete within a few hrs or within a day max and if not it should at least generating an error report.

### Log Files

[debug.log](https://github.com/neo4j/neo4j/files/2211038/debug.log)
[security.log](https://github.com/neo4j/neo4j/files/2211039/security.log)

**Comment by SaschaPeukert** [comment]
@zhizh Thanks for reporting this. We will have a look at it

**Comment by craigtaverner** [comment]
In order to reproduce this we would need a sample data file. We also wonder if it is necessary to load this data in three LOAD CSV commands, instead of just one?

One other thing to try would be to test with smaller CSV files and see how the performance difference is for cases where the third command actually completes, so we can verify that this is a performance issue, not some other bug.

**Comment by zhizh** [comment]
Sample data file is at 
`    
https://snap.stanford.edu/data/twitter-2010.txt.gz
`    

Sure, it is not necessary to divide into three statements. But I tried to import this file using a single statement, and it ended in failure. It would be very appreciated if you could efficiently deliver it with a statement.

In addition, I have not stopped exploring the problem. I'm trying to complete this import with APOC. The statement I'm using is

CREATE CONSTRAINT ON (person:Person) ASSERT person.id IS UNIQUE;

CALL apoc.periodic.iterate(
'CALL apoc.load.csv("file:///C:/poc/import/twitter-2010.txt.gz", {header:false, sep:" "}) yield list',
'WITH toInt(list[0]) as id0, toInt(list[1]) as id1 WHERE id0 IS NOT NULL and id1 IS NOT NULL'+
'  MERGE (n0:Person {id:id0}) WITH *'+
'  MERGE (n1:Person {id:id1}) WITH *'+
'  CREATE (n0)-[r:FOLLOWS]->(n1)',
{batchSize:1000}
);

It's not going well at the moment.

**Comment by zhizh** [comment]
The import was finally completed, and the following statement was used, which took 207060 seconds.

CREATE CONSTRAINT ON (person:Person) ASSERT person.id IS UNIQUE;

CALL apoc.periodic.iterate(
'CALL apoc.load.csv("file:///C:/poc/import/twitter-2010.txt.gz", {header:false, sep:" "}) yield list',
'WITH toInt(list[0]) as id0, toInt(list[1]) as id1 WHERE id0 IS NOT NULL and id1 IS NOT NULL'+
'  MERGE (n0:Person {id:id0}) WITH *'+
'  MERGE (n1:Person {id:id1}) WITH *'+
'  CREATE (n0)-[r:FOLLOWS]->(n1)',
{batchSize:100}
);

**Comment by craigtaverner** [comment]
The root issue here is that this is a very large amount of data with a large number of duplicate `Person` nodes, and the process of detecting duplicates requires an index lookup, which is of order log(n).

If you keep the current input file with one record per relationship and many duplicate persons, then the best approach is the one you have taken, which is to use `MERGE` on the nodes and `CREATE` on the relationships. The original query with `MERGE` on the relationship would make it much slower, as you observed.

The only other way to make this faster is to move the duplicate detection outside of Neo4j, and do that as a pre-processing step. In this case you would create two input files, one containing only 50M lines of unique `Person` nodes which you could import without using `MERGE`. Just use `CREATE`. This import should run once creating all users with linear time since there is no index lookup. Then a second import would create the relationships and use a `MATCH ... MATCH ... CREATE...` pattern to find the nodes and create the relationships. However, the `MATCH` statements will still need an index lookup, so this approach might not help a lot.

In order to do the above you need to create the file of unique persons. That can be done with any scripting environment that supports maps (hash-map, etc.).

One further suggestion. If you have gone to the trouble of building a unique list of persons, you could also consider using the `neo4j-admin import` tool. This tool allows you to import large amounts of data at very high performance into a blank database. It works by importing offline, so there are no transactions to take into account, and writes directly to the raw store format. You will also not need to worry about transactions sizes (so no need for `USING PERIODIC...` or `CALL apoc.periodic.iterate(...)`).

Read more about this at https://neo4j.com/docs/operations-manual/current/tutorial/import-tool/

Unless you are importing into a database with existing data, this will be by far the fastest import option.
