### ISSUE TITLE
Cypher query returns wrong result for some pattern matching.

### ISSUE THREAD

**Issue by cuigm85** [neo4j/neo4j#11983]
- Neo4j version: 3.4.1
- Operating system:  Windows 10
- API/Driver: Neo4j Desktop 1.1.7
- **Steps to reproduce**

1. create nodes : 
```
create (:A{name:'A'})-[:NEXT]->(:B{name:'B'})-[:NEXT]->(:C{name:'C'})
```
2. test three queries:

```
match path1 = (a:A)--(b),
      path2 = (b)--(c)
return *
```

```
match path1 = (a:A)--(b),
      path2 = (a)--(b)--(c)
return *
```

```
match path2 = (a)--(b)--(c)
return path2
```

- Expected behavior
All three queries should return the same result (a)--(b)--(c).

- Actual behavior
The first and third query return the same result but the second one returns nothing.

**Comment by SaschaPeukert** [comment]
Hey @cuigm85 ,

The behavor you are seeing is actually correct. Your second query does not return anything because there are two things at play here:

- `MATCH` will only push results to the next operator if the whole pattern is found. This means that path1 and path2 both need to match something
- You cannot expand the same relationship twice in one `MATCH` clause. If you match on `(a:A)--(b)` for path1, path2 will have problems with `(a)--(b)` since it "is already handled". This results in no match for path2

**Comment by cuigm85** [comment]
- You said "You cannot expand the same relationship twice in one MATCH clause", but I can not find this from developer manual. It just says that ["While pattern matching, Neo4j makes sure to not include matches where the same graph relationship is found multiple times in a single pattern."](https://neo4j.com/docs/developer-manual/current/cypher/introduction/uniqueness/)

- Even if you are right, the second query should better return an error or warning instead of zero result.

**Comment by SaschaPeukert** [comment]
Maybe I did not choose the right words, but yes that is exactly the reason here:

> While pattern matching, Neo4j makes sure to not include matches where the same graph relationship is found multiple times in a single pattern.

For `MATCH` both parts together are considered "the pattern" and like I said, both parts need to return something to have it count as "the whole pattern returned something"
