### ISSUE TITLE
date duration comparison doesn't factor in length of underlying months

### ISSUE THREAD

**Issue by mdfrenchman** [neo4j/neo4j#11996]
- **Neo4j version:** 3.4.0
- **Operating system:** WIndows 10
- **API/Driver:** browser
- **Steps to reproduce / Actual Behavior / Description**
Date and duration math isn't accurate. It appears to be each tied to each component of the date. Leading to potentially misleading results.

Below Cypher gives a good example
```
:params {
start1: '20180101', end1: '20180209', actualdays1: 40, 
start2: '20180201', end2: '20180310', actualdays2: 38
}

WITH 
duration.between(date($start1), date($end1)) as duration1, 
duration.between(date($start2), date($end2)) as duration2 
RETURN duration1, duration2

```
**╒═══════════╤═══════════╕
│"duration1"          │"duration2"           │
╞═══════════╪═══════════╡
│"P1M8DT0S"        │"P1M9DT0S"         │
└───────────┴───────────┘**

```
WITH 
duration.between(date($start1), date($end1)) as duration1, 
duration.between(date($start2), date($end2)) as duration2 
WITH duration1, duration2 
RETURN duration2 - duration1
```
**=> "P0M1DT0S"** 

- **Expected behavior**
  I would expect that the duration2 - duration1 would equal -2D. Currently using duration it looks like duration 2 is longer, when it's not.

**Comment by SaschaPeukert** [comment]
Hey @mdfrenchman ,

As funny as it sounds, this is actually correct behavior. Why is that? Using `duration.between` basically splits your value into logical chunks (months, days, hours,...). Applied to 45 days it would basically result in `1Month 15days` for example. But from this point onward, it assumes that every month in your duration values ("P1M8DT0S" and "P1M9DT0S" ) is 30 days. This means that for your example duration1 would actually be 38 days and duration2 would be 39 days. 

So, what to do about it? If you are only interested in the total amount of days you should use `duration.indays` instead of `duration.between`. So your query will look like this:

```
WITH 
duration.indays(date($start1), date($end1)) as duration1, 
duration.indays(date($start2), date($end2)) as duration2 
RETURN duration2 - duration1
```

This will return the expected `P0M-2DT0S`

**Comment by mdfrenchman** [comment]
Awesome! Thanks Sascha!

I didn’t see the duration.indays in the manual or on cypher ref. I see it in the procs though.  Exactly what I needed.

Thanks again!

**Comment by SaschaPeukert** [comment]
Happy to help! 

More information about temporal functions and the different ways of computing the duration between two temporal instants can be found in our developer manual: 
https://neo4j.com/docs/developer-manual/current/cypher/functions/temporal/#functions-duration-computing
