### ISSUE TITLE
Insert a node into a linked list causes heap overflow

### ISSUE THREAD

**Issue by lchrennew** [neo4j/neo4j#12011]
- **Steps to reproduce**
I want to insert a element into a linked list
```
MATCH (a), (b)
WHERE id(a)==1 AND id(b)==2
OPTIONAL MATCH (b)-[r:LINK_TO]->(c)
DELETE r
CREATE (b)-[:LINK_TO]->(a)
CREATE (a)-[:LINK_TO]->(c)
```
- Expected behavior
If `c` EXISTS, then delete the relationship `(b)-[]-(c)` and create path `(b)-[]->(a)-[]->(c)`
If `c` NOT EXISTS, then just create the relationship `(b)-[]-(a)`

- Actual behavior
If `c` EXISTS, then it works. BUT if `c` NOT EXISTS, infinitely execution until heap overflow!

**Neo4j Version:** 3.4.4 Enterprise  
**Operating System:** WIN 10  
**API:** Docker

**Comment by SaschaPeukert** [comment]
@lchrennew Thank you for reporting this. We will take a look at it!

**Comment by fickludd** [comment]
@lchrennew This turned out to be a problem in CREATE when either end-node was named but null. We do not want to change the existing behavior as some users might rely on getting exceptions in these cases, but we have now added a fix for this which will can be enabled through a configuration flag (https://github.com/neo4j/neo4j/commit/eae074c56b416d7d7d15d39694b44898d503dd63). From the next patch release (3.4.8) you can set `cypher.lenient_create_relationship = true` in `neo4j.conf` and your query should work fine.
