### ISSUE TITLE
license additions ineffective

### ISSUE THREAD

**Issue by philhoefer** [neo4j/neo4j#12027]
The “Commons Clause” you added (47d845925e639297ab2564965ba68105d897e818) to the AGPL licensed software (Neo4j Enterprise) is ineffective and could as well be removed.

The AGPL states that “[i]f the Program as you received it, or any part of it, contains a notice stating that it is governed by this License along with a term that is a further restriction, you may remove that term”.   
Therefore the “Common Clause” can simply be removed and—when removed—has no effect.

**Comment by jmsuhy** [comment]
This topic was brought up a while ago - see the following duplicate issue:   https://github.com/neo4j/neo4j/issues/11821

**Comment by philhoefer** [comment]
That other issue was closed with a statement of intent to move Neo4j Enterprise away from the AGPL to a non-FLOSS one.
I think I'm in no position to question that intent and I don't want to raise that issue here. 
This issue here is intended to address another issue; specifically that the license additions are ineffective and add unnecessary text to an already long license.
If you want to change the license you'd have to make changes to the AGPL (which I don't think RMS would allow) or write a new license.
Anyway IANAL.

**Comment by ddevault** [comment]
Ignoring this problem seems folly - as it stands your license is ineffective and people can use it according to the AGPL license verbatim. You're relying on a falsehood to enforce the licensing terms of your project. If you want to use a restrictive nonfree license that's your choice to make, but currently you're not doing that. The AGPL gives users the right to disregard any extra clauses tacked on.

**Comment by jmsuhy** [comment]
It took 5 years, but the FSF has come out and made their position clear about the commons clause.  This article was targeting Neo4j’s behavior with the commons clause.   

https://www.fsf.org/blogs/licensing/protecting-free-software-against-confusing-additional-restrictions

**Comment by jmsuhy** [comment]
I am guessing this ticket can be closed now.   

It looks like Neo4j was forced to comply with a cease and desist from the Free Software Foundation, related to the addition of the commons clause to the AGPL license, which is copyrighted to the FSF.     

Neo4j chose to rename the license name for enterprise to something other than AGPL for the 3.4 branch.
https://github.com/neo4j/neo4j/commit/b6237ca4e31706b1efbd0f874d265117b84c12d5

And removed the following infringing version tags recently.
3.5.0-alpha01
3.5.0-alpha02
3.5.0-alpha04
3.5.0-alpha05
3.5.0-alpha06
3.5.0-alpha07
3.5.0-alpha08
3.5.0-alpha09
3.5.0-beta01
3.5.0-beta02
3.5.0-beta03

**Comment by klaren** [comment]
I will close this issue as it's not relevant anymore.

I can try to summarize from **my point of view** as an engineer at neo4j and explain why this took so long. 

- There was an active legal case against neo4j, where the "Commons Clause" addition was used as evidence. While the case was ongoing, the old code was not updated/removed to avoid any possibility of "destruction of evidence" claims or similar. Whether this is a valid concern or not, I have no idea, IANAL.
- This case dragged on for a really long time(5+ years) because it was appealed several times. This is the main reason nothing was done sooner.
- The court concluded that neo4j was allowed to add the commons clause and that it was effective because it's considered to be a different license in regards to AGPL.
- Since neo4j's AGPL+CC was now considered a completely new license, and the court case was over so the files could be updated, this was addressed by https://github.com/neo4j/neo4j/commit/b6237ca4e31706b1efbd0f874d265117b84c12d5 and all references to the AGPL+CC was iteratively removed.
- After the case was over, FSF sent a cease-and-desist to neo4j, since the license contained copyrighted text and trademarks that could not be used anymore. Neo4j complied and removed all mentioned infringements.

So all in all, both neo4j and FSF waited for the court case to conclude before acting, and unfortunately, the legal system is not known for being fast and efficient :(

**Comment by jmsuhy** [comment]
Your response seems either misguided or based on limited information. Perhaps it reflects what you were told by your company rather than the full facts of the case.  

Here’s the reality: 

Neo4j spent five years and substantial resources in legal battles against me over my removal of the Commons Clause from AGPL license files that contained FSF copyright and preamble. 

Once the Free Software Foundation became aware, they promptly issued a cease and desist, which led Neo4j to remove the Commons Clause—essentially validating the exact action I took and which became the basis of Neo4j’s lawsuit.

The claim that Neo4j delayed actions to “protect evidence” is clearly unfounded, especially since the case is still in the appeals process and has active appeal in Ninth Circuit court of appeals.

I encourage Neo4j to be transparent with the community. It’s evident that Neo4j’s position in this matter was flawed; acknowledging it would allow everyone to move forward constructively.


Relevant links including the Cease and Desist from FSF to Neo4j below. 

https://dominionresearch.org/research/neo4j/documents/FSF-cease-desist-to-neo4j.pdf

https://www.fsf.org/blogs/licensing/protecting-free-software-against-confusing-additional-restrictions

https://sfconservancy.org/blog/2022/mar/30/neo4j-v-purethink-open-source-affero-gpl/

**Comment by jmsuhy** [comment]
For the community’s awareness, I helped found the ONgDB fork of Neo4j and am also the founder of DozerDB—two open-source projects that provide alternative solutions to Neo4j’s enterprise offerings.

It’s worth considering whether Neo4j’s actions are influenced by the fact that these projects offer freely accessible options that could impact their enterprise subscription revenue. 

Neo4j could have just created a new license with their own name using AGPL terms, removed the FSF copyright and preamble and things would have been different. 

They did not though - they added restrictive terms to the FSF copyrighted AGPL license file keeping the AGPL name, FSF copyright, and FSF AGPL preamble.

Something to think about. 



https://dozerdb.org

https://graphfoundation.org/ongdb/
