### ISSUE TITLE
WITH LIMIT cardinality reduction prevents effects of preceding CREATE

### ISSUE THREAD

**Issue by beho** [neo4j/neo4j#12028]
I'm trying to design a single query that creates a node including input/output links with possible linking to existing nodes. Creation stages are separated by cardinality reduction clauses using `LIMIT 1`. This method prevents creation of certain nodes in preceding `CREATE` clause,  however.

- Neo4j version: 3.4.6
- Operating system: macOs 10.13.6
- API/Driver: Cypher in neo4j browser

### Steps to reproduce

1. Create a structure that next step is going to build upon:
```
CREATE (m:Move {id: "m1"})
WITH m
UNWIND [{i: 0}, {i: 1}, {i: 2}] as p
CREATE (m)-[:OUT]->(:Position {id: p.i})
```

2. Tie to output positions from previous step:
```
CREATE (m:Move {id: "m2"})

WITH m
UNWIND [{pid: 0}, {pid: 1}] as i
MATCH (p:Position {id: i.pid})
CREATE (p)-[:IN]->(m)

WITH m LIMIT 1
UNWIND [{pid: 2, addr: "street"}] as i
MATCH (p:Position {id: i.pid})
MERGE (p)-[:IS_A]->(a:Place {id: i.addr})
CREATE (p)-[:IN]->(m)
```

### Expected behavior
All positions are linked to m2 by IN edges.

![correct](https://user-images.githubusercontent.com/936155/44881933-a0b1dd00-acb1-11e8-88aa-c6a1eb9453f7.png)

### Actual behavior
Position 1 is not linked.

![wrong](https://user-images.githubusercontent.com/936155/44881939-a4ddfa80-acb1-11e8-8734-b4dfcc8f3c11.png)

The problem seems to be in cardinality reducing `WITH m LIMIT 1` because it prevents creation of the link according to second map in first unwind (just to test – link is created when using `WITH m LIMIT 2` but that leads to duplicate link from second unwind of course). I could use `WITH distinct m` but that is more expensive construct.

I do not think that WITH clause should have this "backward" effect so I consider it a bug for now. I would welcome an explanation if I'm wrong :)

Thanks!

**Comment by SaschaPeukert** [comment]
Hej @beho ,

As the [developer manual states ](https://neo4j.com/docs/developer-manual/current/cypher/clauses/limit/)

> LIMIT constrains the number of rows in the output.

That is true regardless of the fact that you do UNWIND before. It basically skips everything in your list after the first element because of `LIMIT 1`.  

I can see, why you are doing this (and why you don't want to use `distinct` here), but maybe we can reformulate the query a bit. What do you think about this approach for your second query?

```
CREATE (m:Move {id: "m2"})
WITH m
UNWIND [{pid: 0}, {pid: 1}] as i
MATCH (p:Position {id: i.pid})
CREATE (p)-[:IN]->(m)

WITH m
UNWIND [{pid: 2, addr: "street"}] as i
MATCH (p:Position {id: i.pid})
MERGE (p)-[:IS_A]->(a:Place {id: i.addr})
MERGE (p)-[:IN]->(m)
```

Another possibility would be to split up the query in two if that is an option for you:

```
CREATE (m:Move {id: "m2"})
WITH m
UNWIND [{pid: 0}, {pid: 1}] as i
MATCH (p:Position {id: i.pid})
CREATE (p)-[:IN]->(m)
```

and 

```
MATCH (m:Move {id: "m2"})
UNWIND [{pid: 2, addr: "street"}] as i
MATCH (p:Position {id: i.pid})
CREATE (p)-[:IS_A]->(a:Place {id: i.addr})
CREATE (p)-[:IN]->(m)
```

**Comment by sherfert** [comment]
It is unfortunately not defined what `LIMIT` does with a preceding update clause. And I agree with @beho that is should only influence the number of rows in the output, not the number of created rows.

One simply example to highlight this inconsistency:

Given a graph of 10 nodes:

```
MATCH (n) CREATE (m) RETURN m LIMIT 1
```

will create 1 node, whereas

```
MATCH (n) CREATE (m:L) WITH m MATCH (l:L) RETURN m LIMIT 1
```

will create 10 nodes. This happens since the second `MATCH` forces the planner to use an `Eager` after the `Create`, making all writes happen before the `LIMIT` can reduce carnality.

Since we have nowhere specified the interaction between `LIMIT` and updates clauses, people might rely on the current behavior. We will consider this as a feature for the next major release.

**Comment by Hunterness** [comment]
As per Neo4j 4.3 the behaviour have changed so that `LIMIT` does not affect the updates but only the returned rows.
