### ISSUE TITLE
Feature Request: Row Number for RETURN

### ISSUE THREAD

**Issue by graphadvantage** [neo4j/neo4j#12055]
Hi

A really useful feature for programatic control would be an introspectable row_number object as parameter for RETURN

or maybe row_number is a RETURN-able function like timestamp, this might be the cheapest way to implement.

Thanks

Michael

** added some notes below ***

**Comment by technige** [comment]
What would you want to do with that row number?

**Comment by technige** [comment]
To expand on my question a little further, I'd like to understand whether you are asking for:

1. A counter for records in a result stream
2. A reference to some underlying store identifier
3. Something else

In the case of (1) this could easily be added by a client application, the driver would need to do nothing special.

For (2) it would be important to understand what remote identifier you would like to see exposed. "Row numbers" make sense in an RDBMS wherein tables have rows so there is a natural mapping for the term. In a graph, what would _row number_ mean?

Or (3) ...?

**Comment by zhenlineo** [comment]
Hi @graphadvantage,

We would like to follow up on this feature request. Could you give us more information by answering @technige 's question?

Zhen

**Comment by zhenlineo** [comment]
Hi @graphadvantage,
We are closing this issue now as we are missing the necessary information to understand this feature request. Please be free to open this issue once you are available to provide us more information for us to continue.

**Comment by graphadvantage** [comment]
Hi Zhen

Sorry I wasn’t able to get back to you sooner - what I’m looking for is the ability to introspect the sort order rank on final row sets, as an integer reference on the record stream.

Currently this is accomplished through something like this, a bit of a long walk

MATCH (n:Movie) 
WITH COLLECT([id(n),n.title]) AS rows 
WITH apoc.coll.zip(RANGE(1,SIZE(rows)),rows) AS enumerated_rows
UNWIND enumerated_rows AS er
RETURN er[0] AS row_num, er[1][0] AS node_id, er[1][1] AS movie_title SKIP 10 LIMIT 10

**Comment by zhenlineo** [comment]
Hi @graphadvantage,

I would like to know if you want this feature to be a Cypher language feature or a client side driver [reactive streams](http://www.reactive-streams.org/) feature? 

Given a stream of 100 records, do you want the Cypher to provide a way to describe that you want to have the 11th to 50th records (only a part of the result) to return? 

Or do you only want a way to consume the records in "pages". In this case, you still want to handle all records, but you want to handle the first 10 records, then the next 10 records, and then all the rest for example?

Cheers,
Zhen

**Comment by graphadvantage** [comment]
Hi Zhen

In consulting with our team the thinking is an integer on the record stream, that is accessible by calling rownum() function in Cypher.

SKIP and LIMIT provide sufficient functionality for slicing the record set.

Thanks 

Michael

**Comment by craigtaverner** [comment]
Hi Michael,

We've discussed this in the Cypher team and we think it is a feature that is highly unlikely to get prioritized anytime soon for many reasons, not least of which is the fact that is will work badly (perhaps unpredictably) with the parallel runtime and ordering (or combinations of the two). The impression we have is that this is something that is most easily implemented by the client. There are two scenarios:

* The client code controls the values of the SKIP, and therefore knows and can track the `row_number` as `record_num+skip`.
* Or the client has no idea of the SKIP field, because this was written into an app GUI as raw Cypher, in which case it is still possible to get this capability using _user defined functions_.

In the unlikely case you do need to write user defined functions, all you would need is a way to initialize the counter and increment and return the counter:

* `public long init(){counter=0;return counter;}`
* `public long increment(){counter++;return counter;}`

And then use in a query like:

```
WITH myfunc.init as dummy
MATCH (n:Movie)
WITH n, myfunc.increment() as row_num
RETURN n.title, row_num SKIP 10 LIMIT 10
```
