### ISSUE TITLE
Query parser allows multiple pattern entities to bind to the same variable name

### ISSUE THREAD

**Issue by aanastasiou** [neo4j/neo4j#12065]
The parser accepts and attempts to execute queries that have the same pattern variable bind to different entities.

**Neo4j Version:** 3.4.5 (Community)
**Operating System:** Ubuntu 16.10
**API:** Behaviour is consistent across the Browser and `cypher-shell`.

### Steps to reproduce
1. Load the Movie graph
2. Try to execute `MATCH (a:Person)-[:ACTED_IN]-(a:Movie) return a.name`

### Expected behavior
CYPHER Error

### Actual behavior
The query appears to execute returning zero results and no complaints.

In this case, it is not that the parser binds to the last associated entity (here `Movie`) because `return a.title` does not work as well. If you change the variable name of one of the entities, the query runs as expected.

If you happen to use the same identifier for both pattern entities, you "lose" the whole query altogether.

This might be trivial here of course, but when you have long queries involving multiple entities, it would be very useful if during syntax checks, the parser raised an error if it spotted this condition in a pattern.

Hope this helps.

All the best

**Comment by craigtaverner** [comment]
This is actually correct behaviour and can return real results with the appropriate graph. What the query means is that you are looking for a node that has both labels `:Person` and `:Movie` and has a relationship `:ACTED_IN` to itself.

Because nodes can have self-relationships and also can have multiple labels, this query can fulfil a real purpose in recognising those cases.

Here is an example that creates this situation:

```
CREATE (n:Movie:Person {name:"Joe Soap"})
CREATE (m:Movie {name:"Joes Movie"});
```

```
MATCH (n:Person), (m:Movie) MERGE (n)-[:ACTED_IN]->(m) RETURN n.name, m.name;
```

Then query with the same query you used

```
MATCH (n:Person)-[:ACTED_IN]->(n:Movie) RETURN n
```

And you will get actual results with the self-relationship. Using a different name for the second variable will give both movies.

**Comment by aanastasiou** [comment]
That's great, thank you very much, I stand corrected :)
