### ISSUE TITLE
Concurrent transactions hang the client AND server.

### ISSUE THREAD

**Issue by purplemana** [neo4j/neo4j#12104]
A prior issue search didn't result in a match so here you go...

A minimal repo is available [here](https://github.com/purplemana/neo4j-concurrent-transactions).

Basically, two concurrent transactions (unrelated in my case), cause the client AND Server to hang, until the connection is terminated.

My setup info:
Neo4j: 3.4.6 Ent on Windows 10.
Client neo4j-driver: 1.7.2
Dev env: Ubuntu on Windows 10.

Example code from the repo:

    const neo4j = require("neo4j-driver");

    async function test() {
      const driver = neo4j.v1.driver(
        "bolt://localhost:6687",
        neo4j.v1.auth.basic("api-server-test", "api-server-test"),
        {
          logging: {
            level: "info",
            logger: (level, message) => console.log(level + " " + message),
          },
        }
      );

      const sessionOne = driver.session();
      const sessionTwo = driver.session();

      const transactionOne = sessionOne.beginTransaction();
      const transactionTwo = sessionTwo.beginTransaction();

      try {
        console.log("This executes :)");
        await transactionOne.run(`MERGE (n:TestNode {id: $id}) RETURN n`, {id: "1"});
        console.log("Yep! :)");

        // Removing `return n` from the above query somehow doesn't hang the code.
        // console.log("This executes too :?");
        // await transactionOne.run(`MERGE (n:TestNode {id: $id})`, { id: "1" });

        console.log("This doesn't :(");
        console.log(
          "And it also hangs the Neo4j server :((. Kill this process with `Ctrl+C` or `Cmd+.`"
        );

        await transactionTwo.run(`CREATE CONSTRAINT ON (book:Book) ASSERT book.isbn IS UNIQUE`);

        await transactionOne.commit();
        await transactionTwo.commit();
      } finally {
        sessionOne.close();
        sessionTwo.close();
      }

      console.log("done!");
    }

    test().then(() => {
      process.exit(0);
    });

My guess is I am not doing it the way its supposed to be done. This appears to be so easily reproducible that I spent a lot of time re-rechecking the setup in my app. How's it working for others?

**Comment by Hunterness** [comment]
Hi, we will investigate the problem further and get back to you.

**Comment by fickludd** [comment]
Hi @purplemana,

Thank you for taking the time to report this issue.

This turned out to be a bug in locking on node set property (which is done by the merge when the node does not exist), which would unnecessarily lock all constraints. This would force your `CREATE CONTRAINT` query to wait for the `MERGE` to commit before continuing. A fix is incoming, and should make it for `3.4.12`.

**Comment by purplemana** [comment]
Thanks @fickludd! Due to the lock, I had removed transactions for my migration utility code while creating constraints. After this issue is fixed, I would retry the strategy.

FYI, the migration approach is to keep one `up` method which creates constraints and data and one `down` method which removes constraints and data. To make the migration consistent, the `up` method must create all constraints in one transaction and then add the data in another transaction. Would this be possible after this fix? Ideally both constraints and data should be part of the same transaction but I guess Neo4j doesn't support constraints and data statements in the same transaction.

**Comment by fickludd** [comment]
@purplemana so even with the fix, transactions will lock labels that they write to, and transactions that create constraints on such a label will still have to wait. That however we cannot change because it it required to ensure consistent data.

It is not possible to both write data and create constraints/indexes in one transaction, and this is not something we can change, you will have to use two transactions. 

Closing this issue as solved, hope your utility works out!
