### ISSUE TITLE
Different results - same query and data.

### ISSUE THREAD

**Issue by dbarton-uk** [neo4j/neo4j#12111]
## Guidelines

- Neo4j version: 3.4.10
- Operating system: MacOS Mojave 10.14.2
- API/Driver: Neo4j Desktop Browser 3.2.15

Running the same Cypher query returns a smaller resultset on the first run, to all subsequent runs. The subsequent resultset give the expected result.
### Steps to reproduce

1.  From a clean neo4j instance. Create some example nodes:

```
WITH RANGE(1, 5) as range
UNWIND range as r1
CREATE (:MyLabel {id: r1})
```

2. Run the following query:

```
MATCH (l1:MyLabel)
MATCH (l2:MyLabel)
WHERE l1.id < l2.id
MERGE (l1) -[:TO]-> (l2)
WITH l1, l2
CALL apoc.path.expandConfig(l1, {relationshipFilter: 'TO', minLevel: 5, maxLevel: 5, terminatorNodes: [l2]}) YIELD path
RETURN count(*)
```

3. Run the same query one or more times again.

### Expected behaviour

I expected to see a count of 180 for the first run, and all subsequent runs

### Actual behavior

40 was returned in the first run. 180 was returned in all subsequent runs.

### Preliminary Analysis

I've did a little analysis to try and figure out where the issue may be. One thing I observed was that separating the query into two queries yielded the expected result on the first run of path expander. So, if you do the merge as the first cypher statement and then the do the path.expand as the second statement independently, the result is 180 as expected. Also I tried to putting an apoc.util.sleep between the merge and the path.expand but no change to the expected first time result.

**Comment by Hunterness** [comment]
Hi, thanks for reporting, we will look into it.

**Comment by Lojjs** [comment]
@dbarton-uk, I have looked a bit into your query and it is unfortunately an expected behaviour/known limitation of procedures that you have run into. 

On the first run your MERGE will lead to a write (CREATE) before the procedure read, but since our planner doesn't know that your procedure will touch the relationships you just created, it doesn't plan an eager between them. This means that all writes is not forced to happen before all reads, which in this case leads to an unexpected result. On the subsequent runs, the MERGE will instead match and no eagerization is needed to get the correct result. 

We will consider implementing a more clever eagerization over procedures for your use case, but since it will rather be seen as an enhancement than a bug fix, it will need to be prioritized against other enhancements/features. For the time being you can either split your query into two queries (as you noted) or you can force an eager before the procedure call by replacing `WITH l1, l2` with `WITH collect([l1,l2]) as data UNWIND data AS row`.

Best regards Louise, Neo4j Cypher team

**Comment by dbarton-uk** [comment]
Thanks @Lojjs for the clarity of your explanation. I will look to implement using the workarounds you suggest. Best wishes, Dave.

**Comment by craigtaverner** [comment]
We thought this through a while back when this was first discovered, but it was not reported again until now, so no action has been taken. I thought however to present some of the ideas here in case you have opinions or preferences:

* Make all procedures require an Eager. This seems like a bad idea because it will increase the memory requirements of all queries that use procedures. Since this issue has been observed infrequently, we recommend against doing this.
* Provide an @EagerBefore annotation (or perhaps an attribute of the @Procedure annotation) to mark that these procedures should always have an Eager before they are run. This could work, but does not differentiate between cases where the procedure is run in a read-only context and the eagerness would not be required.
* Provide an @EagerInUpdateQuery, or similar, annotation to plan an eager when the procedure is used in update queries.
* Provide a complex set of annotation enhancements to describe the nature of the reads that will be done, so the planner can plan Eager only when necessary. This is the most powerful, but also the most complex to implement, and the one most likely to get wrong since the user needs to align the procedure annotation with the procedure behaviour, which could diverge.
* Do byte-code analysis of the procedure to deduce its behaviour accurately, and plan accordingly.

The best compromise we think is the third last option, as the simplest to implement, and therefor the least risk.
