### ISSUE TITLE
Neo4j 3.5.1 enterprise download. SHA-256 checksum doesn't match.

### ISSUE THREAD

**Issue by kfiz** [neo4j/neo4j#12124]
Hi,

the SHA-256 checksum on the 3.5.1 enterprise release doesn't match.

Neo4j Version:3.5.1
Operating System: OSX  

### Expected behavior
Matching checksums.

### Actual behavior
```
$ openssl sha256 neo4j-enterprise-3.5.1-unix.tar
SHA256(neo4j-enterprise-3.5.1-unix.tar)= ede17da989f3da658eb030ffdc16b43dbe889ac417edfdf02e9b35468a86410b
```

Best
<img width="1051" alt="screenshot 2019-01-06 at 06 23 37" src="https://user-images.githubusercontent.com/5100646/50732483-8cf51680-117c-11e9-94eb-9edf78523c94.png">

**Comment by glindroth** [comment]
Hey,
I tried to reproduce this locally but ended up with the same checksum as the one posted on the web site.

I thought for a while that your file name with only ".tar" rather than ".tar.gz" could be the culprit but when I tried that locally I also ended up with the same checksum as on the website.

Are you sure you do not have a damaged file? Have you tried to download it again and retried?

<img width="877" alt="screenshot 2019-01-07 at 08 46 43" src="https://user-images.githubusercontent.com/12694230/50755262-cbf89a00-1258-11e9-92e6-b22f8abb93cc.png">

**Comment by kfiz** [comment]
Weird. Maybe this is a a problem local to my machine.
Would you like to check the file?
https://www.dropbox.com/s/ludfo10dx9fqr3x/neo4j-enterprise-3.5.1-unix.tar?dl=0

**Comment by chrisvest** [comment]
Maybe you somehow gunzipped the file without otherwise unpacking the tar archive?

**Comment by kfiz** [comment]
Don't think so. But even if that were the case, judging from 
https://github.com/neo4j/neo4j/issues/12124#issuecomment-451848390 that shouldn't have mattered, right?
Anyway, something must have gone wrong, but If this was a real problem it should have occurred again, which it didn't (at least on one occasion). So I suggest we close this issue. Thanks for the quick replies.

Best

**Comment by chrisvest** [comment]
In https://github.com/neo4j/neo4j/issues/12124#issuecomment-451848390 the file was simply renamed. Not decompressed. That's why the SHA-256 is the same in both outputs.

It sounds like you downloaded the file again and got a correct checksum? If that's the case, then maybe something really did go wrong during the downloaded. Anyway, will close.
