### ISSUE TITLE
Basic permissions settings to get started with Debian install

### ISSUE THREAD

**Issue by cloudwheels** [neo4j/neo4j#12123]
Forgive me for ignoring the template, there is no bug, just lack of understanding.

I've made a Debian install as per instructions but I can't find a simple explanation of exactly what and how to set up permissions. I get permissions errors after, in theory, changing ownership of relevant directories to neo4j. If I run as root I get the lockfile error mentioned elsewhere, but can't resolve that either, and I've probably just not done it correctly.

Assuming I'm interested in a simple dev setup on my local machine, can anyone please just give me list of commands for adding/modifying users/groups and their permissions.

**Comment by jennyowen** [comment]
On installation, the Neo4j folders are automatically chown'd to a user `neo4j` (this user is created if it doesn't already exist). It's not necessary to manually set up permissions yourself if you're just using a simple setup.

A list of Neo4j files/folders is given here:
https://neo4j.com/docs/operations-manual/current/configuration/file-locations/

I'd recommend uninstalling Neo4j and deleting folder `/var/lib/neo4j`, then reinstalling with:
`sudo apt-get install neo4j` 
(or neo4j-enterprise if that's what you were using).

Then start neo4j with `sudo service neo4j start`.

If that still doesn't work, I'll need to know:
- Neo4j version
- Operating system
- **Steps to reproduce**
- Expected behaviour
- Actual behaviour, including error messages
