### ISSUE TITLE
Cypher Regex matching with slashes

### ISSUE THREAD

**Issue by g3rd** [neo4j/neo4j#12129]
## Bug report

After upgrading from Neo4j 3.4.x to 3.5.x, regex now needs to be escaped.
Also, the python driver no longer binds regex values correctly.

The following query example has worked on Neo4j since I believe 3.1ish, both community, and enterprise. Python 2.7, 3.6, and 3.7.

**Neo4j Version:** 3.5.1 EE and 3.5.0 EE
**Operating System:** Neo4j provided docker image & Ubuntu 18.04.1 LTS
**API:** Cypher, Neo4j Browser
**Driver:** Python 1.7.1 (Python 3.6 and Python 3.7)

## Steps to reproduce
1. Create data
```
CREATE (n:Document)
SET n.tagIds = '111', n.isValid = false;

UNWIND ['111', '111,222,333', '222', '222,333', '111,222'] AS val
CREATE (n:Document)
SET n.tagIds = val, n.isValid = true;
```

### Neo4j Browser
2. Cypher to Query in the Neo4j Browser
```
MATCH (n:Document {isValid: true})
WHERE n =~ '.*\b222\b.*'
RETURN n
```

This is how I got the above query to work in 3.5.x:

```
MATCH (n:Document {isValid: true})
WHERE n =~ '.*\\b222\\b.*'
RETURN n
```

### Python
2. `query.py`
```python
from neo4j import GraphDatabase
driver = GraphDatabase.driver(
    "URL",  auth=("NEO4J_USER", "NEO4J_PASSWORD"))

def query(tag_id):
    cypher = (
        "MATCH (n:Document {isValid: $is_true}) "
        "WHERE n =~ $regex_pattern "
        "RETURN n"
    )
    with driver.session() as session:
        results = session.run(
            cypher, is_true=True, regex_pattern=r".*\b222\b.*")
```

When I add a pdb breakpoint and examine what is being passed to the server, the escaping of the slash is wrong. I've tried various combinations of the string to get the escaping correct. However, none have been successful.

The only way I have gotten the above query to work is to remove the binding:

```python
cypher = (
    "MATCH (n:Document {{isValid: $is_true}}) "
    "WHERE n =~ '.*\\\\b{}\\\\b.*' "
    "RETURN n"
).format(tag_id)
```
## Expected behavior
* Results to be returned
* Documentation that details the change to escaping 
  (I'd be happy to contribute if pointed in the right direction)

## Actual behavior
No results are returned

**Comment by pontusmelke** [comment]
Hi @g3rd, thanks for reporting this. Just to be sure you meant to write

```
WHERE n.tagIds =~ '.*\b222\b.*'
```
right?

The escaping looks like it was needed at least from 2.3 but maybe there has been some driver change. I'll continue investigating.

Regards,
Pontus

**Comment by technige** [comment]
Hi @g3rd.

While I completely agree that backslash escaping can be confusing and messy, I've so far been unable to recreate any functional differences between the handling of regular expressions in 3.3.0, 3.4.0 and 3.5.0, in either the browser or the Python driver (I'm using the 1.7 driver).

Let me try to dig through the detail...

My tests use a slightly adapted version of your query, in two forms. One where the regex is included inline in the query itself, and the other where the regex is passed as parameter. The general form of my query is as below:
```
UNWIND ['A', 'B', 'C', 'A B', 'B C', 'A B C', 'A BC', 'AB C'] AS t
WITH t WHERE t =~ '.*\bB\b.*' RETURN t
```
This should always return `["B", "A B", "B C", "A B C"]`.

The `\b` sequence needs to be transmitted verbatim to the regular expression engine, and not interpreted by one of the higher-level host languages or environments. In other words, we need to unambiguously distinguish between sending a `\` followed by a `b` and sending an ASCII backspace character (for which the common escape code is `\b`).

We also need to consider the multiple levels of host environment through which the regular expression string passes: the client language, the Cypher parser, and the regular expression engine. We're implicitly converting a string into a regular expression here, but the string parsing comes first, so we need to account for escaping at that level too.

In the case of the browser, we can ignore the client language parser; this level of parsing is already accounted for. So to get the regex engine to see a `\b`, we need Cypher to see a `\\b`. We enter that literally in the browser:
```
UNWIND ['A', 'B', 'C', 'A B', 'B C', 'A B C', 'A BC', 'AB C'] AS t
WITH t WHERE t =~ '.*\\bB\\b.*' RETURN t
```

In Python, raw strings (with an `r` prefix) can be used to skip client language escape sequences and achieve the same effect:
```
def test_regex_inline_raw(self):
    with self.driver.session() as s:
        matches = s.run(r"UNWIND ['A', 'B', 'C', 'A B', 'B C', 'A B C', 'A BC', 'AB C'] AS t "
                        r"WITH t WHERE t =~ '.*\\bB\\b.*' RETURN t").value()
        self.assertEqual(["B", "A B", "B C", "A B C"], matches)
```
Without raw strings, we'd need more slashes: some for Python, some for Cypher and some for the regex engine:
```
def test_regex_inline(self):
    with self.driver.session() as s:
        matches = s.run("UNWIND ['A', 'B', 'C', 'A B', 'B C', 'A B C', 'A BC', 'AB C'] AS t "
                        "WITH t WHERE t =~ '.*\\\\bB\\\\b.*' RETURN t").value()
        self.assertEqual(["B", "A B", "B C", "A B C"], matches)
```
Passing the regex as a parameter is arguably somewhat easier to read:
```
def test_regex_in_parameter(self):
    with self.driver.session() as s:
        matches = s.run("UNWIND ['A', 'B', 'C', 'A B', 'B C', 'A B C', 'A BC', 'AB C'] AS t "
                        "WITH t WHERE t =~ $re RETURN t", re=r'.*\bB\b.*').value()
        self.assertEqual(["B", "A B", "B C", "A B C"], matches)
```
Note here though that we can also drop another level of escaping. This is because Cypher doesn't need to parse the string parameter since it's passed as a direct value, rather than Cypher source code. We're also using raw strings here to avoid Python escaping, so what we type is literally what gets passed to the regex engine.

All of that said, my original dilemma remains: I'm still unable to see any functional differences between 3.3.0, 3.4.0 and 3.5.0. Can you point out what else I should be comparing with?

**Comment by pontusmelke** [comment]
@g3rd I am going to close this issue now. Feel free to reopen or open a new one if you are still having problems.

Best Regards,
Pontus
