### ISSUE TITLE
Can't start Neo4j using K8S discovery type

### ISSUE THREAD

**Issue by mikernorton** [neo4j/neo4j#12139]
- Neo4j version: 3.5.1 enterprise (rpm)
- Operating system: Centos 7.6 Container in Helm/Kubernetes
- **Steps to reproduce**
Install 3 core PODS using helm chart, the configuration of each is like:
```
causal_clustering.discovery_advertised_address=neo-cneo.default.svc.cluster.local:0
causal_clustering.discovery_listen_address=0.0.0.0:5000
causal_clustering.discovery_type=K8S
causal_clustering.expected_core_cluster_size=3
causal_clustering.kubernetes.address=kubernetes.default.svc:443
causal_clustering.kubernetes.label_selector=app=neo-cneo,release=neo,heritage=Tiller,csfcomponent=cneo,
causal_clustering.kubernetes.service_port_name=discovery
causal_clustering.raft_advertised_address=192.168.1.78:7000
causal_clustering.raft_listen_address=0.0.0.0:7000
causal_clustering.transaction_advertised_address=192.168.1.78:6000
causal_clustering.transaction_listen_address=0.0.0.0:6000
cneo-dbtype=core
dbms.connectors.default_advertised_address=192.168.1.78
dbms.connectors.default_listen_address=0.0.0.0
dbms.directories.import=/var/lib/neo4j/import
dbms.mode=CORE
dbms.security.auth_enabled=true
wrapper.java.additional=-Dneo4j.ext.udc.source=docker
```

- Expected behavior
The three cores form a cluster and run.
- Actual behavior
All three cores roll continuously with the following in the debug.log:
```
2019-01-18 23:21:44.384+0000 INFO [o.n.c.d.KubernetesResolver$KubernetesClient] Received from k8s api: {"kind":"ServiceList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/default/services","resourceVersion":"4104800"},"items":[{"metadata":{"name":"neo-cneo","namespace":"default","selfLink":"/api/v1/namespaces/default/services/neo-cneo","uid":"e822705d-1b75-11e9-8bde-fa163e3202df","resourceVersion":"4102321","creationTimestamp":"2019-01-18T23:08:03Z","labels":{"app":"neo-cneo","cneo-dbtype":"core","csf-component":"cneo","heritage":"Tiller","release":"neo"}},"spec":{"ports":[{"name":"discovery","protocol":"TCP","port":5000,"targetPort":5000},{"name":"tx","protocol":"TCP","port":6000,"targetPort":6000},{"name":"raft","protocol":"TCP","port":7000,"targetPort":7473},{"name":"https","protocol":"TCP","port":7473,"targetPort":7473},{"name":"bolt","protocol":"TCP","port":7687,"targetPort":7687}],"selector":{"app":"neo-cneo","release":"neo","type":"core"},"clusterIP":"None","type":"ClusterIP","sessionAffinity":"None"},"status":{"loadBalancer":{}}}]}

2019-01-18 23:21:44.460+0000 INFO [o.n.c.d.KubernetesResolver$KubernetesClient] Resolved [neo-cneo.default.svc.cluster.local:5000] from Kubernetes API at kubernetes.default.svc:443 namespace default labelSelector app=neo-cneo,release=neo,heritage=Tiller,csf-component=cneo,cneo-dbtype=core
```

I am trying to K8S move from DNS because 3.5.1 changed how DNS is handled from 3.4.9. In 3.4.9, the system would come up even if only one pod was was ready (and thus available form DNS). Now all core pods must be available before any pod will start.

**Comment by jlislas** [comment]
I got the same error, and in debug mode it shows the following line, after it identified the service: 

> DEBUG [o.n.c.d.MultiRetryStrategy] Try attempt was unsuccessful for input: null

I tried to identify what other setting was missing.

**Comment by phoerious** [comment]
This is a bug in both the Helm chart (see https://github.com/neo4j-contrib/neo4j-helm/issues/67) and apparently also Neo4j itself. Both assume the cluster domain to be `cluster.local`, which is probably never the case for any deployment beyond a local Minikube.

I fixed the bug for me in the Helm chart, which gives me a correct startup script, but the pod still hangs with

```
Resolved [discovery-neo4j-my-release-neo4j-0.neo4j.svc.cluster.local:5000, discovery-neo4j-my-release-neo4j-2.neo4j.svc.cluster.local:5000, discovery-neo4j-my-release-neo4j-1.neo4j.svc.cluster.local:5000] from Kubernetes API at kubernetes.default.svc:443 namespace neo4j labelSelector neo4j.com/cluster=neo4j-my-release-neo4j,neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
```

The docs at https://neo4j.com/docs/operations-manual/current/clustering/discovery/index.html say

> The configured causal_clustering.discovery_advertised_address must exactly match the Kubernetes-internal DNS name, which will be of the form <service-name>.<namespace>.svc.cluster.local.

So either this is an oversight or a really bad design decision. Neo4j should not rely on the cluster domain being `.cluster.local`. Unfortunately, K8S discovery is an Enterprise edition feature, so I can't find the code that generates this log message online.

After fixing the Helm chart, the init script correctly sets

```
export DISCOVERY_HOST="discovery-neo4j-my-release-neo4j-${core_idx}.neo4j.svc.mydomain.local"
```

but Neo4j seems to be ignoring it.

**Comment by phoerious** [comment]
The only workaround is to revert the Helm chart to its buggy version where it ignores `{{ .Values.clusterDomain }}` and simply hard-codes `.cluster.local` into `DISCOVERY_HOST` and then add `cluster.local` to the CoreDNS ConfigMap as an additional cluster domain so that the name resolution works.

**Comment by eastlondoner** [comment]
Sorry that this issue has not had any responses - this relates to a Neo4j Enterprise feature so please raise support requests via your enterprise support channel or your account manager so that we can help to investigate these issues properly.

We’ve got customers using this discovery type on self-hosted Kubernetes, Azure Kubernetes, AWS Kubernetes, GKE, OpenShift, and IBM who are using this successfully - there is no significant bug that prevents this from working. 

@mikernorton & @jlislas to switch from the `DNS` discovery mechanism to the `K8S` discovery mechanism requires additional Kubernetes configuration. The Neo4j helm charts made this change in this PR: https://github.com/neo4j-contrib/neo4j-helm/pull/4/files . Typically resolving issues with the `K8s` discovery mechanism involves making changes to Kubernetes configuration rather than Neo4j and to diagnose problems we would need to see all your current Kubernetes configuration - which is best handled via normal enterprise support channels.

@phoerious you're correct that the K8s discovery mechanism currently assumes the cluster domain is `.cluster.local`. As you helpfully point out this can be worked around. However I've made a change in the enterprise code today that should allow setting different cluster domains but it will take a few weeks to ship - please use enterprise support channels if you want to find out more about that.

**Comment by madianas** [comment]
@phoerious how do I add  `cluster.local` as an additional cluster domain?

**Comment by phoerious** [comment]
@madianas Edit the coredns config map in your kube-system namespace:

```
kubectl edit cm/coredns -n kube-system
```

There you can add additional search domains:

```
  Corefile: |
    .:53 {
        errors
        health
        kubernetes yourdomain.local cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

Restart the CoreDNS deployment afterwards.

**Comment by eastlondoner** [comment]
Yes, unfortunately you've got to use that workaround at the moment. However this is fixed in the upcoming release of Neo4j (4.2).

When Neo4j 4.2 arrives (which should be under one month from now) it will be possible to set `causal_clustering.kubernetes.cluster_domain=<your custom domain>` in your neo4j configuration.

n.b. If you are using the neo4j helm chart there will be a corresponding neo4j-helm 4.2.0 release which will have its own mechanism to set the cluster domain and you shouldn't need to set the neo4j.conf value directly.

**Comment by madianas** [comment]
@phoerious This is the first of many things, that I've tried to do. Here is my CoreDNS config. 

```
.:53 {
    errors
    health
    ready
    kubernetes my.domain cluster.local in-addr.arpa ip6.arpa {
      pods insecure
      upstream /etc/resolv.conf
      fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    forward . /etc/resolv.conf {
      prefer_udp
    }
    cache 30
    loop
    reload
    loadbalance
}
```
I am doing fresh install of current helm chart version 4.1.2-1,(kubelet version v.1.17.5) with the following settings:
```
helm upgrade neo4j ./neo4j/ --install --create-namespace --set acceptLicenseAgreement=yes --namespace neo4j-dev
```
Here is what I get from all three nodes and it continues indefinitely:
```
INFO  Resolved [discovery-neo4j-neo4j-2.neo4j-dev.svc.cluster.local:5000, discovery-neo4j-neo4j-1.neo4j-dev.svc.cluster.local:5000, discovery-neo4j-neo4j-0.neo4j-dev.svc.cluster.local:5000] from Kubernetes API at kubernetes.default.svc:443 namespace neo4j-dev labelSelector neo4j.com/cluster=neo4j-neo4j,neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
INFO  Database 'system' is waiting for a total of 3 core members...
INFO  Database 'system' is waiting for a total of 3 core members...
```

Ping and resolving `my.domain` works: 
```
/app # nslookup discovery-neo4j-neo4j-2.neo4j-dev.svc.my.domain
Name:   discovery-neo4j-neo4j-2.neo4j-dev.svc.my.domain
Address: 10.233.111.105
```

Resolving `cluster.local` domain does not work:
```
/app # nslookup  discovery-neo4j-neo4j-2.neo4j-dev.svc.cluster.local
** server can't find discovery-neo4j-neo4j-2.neo4j-dev.svc.cluster.local: NXDOMAIN
```

I've searched around and couldn't find any similar case when `my.domain` and `cluster.local` can resolve to the same service.

**Comment by phoerious** [comment]
I think you are trying it the wrong way round. You can have your custom domain for everything else, but you MUST use cluster.local for Neo4j. The workaround is only for making Neo4j compatible with your cluster if you are ALREADY using a custom domain. It does not make Neo4j use the custom domain. It only enables Neo4j to resolve cluster.local if your DNS setup otherwise wouldn't (because you are using something else). That also means that you cannot use the Helm setting for changing the cluster domain. You also cannot patch the Helm chart to use your custom domain, since that is not supported by Neo4j itself.

**Comment by madianas** [comment]
Yes, I am using my own custom domain in the cluster.
As you can see, I did not set clusterDomain in helm, it stays `cluster.local` by default.

By workaround, you mean adding `cluster.local` to coredns config, right?
What am I doing wrong?

**Comment by phoerious** [comment]
If you are using the standard Helm chart without any patches or custom domain settings, adding `cluster.local` to your DNS config should be enough to be able to start the causal cluster.

I had to recreate all five core pods after changing the DNS settings, though. Afterwards, they all passed their ready checks once all five were up:

```
NAME                        READY   STATUS    RESTARTS   AGE
pod/neo4j-XX-neo4j-core-0   1/1     Running   0          3m5s
pod/neo4j-XX-neo4j-core-1   1/1     Running   0          3m18s
pod/neo4j-XX-neo4j-core-2   1/1     Running   0          3m46s
pod/neo4j-XX-neo4j-core-3   1/1     Running   0          4m8s
pod/neo4j-XX-neo4j-core-4   1/1     Running   0          6m46s
```

Look for this log line in your core-0 output:

```
Resolved [discovery-neo4j-XX-neo4j-0.neo4j.svc.cluster.local:5000, discovery-neo4j-XX-neo4j-2.neo4j.svc.cluster.local:5000, discovery-neo4j-XX-neo4j-1.neo4j.svc.cluster.local:5000] from Kubernetes API at kubernetes.default.svc:443 namespace neo4j labelSelector neo4j.com/cluster=neo4j-XX-neo4j,neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
```

**Comment by madianas** [comment]
Yes, I am already getting this log:

Here is what I get from all three nodes and it continues indefinitely:
```
INFO  Resolved [discovery-neo4j-neo4j-2.neo4j-dev.svc.cluster.local:5000, discovery-neo4j-neo4j-1.neo4j-dev.svc.cluster.local:5000, discovery-neo4j-neo4j-0.neo4j-dev.svc.cluster.local:5000] from Kubernetes API at kubernetes.default.svc:443 namespace neo4j-dev labelSelector neo4j.com/cluster=neo4j-neo4j,neo4j.com/role=CORE,neo4j.com/coreindex in (0, 1, 2)
INFO  Database 'system' is waiting for a total of 3 core members...
INFO  Database 'system' is waiting for a total of 3 core members...
```

It seems that this workaround does not work for me. Is there another way or should I create a separate issue for this?

**Comment by phoerious** [comment]
That's another issue. You wouldn't get the resolved line if they pods couldn't talk with each other.

**Comment by RagnarW** [comment]
Closing due to unsupported version
