### ISSUE TITLE
big different performances of i/O intensive query on server and client side

### ISSUE THREAD

**Issue by StefanoBelloni** [neo4j/neo4j#12132]
## General

- Neo4j version: 3.5
- Operating system: Debian 9
- API/Driver: REST and Python Driver

I create a project to reproduce the issue:
https://github.com/StefanoBelloni/TestNeo4jBoltDriverProfiler.git
The project try to reproduce an easier situation of our current use-case.
The simple case is as follows

1.  We load in the graph a large number of nodes (more then 1M nodes):
   - There are approximately 150k parent nodes
   - every parent node has between 5 and 10 child nodes, 
2. We calculate a subgraph and save it separately for future look-up
   The subgraph might have 30k nodes.
   This subgraph is saved since might be queried against many times and it is too expensive to recalculate it  every time.

* The implementation of the two steps is done via a custom procedure. 
* Both procedures are just returning a Long.
* I presume that I am using the drivers correctly ... 

### Steps to reproduce
* clone the repository and run the test.
To run the test, one needs maven, docker, curl and python3
```
<git-root>/script/run_test.sh
```
This will print the times measure on the server side and on the client side, for example
```
=========================================================
| RESULT run_python:            
| * server: procedure returned after      798 
| * client: session.run() returned after  1916
=========================================================
=========================================================
| RESULT run_rest:            
| * server: procedure returned after      435 
| * client: session.run() returned after  1.480s
=========================================================
```

* Afterwards
1. run in a shell
```
cd <git-root>/script/
python3 -u my_neo4j_test.py 'prepare'
```
2. open the neo4j browser and run
`CALL example.calculate.save(0, 80000) YIELD out as o RETURN o`

3. clean the database
` python3 -u ${__dir}/my_neo4j_test.py 'clean'`

### Expected behavior
Wen performing the query using the  _neo4j browser_ or a client using the python driver (directly curl) should return in a similar amount of time.

### Actual behavior
The time needed when using the _neo4j browser_  is few milliseconds (server 500 -> client 502ms)  the one measured on the server side, while the one other clients almost twice the time.

**Comment by zhenlineo** [comment]
Hi @StefanoBelloni 

I have a few questions regarding how you calculated these numbers.
Have you warmed up your test environment before running the real test?
Have you repeated the tests and get an average number as the final result?
Is the server and client running environment totally isolated, a.k.a. sharing no resource?

Suppose that the server and client share no resource (such as the same limited memory/ram etc.), the client/driver you use shall not affect any work performance on the server side. The numbers you get in procedures (`procedure returned after`) are a pure server side operation. As a result, I would wonder if you warmed up your tests properly? The neo4j caches previous db access in memory, so if you run test sequentially against the same alive db, then there is no wonder the second run takes shorter time.

Hope this helps with your test.

Regards,
Zhen

**Comment by StefanoBelloni** [comment]
Hallo and thanks for the quick response,

I have to say sorry if I mislead then point with a bit of confusion in the issue description:

The test does not go in the direction of different performances of the query on server or client side, but only about the big discrepancy between the time measure on the server side and the one measured on the client side of a single request which calls a self defined procedure which is read-write intensive ...

Just to be sure If it had something to do with a particular driver, I perform the same test using
* curl and the REST API
* c-driver and c neo4j-client (https://neo4j-client.net/)
* python-driver

1. To evaluate which is the transport cost of a simple query I just run the query `'RETURN 1'` and obtained values around 1 ms. (i am working as `localhost`)
2. I then populate the graph.
3. I then run a query which calls a self defined procedures
     1.  the procedures read and write something like 30K relations and 30K nodes and write also that number of new nodes and relationship.
     2. the procedures returns a `Stream<QueryCount>`, a `Long` wrapped in the following class: 
```
     public class QueryCount
     {   
         public final Long out;
         public QueryCount(Long o_) 
         {
             out = o_; 
         }
     }   
```
4. I compare the time needed to perform various operation for a single request, for example
    * server:
          * time on the server side from start to the return statement: `748 ms`
    * client (python-driver)
          * time to open a session, write a transaction and consume the result `1523 ms`
          * time to write the transaction and consume the result `1487 ms`
5. Repeating the test with various drivers,
    1. starting a new server from an empty database for every driver
    2. using the same server and just cleaning up the database (via cypher) before every new tests
    Although the performance of a single query changes for the reasons that you mentions, the ratio between the server time is always around twice as fast as the client side.
6. For fear I was not properly using the driver and not consuming all the result inside a session and/or connection I tried apart from assuming that every `session.close()` or equivalent `with driver.session() as ...` consume all the results
    1. making a new connection for every step 1 to 3
    2. consuming explicitly all the requests that are not timed.
    But I got always similar results.

This discrepancy is not clear to me and I do not understand from where it might come, if is expected or I am simply using something wrong.

Thanks again and regards,
Stefano.

**Comment by technige** [comment]
Overall, the performance you see will vary enormously depending on a large number of factors, such as the backend server topology, the shape and size of your query, the data types sent and received, the client software stack (and whether that is compiled or interpreted), the protocol you're using, other processes running on the database server, other processes running on the application server, other traffic flowing few the network, and so on. We have never attempted to unify timings across all surfaces and driver languages: there is little to gain from that.

On top of that, timings are very hard to measure reliably. You need to measure in an isolated context, take repeated measurements, and - as @zhenlineo says - make sure you've warmed up your database first.

Comparing official drivers with community drivers might not be as helpful as you think, since both are likely at different levels of functionality and are maintained by different parties. Comparing Bolt with HTTP will not tell you much either, since the stacks of software involved are quite different.

What is important to consider however is _your_ application SLAs in relation to _your_ application software stack, _your_ data model and _your_ server architecture. Is your application fast enough to meet your SLAs? If not, where can you optimise? Can you refine your queries, change your application architecture or data model, or return a smaller amount of data over the network?

From a quick look, it looks like you're using the Python driver correctly, though. We can probably help with optimisations along the way, too, so feel free to continue that conversation. The [community.neo4j.com](url) site is a good place to have a higher-bandwidth conversation on that kind of thing.

**Comment by StefanoBelloni** [comment]
Many thanks for the answer and the suggestion of _community.neo4j.com_: i will try to forward my questions there.
