### ISSUE TITLE
using % operator with long value causes Neo.DatabaseError.General.UnknownError: Cannot produce a double from java.lang.Long

### ISSUE THREAD

**Issue by davidbarnhill** [neo4j/neo4j#12153]
**Neo4j Version:** desktop 3.5.1
**Operating System:** windows   
**API:** Cypher

### Steps to reproduce

Create node with long value for a key.
create (n:Node {Pk:79094469075707465})
Then try to match on the node and return the modulus of the key:
match (n:Node) return (n.Pk % 4)
This returns:
Neo.DatabaseError.General.UnknownError: Cannot produce a double from java.lang.Long
If you run this instead it works:
match (n:Node) return (toInteger(n.Pk),  (n.Pk % 4)
You get:

79094469075707465   1

### Expected behavior
using mod on a long shouldn't throw an exception.

### Actual behavior
Exception is thrown

**Comment by Hunterness** [comment]
Hi @davidbarnhill, thanks for reporting this. We will look into it.

Best Regards,
Team Cypher

**Comment by Lojjs** [comment]
@davidbarnhill This turned out to be a bug in our compiled runtime, which I now have merged a fix for. The fix will be included in 3.5.3. For the time being you can either use the workaround query that you provided or prepend your query with `CYPHER runtime=slotted` (if you run enterprise) or `CYPHER runtime=interpreted`.

Best regards Louise, Team Cypher
