### ISSUE TITLE
Incorrect Cypher query result when relationship type is specified

### ISSUE THREAD

**Issue by averza** [neo4j/neo4j#12168]
- Neo4j version: 3.5.2
- Operating system: Windows 10
- API: Cypher

### Steps to reproduce
1. Start Neo4j with the example Cineasts database (https://neo4j.com/developer/example-data/#_data_sets).
2. Open localhost:7474 and execute these queries:
2a. match (a)-[:DIRECTED]-(b)--(c) where a.id="6593" and c.id=a.id return c.id
2b. match (a)-[:DIRECTED]-(b)-[:DIRECTED]-(c) where a.id="6593" and c.id=a.id return c.id

### Expected behavior
Both queries should return "6593" because the relationship type is DIRECTED and it shouldn't matter if we specify it or not.

### Actual behavior
Query 2a returns "6593" while the query 2b returns an empty result set.

![image](https://user-images.githubusercontent.com/20924082/53271078-0679a180-36f6-11e9-9f83-c0ec294f5524.png)

**Comment by Hunterness** [comment]
Hi, thanks for reporting. We will look into it.

/Team Cypher

**Comment by Lojjs** [comment]
@averza This is not a bug but intended behaviour. When running your first query, you get the result shown in the attached image. The variables `a` and `c` will both map to the same node namely `John Huston` and you will get 2 results since you have 2 different `b` nodes. The relationship between `a` and `b` will be the `DIRECTED` and the one between `b` and `c` will be `ACTED_IN`.

In your second query you search for 2 `DIRECTED` relationship but since each `b` node just have one `DIRECTED` relationship to the node with id 6593 and Cypher never traverse the same relationship twice you won't get any matches.

Best regards Neo4j Cypher team

<img width="502" alt="cypher_rel_issue" src="https://user-images.githubusercontent.com/7222590/53328148-a1869d00-38e9-11e9-912b-91416cbcffc9.png">

**Comment by InverseFalcon** [comment]
@averza Here's a section in the docs where we discuss the uniqueness of a relationship per path:

https://neo4j.com/docs/cypher-manual/current/introduction/uniqueness/
