### ISSUE TITLE
Neo4j 3.5.1 Azure Marketplace Template - Bolt Connection Browser Fails, Due to TLS Setting

### ISSUE THREAD

**Issue by graphadvantage** [neo4j/neo4j#12164]
#### Steps to reproduce:
1. Deploy Azure Marketplace Image 3.5.1 Single Node
2. Config administrator login, SSH key pair, register public key
3. Open Neo4j Browser, connect on Bolt ==> connection fails "Due to security constraints on your browser..."

#### Actual behavior: Connection fails - however http://[IP Address]:7474 succeeds.

After much testing of various settings in neo4j.template  (which in Azure overwrites neo4j.conf on restart) the fix is to comment out the template TLS setting as follows and instead set dbms.connector.bolt.tls_level to OPTIONAL.  

```
#dbms.connector.bolt.tls_level=$dbms_connector_bolt_tls_level
dbms.connector.bolt.tls_level=OPTIONAL
```

The current template configuration defaults to REQUIRED in neo4j.conf, which is causing Bolt to reject non-encrypted connections.

I can see why this is done, however it should at least be better documented, there's no mention of TLS being set this way or how neo4j.template and pre-neo4j.sh generate the neo4j.conf on restart.

https://neo4j.com/developer/neo4j-cloud-azure-image/

**Comment by moxious** [comment]
@graphadvantage as of 3.5.3 on azure we're making tls_level optional, and including extra messages if memory serves about TLS settings.  In general it's strongly recommended to configure valid SSL certs, which are ultimately up to the deployment as they are DNS specific.  Making tls optional can help get past the unfortunate error, which is caused by a combination of how Neo4j Browser is built, and the web browser's built-in security model, but passing usernames/passwords in the clear without encryption isn't much of a long-term solution.

Instructions for generating valid SSL certs for neo4j cloud instances [can be found here](https://medium.com/neo4j/getting-certificates-for-neo4j-with-letsencrypt-a8d05c415bbd) and troubleshooting information which discusses the failure connect error (which does stem from SSL issues) [can be found here](https://community.neo4j.com/t/troubleshooting-connection-issues-to-neo4j/129)
