### ISSUE TITLE
AttributeError: type object 'GraphDatabase' has no attribute 'uri_schemes'

### ISSUE THREAD

**Issue by FinancialAIGhost** [neo4j/neo4j#12179]
**my code:**
`
from py2neo import Graph,Node,Relationship,http

import neo4j

graph = Graph('http://localhost:7474',username='neo4j',password='neo4j')
`

**my issues**

i try to do this.but i have trouble:

File "C:/Users/Bai'rong/PycharmProjects/untitled10/1.py", line 7, in 
graph = Graph('http://localhost:7474',username='neo4j',password='neo4j')
File "C:\ProgramData\Anaconda3\lib\site-packages\py2neo\graph.py", line 335, in new
graph_service = GraphService(*uris, **settings)
File "C:\ProgramData\Anaconda3\lib\site-packages\py2neo\graph.py", line 80, in new
register_http_driver()
File "C:\ProgramData\Anaconda3\lib\site-packages\py2neo\http.py", line 120, in register_http_driver
if "http" not in GraphDatabase.uri_schemes:
AttributeError: type object 'GraphDatabase' has no attribute 'uri_schemes'

**my version**

my neo4j version is neo4j-desktop-offline-1.1.15-setup.exe

**what i find**

i try to look if v1.GraphDatabase have attribute 'uri_schemes'

it don't have

**Comment by FinancialAIGhost** [comment]
oh my god,somebody can help me

**Comment by technige** [comment]
@FinancialAIGhost Py2neo is a community Python Driver and not part of Neo4j's official suite of products. As such, this is entirely the wrong place to raise your issue.

However, as you're here...

You don't mention what version of py2neo you are using, but given that you have a `py2neo/http.py` file as part of your stack trace, I can only assume it's not the latest version. I would therefore recommend upgrading to the latest version (4.2 as of this reply) and running your code again.

The problem itself is likely caused by a mismatch in the versions of py2neo and the official driver that you have installed. Py2neo uses components of the official driver but is tightly bound to specific versions, so if you choose upgrade the official driver independently of your py2neo installation, you will break py2neo. In the general case, you should not need to manually install both drivers: choose one or the other, and if you choose py2neo, allow _it_ to control its own dependencies.

For future reference, py2neo issues should be raised on https://github.com/technige/py2neo.
