### ISSUE TITLE
Did you remove the enterprise edition code?

### ISSUE THREAD

**Issue by ksonbol** [neo4j/neo4j#12178]
I cannot find the enterprise edition code in this repo anymore, but it still mentioned in the project README.md file. Did you decide to close-source the enterprise edition code or was it moved to another location? I am specifically interested in the causal clustering code that was available earlier.

**Comment by jimwebber** [comment]
Hello @ksonbol 

Please see: https://neo4j.com/open-core-and-neo4j/

I'll update the readme now, thanks for flagging it.

**Comment by bradnussbaum** [comment]
@ksonbol The Graph Foundation is continuing forward development of open source enterprise under the ONgDB Project. You can read TGF response to Neo4j Inc taking enterprise closed here: https://www.graphfoundation.org/neo4j-is-open-core-now-what-ujah7ein5mis/

Open Enterprise codebase for 3.5 can be found here: https://github.com/graphfoundation/ongdb
Status of ONgDB Licensing: https://github.com/graphfoundation/ongdb/issues/3
ONgDB Project Site: https://www.graphfoundation.org/projects/ongdb/

**Comment by bradnussbaum** [comment]
So let's get this straight. After 10 years you delete open source code because "that was always what was intended" and then you delete comments from the community that challenge that? Unreal.

**Comment by bradnussbaum** [comment]
Neo4j Enterprise was ALWAYS open source. Let's not start pretending that removing it is anything but unethical by any measure and anyone that disputes that has already reached the pinnacle of corruption. You gained popularity because of open source. Don't forget that. Don't hate us because you turned your back on the community that made you.

**Comment by bradnussbaum** [comment]
The Graph Foundation is continuing forward development of open source enterprise under the ONgDB Project. You can read TGF response to Neo4j Inc taking enterprise closed here: https://www.graphfoundation.org/neo4j-is-open-core-now-what-ujah7ein5mis/

Open Enterprise codebase for 3.5 can be found here: https://github.com/graphfoundation/ongdb
Status of ONgDB Licensing: graphfoundation/ongdb#3
ONgDB Project Site: https://www.graphfoundation.org/projects/ongdb/

**Comment by jmsuhy** [comment]
They removed enterprise code starting at 3.5 - The Open Native Graph Database (ONgDB) fork by Graph Foundation, adds the enterprise code back into Neo4j core.

**Comment by bradnussbaum** [comment]
So let's get this straight. After 10 years you delete open source code because "that was always what was intended" and then you delete comments from the community that challenge that? Unreal.

**Comment by bradnussbaum** [comment]
Neo4j Enterprise was ALWAYS open source. Let's not start pretending that removing it is anything but unethical by any measure and anyone that disputes that has already reached the pinnacle of corruption. You gained popularity because of open source. Don't forget that. Don't hate us because you turned your back on the community that made you.
