### ISSUE TITLE
Update from 3.4.11 to 3.5.3 is a breaking change?

### ISSUE THREAD

**Issue by Bierbarbar** [neo4j/neo4j#12185]
- Neo4j version: 3.4.11-enterprise & 3.5.3-enterprise
- Expected behavior
We have some queries & plugins (on 3.4.11) that are using the `db.indexes()` procedure in the following way: `call db.indexes() yield labels`
- Actual behavior
Now we were thinking about updating our database to 3.5, but when I started evaluating 3.5 i got an error message while calling `call db.indexes() yield labels` because there is no attribute called labels anymore in the return call. 

Steps to reproduce:
1. Start a docker container with 3.5.3
`docker run --publish 7474:7474 --publish 7687:7687 --env=NEO4J_ACCEPT_LICENSE_AGREEMENT=yes  neo4j:3.5.3-enterprise`
2. Create a single node with an index on the label
`create (:Test {hasid:1})`
`CREATE INDEX ON :Test(hasid)`
3. Run the following query from the [neo4j getting started guide](https://neo4j.com/docs/getting-started/current/cypher-intro/schema/):
`CALL db.indexes
YIELD description, label, properties;`
 
And you will see *BAM* query gives back an error, but it run still on 3.4.X

So is this breaking change an intended behavior and will it remain or is it just a bug? Will this be fixed in an upcoming release?

**Comment by chrisvest** [comment]
It was a necessary breakage because 3.5 introduced fulltext schema indexes, which can be so-called _multi-token_ indexes, which means that they can apply to a _set_ of labels and relationship-types.

Because relationship-types can now also be used for defining the schema of an index, "label" isn't really fitting any more. If we kept a "label" column, it would be mis-named for indexes on relationships, or it would have NULLs in it if we added a relationship-type column, which might also break expectations of existing code.

Because of the multi-token indexes, the column will also need to be a list of strings, rather than a string. If "labels" stayed a string, then there would be no obviously good value it could have for multi-token indexes.

We also needed to add a column for index names, so neither column index nor column name can be relied upon to survive the change from 3.4 to 3.5.

In the future we want to re-purpose the "type" column. The values it currently contains are really weird, and not what one normally think of as "index type" in a database context. The procedure name "db.indexes" is also quite good, so we didn't want to pollute the namespace with a new one to support the new features. And even if we didn't, it wouldn't resolve the questions of what "db.indexes" is supposed to do for the new indexes that are possible in 3.5.

Making the changes we did looked like the least bad option. We need to update the Getting Start guide, though. Thanks for pointing that out.

**Comment by Bierbarbar** [comment]
Ok fine, i can understand this all, but why you are namning this as neo4j 3.5.X? Your Versioning Schema pretend that you are using [semantic versioning](https://semver.org/) aren't you ? If you using a semantic versioning a change in the minior version part would mean that all that worked with prior 3.X versions should work with the new one without any problems. I would especially expect from enterprise software to stick to this rules/behavior. 

So why you didn't change the Version number to 4 when you are aware that you are making a breaking change? A version does not cost anything and version numbers are not are restricted resources.

**Comment by chrisvest** [comment]
We follow semantic versioning as closely as we can. Version numbers are not free, though. They have a lot of value in marketing. Going through major versions too quickly also reflects poorly on a product.
