### ISSUE TITLE
error on mvn install neo4j-io

### ISSUE THREAD

**Issue by bluejoe2008** [neo4j/neo4j#12223]
when run unit tests on neo4j-io
an error happens:
```
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.094 s <<< FAILURE! - in org.neo4j.test.extension.TestDirectoryExtensionTest
[ERROR] exceptionOnDirectoryDeletionIncludeTestDisplayName  Time elapsed: 0.04 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:40)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:42)
	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:37)
	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:129)
	at org.neo4j.test.extension.TestDirectoryExtensionTest.exceptionOnDirectoryDeletionIncludeTestDisplayName(TestDirectoryExtensionTest.java:127)
```
it seems that `File.setReadonly()` failed

Environment:

- Neo4j version: branch 3.5
- Operating system: CentOS Linux release 7.5.1804 (Core)

### Steps to reproduce
1.  cd community/io/
2. mvn clean install

**Comment by chrisvest** [comment]
This passes on Fedora 29, and on all of our CI machines. Can you verify that `mvn clean` removes the relevant `target` directory? Maybe you ran a build earlier as a different user who now owns the directories and prevent files from having their permissions changed.

**Comment by MishaDemianenko** [comment]
@bluejoe2008 Thx for your report.

The most probable reason for this failure is the lack of permissions to change test file access permissions. 
To be able to run neo4j tests you need to make sure that your user has a full set of privileges and or your underlying file system support used functionality.
As @chrisvest already mentioned we run tests continuously on a variety of platforms and setups and so far this was not a problem for us.

I will close this issue since most probably this is a problem with local environment setup, but please feel free to reopen this report if you think otherwise.
