### ISSUE TITLE
Cypher version does not match docs

### ISSUE THREAD

**Issue by LWprogramming** [neo4j/neo4j#12239]
According to the [Cypher Query Language Reference](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher9.pdf), the standard Cypher version is Cypher 9 (page 196). However, when running some queries, I noticed that this resulted in errors and wanted to clarify what's going on with versioning.

For instance:

```cypher
CYPHER 9
MATCH(n)
RETURN n
```
results in `Neo.ClientError.Statement.SyntaxError: Invalid input '9': expected <init> (line 1, column 8 (offset: 7)) "MATCH(n)" ^`.

After further experimentation I found that replacing `9` with `9.0` yields ` Neo.ClientError.Statement.SyntaxError: Supported CypherVersion values are: 2.3, 3.1, 3.4, 3.5`.

Replacing `9.0` with any of those versions listed does work, so is this a discrepancy between the language reference and what actually happens, or is something else going on?

Other information:

- Running Neo4j in a Docker container (image version neo4j:3.5.6)

- OS: Ubuntu 18.04

**Comment by sherfert** [comment]
Hi @LWprogramming 
I totally understand the confusion and I think this is something we can improve in the neo4j documentation. In [our official documentation](https://neo4j.com/docs/cypher-manual/current/query-tuning/query-options/#cypher-version) we specify that neo4j accepts `2.3`, `3.4`, and `3.5` as language version values.

This obviously deviates from what openCypher dictates. The reason is that all neo4j versions (so far) implement Cypher 9, but to varying degrees. Providing the neo4j version to use a previous language implementation has always existed as an option in neo4j, even before openCypher and that versioning scheme existed.

Our plan is to overthink the way to specify to use a specific language version vs. product version as soon as we have support for parts of Cypher 10.

I hope this made sense.
