### ISSUE TITLE
Match quotation escape behavior in LOAD CSV and neo4j-admin

### ISSUE THREAD

**Issue by FirefoxMetzger** [neo4j/neo4j#12242]
In the documentation for the `neo4j-admin import` feature it states that:

Character to treat as quotation character for values in CSV data. Quotes can be escaped by doubling them, for example "" would be interpreted as a literal ". You cannot escape using \. Default: " ((source)[https://neo4j.com/docs/operations-manual/current/tools/import/options/])

And the `LOAD CSV` command would like to have quotations escaped using \". 

So depending on which tool you use to import a .csv, you either have to escape the quotation character using `""` or `\"`

## Feature request template

**Is your feature request related to a problem? Please describe.**
I am formatting my data for bulk import via `neo4j-admin import`. I tested a subset of the data via the `LOAD CSV` function, assuming that it will behave in the same way as the bulk import tool, to be sure the formatting is acceptable.

It's frustrating that the bulk import ignores \ and wants "" for the " character, because I have to adjust / convert my data again now, which will take about a day to parse. It would be nice if both functions behave congruently.

**Describe the solution you'd like**
I would like the `neo4j-admin import` tool to behave in the same way as LOAD CSV, that is to respect "\" as an escape character in strings (which it partly does, because \n is recognized as the new line symbol (??), but the documentation says it won't respect \)

**Describe alternatives you've considered**
Alternatively, the documentation of the `neo4j-admin import` tool could have a more visible note that it won't behave like your average .csv parser (in that it ignores the escape character)

**Comment by tinwelint** [comment]
I understand your pain. The basis for this change is that the "proper" CSV quotation (https://tools.ietf.org/html/rfc4180) is double quotes, but for legacy reasons i.e. when first writing the parses it supported `\"` too. One example of reason `\"` is not ideal is that it would be difficult/impossible to convey certain combinations of characters in your data, see `"""abc\"""` where you would like to get `"abc\"` but wouldn't.

In your case you can use `neo4j-import` command instead of `neo4j-admin import`, since that gives you the option to enable/disable support for `\"`, by the use of the `--legacy-style-quoting=true/false` option. It looks like 4.0 will have support for this in the `neo4j-admin import` command directly and the deprecated `neo4j-import` command removed.

**Comment by tinwelint** [comment]
Just a heads-up that I'll close this card in a couple of days if there's no response.

**Comment by FirefoxMetzger** [comment]
Yes, please go ahead and close this issue.
