### ISSUE TITLE
MERGE operation brings down performance significantly. 

### ISSUE THREAD

**Issue by kant111** [neo4j/neo4j#12243]
I have a total of 200,001 nodes out of which one node joins with 200,000 other nodes. so 200,000 relationships total. 

All these nodes are coming from Kafka so my Kafka Consumer reads a set of nodes(a batch) from Kafka and applies the following operation.

```
MATCH (a:Dense1) where a.id <> "1" 
WITH a 
MATCH (b:Dense1) where b.id = "1" 
WITH a,b 
WHERE a.key = b.key 
MERGE (a)-[:PARENT_OF]->(b)
```
And this takes forever to build 200,001 relationships both with index or without index on id and key. If I change `Merge` to `CREATE` then it is super quick(the fastest)! however, since I have to read a batch from kafka and apply the same operation incrementally the relationships are getting duplicated if I use `CREATE` for every batch.

Ideally, if a relationship exists I don't want Neo4j to do anything or even better throw an exception or something to the client driver that way application can do something useful with it. I also tried changing `MERGE` to `CREATE UNIQUE` in the above code it is 50% faster than `MERGE` but still slow compared to `CREATE`.

If `MERGE` is this slow due to double locking as explained [here](https://stackoverflow.com/questions/56884135/creating-200k-relationships-to-a-node-is-taking-a-lot-of-time-in-neo4j-3-5/56910110) Then it almost becomes unusable.

Any approach to make it better would be great!

**Comment by kant111** [comment]
**Neo4j is built similar to MySQL, run on a single machine with a global mutex lock to ensure full ACID-compliant transactional model. Dgraph is a distributed system built for low latency, high throughput query execution. It picks pages from Google’s Bigtable and Facebook’s Tao, both of which achieve high scalability at the cost of lack of full ACID compliant transactional support. Also see: Note on Transactions**

https://docs.dgraph.io/v0.7.5/dgraph-compared-to-other-databases/#neo4j

**Comment by craigtaverner** [comment]
@kant111 The performance of MERGE in your query is strongly dependant on the number of relationships that the two bound nodes have. If there are very few, MERGE will be fast because it is quick to check if the relationships already exist or not. If there are very many, it will take longer to make this check. This means that MERGE is sensitive to so-called 'super-nodes'. Sometimes it is possible to improve this by restructuring the data model to avoid super-nodes, but that is application dependent, so I do not know if it applies in your case.

I do not that supernodes have improved in performance over the various releases of Neo4j by refining the underlying relationships store structure in a way that is faster specifically for supernodes. I would not be surprised to see continued improvements in this area with future releases of Neo4j.

Your second comment regarding locking suggests that Neo4j takes a global lock. It is worth reviewing the relevant documentation in Neo4j for the actual locking behaviour. See https://neo4j.com/docs/java-reference/current/transactions/. In particular, it mentions that Neo4j will take locks on the individual nodes and relationships involved, not a global lock on the database. So a query locking one set of nodes will not affect queries locking other nodes. I hope this clarifies things.

**Comment by kant111** [comment]
@craigtaverner Just to be clear those are not my comments. I am quoting the text from the dgraph link cited above.

More discussions on this thread.
https://community.neo4j.com/t/creating-200k-relationships-to-a-node-is-taking-a-lot-of-time-in-neo4j-3-5/8621/12

While this is concluded that it is indeed a bug I am very surprised that the query engine couldn't do this basic thing. I hope the fix happens soon.

**Comment by craigtaverner** [comment]
I think the community forum you referred to is the the right place for discussions like this. Since the performance improvements are part of an ongoing project on store formats, and not related to the query planner as such, I think this issue can be closed.
