### ISSUE TITLE
Running more than one database in different https port address at the same time

### ISSUE THREAD

**Issue by theheedfulcoder** [neo4j/neo4j#12248]
In modern era, working with more than one database at the same time is a necessity. In few other query languages we can work with many database at the same time simultaneously even we can do connection and fire query and work with different database at the same time. So, I will look forward for this feature to get added. In this case each database can run in their own port address of localhost.

**Comment by technige** [comment]
Hi @dipayan6ghosh. Multidatabase functionality will arrive with our 4.0 release later this year. In terms of connectivity though, all client connections will be made through the same port (for a given protocol). This is because you will be connecting to the DBMS, and then over that connection, selecting a database on which to run your query.

For more information, keep your eye out for our 4.0 pre-releases.

**Comment by theheedfulcoder** [comment]
Hi @technige 
Fantastic !! Looking forward for such update

**Comment by sherfert** [comment]
@theheedfulcoder Check this page out to get started with multiple databases in neo4j: https://neo4j.com/developer/manage-multiple-databases/
