### ISSUE TITLE
Regular expression not capturing for certain string

### ISSUE THREAD

**Issue by kohtianan** [neo4j/neo4j#12260]
this is with reference to a post i have in stackoverflow 
https://stackoverflow.com/questions/50523643/neo4j-cypher-regular-expression-not-matching/57408131#57408131

To match this string in one of the edge's property: 
TargetObject: hklm\\software\\microsoft\\windows\\currentversion\\run\\xyz

This regular expression does not work:
MATCH (n)-[r]->(m) where r.TargetObject=~'hklm\\\\s.*' return n, r, m

But this works:
MATCH (n)-[r]->(m) where r.TargetObject=~'hklm\\\\.*s.*' return n, r, m

Doesn't neo4j follow the Java regular expression class?

**Comment by Hunterness** [comment]
Hi, this seems weird, thanks for reporting. We will look into it.

/Therese, Team Cypher

**Comment by Hunterness** [comment]
Hi, 

I'm currently looking at this and what I think is happening is that the query string rewrites the \ into fewer \\'s.  For a target string `hklm\\software` the regex, once rewritten need to have double \ when being evaluated. From what I find when trying it out we do two rewrites, first once for the query and then once for the regex itself:

In the non-working query, the regex `hklm\\\\s.*`  is rewritten first to `hklm\\s.*` in the query string and then as `hklm\s.*` once its evaluated in the query, which only matches one \ and not the two needed for the target string. The `.` between the \ and the s in the working regex will then match the second \ in the target string.

To get around this issue, try and add another set of \\'s: `hklm\\\\\\\\s.*`
This should then be rewritten as `hklm\\\\s.*` in the first step and then `hklm\\s.*` in the second step, which should then match the target string.

I hope this helps you understand what the problem is and why it doesn't seem to behave as you expected, while still following the Java regular expression class.

Best Regards,
Therese
Team Cypher

**Comment by kohtianan** [comment]
Hi Therese,

Thank you for the update.

i did apply what you have suggested by adding the additional set of \'s to the regex to become `hklm\\\\\\\\s.*`. It works and does return the expected strings.

**Comment by Hunterness** [comment]
Hi Kohtianan,

That's great, then I'll close this issue :)

I also answered on stack overflow (so others that find it can get a good answer as well)

/Therese
