### ISSUE TITLE
fulltext search - I try to search numeric field,but I get nothing by lucene query string.

### ISSUE THREAD

**Issue by crazyyanchao** [neo4j/neo4j#12262]
```
CALL db.index.fulltext.createNodeIndex('updateTime',["Event"],["update_time_mills"])
CALL db.index.fulltext.queryNodes("updateTime", "update_time_mills:(>=1565093559170 AND <=1565093559180)") YIELD node, score
RETURN node limit 10
```
How can I do it?

**Comment by chrisvest** [comment]
Full-text schema indexes only index strings for the time being, because it's the only data type where there's no ambiguity in how to index and query them for full-text.

If you want to query numbers, the regular schema indexes are much better equipped.

**Comment by crazyyanchao** [comment]
@chrisvest Thanks for your reply!
I need search nodes by lucene query,but numeric range is a condition.
The following query,what is the diffrence between query-one and query two?Is it the same effect?
```
// QUERY TWO
CALL db.index.fulltext.queryNodes("search", "name:HongKang* AND  update_time_mills:(>=1565093559170 AND <=1565093559180)") YIELD node, score
RETURN node limit 10
```
OR
```
// QUERY ONE
CALL db.index.fulltext.queryNodes("search", "name:HongKang*") YIELD node, score WHERE update_time_mills>=1565093559170 AND update_time_mills<=1565093559180
RETURN node limit 10
```

**Comment by chrisvest** [comment]
This query does the full-text search and then filters the results:

```
// QUERY ONE
CALL db.index.fulltext.queryNodes("search", "name:HongKang*") YIELD node, score
WHERE update_time_mills>=1565093559170 AND update_time_mills<=1565093559180
RETURN node limit 10
```

This query doesn't work since full-text indexes only indexes strings, but if it did, the `update_time_mills` predicate would be pushed into the index search, which would incur fewer property reads and have higher index selectivity:

```
// QUERY TWO
CALL db.index.fulltext.queryNodes("search",
 "name:HongKang* AND  update_time_mills:(>=1565093559170 AND <=1565093559180)")
YIELD node, score
RETURN node limit 10
```

The two queries might produce different scores, and the node might be returned in a different order because of that. Otherwise, if you don't have the `limit` clause, the same set of nodes should be returned from both.

**Comment by crazyyanchao** [comment]
@chrisvest If I can filter data by time range by db.index.fulltext.queryNodes (Not using where parameters) ,It great!
