### ISSUE TITLE
Neo4j EE 4.0 MR2 - REVOKE MATCH doesn't remove find privilege

### ISSUE THREAD

**Issue by Pablissimo** [neo4j/neo4j#12285]
It seems that in MR2, REVOKE MATCH only removes the underlying `read` privilege, and not the underlying `find` privilege even though GRANT MATCH is a short-hand that allocates both privileges. It means that the following two statements are not the inverse of each other, which I think would be the expected behaviour:

* `GRANT MATCH(*) ON GRAPH graph NODES * TO role`
* `REVOKE MATCH(*) ON GRAPH graph NODES * FROM role`

Raising for visibility in case noone's noticed, obviously feel free to close if it's in hand.

* Neo4j EE 4.0 MR2 (4.0.0-alpha09mr02)
* Using the Docker tarball from the docs (http://dist.neo4j.org/neo4j-enterprise-4.0.0-alpha09mr02-docker-complete.tar)
* Using Neo4j Browser

## Repro steps

Run the following commands in sequence to create a database, create a role and grant the MATCH privilege to the role on all nodes in the test database:

* `:use system`
* `CREATE ROLE RevocationTest`
* `CREATE DATABASE test`
* `GRANT MATCH(*) ON GRAPH test NODES * TO RevocationTest`
* `SHOW ROLE RevocationTest PRIVILEGES`
* `REVOKE MATCH(*) ON GRAPH test NODES * FROM RevocationTest`
* `SHOW ROLE RevocationTest PRIVILEGES`

## Expected behaviour

The `REVOKE` near the end should leave the role RevocationTest with no underlying privileges, since we've revoked exactly what we just granted. The last `SHOW ROLE RevocationTest PRIVILEGES` call should return an empty result set.

## Actual behaviour

The RevocationTest role retains a `find` privilege on `NODES *`. 

The following (from bottom to top) demonstrates the issue more visually:

![image](https://user-images.githubusercontent.com/1470336/64104151-98c8c500-cd6b-11e9-8760-2f68ae2a92be.png)

**Comment by Hunterness** [comment]
Hi,

We are aware of this issue and agree that it is not logical for the `REVOKE MATCH` to behave differently than the `GRANT MATCH` in this regard. However, it is not an easy fix.

Think of this example:
`GRANT TRAVERSE ON GRAPH test NODES * TO RevocationTest`
`GRANT MATCH (*) ON GRAPH test NODES * TO RevocationTest`
The underlining privileges will still only be one find and one read privilege. Now, if you `REVOKE MATCH`, should the find privilege also disappear? Since it was granted separately from the match, I would assume not.

We are not going to fix the `REVOKE MATCH` properly for 4.0 (but plan to at a later stage) but instead disallow the command completely, to avoid this confusion. `GRANT MATCH` will still be an available shorthand, but the privileges have to be revoked separately through `REVOKE READ` and `REVOKE TRAVERSE`.

If you try to `REVOKE MATCH` in 4.0, you'll get an error which tells you to revoke the individual privileges on their own instead.

Hope this helps you understand the MR2 behaviour and that you find the 4.0 behaviour acceptable.
Best Regards,
Therese, Team Cypher

**Comment by Pablissimo** [comment]
Thanks for the response. I agree that failing with an error is probably better than not removing privileges and not reporting it.

Re: your example, I think that's exactly what I'd expect to happen - `MATCH` isn't a privilege, `READ` and `FIND` are. How they got granted isn't as relevant as the set of privileges you end up with (unless there's some underlying record that your privs came into being via a `GRANT MATCH`). Unless `REVOKE` throws if you don't have the privilege it just seems like an odd situation to put yourselves in when just being permissive and treating `REVOKE` and `GRANT` as idempotent operations on a set marries better with expectations people might bring from other DBMSes.

It's similar in my mind to the SQL statement `REVOKE ALL FROM username`. `ALL` isn't an object privilege, it's short-hand for `{SELECT, INSERT, UPDATE, DELETE}` but I wouldn't expect that command to fail if I didn't have all of `{SELECT, INSERT, UPDATE, DELETE}` - I'd expect it to remove those privileges in that set that I have allocated, if any.

Don't know if you get usage data from features in use, but my gut feel would be that people using RBAC will use it for the most part simply, and tend to use the `MATCH` shorthand for most things so wonder if it might be a case worth optimising the developer experience for?

Either way looking forward to the functionality going live, it's a solid step forward for access control in Neo4j.

**Comment by Hunterness** [comment]
Hi again,

Thanks for your input. The problem with using MATCH as a shorthand often for revoking is that unexpected things can happen. Another example, that might be better to highlight the problem with revoking both the find and read for MATCH:

```
GRANT MATCH (prop1) ON GRAPH test NODES * TO RevocationTest
GRANT MATCH (prop2) ON GRAPH test NODES * TO RevocationTest
```
The underlining privileges will now be one find (they share the find) and two read privileges. Now, if you `REVOKE MATCH (prop1)`, should the find privilege also disappear? Then the MATCH on prop2 would no longer keep its find privilege, but only the read.

This would mean that you can no longer find any nodes and will appear to have an empty graph.  So even though you can read prop2 on nodes with the property, you can't find those nodes. So revoking one of the two MATCH that has been granted has the effect of destroying both of them for the role.

There is just a lot of these kinds of scenarios around REVOKE MATCH, which is why we have to look over it properly and for the moment disabled the command in 4.0 :)

**Comment by Pablissimo** [comment]
Ah, I see the issue now! Yeah that's a bummer!
