### ISSUE TITLE
Neo4j repo for debian is down

### ISSUE THREAD

**Issue by sirmax123** [neo4j/neo4j#12289]
Steps to reproduce:

1. Follow instructions: https://debian.neo4j.org

Expected result: 
 - installed neo4j

Actual result:

```
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?
E: Failed to fetch https://debian.neo4j.org/repo/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
```
curl  https://debian.neo4j.org/repo/stable/InRelease -I
HTTP/1.1 404 Not Found
Content-Length: 168
Content-Type: text/html
Date: Thu, 05 Sep 2019 14:07:19 GMT
Server: nginx/1.6.2
Connection: keep-alive
```

**Comment by jennyowen** [comment]
Install `apt-transport-https` and try again. It's usually installed (or at least transitively available) by default. I tried this on a fresh Ubuntu 18 instance and apt fetched the packages without complaint. Which OS are you using? Maybe `apt-transport-https` got deleted somehow or somehow isn't available by default?

Anyway, this is really an issue with `apt` because it needs `apt-transport-https` to be able to download packages over https. 
If that still doesn't work, you need to check that you're not behind a firewall or proxy that's blocking access.

**Comment by sirmax123** [comment]
I  can't reproduce this issue on fresh Ubuntu 16.04 today 

But according to the builds logs It was issue related to hashsum:
```
E: Failed to fetch https://debian.neo4j.org/repo/stable/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

May be it was network-related issue from my side.

Thank you
