### ISSUE TITLE
"Found no solution for block ..." with complex queries

### ISSUE THREAD

**Issue by maksbotan** [neo4j/neo4j#12329]
Complex queries on some data sets lead to errors like this one:

```
Found no solution for block with size 0,\nVector() were the selected candidates from the table IDPPlanTable(numberOfPlans=17, largestSolved=3)
```

We experienced such errors on 3.5.3, then discovered https://github.com/neo4j/neo4j/issues/12212, upgraded to 3.5.11 and the problem seemed solved.

However, it appeared again with slightly more complicated query. And it reproduces only on fairly large datasets.

Here's an example of such query:

```cypher
MATCH
  (mol:Foo)<-[pl:PL_FOO]-(el:El),
  (mol)<-[:NAME_OF]-(name:Name)
OPTIONAL MATCH (el)<-[:TAG_OF]-(tag:Tag)
WITH
  mol, el, pl, collect(DISTINCT name.name) as names,
  collect(DISTINCT tag.tag) as tags WITH mol,
  names, collect(DISTINCT pl.pl) as pls,
  collect(DISTINCT tags) as tags,
  ["AAA","BBB","CCC","DDD","EEE","FFF","GGG","HHH"] AS allowedElements

WHERE ALL (p IN pls WHERE p in allowedElements)

MATCH (mol)<-[:PL_FOO{pl:"AAA"}]-(el1:El)
MATCH (mol)<-[:PL_FOO{pl:"BBB"}]-(el2:El)
MATCH (mol)<-[:PL_FOO{pl:"CCC"}]-(el3:El)
MATCH (mol)<-[:PL_FOO{pl:"DDD"}]-(el4:El)
MATCH (mol)<-[:PL_FOO{pl:"EEE"}]-(el5:El)
MATCH (mol)<-[:PL_FOO{pl:"FFF"}]-(el6:El)
MATCH (mol)<-[:PL_FOO{pl:"GGG"}]-(el7:El)
MATCH (mol)<-[:PL_FOO{pl:"HHH"}]-(el8:El)

WITH mol, pls, names, tags, el8, el6, el1, el4, el3, el2, el5, el7
WHERE TRUE 
MATCH
  (bar1:Bar{barType:"sequential"})<-[:SPAM_BAR]-(:Spam{spamName:"XXXXX"}),
  (bar1)-[:BAR_EL]->(el5)
MATCH
  (bar2:Bar{barType:"sequential"})<-[:SPAM_BAR]-(:Spam{spamName:"XXXXX"}),
  (bar2)-[:BAR_EL]->(el6)
MATCH 
  (bar3:Bar{barType:"sequential"})<-[:SPAM_BAR]-(:Spam{spamName:"XXXXX"}),
  (bar3)-[:BAR_EL]->(el8)
MATCH
  (bar4:Bar{barType:"sequential"})<-[:SPAM_BAR]-(:Spam{spamName:"XXXXX"}),
  (bar4)-[:BAR_EL]->(el7)
MATCH
  (bar5:Bar{barType:"opposite"})<-[:SPAM_BAR]-(:Spam{spamName:"XXXXX"}),
  (bar5)-[:BAR_EL]->(el1),
  (bar5)-[:BAR_EL]->(el2)
MATCH
  (bar6:Bar{barType:"opposite"})<-[:SPAM_BAR]-(:Spam{spamName:"XXXXX"}),
  (bar6)-[:BAR_EL]->(el3),
  (bar6)-[:BAR_EL]->(el4)
WITH DISTINCT mol, names, pls, tags
OPTIONAL MATCH
  (bEl:El)-[:PL_FOO]->(mol),
  (bar:Bar)-[:BAR_EL]->(bEl)
WITH DISTINCT mol, names, pls, tags, bar

OPTIONAL MATCH (bar)-[:BAR_EL]->(barEl:El)
WITH mol, names, pls, tags, bar, collect(DISTINCT barEl) as barEls
WHERE ALL(el in barEls WHERE EXISTS((el) -[:PL_FOO]-> (mol))) 

OPTIONAL MATCH
  (spam:Spam)-[:SPAM_BAR]->(bar)
WITH DISTINCT mol, names, pls, tags, collect(DISTINCT spam.spamName) as spams 

RETURN DISTINCT mol.uuid as molId, labels(mol) as labels, names, pls, tags, spams
```

This particular problem is solved by upgrading to 3.5.12, but the pattern of these errors popping out of nowhere is frightening, as we can't be sure it won't occur again.

**Neo4j Version:** 3.5.11
**Operating System:** Image from Docker hub

**Comment by maksbotan** [comment]
Can you please take a look at this patch (on top of 3.5.11 a55901af4f0a8f1ebeca5d3696644c4cbefc22ea)?

```diff
--- a/community/cypher/cypher-planner-3.5/src/main/scala/org/neo4j/cypher/internal/compiler/v3_5/planner/logical/idp/IDPSolver.scala
+++ b/community/cypher/cypher-planner-3.5/src/main/scala/org/neo4j/cypher/internal/compiler/v3_5/planner/logical/idp/IDPSolver.scala
@@ -54,7 +54,7 @@ class IDPSolver[Solvable, Result, Context](generator: IDPSolverStep[Solvable, Re
     val goalSelector: Selector[(Goal, Result)] = projectingSelector.apply[(Goal, Result)](_._2, _)
 
     def generateBestCandidates(maxBlockSize: Int): Int = {
-      var largestFinishedIteration = 0
+      var largestFinishedIteration = 1
       var blockSize = 1
       var keepGoing = true
       val start = System.currentTimeMillis()
```

It seems to fix our problem, does not break our other queries and does not break `cypher-planner` test suite. I did not, though, run full neo4j test suite, nor did I check for performance degradation (it doesn't look degraded judging with my eyes, but maybe additional tests are required).

Here's a rationale for this fix: `generateBestCandidates` function is supposed to find a block of operators than can be joined, returning a number of elements in such block, let's call this number `n`.

Later, `findBestCandidateInBlock` generates `n`-subsets of blocks and finds the best among them. Now, if `generateBestCandidates` failed to find anything, it returns `0`, there are, of course, no subsets of size `0` found and so `throw` on https://github.com/neo4j/neo4j/blob/3.5/community/cypher/cypher-planner-3.5/src/main/scala/org/neo4j/cypher/internal/compiler/v3_5/planner/logical/idp/IDPSolver.scala#L87 is triggered.

As far as I understand, if no blocks can be joined, it's okay to return `1` as size of block in this case, at least nothing gets stuck later on.

Even if this "fix" is incorrect, I hope it would give you some intuition about what is happening.

Thanks!

**Comment by Hunterness** [comment]
Hi, 

The error you see comes from the planner not finding any plan at all and changing the number to a 1 is not a valid solution. We have plans to at least get a better error message to explain the issue at hand instead of this weird `Found no block of size 0`.

We also have seen this error for several issues and fixes them as they come up. We have recently done more fixes in this area to hopefully make it fail at planning less often. But very complex queries might still see the error.

I know @craigtaverner knows more about how the planner works and probably can explain better exactly why we fail at planning sometimes, but it has to do with us finding smaller parts of plans and then combining into bigger that solves the full query. These partial plans are stored in a table and when its full we compact the table and removes parts which we expect to not need. Sometimes this leads to bigger more complex queries not succeeding in being solved at all.

Since your particular case has been solved I'll close the issue, feel free to re-open it if your problem comes back :)

Best Regards,
Therese
Team Cypher

**Comment by maksbotan** [comment]
Sorry, but "fix as they come up" does not sound as a solid plan for me. To me, this looks like a fundamental issue somewhere in the planner that is being swept under the rug by ad-hoc fixes.

Actually, I was able to reproduce this even on 3.5.12 with other queries, so if I can provide you more info about my data and queries, please tell me what to look for. I am very much interested in this fixed. I believe that a planner in a decent DBMS should never "fail", this is strictly worse than producing non-optimal solutions.

**Comment by Hunterness** [comment]
Hi again, 

For now we have "fixed them as they come up" since we need to do a bigger refactoring of the whole planner to get to the real bottom of this. We plan to invest some time in the upcoming months for this but it has not been prioritized for the 4.0 release.

If you have a query and example data that shows the exception, please open a new issue with that so we can try and fix it as well. Before looking at each specific case we don't know what the real issue is so I can't really point you anywhere. It still feels like a good idea to patch the issues we can before we have the time and resources to really look into the planner.

Our planner is a IDP (Iterative Dynamic Programming), which is an algorithm for solving complex optimization problems in an efficient way. It is based on this paper `Iterative Dynamic Programming: A New Class of Query Optimization Algorithms` by Donald Kossmann and Konrad Stocker if you are interested in learning more about it. It has the unfortunate issue of not always finding a solution.

Best Regards,
Therese
Team Cypher

**Comment by craigtaverner** [comment]
@maksbotan We absolutely agree that it is not acceptable for the IDP planner to fail entirely to find a solution. The design and intent of this algorithm is to speed up planning at the risk of finding less optimal solutions but always find some solution. However there are an infinite number of possible Cypher queries that could exist, and it turns out that in a few rare cases of very complex queries, the optimizations built into IDP (at least our implementation of IDP) have resulted in dead-ends, and the error you have found here.

It has happened a few times that others have found cases like this, and each time we have used the case to figure out what kind of dead-end the planner is finding, and work out a way to ensure that the failing query and similar queries that might conceivably fail for the same reason will work in future.

So the work to improve the IDP algorithm is not ad-hoc fixes, but it does need to be driven by the discovery of the particular complex query that can trigger such a case. And each time we are looking to use the case to understand if there are any further conceivable cases where dead-ends can occur, with the goal of never having such cases.

In the meantime, it might interest you to know that there are some config settings that can influence the IDP planner, and reduce the chance of your query failing. IDP is a performance optimization of DP, and there are tuning parameters that will make it behave more like DP (take longer to plan, more likely to find better plans).

There are two settings to consider and I would recommend increasing the values of both of them:

* `unsupported.cypher.idp_solver_table_threshold=128`
  * The default value if 128 forces IDP to reduce the set of possible solutions as soon as it reached 128. I would recommend doubling this to `256`.
* `unsupported.cypher.idp_solver_duration_threshold=1000`
  * The default value of 1s (`1000 ms`) forces the reduction to happen after 1 second. The choice of 1s is only that for first time users that are trying Neo4j interactively, it is nice if the planner does not take much more than 1s to find a plan for complex queries. But in a production environment, if first time planning takes much longer (10s or more) but then it runs very fast without replanning for days, no-one cares about that first-time planning. So I recommend increasing it to something like 10s.
