### ISSUE TITLE
algo.similarity.jaccard throws ArithmeticException

### ISSUE THREAD

**Issue by seyeda** [neo4j/neo4j#12363]
**Server spec:**
- Neo4j version: 3.5.12
- Graph algorithms version: 3.5.12.0 or 3.5.13.0
- Operating system: macOS Sierra

**Steps to reproduce:**
1. Install neo4j with the above spec. Don't forget to add the graph algorithms jar file.
2. Run the following cyphers to create a small sample graph
```
merge (a:Test {name:"a"})   
merge (t1:Test {name:"t1"})   
merge (t2:Test {name:"t2"})   
merge (t3:Test {name:"t3"})   
merge (t4:Test {name:"t4"})   
merge (t5:Test {name:"t5"})   
merge (t6:Test {name:"t6"})   
merge (t7:Test {name:"t7"})   
merge (t8:Test {name:"t8"})   
merge (t9:Test {name:"t9"})   
merge (t10:Test {name:"t10"})   
merge (t11:Test {name:"t11"})   
merge (t12:Test {name:"t12"})   
merge (t13:Test {name:"t13"})   
merge (t14:Test {name:"t14"})   
merge (t15:Test {name:"t15"})   
merge (t16:Test {name:"t16"})   
merge (t17:Test {name:"t17"})   
merge (t18:Test {name:"t18"})   
merge (t19:Test {name:"t19"})   
merge (t20:Test {name:"t20"})   
merge (t21:Test {name:"t21"})   
merge (t22:Test {name:"t22"})   
merge (t23:Test {name:"t23"})   
merge (t24:Test {name:"t24"})   
merge (t25:Test {name:"t25"})   
merge (t26:Test {name:"t26"})
merge (a)-[:CONNECTED_TO]->(t1)
merge (a)-[:CONNECTED_TO]->(t2)
merge (a)-[:CONNECTED_TO]->(t3)
merge (a)-[:CONNECTED_TO]->(t4)
merge (a)-[:CONNECTED_TO]->(t5)
merge (a)-[:CONNECTED_TO]->(t6)
merge (a)-[:CONNECTED_TO]->(t7)
merge (a)-[:CONNECTED_TO]->(t8)
merge (a)-[:CONNECTED_TO]->(t9)
merge (a)-[:CONNECTED_TO]->(t10)
merge (a)-[:CONNECTED_TO]->(t11)
merge (a)-[:CONNECTED_TO]->(t12)
merge (a)-[:CONNECTED_TO]->(t13)
merge (a)-[:CONNECTED_TO]->(t14)
merge (a)-[:CONNECTED_TO]->(t15)
merge (a)-[:CONNECTED_TO]->(t16)
merge (a)-[:CONNECTED_TO]->(t17)
merge (a)-[:CONNECTED_TO]->(t18)
merge (a)-[:CONNECTED_TO]->(t19)
merge (a)-[:CONNECTED_TO]->(t20)
merge (a)-[:CONNECTED_TO]->(t21)
merge (a)-[:CONNECTED_TO]->(t22)
merge (a)-[:CONNECTED_TO]->(t23)
merge (a)-[:CONNECTED_TO]->(t24)
merge (a)-[:CONNECTED_TO]->(t25)    
merge (a)-[:CONNECTED_TO]->(t26)
merge (b:Test {name:"b"}) 
merge (b)-[:CONNECTED_TO]->(t1)
```
3. Find jaccard similarity between nodes `a` and `b`:
```
match (a:Test {name:"a"})-[ie:CONNECTED_TO]->(t:Test)
with [{item:id(a), categories: collect(distinct id(t))}] as source_data, collect(distinct id(a)) as source_id
match (b:Test {name:"b"})-[ie:CONNECTED_TO]->(t:Test)
with [{item:id(b), categories: collect(distinct id(t))}] as target_data, source_data, source_id, collect(distinct id(b)) as target_id
CALL algo.similarity.jaccard(source_data+target_data, {similarityCutoff:0.01, sourceIds:source_id , targetIds: target_id, write:true, writeRelationshipType:'SIMILAR', writeProperty: 'jaccardSimilarity'})
YIELD nodes, similarityPairs, write, writeRelationshipType, writeProperty, min, max, mean, stdDev, p25, p50, p75, p90, p95, p99, p999, p100
return nodes, similarityPairs, write, writeRelationshipType, writeProperty, min, max, mean, stdDev, p25, p50, p75, p90, p95, p99, p999, p100
```

**Expected behaviour:**
Returns jaccard similarity between the two nodes and add an edge of type `SIMILAR` between the nodes

**Actual behaviour**
Throws an exception and shows the following error message:
`Failed to invoke procedure algo.similarity.jaccard: Caused by: java.lang.ArithmeticException: / by zero`

**Further explanation**
I noticed that if I set the `similarityCutoff` threshold to zero or `write` to False, it works. Or if I use `algo.similarity.jaccard.stream`, it will still work. It looks like when it needs to add the a new edge to the graph then it fails. 
If I use version 3.5.11 of the graph algorithms library, it seems to work.

* As a side note, I noticed that if I set the `similarityCutoff` to zero, it never writes the result back to the graph. This is not documented in neo4j manual. In fact there are some examples in the manual for `algo.similarity.jaccard.stream` where `similarityCutoff:0.0` which makes you to think that you can do the same with `algo.similarity.jaccard`

**Comment by Mats-SX** [comment]
Hello @seyeda and thank you for your very extensive bug report.

I think we caught you also on the Neo4j community forums, but I'll reply similarly here. We have productised an algorithm dubbed `Node Similarity` which is designed to replace the algorithm you're reporting on here. It is our recommendation to try and use the Node Similarity algorithm instead, to try and get away from the errors.

We are currently planning on making this replacement de facto with the new version of the library that we are currently developing and which is planned to be coming out sometime early in the next year. Therefore we may not try and fix the implementation of this at all. If it turns out that Node Similarity does not suit your use case at all, please tell us and we'll consider whether to retain both algorithms side by side, which we currently would not do.

All the best
Mats

**Comment by seyeda** [comment]
Hi @Mats-SX 
Thanks for your reply. Based on what you said and the responses I got in the community forums, I am going to try `Node similarity` algorithm and see how it goes. At least from its description I can say it will work.

**Comment by Mats-SX** [comment]
Very good. I will close this issue for now, but you can always reach back here if anything else fails.

**Comment by fixbravo** [comment]
> We are currently planning on making this replacement de facto with the new version of the library that we are currently developing and which is planned to be coming out sometime early in the next year. Therefore we may not try and fix the implementation of this at all. If it turns out that Node Similarity does not suit your use case at all, please tell us and we'll consider whether to retain both algorithms side by side, which we currently would not do.

Hello @Mats-SX ,

May I suggest that you do keep algo.similarity.jaccard in the future versions of the library ? The ability to do an index-based property filtering of the nodes before running the algorithm is quite useful given the fact that the complexity of the algorithm is quadratic.

Best regards,

Fix

**Comment by Mats-SX** [comment]
Hello @fixbravo

We have now opened up our open source repository for the GDS library here: https://github.com/neo4j/graph-data-science. If you don't mind, please create an issue there if you have feature requests or bug reports, and we will process them.

For `algo.similarity.jaccard` we have opted to keep the function version around, which you can read about in the [GDS Manual](https://neo4j.com/docs/graph-data-science/current/alpha-algorithms/jaccard/). Since Node Similarity has a significant overlap with the previous algorithm version of Jaccard for which there was a procedure in the Graph Algorithms library, we chose to remove it, as we expect use cases to be covered by the new algorithm. If the combination of the function and the new algorithm doesn't work for you, please let us know more about your use case and we will have a think about options.

Sincerely
Mats
