### ISSUE TITLE
Subqueries: returning values behaves inconsistently

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j#12378]
Returning values from subqueries seems to work inconsistently across nodes and properties

**Neo4j Version:** 4.0.0

### Steps to reproduce

```
call {
match (n:Person)-[:ACTED_IN]->(m) return m
union
match (n:Persin)-[:DIRECTED]->(m) return m
}
return m.title
```
works as expected but

```
call {
match (n:Person)-[:ACTED_IN]->(m) return m.title
union
match (n:Persin)-[:DIRECTED]->(m) return m.title
}
return m.title
```

produces
```
Variable `m` not defined (line 6, column 8 (offset: 120))
"return m.title"
```

### Expected behavior
Returning `m.title` should not produce an error

### Actual behavior
This error is returned
```
Variable `m` not defined (line 6, column 8 (offset: 120))
"return m.title"
```

**Comment by InverseFalcon** [comment]
I don't believe we allow `m.title` as a valid variable name within a query. This fails for example because a period isn't allowed in the variable name:

```
WITH 1 as m.title
RETURN *
```

As a convenience, in a RETURN, we do allow a projection expression to be used as the variable name, but it's not allowed as a valid variable in any other circumstance (where it could possibly be referenced elsewhere in the query).

I think we would recommend aliasing as a different variable (with a valid variable name) in your subquery.

Note that you can escape the variable name if you do need it in a similar format. This works:

```
call {
match (n:Person)-[:ACTED_IN]->(m) return m.title as `m.title`
union
match (n:Persin)-[:DIRECTED]->(m) return m.title as `m.title`
}
return `m.title`
```

**Comment by luanne** [comment]
@InverseFalcon okay, thanks. Would be great to have this in the docs for subqueries

**Comment by sherfert** [comment]
I think we should enforce aliasing in `RETURN` clauses inside of subqueries to generate better error messages. Thanks for the bug report @luanne !

**Comment by fickludd** [comment]
We have now (effective from `4.0.1`) changed the sub-query semantics to require an alias for any sub-query return item which it not a simple variable. This will generate a much better error message (`Expression in CALL { RETURN ... } must be aliased (use AS)`) for this query, which should help anyone else running into this problem.

Thanks again for reporting, I'm closing the issue.
