### ISSUE TITLE
cypher projection doesn't work?

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#12376]
`$ pip3 show neo4j` = 1.7.6

Script
```
write_lpa = """
CALL algo.labelPropagation(
  'MATCH (n) RETURN id(n) AS id',
  'MATCH (n)-->(m) RETURN id(n) AS source, id(m) AS target',
  {graph: "cypher"})
"""

with driver.session() as session:
    session.write_transaction(lambda tx: tx.run(write_lpa))
```

Error
```
CypherSyntaxError: Type mismatch: expected String but was Map (line 5, column 3 (offset: 126))
"  {graph: "cypher"})"
```

I think it's looking for the 3rd argument to the label projection as seen below, which runs successfully.
```
write_query = """
CALL algo.labelPropagation(
  'NodeClass', 
  'RelClass',
  'OUTGOING',
  {iterations:10, partitionProperty:'partition', write:true})
YIELD nodes, iterations, loadMillis, computeMillis, writeMillis, write, partitionProperty;
"""
```

**Comment by technige** [comment]
Transferred issue as this is not driver-related.

**Comment by s1ck** [comment]
@HashRocketSyntax There are two variants of label propagation in the library (at least in the version you're using): `CALL algo.labelPropagation(STRING, STRING, STRING, MAP)` and `CALL algo.beta.labelPropagation(STRING, STRING, MAP)`. If you use the latter, it should work as expected. 

That being said, we're currently working on an improved API that will be released soon, docs will of course be aligned with that.

**Comment by ghost** [comment]
@s1ck Thank you for letting me know. Is that API a Q1 thing?

I've been formatting projection calls based on these docs
https://neo4j.com/docs/graph-algorithms/current/projected-graph-model/cypher-projection/

**Comment by ghost** [comment]
For now, I am just going to use a cypher query to `SET` many longitudinal `:labels`. Then use those to run the `label propagation` method. Then pull the labels off again because neomodel does not like them.

**Comment by Mats-SX** [comment]
@HashRocketSyntax Yes, Q1.

**Comment by ghost** [comment]
Here is a use case to help advocate for cypher projection.

I've run into a situation where I need to dig my weight out of a json field `{"0": weight, "1": weight, "2": weight}` (greatly over simplified). I'll either need to query it out somehow with a cypher projection, or refactor my Object Graph Model to create a node for each of those 0,1,2 and reconstruct the edges of the whole network around each of them.

**Comment by Mats-SX** [comment]
@HashRocketSyntax We now have another location for issues relating to the GDS library: https://github.com/neo4j/graph-data-science

The new API you asked about is available in a preview release which you can find there. The preview documentation can be found at https://neo4j.com/docs/graph-data-science/preview/

I would kindly ask that you raise a new issue at that repository and then we will process it in normal fashion. [Cypher projection](https://neo4j.com/docs/graph-data-science/preview/management-ops/cypher-projection/) is a supported feature so any bug reports or feature requests are welcome.

Due to that, I will close this issue.
