### ISSUE TITLE
Missing doc for config "unsupported.cypher.idp_solver_table_threshold"

### ISSUE THREAD

**Issue by fabio-s-franco** [neo4j/neo4j#12434]
I am getting this error:

> Neo4jError: Unfortunately, the planner was unable to find a plan within the constraints provided.
> Try increasing the config values `unsupported.cypher.idp_solver_table_threshold`
> and `unsupported.cypher.idp_solver_duration_threshold` to allow
> for a larger sub-plan table and longer planning time.

However I cannot find these settings in the documentation configuration reference. The only reference about this config that I found was here: https://neo4j.com/developer/kb/manually-migrating-configuration-settings-from-neo4j-2x-to-neo4j-3x/

- Neo4j version: 4.0.2 enterprise
- Operating system: Origianl neo4j docker image
- API/Driver: NodeJS 4.0.1
- **Steps to reproduce**: N/A this is about documentation
- Expected behavior. Documentation be present
- Actual behavior. Documentation absent

**Edit**

This cypher triggers it:
```
MATCH (p:elements:Person{polyglotID:'79224171-10e7-4162-a062-bded2c200572'})
OPTIONAL MATCH (p) -[:has]->(av:elements:Avatar)
CALL apoc.create.node(['Creation', 'Model', 'Personal'], {name: $name, polyglotID: $polyglotID, createdBy: $createdBy, identifierProperty: $identifierProperty, userLabels: $labelNames}) YIELD node as m
WITH *
UNWIND $modelItems as modelItem CALL apoc.create.node(['Artefact', 'ModelItem', 'Personal'], {name: modelItem.name, polyglotID: modelItem.polyglotID, identifierProperty: modelItem.identifierProperty, userLabels: modelItem.labelNames, createdBy: $createdBy}) YIELD node as mi
WITH mi,m,p,av
MERGE (mi) <-[:contains]-(m) RETURN m{.*, createdByPerson: p{.*, avatar:av.polyglotID},  assignees: []}
```

**Comment by SaschaPeukert** [comment]
Hej @fabio-510,

Thanks for reporting this issue. We don't want to publicly advertise using those config settings because unnecessarily tweaking them could result in unfavorable planning behavior (e.g. longer planning times). Thus we would like to not add them to the documentation as indicated by the `unsupported` prefix.

Having said that, I would like to take a look at this query that triggers this unfortunate planner timeout. Could you provide us with
-  your used parameters 
- a sample dataset where this bug appears in or graph statistics ( look at the `db.stats.*`procedures in https://neo4j.com/docs/operations-manual/current/reference/procedures/ ) 

so that I can recreate the problem in the correct environment?

Thank you,

Sascha Peukert
Neo4j Cypher team

**Comment by SaschaPeukert** [comment]
Since there was no update, I am gonna close this for now. Reopen it if you want to pursue this further.

**Comment by fabio-510** [comment]
Apparently the issue was on a cypher just before that one:

`MATCH (m:Elements:`09d39560-3ef6-4add-b7a8-8b66d75fa051`:Creation:Model{polyglotID:$polyglotID})`

We dynamically inject the label "09d39560-3ef6-4add-b7a8-8b66d75fa051" and apparently using a verbatim string triggers this problem. Removing the backticks resolved the issue. So I guess that's the real issue behind it. This should throw a compile time error or a better run-time error.

**Comment by ibsmfar** [comment]
> Thanks for reporting this issue. We don't want to publicly advertise using those config settings because unnecessarily tweaking them could result in unfavorable planning behavior (e.g. longer planning times). Thus we would like to not add them to the documentation as indicated by the `unsupported` prefix.

However, we can readily configure them if we want to right?
