### ISSUE TITLE
Neo4j hangs by a heavy write operation

### ISSUE THREAD

**Issue by dj9966** [neo4j/neo4j#12511]
- Neo4j version: Community3.5.7
- Operating system: RedHat 7.2 
- API/Driver: (Spring Data Neo4j)

Dear all,
We met a big problem recently. Sometimes when user commit a heavy write operation(about create/remove 30000 relationship),the neo4j instance hangs and could not accept request anymore, can't even login from the command line.We have to restart the instance.
After monitoring the linux system,we found out the db connnections increased dramatically from 50 to 200+. We dumped the stack of neo4j process and found out about 200 threads in BLOCKED status
[stack_397682.txt](https://github.com/neo4j/neo4j/files/4621355/stack_397682.txt)

So our question are:
1.Seems write operation will lead in a write lock and block other read operations?After checking chapter "[Transaction management](https://neo4j.com/docs/java-reference/current/transaction-management/)", I think read operation will not be affected by the write operation so long as not adding a read lock explicitly(we use transaction provided by Spring Data Neo4j and didn't add any lock explicitly)
2.From the stack log, we can see some operations acquired read lock("getRWLockForAcquiring"), so how could I find out these operations which involve read lock in?
3.From the stack log, we can see a thread held the lock by (locked <0x0000000580bc4a80>) "CommunityLockClient.terminateAllWaiters" and so many other threads were waiting the lock for "CommunityLockClient.terminateAllWaiters" too,so why "terminateAllWaiters" held the lock so long and didn't release it?

Thanks a lot in advanced
Zhe Dong

**Comment by ghost** [comment]
Related issue: https://github.com/neo4j/neo4j/issues/12357

**Comment by burqen** [comment]
@dj9966 Hi! Thank you for reporting.

The thread currently holding the lock on the synchronous community lock manager is in progress of releasing locks and most of the other threads are waiting for this to finish. They are not necessarily waiting for the locks help by this thread but they are waiting to access the lock manager itself. The thread holding that structure does not seem to be stuck however and should progress. We could confirm this if you could provide multiple stack traces or a JFR recording.

1. Yes, in some scenarios read operations need to take read locks. In this case it is because we need to make sure that the set of indexes and constraints doesn't change while we are executing the query.
2. Exactly which operations that need read lock is not documented, at least not to my knowledge.
3. From only this stack trace we don't know how much time that thread spend in "terminateAllWaiters", but if you can provide more stack traces taken within some time intervall of a JFR recording we might figure that out.

If you have the option to upgrade to Enterprise version there is an asynchronous lock manager available that I think would help with this problem.

In any case, I think what you actually need help with is tuning your queries and workload and I would recommend reaching out to the neo4j community for that. There are a lot of neo4j experts there that are happy to help. https://community.neo4j.com/

**Comment by burqen** [comment]
Closing inactive issue. Please, feel free to re-open if needed.
