### ISSUE TITLE
Server no longer accepts writes during a large dataset load and create cypher statement

### ISSUE THREAD

**Issue by bugzyz** [neo4j/neo4j#12562]
We are using a 3 cores + 2 replicas in our scenario. 
Now, We are trying to load a 300mb dataset file and create some edge based on the dataset file using a cypher statement shown below.
`
CALL apoc.load.csv("http://<ip>/datasets_incremental/output_100000000/edge.PHONE",{header:false, delimiter:","}) YIELD list AS lineMATCH (a:CUST_ID {id: line[0] }), (b:PHONE {id: line[2] })CREATE (a)-[r:PHONE]->(b)RETURN count(r);
` 
When the edge.PHONE file is small, like below 100mb. It’s easy to load the data into db. But when the file is large large like 1.5GB, it will failed with the “server xxx no longer accepts write operation” error.

**Comment by graphadvantage** [comment]
Try wrapping this in apoc.periodic.iterate, and set batchSize to 10000, parallel false

**Comment by bugzyz** [comment]
Hi! Thanks! It does work! 👍 

I have two question about this procedure, that:
1. What's the reason that the “server xxx no longer accepts write operation” error interrupt this update operation that occurs before?
2. I used parallel:true on the node creation and it's fine. But when I use parallel:true on the edge creation, an error message shown as below picture. What's the reason that cause such error message. Is it unavailable for user to use parallel:true on the edge creation?
![image](https://user-images.githubusercontent.com/31982774/89308206-93bf7480-d6a4-11ea-8403-63b64b940a0e.png)

**Comment by bugzyz** [comment]
The 3rd question is that,
How to deal with the cluster leader crash during the iteratively update since half of the creation are already available in the database before the crash?

**Comment by AbhishekTripathi** [comment]
4 years and counting :) Similar issues on Neo4j 5

**Comment by mnd999** [comment]
This is a very old issue, which probably should be closed due to inactivity. It's likely the original issue was due to the bulk load generating a large amount of transaction state and causing the database to run out of memory. In common with many transaction systems, it is good practice to batch loads into smaller transactions to avoid using too much memory for the transaction state, which is what `apoc.periodic.iterate` is doing for you here. 
Since this issue was raised, we also introduced [`CALL {} IN TRANSACTIONS`](https://neo4j.com/docs/cypher-manual/5/subqueries/subqueries-in-transactions/) to make this easier.

@AbhishekTripathi If you are having similar problems and you think you've found a bug, I would suggest opening a new issue with all the details, or if you're looking for help reach out in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j).
