### ISSUE TITLE
Composite index causes "Cursor cannot be cast to class org.neo4j.kernel.impl.newapi.EntityIndexSeekClient" exception on certain queries

### ISSUE THREAD

**Issue by vleipnik** [neo4j/neo4j#12582]
**Neo4j version**: 4.1.1
**Operating system**: macOS Catalina
**API/Driver**: JavaScript

### Steps to reproduce

Add an index on two properties, like this `CREATE INDEX ON :obj(x, y)`.

Run this query: 
`
match (:obj {x: 'x',y: 'y'})<-[:z]-(:obj {y: 'y'})-[:z]->(k {y: 'y'}) with collect(k) as ks match (:obj {x: 'x',y: 'y'}) return *
`

### Expected behavior

No errors.

### Actual behavior

This exception:
`
 [Neo.DatabaseError.Statement.ExecutionFailed]: class org.neo4j.cypher.internal.runtime.ValuedNodeIndexCursor cannot be cast to class org.neo4j.kernel.impl.newapi.EntityIndexSeekClient (org.neo4j.cypher.internal.runtime.ValuedNodeIndexCursor and org.neo4j.kernel.impl.newapi.EntityIndexSeekClient are in unnamed module of loader 'app'), reference cfd8b95a-993d-439c-9189-3109502d896e.
`

**Note**: 
Running `DROP INDEX ON :obj(x, y)` makes the query execute fine, without errors.

**Comment by pontusmelke** [comment]
Hi @vleipnik, thanks for reporting this. This problem was solved in a recent commit and should be available in the next point release of neo4j. As a temporary workaround you can run the query with `CYPHER runtime=slotted` prepended to your query.

I'll close this issue, but feel free to reopen or open a new one should the problem come back.

Regards,
Pontus

**Comment by vleipnik** [comment]
Thanks for the reply and the workaround @pontusmelke!
