### ISSUE TITLE
Relationship isomorphism bug

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j#12584]
- Neo4j version: 4.1.1
- Operating system: MacOS 10.15.6
- API/Driver: Cypher

### Steps to reproduce

First, create sample data:

    CREATE (a:X {id:'a'}), (b:X {id:'b'})
    CREATE (a)-[:BAR {id: 'ab'}]->(b)
    CREATE (b)-[:BAR {id: 'ba'}]->(a)

Then run this non-directional query:

    MATCH (:X)-[r]-(:X)
    RETURN r

And compare the results with the results from this directional query:

    MATCH (:X)-[r]->(:X)
    RETURN r

### Expected behavior

  Both queries will have 2 result rows (with each relationship appearing just _once_).

### Actual behavior

  The non-directional query actually returns 4 rows, with each relationship appearing _twice_, which violates [relationship isomorphism](https://neo4j.com/docs/cypher-manual/current/introduction/uniqueness/#cypher-result-uniqueness).

**Comment by mnd999** [comment]
Hi @cybersam, thanks for the report. We've looked at it and we believe the current behaviour is correct. The query is non-directional so it will traverse the relationship in both directions. The results are thus:

```
a, r1, b
a, r2, b
b, r1, a
b, r2, a
```

Relationship isomorphism  applies at result record level, that is to say if one result record contains multiple relationships, e.g. because your query returns a path or RETURN r1, r2  those cannot be the same relationship. In this case each of the four rows constitutes a separate result record and none of them contain more than one relationship.
