### ISSUE TITLE
Node Count as Negative Number...  Neo4j version:3.5.14

### ISSUE THREAD

**Issue by kethan6028** [neo4j/neo4j#12600]
<img width="504" alt="Screenshot 2020-10-01 at 5 12 03 PM" src="https://user-images.githubusercontent.com/47622869/95211964-d1f32480-080a-11eb-94b3-c270486caace.png">
When I try to fetch the number of nodes in my neo4j instance,its giving me a negative number.
Neo4j version:3.5.14
OS : Neo4j is running as a pod on openshift 4.3
Expected Result : 894
Actual Result: -901

**Comment by mnd999** [comment]
Thanks for the report, this doesn't look correct. Are you able to provide us with some stats about your data using the `CALL db.stats.retrieve("GRAPH COUNTS")`?

**Comment by kethan6028** [comment]
@mnd999 thanks for responding..
[graph_count.txt](https://github.com/neo4j/neo4j/files/5364295/graph_count.txt)
I have attached a file with some stats on my data..since data changes in the db changes every hour..I couldn't give the exact information..
[https://stackoverflow.com/questions/64170948/neo4j-gives-node-count-as-negative](url)
Not just the node count but also node labels are not working properly.Please refer to the stackoverflow question I posted for the same issue.
This has become a major issue in my application. Please suggest what can we do to avoid it..Thanks 👍

**Comment by tinwelint** [comment]
Hello, I come to think of a bug which was recently fixed and that could result in counts less than expected, even negative when deleting self-relationships or deleting relationships for nodes that has self-relationships. But this query above shouldn't be affected by this since it's only looking at the number of nodes, not relationships.

May I take a guess and say that your counts store has become corrupt for some reason. What you could try to do is to shut down the database, delete the files: `neostore.counts.db.a` and `neostore.counts.db.b` and start the database again. On that startup those counts files will be rebuilt from the actual graph store and should therefore be correct.

**Comment by tinwelint** [comment]
Would you be able to run a consistency check on your store? You should be able to use something like `neo4j-admin check-consistency` for that check.

**Comment by kethan6028** [comment]
@tinwelint thanks for responding.
Today we cleared everything(deleted the whole volume) then did a fresh installation then it started working..like u said counts.db.* must have corrupted.
But any idea on the scenarios when they get corrupted.
Thanks

**Comment by tinwelint** [comment]
The counts store should not become corrupted under any type of workload or scenario, so that's a bit odd. However the counts store has had a number of issues in its life time and was therefore rewritten in 4.0 and is now considered much more stable and safe.

So you don't have the corrupted database or counts store left somewhere for potential post-mortem forensics? That is if you would even be OK w/ sharing it.

**Comment by tinwelint** [comment]
If not then there cannot be much more done than to close this issue, wdyt?
