### ISSUE TITLE
not founded neo4j 4.1.4 tag.

### ISSUE THREAD

**Issue by shifeiluo** [neo4j/neo4j#12620]
Since Neo4j 4.1.4 has released,  neo4j 4.1.4 tag not founded.

**Comment by jennyowen** [comment]
It usually takes around 24 hours after we do a release before the image is available in docker. This is because it has to be manually submitted to the docker team through a github PR, then go through a test and approval process on their side.

Neo4j 4.1.4 is available on dockerhub now: https://hub.docker.com/_/neo4j?tab=description

Thank you for taking the time to report the issue though!
