### ISSUE TITLE
cypher order by DESC not effective with two USING INDEX

### ISSUE THREAD

**Issue by ghost** [neo4j/neo4j#12626]
- Neo4j version: 4.2.0
- Operating system: (Ubuntu 18.04)
- API/Driver: (Cypher)
- Expected behavior: ORDER BY DESC on both indices
- Actual behavior: ORDER BY DESC applied to first only, ORDER BY ASC to the 2nd one

```
PROFILE MATCH (ti:TransferIn)-[:Transfers]->(t:Transfer)-[:Transfers]->(to:TransferOut)
USING INDEX ti:TransferIn(from_address, timestamp)
USING INDEX to:TransferOut(to_address, timestamp)
USING JOIN ON t
WHERE ti.from_address='xxxx1' and ti.timestamp>0 
and to.to_address='xxxx2' and to.timestamp>0
RETURN t
ORDER BY ti.from_address DESC, ti.timestamp DESC, to.to_address DESC, to.timestamp DESC
LIMIT 1
```

![image](https://user-images.githubusercontent.com/5498561/99589588-31238780-29ba-11eb-8a71-1d70aa5ff6a1.png)

**Comment by mnd999** [comment]
Thanks for the report, we'll take a look at it and get back to you.

**Comment by sherfert** [comment]
@ymzz277 Could you please post the complete PROFILE output? Preferably from using `cypher-shell` and not the browser, but from the browser would be OK, too.

**Comment by sherfert** [comment]
@ymzz277 

We can't really analyze if this is actually a bug without more information.

My assumption is that there has to be a `Sort` operator that comes after the `NodeHashJoin`. 
Your full `ORDER BY` clause cannot be solved by joined `IndexSeek`s. Therefore a `Sort` becomes necessary, and then the planner is free to choose any index ordering since the rows will be re-sorted later anyway.
