### ISSUE TITLE
rss is going up all the time

### ISSUE THREAD

**Issue by he7g** [neo4j/neo4j#12627]
neo4j version: 3.5.20

My app load data by switch DB, start new DB, and shutdown old DB.  But, I found the Resident Set Size (rss) is going up all the time, but jvm heap is normal, off-heap is also normal.  I don't know why...  

BatchInserter is used to import data, and use embedded DB to load it.

This problem is still existing, after #12623 problem has been solved by the workaround way (LifecycleListener, Reflection) .

**Comment by he7g** [comment]
Use gperftools, the mem result are as follow files, `12.pdf` is twelfth dump file, `13.pdf` is thirteenth dump file, `12-13.pdf` is compare dump file between 12 and 13.  I think that memory is leaked.

[12.pdf](https://github.com/neo4j/neo4j/files/5580956/12.pdf)
[12-13.pdf](https://github.com/neo4j/neo4j/files/5580957/12-13.pdf)
[13.pdf](https://github.com/neo4j/neo4j/files/5580958/13.pdf)

**Comment by he7g** [comment]
@mnd999 Please take a look at this issue, and confirm whether it's a bug. Thanks!

**Comment by he7g** [comment]
The `dbms.memory.pagecache.size` has been set, but it does not like `MaxDirectMemorySize`, neo4j use `Unsafe` to `allocateMemory`, not `DirectByteBuffer`, So `MaxDirectMemorySize` won't trigger FGC when direct memory is overflow.  And it seems that `dbms.memory.pagecache.size` has not limiting function within `GrabAllocator`, so the off-heap is going up all the time...  

Am i right? @tinwelint @PetrJanouch

**Comment by he7g** [comment]
And, i found other probable bug:
`UnsafeUtil.allocateMemory(long bytes, MemoryAllocationTracker allocationTracker)` will call `allocateMemory( bytes )` that calls `GlobalMemoryTracker.INSTANCE.allocated( bytes )`,  and `UnsafeUtil.allocateMemory(long bytes, MemoryAllocationTracker allocationTracker)`  also will call `allocationTracker.allocated( bytes );` ， so,  allocated will be tracker twice... 

```
    public static long allocateMemory( long bytes, MemoryAllocationTracker allocationTracker ) throws NativeMemoryAllocationRefusedError
    {
        final long pointer = allocateMemory( bytes );
        allocationTracker.allocated( bytes ); // here
        return pointer;
    }
    public static long allocateMemory( long bytes ) throws NativeMemoryAllocationRefusedError
    {
        final long pointer;
        try
        {
            pointer = unsafe.allocateMemory( bytes );
        }
        catch ( Throwable e )
        {
            throw new NativeMemoryAllocationRefusedError( bytes, GlobalMemoryTracker.INSTANCE.usedDirectMemory(), e );
        }

        addAllocatedPointer( pointer, bytes );
        GlobalMemoryTracker.INSTANCE.allocated( bytes );  // here 
        if ( DIRTY_MEMORY )
        {
            setMemory( pointer, bytes, (byte) 0xA5 );
        }
        return pointer;
    }
```

**Comment by tinwelint** [comment]
Hi @hebelala I'll look into this, thanks for reporting!

**Comment by he7g** [comment]
> Hi @hebelala I'll look into this, thanks for reporting!

How is it going on?

**Comment by he7g** [comment]
I found, after `System.gc()`, the RSS goes down.   Neo4j embedded DB wont release memory when shutdown?    And all the unreleased memory wont trigger FGC?

**Comment by PetrJanouch** [comment]
@hebelala Sorry for the long delay.

We use direct memory for page cache and currently the page cache memory is released in phantom reference handling. It is done so, because when the server is used in an embedded deployment as a library if someone shuts down the DBMS it is very hard for us to check that there is no way the page cache memory cannot be touched. An example would be if an application thread shuts down the DBMS while another application thread still uses its transaction. If we release the memory as part of DBMS shutdown, such incorrect use of the API might lead to a segfault in an edge case (if other threads are working with the page cache when the shutdown is called).

The page cache memory will not be released until there is a GC which if of course triggered by heap occupancy. So there is an edge case when the RSS  can go up when the DBMS is started and shutdown without generating enough stuff on the heap to trigger GC. You have already figured out that using an explicit System.gc() is a workaround for this.

We had a long discussion about this, but as I already explained this is a segfault territory and starting and shutting down the DBMS without GC being triggered is very rare (it has been like this for years and you are the first user reporting issues with it), so we decided to keep it as it is.

**Comment by he7g** [comment]
@PetrJanouch "An example would be if an application thread shuts down the DBMS while another application thread still uses its transaction" -- The situation wont be happened in my app, because we switch DBMS **gracefully**, the code is as follow:  
```
private volatile GraphDatabaseService graphDatabase;
private ConcurrentHashMap<Thread, GraphDatabaseService> threadGraphDbMap = new ConcurrentHashMap<>();

public GraphDatabaseService acquireGraphDb() {
	Thread thread = Thread.currentThread();
	threadGraphDbMap.putIfAbsent(thread, graphDatabase);
	return threadGraphDbMap.get(thread);
}

public void releaseGraphDb() {
	threadGraphDbMap.remove(Thread.currentThread());
}

public synchronized void switchDB() {
	GraphDatabaseWrapper oldGraphDatabase = graphDatabase;
	graphDatabase = createNewGraphDb();
	if (oldGraphDatabase != null) {
		shutdownGraphDbGracefully(oldGraphDatabase);
	}
}

private void shutdownGraphDbGracefully(GraphDatabaseService theGraphDatabase) {
	while (threadGraphDbMap.containsValue(theGraphDatabase)) {
		try {
			Thread.sleep(200L);
		} catch (InterruptedException e) {
			Thread.currentThread().interrupt();
			break; // break, will still try to shutdown db
		}
	}
	theGraphDatabase.shutdown();
}
```

In my opinions, the old shutting down DBMS should recycle itself stuff. The API should provide the ability to shutdown gracefully at least. The incorrect use of the API, like the example you said, should be due to the user, but not the API.

In other side, the explicit `System.gc()` will influence the app services beacause of STW.

**Comment by PetrJanouch** [comment]
I am not disputing that you use the API correctly, but we cannot punish the users who don't by segfaulting.
