### ISSUE TITLE
The eager operator causes a huge unnecessary waste of resources in the query of matching two points and creating edges

### ISSUE THREAD

**Issue by Northwo** [neo4j/neo4j#12647]
## The eager operator causes a huge unnecessary waste of resources in the query of matching two points and creating edges
In my graph ,there are 60,047,435 nodes，i want to find two nodes to create a edge between them,but it cost a long time to finish this job. the i find out this query will product a large Cartesian product result which includes 3,605,694,450,079,225 node pairs. but acually one node pair is enough. so i think it could probably be optimized。

"match (m),(n) create (m)-[r]->(n) return r limit 1"
In the execution plan of this command, the parent of the Cartesian product operator is a eager operator , which leads to a huge Cartesian product intermediate result, but this is not necessary,
![image](https://user-images.githubusercontent.com/32172201/103086930-f1873580-4620-11eb-9df6-b6938e1e3f59.png)

**Comment by mnd999** [comment]
Thanks for the report, we'll take a look at it and get back to you.

**Comment by sherfert** [comment]
@Northwo 

When I execute the following query `PROFILE MATCH (m), (n) CREATE (m)-[r:R]->(n) RETURN r LIMIT 1` in neo4j 4.2 I get this profile output:

```
+-------------------+----------------+----------------+------+---------+------------------------+
| Operator          | Details        | Estimated Rows | Rows | DB Hits | Page Cache Hits/Misses |
+-------------------+----------------+----------------+------+---------+------------------------+
| +ProduceResults   | r              |              1 |    1 |       0 |                    0/0 |
| |                 +----------------+----------------+------+---------+------------------------+
| +Limit            | 1              |              1 |    1 |       0 |                    0/0 |
| |                 +----------------+----------------+------+---------+------------------------+
| +Create           | (m)-[r:R]->(n) |        1000000 |    1 |       2 |                    2/0 |
| |                 +----------------+----------------+------+---------+------------------------+
| +CartesianProduct |                |        1000000 |    1 |       0 |                    0/0 |
| |\                +----------------+----------------+------+---------+------------------------+
| | +AllNodesScan   | n              |           1000 |    1 |       2 |                    1/0 |
| |                 +----------------+----------------+------+---------+------------------------+
| +AllNodesScan     | m              |           1000 |    1 |       2 |                    1/0 |
+-------------------+----------------+----------------+------+---------+------------------------+
```

There is no `Eager` operator. Are you worried about the performance of the `CartesianProduct`?

---

As a side node: The amount of relationships this query creates is non-deterministic in 4.2. It will usually only create one relationship, but that is nothing you should rely on. Especially since that behavior is going to change from version 4.3 onward, where it will make sure all side effects _before_ a `LIMIT` are executed to completion.

If you intend to create exactly one relationship, you should rewrite your query to: `MATCH (m), (n) WITH m, n LIMIT 1 CREATE (m)-[r:R]->(n) RETURN r`.
