### ISSUE TITLE
`size(...) <= x` misbehaving

### ISSUE THREAD

**Issue by patrickkwang** [neo4j/neo4j#12641]
**Neo4j Version:** 4.2.1
**Operating System:** MacOS 11.0.1
**API:** Docker, Neo4j Browser

### Steps to reproduce:
```
CREATE (:a)-[:AB]->(:b), (:a)
MATCH (n) WHERE size( (`n`)-[]-() ) <= 1 RETURN count(*)
```

### Expected:
3

### Actual:
1

---

```
MATCH (n) WHERE (size( (`n`)-[]-() ) < 1) OR (size( (`n`)-[]-() ) = 1) RETURN count(*)
```
gives the expected 3 rows.

**Comment by mnd999** [comment]
Thanks for the report. We're investigating it now. Can you confirm whether you're using the Community or Enterprise editions?

**Comment by patrickkwang** [comment]
I'm using the Community edition.

**Comment by mnd999** [comment]
Thanks, it definitely looks like a bug in the interpreted runtime which would be active for this query in the community edition. I see you have a workaround, but another would be to use the enterprise edition from Neo4j Desktop until we fix it.

**Comment by pontusmelke** [comment]
@patrickkwang Thanks for reporting this. The bug has been fixed and will be rolled out with the next update. If you need an urgent (and for us somewhat embarrassing) workaround you can use `size( (`n`)-[]-() ) < 2` instead of `size( (`n`)-[]-() ) <= 1` in your query.

I'll close this now but don't hesitate to reopen or open a new issue if there are any other issues.

Regards,
Pontus
