### ISSUE TITLE
Neo4j Status Codes “Effect on transaction” docs incorrect

### ISSUE THREAD

**Issue by johannessen** [neo4j/neo4j#12651]
I think this is a documentation bug.

According to [Neo4j Status Codes](https://neo4j.com/docs/status-codes/4.2/), all `ClientError`s cause a **rollback** on transactions. But as of Neo4j 4.2.1, this is not in fact the case.

### Steps to Reproduce
1. Begin new HTTP transaction.
2. Try to access the new transaction without the correct credentials.
3. Try to access the new transaction _with_ the correct credentials.

For example:
1. **Begin new transaction**   
   Request:  
   ````
   POST http://localhost:7474/db/neo4j/tx HTTP/1.1
   Authorization: ...
   
   {"statements":[]}
   ````
   Response:  
   ````
   201 Created
   Location: http://localhost:7474/db/neo4j/tx/20
   
   {"results":[],"errors":[], ...}
   ````
2. **Access without the correct credentials**   
   Request:  
   ````
   POST http://localhost:7474/db/neo4j/tx/20 HTTP/1.1
   
   {"statements":[]}
   ````
   Response:  
   ````
   401 Unauthorized
   
   {"errors":[{"code":"Neo.ClientError.Security.Unauthorized","message":"No authentication header supplied."}]}
   ````
3. **Access _with_ the correct credentials**   
   Request:  
   ````
   POST http://localhost:7474/db/neo4j/tx/20 HTTP/1.1
   Authorization: ...
   
   {"statements":[]}
   ````

### Expected Behaviour

Following [RFC 7235](https://tools.ietf.org/html/rfc7235#section-3.1), which states that a `401` response “indicates that the request has not been applied”, the expected result at step 3 would be **success** because the transaction has remained open at step 2.

Following [Neo4j Status Codes](https://neo4j.com/docs/status-codes/4.2/), which states that all `ClientError`s have a “rollback effect on transaction”, the expected result at step 3 would be **failure** because the transaction was closed due to `Neo.ClientError.Security.Unauthorized` at step 2.

### Actual Behaviour

Success, as per the RFC:

````
200 OK

{"results":[],"errors":[], ...}
````

I’d argue that this behaviour of the Neo4j server is in fact correct and that the status code documentation should be fixed accordingly.

- - -

This issue begs the question whether further cases exist in which the transaction should be closed according to [Neo4j Status Codes](https://neo4j.com/docs/status-codes/4.2/), but does in fact remain open.

It occurs to me that an HTTP 4xx or 5xx response should probably **never** imply a transaction rollback. Conceptually, these seem to relate to the network status, while the database status is handled on a higher layer. Would this be a reasonable assumption for HTTP driver implemeters?

**Comment by gjmwoods** [comment]
Hi @johannessen. Firstly, many apologies for the long delay in getting back to you on this one.

I agree this is an issue with the docs. The one you've linked to appears to be a more generic one that doesn't apply completely to HTTP. We'll update the docs with something more specific section in the HTTP docs.

In case you're curious, this happens because each request that is received first passes through an auth mechanism before reaching the code that actually handles the transaction execution.  Therefore this is the only error the deviates from that doc page. 

Worth noting is that this first check only ensures that you are an authenticated user. After you pass that step and move on to the transaction handling part you could experience a `ClientError` (specifically a `Neo.ClientError.Security.Forbidden`) if you are not authorized and that would have the effect of rolling back the transaction.

I think your final assertion is a reasonable one, this case being a good marker. 

Many thanks!

**Comment by johannessen** [comment]
Hey @gjmwoods, thank you for getting back to me! The details you mention in your explanation are very helpful. It makes sense to me that a 401 gets special treatment.
