### ISSUE TITLE
Implicit group key when mixing aggregation and none-aggregation  functions in a single expression

### ISSUE THREAD

**Issue by swilly22** [neo4j/neo4j#12653]
Neo4j version: 4.2.1

`docker run -p7474:7474 -p7687:7687 -e NEO4J_AUTH=neo4j/s3cr3t neo4j`

Initial graph:
`CREATE (:N {v:2}), (:N {v:1}), (:M {v:2}), (:M {v:3})`

Query 1:
`MATCH (n:N), (m:M) RETURN n.v + m.v + count(m)`
Result: `[6, 6, 4]`

Query 2:
`MATCH (n:N), (m:M) RETURN n.v + count(m) + m.v`
Result: `[6, 6, 4, 5]`

Expecting both queries to return the same result-set `[6, 6, 4]` Assuming group key is: `n.v + m.v`

**Comment by mnd999** [comment]
Thanks for the report, we'll take a look at it and get back to you.

**Comment by swilly22** [comment]
http://www.opencypher.org/articles/2017/07/27/ocig1-aggregations-article/

**Comment by InverseFalcon** [comment]
The article is a good one.

I ran your query and actually got back a slightly different result set, so you may want to double-check your nodes and results:

```
╒══════════════════════╕
│"n.v + count(m) + m.v"│
╞══════════════════════╡
│5                     │
├──────────────────────┤
│6                     │
├──────────────────────┤
│4                     │
├──────────────────────┤
│5                     │
└──────────────────────┘
```

Your misassumption is that `n.v + m.v` is the grouping key; it is not.

In the second query, there are two components to the grouping key: `n.v` and `m.v`, and this is also why there are 4 result rows instead of 3.

We can see this if we return each component instead of summing them:

```
MATCH (n:N), (m:M) 
WITH n.v as nv, count(m) as count, m.v as mv
RETURN nv, count, mv, nv + count + mv as sum
```

```
╒════╤═══════╤════╤═════╕
│"nv"│"count"│"mv"│"sum"│
╞════╪═══════╪════╪═════╡
│2   │1      │2   │5    │
├────┼───────┼────┼─────┤
│2   │1      │3   │6    │
├────┼───────┼────┼─────┤
│1   │1      │2   │4    │
├────┼───────┼────┼─────┤
│1   │1      │3   │5    │
└────┴───────┴────┴─────┘
```

It looks as though the order of operations was used for the term. In your first query, it was able to sum `n.v + m.v` before it got to the aggregated term, so the combined value became the grouping key. The second query ran into the aggregation on the second term. In order to add `n.v` to `count(m)`, n.v would have to be a grouping key. In order to add the result of that to `m.v`, `m.v` had to be a grouping key.

The takeaway from this is: don't try to be clever. When performing operations on an aggregation term during the aggregation, or doing other complex things like applying a function to an aggregation, the grouping keys may become harder to discern. So avoid the complexity, keep the aggregated term simple (no nesting functions, no operations performed to it), and wait until after the aggregation to do that.

For example:

```
MATCH (n:N), (m:M) 
WITH n.v + m.v as grouping, count(m) as count
RETURN grouping + count
```

Or if you want to use each separately as part of grouping key:

```
MATCH (n:N), (m:M) 
WITH n.v as nv, m.v as mv, count(m) as count
RETURN nv + mv + count
```

Keep the aggregation term simple and the grouping key will always be clear, and you won't have trouble with your query.

**Comment by thobe** [comment]
@swilly22 As you have seen from the 2017 article, the inference of what the grouping key is when the result of an aggregation function is part of a larger expression ranges from confusing to ambiguous. It also breaks commutativity of normally commutative operators.

Evidently this problem has been known for quite a while without being adressed. This is because it has mainly been a theoretical problem. It just has not been something that users have struggled with in practice (my guess is because users avoid such ambiguous constructs in their queries, and instead express their queries using the methods @InverseFalcon has outlined).

Based on this report we had a discussion at Neo4j about what we think should be done about this issue, and came to the conclusion of disallowing such ambiguous aggregation expressions, and force the user to express the aggregation separately from the calculation that involves it in order to make the grouping key clear.

We will propose to the openCypher Implementors that rejecting such aggregation expressions should be the official openCypher behaviour, and issue warnings for such aggregations in Neo4j.

**Comment by swilly22** [comment]
Thank you @InverseFalcon , @thobe 
I think this is a good compromise

Can we expect a formal definition describing what is considered legal aggregated expression e.g. `sum(n.a) + count(n.b)` ?

Would you consider enforcing this at the grammar / parser level or would you consider this to be a query validation?

**Comment by thobe** [comment]
@swilly22 that is a very useful question.

Since both `sum(n.a)` and `count(n.b)` are aggregations, neither of them would be part of the inferred grouping key, even if stated separately and not composed through addition as in your example.

This means that the grouping key would be the same for:

```
WITH sum(n.a) + count(n.b) AS res, x, y, z
```

 as it would for:

```
WITH sum(n.a) AS sna, count(n.b) AS snb, x, y, z
WITH sna + snb AS res, x, y, z
```

in both cases the inferred grouping key would be `x, y, z`.

Because of that, I personally think it is good to err on the side of restrictive, and have openCypher allow only the latter of the two - i.e. only allow a single aggregation in an aggregating expression.

When it comes to enforcement, I would think this is easier and more future proof to enforce through query validation. That is at least the approach I am confident Neo4j will take, since Neo4j supports user defined aggregators, which means the grammar can't know what is an aggregation and what is a function.

**Comment by LinneaAndersson** [comment]
@swilly22 In neo4j 5.x implicit grouping keys are no longer accepted, as it was very confusing like in the example above. You can read more about aggregation functions here: https://neo4j.com/docs/cypher-manual/current/functions/aggregating/ 

I will close this issue, let us know if you have any other questions that you would like us to answer,
Linnéa
