### ISSUE TITLE
Neo4j ETL Tool struggles with complex datamodels

### ISSUE THREAD

**Issue by beslu** [neo4j/neo4j#12668]
Hi, I have tried to use the ETL tool (1.5.1) to create a mapping to our legacy system running on Oracle db.
The seems to be that the ETL tool tries to analyze every table and relations/constraints in the database that has 800+ tables and countless constraints. 

The analyze process times out or have to be killed before producing a result. I think it would be sensible to break up the analyze part into several steps; list tables in the schema, let user select which tables to proceed with and then do the full depth analyze on the selected tables!

I would hope that when a mapping is created for a database, I could reuse the mapping for other identical databases that have a different name. We have many databases that have the same datamodel

**Comment by mnd999** [comment]
Thanks for the report. Unfortunately though, it looks like it relates to the neo4j-etl labs tool. This tool lives in a separate repository, so please re-raise your issue there: https://github.com/neo4j-contrib/neo4j-etl/issues 

Unfortunately, due to it being in a separate org, I am not able to transfer this issue across. If this is incorrect, please feel free to re-open this issue and we will investigate further.
