### ISSUE TITLE
TransactionImpl#nodesByLabelAndProperties scans all nodes with label if no index matches properties exactly

### ISSUE THREAD

**Issue by ivangreene** [neo4j/neo4j#12702]
The [current implementation of `TransactionImpl#nodesByLabelAndProperties`](https://github.com/neo4j/neo4j/blob/4.2/community/kernel/src/main/java/org/neo4j/kernel/impl/coreapi/TransactionImpl.java#L744-L772) will scan all nodes with a label if there are no indices that include all of the query properties and no other properties. It should be optimized to use partially matching indices (indices which have a subset of the query properties, or which have extra properties, or both), and further filter matches if necessary.

This method is used by several methods on Transaction, including `findNodes(Label, Map<String, Object>)`, `findNodes(Label, String, Object)`, etc. This can result in significant performance problems when using these methods with a set of properties that does not match an index exactly.

**Neo4j Version:** current (applies to at least 4.2.x, 4.1.x)
**Operating System:** all
**API:** Java API

### Steps to reproduce
1. Create an index on a node label: `CREATE INDEX FOR (n:Person) ON (n.given_name)`
2. Create a large amount of data
3. Try to find nodes using `transaction.findNodes(Label.label("Person"), Map.of("given_name", "foo", "surname", "bar"))`

### Expected behavior
The partially matching index for given_name should be used, resulting in a performant fetch operation

### Actual behavior
The index for given_name will not be used, which results in scanning all nodes (this can be verified by setting a breakpoint on TransactionImpl line 771, where it returns `return getNodesByLabelAndPropertyWithoutIndex( labelId, queries );`)

**Comment by ivangreene** [comment]
I am testing out an internal workaround for this issue, but it only uses indices which contain a subset of the query properties (and not indices which contain properties not in the query): I was unable to find a way to build an index query where some fields could be missing or have any value. That might be a speedbump in the way of using indices which have extra properties

**Comment by craigtaverner** [comment]
If you use Cypher, you will get the advantages of a more advanced query planner, which should use the index you expect. From the java API this might look like:

    transaction.execute("MATCH (n:Person) WHERE n.given_name = 'foo' AND n.surname='bar' RETURN n");

The lower level API for `findNodes` is not quite that clever. This could be a performance enhancement for them to consider, but would not be seen as a bug.

**Comment by ivangreene** [comment]
@craigtaverner thanks for the suggestion. While I haven't tried executing Cypher like this as a drop in replacement for findNodes, the reason we are using these Java APIs instead of executing Cypher is mostly for performance reasons. In this case, I am using findNodes as part of a re-implementation of MERGE semantics, because I found that calling `transaction.execute("MERGE (n:Person { ... }")` was much slower than using the Java APIs

**Comment by craigtaverner** [comment]
@ivangreene The thing is that `MERGE` is slow for a reason. It is pretty hard to ensure that `MERGE` will never create duplicate nodes in a high-concurrency server environment, so a lot of extra work is involved in multiple index lookups and taking locks. If you do not need that level of assurity, then handling the merge in your own code could be fine, and would certainly be faster. But if you want to be sure, then you might have to take the performance cost...

If you do go this route and implement your own merge, then replacing `findNodes` with `execute` should still be a good idea because I believe the overheads of Cypher itself are not in any way the primary problem with the performance you faced with `MERGE`.

**Comment by ivangreene** [comment]
@craigtaverner thanks for the insight. I will definitely experiment with this when I get a chance. As of now our merge reimplementation has been sufficient, but Andrew on the neo4j Slack gave me some ideas on how to make it more robust, which I haven't gotten around to testing yet

**Comment by PetrJanouch** [comment]
@ivangreene
I think the question about index selection in core API has 2 parts:

1. why do we not select a composite index that partially matches?
For example there is a composite index on a last_name and first_name and just last_name is used in find method.
The reason why we cannot use such index has a technical background. Currently our indexes don't contain null values. So a user with just last_name set and first_name set to null will not be in such a composite index, so if we used such index when just last_name is used in find method, we could potentially miss some results (users with no first name). And correctness is of course a priority for us. Indexes containing null values is a planned improvement and it might make it as soon as 4.4. When index contains null values, we could use the index in the example above.

2. why do we not select an index that has less properties than used in the find method?
The reason why we don't do this is because of the philosophy of Core API. The Core API is simple and does just exactly what it is told to do without any planning or smartness. If you want a sophisticated planner to pick an appropriate index for you, use Cypher. The reason why partial matches are not that easy is for instance the question what to do if more than one index partially matches. For instance, what if there is an index on last_name and another one on first_name and both last_name and first_name are used in the find method? How do we select the appropriate index? Cypher planner uses index statistics to choose, but that is definitely not something we want to do in the Core API.
The reason why we don't need to find a solution to this non-trivial problem is that you can always do something like this:
`
findNodes(Label.label("Person"), Map.of("last_name", "foo")).stream()
.filter( node -> node.getProperty("first_name").equals("bar"))
...
`
The important point is that the core API methods don't return fully materialised Entities, but live references to the graph (In other words, find method just returns a stream of pointers), so doing something similar to the example above does not entail more overhead than whatever we could do on our side of the Core API (Basically using index on last_name and than filtering the index results based on first_name property loaded from the store).

Does it make sense?

**Comment by ivangreene** [comment]
@PetrJanouch thanks for the explanation.

1. This makes a lot of sense. It would indeed be bad to miss data, and given this limitation it sounds like there is currently no possible benefit to using an index with other properties not included in the query, because to ensure accuracy we would have to scan through all nodes to find those with missing values anyway.

2. The distinction between Core API and Cypher makes sense. Wanting to maintain a simple API without adding the complexity of bringing in concepts such as index statistics is understandable. However, there isn't a performant way to use this without burdening business logic code with knowing details about our indices. Using the example, we shouldn't have to be aware that we have an index only on last_name and must query by that first. So I, and perhaps others, are still in need of an extra layer here to keep the querying simpler.

Would the team be interested in accepting a PR to use partial indices without diving into index statistics? In this case choosing an index arbitrarily (ordered by most properties to least properties, no tie breaker)

**Comment by PetrJanouch** [comment]
@ivangreene Sorry I missed your answer in 4.3 completion frenzy.
The Core API is not meant to be a high level API with many convenient utility methods for common tasks like for instance ORMs/OGMs . Maybe the mistake was giving findNodes method with property parameters such a generic name. People have false hopes about what it does. A better name would be findNodesUsingIndexOverSubmittedProperties or something like that, because that is its purpose. Its purpose is not being a convenience method for  `.filter( node -> node.getProperty("first_name").equals("bar"))` or equivalent.

Anyway. We would prefer to keep the Core API as smartness-free and straightforward as it is now.
