### ISSUE TITLE
Wrong info in console when changing dbms.default_listen_address to 0.0.0.0

### ISSUE THREAD

**Issue by jiangying000** [neo4j/neo4j#12701]
- Neo4j version: 4.2.4
- Operating system: Ubuntu 18.04
- API/Driver: N/A

**Steps to reproduce**
- set `dbms.default_listen_address=0.0.0.0` in neo4j.conf
- start neo4j with `neo4j console`

Expected behavior
- see  `INFO  Remote interface available at http://0.0.0.0:7474/` stdout

Actual behavior
- see `INFO  Remote interface available at http://localhost:7474/` in stdout

**Comment by gjmwoods** [comment]
Hi @djy0. Firstly sorry for the delay in responding.

The log line displays the value that is set for `dbms.default_advertised_address` since there can be a difference between the address you want to bind to and the address that you wish to advertise as the address you should use to connect.

If you set that to the same value as the listen to address then you should see what you are expecting.

Hopefully, that helps!

**Comment by jiangying000** [comment]
thanks
