### ISSUE TITLE
Fixed-length path expansion performance issue

### ISSUE THREAD

**Issue by maximAtanasov** [neo4j/neo4j#12759]
- Neo4j version: 4.3.1
- Operating system:  Windows 10 1909
- API/Driver: Neo4j Browser

Using the LDBC-SNB dataset with a scale factor of 10 and running the following query:
`MATCH (p1:Person {id: $personId})-[:KNOWS*3]->(p2:Person) RETURN DISTINCT p2`
causes it to take an enourmous amount of time. The query planner seems to start the expansion from `p2` and not `p1`. The following is the result of profiling (the image is somewhat broken, as the first step of the plan is at the bottom, but it always seems to bug out for long running queries. The amount of db hits seems to have overflown as well).
![plan](https://user-images.githubusercontent.com/32562426/128627003-2714c3f5-e77a-4684-9f32-cdfd2e5c1725.png)

This matches the execution plan from `EXPLAIN`:
![plan (2)](https://user-images.githubusercontent.com/32562426/128627063-29269b99-7313-4da8-b964-1435587c14d6.png)

If the query is rewritten in the following ways:
    `MATCH (p1:Person {id: $personId}) WITH p1 LIMIT 1 MATCH (p1)-[:KNOWS*3]->(p2:Person) RETURN DISTINCT p2`
    `MATCH (p1:Person {id: $personId})-[:KNOWS*3]->(p2:Person) USING SCAN p1:Person RETURN DISTINCT p2`
or if an index is created on the id property, then the planner creates a correct plan and the query finishes in seconds.
This only happens with fixed-length paths. Variable length paths `[:KNOWS*1..3]` do not have this issue, however they can be rewritten using APOC procedures,  whereas fixed length paths cannot. Changing the runtime or planner does not lead to a different plan.

I have not tested, whether the same bug appears with other labels or in other datasets.

EDIT: This happens for variable length queries that do not start from 0/1 as well:

`MATCH (p:Person {id: $personId})-[:KNOWS*3..7]->(p2:Person) RETURN DISTINCT p2`

**Comment by mnd999** [comment]
Thanks for the report, we'll investigate and get back to you.

**Comment by hedengran** [comment]
Thank you again for the report. I've investigated and reached the following conclusion.

This seems to be an unfortunate case where our cost-model gets things wrong.

The cost model was between version `4.2` and `4.3` updated to better reflect the cost of accessing properties, which is why starting on `p2` now seems cheaper according to the model (we do the filtering much later in that case, so there will be less rows to filter on).

We still believe that the updates to the cost model were correct and had a positive effect on the majority of cases. In this case, I think that the correct solution is to expect that an index is created to provide the planner with more data, leading to a more informed decision when deciding on a plan.

**Comment by maximAtanasov** [comment]
I understand. Thank you for looking into this.
