### ISSUE TITLE
client is unauthorized due to authentication failure

### ISSUE THREAD

**Issue by aoleiReiz** [neo4j/neo4j#12772]
### I create container use this command 
`docker run -p7474:7474 -p7687:7687 --name neo4j_container -e NEO4J_AUTH=neo4j/AIRocks -v C:/Users/aolei.bao/neo4jdata/data:/data`

then I use python try to connect, it failed
from py2neo import Graph

g = Graph("bolt://localhost:7687", auth=("neo4j", "AIRocks"))

print(g)

py2neo.errors.ClientError: [Security.Unauthorized] The client is unauthorized due to authentication failure.

**Comment by jennyowen** [comment]
`NEO4J_AUTH` only sets the initial password. If the data was already created with another password then `NEO4J_AUTH` will do nothing (otherwise, that would of course be a huge security hole).
Basically, the database in `C:/Users/aolei.bao/neo4jdata/data` was created with a password that is NOT `AIRocks` and so you're denied access.
