### ISSUE TITLE
WARNING saying IBM Java is not a supported Java Runtime

### ISSUE THREAD

**Issue by geoghegk** [neo4j/neo4j#12791]
When running Neo4J community with IBM Java, a WARNING is displayed in the logs suggesting the Java runtime is not supported. 

**Neo4j version**: 4.3.7
**Operating system**: All
**API/Driver**: Docker

### Steps to reproduce
  - Start NeoJ community 4.3.7 using IBM Java 11 (AKA Semeru) (from https://www.ibm.com/support/pages/java-sdk-downloads) 

### Expected behavior
  -  NeoJ starts normally without errors or warnings
### Actual behavior
  - Following WARNING is shown in the logs:
```
WARNING! You are using an unsupported Java runtime.
* Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.
```
 
The following line in the code has a regex to check the runtime.
https://github.com/neo4j/neo4j/blob/1403c9d2396c3009958d017b3d24640b6d220e2e/packaging/standalone/src/main/distribution/shell-scripts/bin/Neo4j-Management/Invoke-Neo4jUtility.ps1#L312

This may be failing because IBM Java has changed how it reports itself, and now reports runtime as : `Eclipse OpenJ9 VM`

```
./java -version
openjdk version "11.0.13" 2021-10-19
IBM Semeru Runtime Open Edition 11.0.13.0 (build 11.0.13+8)
Eclipse OpenJ9 VM 11.0.13.0 (build openj9-0.29.0, JRE 11 Mac OS X amd64-64-Bit Compressed References 20211021_224 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 2d83aa3b76 based on jdk-11.0.13+8)
```

**Comment by klaren** [comment]
Hello and thank you for the report.

IBM is not considered to be a supported runtime. For a list of supported ones have a look at https://neo4j.com/docs/operations-manual/4.3/installation/requirements/#deployment-requirements-software

Supported means that we run extensive testing on that particular JVM. Currently, we have no specific tests for IBM Semeru, but odds are that everything will work anyway since they all should be compatible.

I know we have users that run Semeru, and to my knowledge, no one have reported any issues.
