### ISSUE TITLE
Neo4j transaction log did not rotate

### ISSUE THREAD

**Issue by aleksanderlech** [neo4j/neo4j#12807]
## Bug report

Hello, we recently had to restart the database that went into unhealthy state and recovery process started that took 2days.
When I checked the transaction logs directory it turned out that we have one file there with 250MB and another one reaching around 5TB.

I was confused since I thought the database uses default rotation of 250MB. Whats more it should only log transactions withing last 7 days as `NEO4J_dbms_tx__log_rotation_retention__policy` was set to `false`.

I would not mind also having some hint on how to safely get rid of this big file as the disk size is close to its limit.

**Neo4j Version:** 4.3.7-community
**Operating System:** Ubuntu 16
**API:** Docker

### Expected behavior
- The transaction log will be rotated every 250MB
- After full database recovery old transaction logs should be deleted

### Actual behavior
- Transaction log will rotate according to the default value used (250MB)
- After recovery old transaction log would be pruned

I don't really know whether it's easy to reproduce but I am attaching full debug.log, docker-compose, docker logs and the view on the transaction log directory content (sorry for images instead of text but this is what I got from the customer).

[neo4j_bug_report.zip](https://github.com/neo4j/neo4j/files/7791634/neo4j_bug_report.zip)

**Comment by emmaholmbergohlsson** [comment]
Hi @aleksanderlech
The provided debug log only seems to cover the recovery, but some observations.
There seems to have been a lot of transactions recovered (16675239), to cut down on any recovery time you could look into you checkpoint strategy. Fewer transactions between checkpoints would reduce the recovery time.
To keep two transaction log files when `NEO4J_dbms_tx__log_rotation_retention__policy` is `false` is expected behavior.

What is not expected though is that the second file has grown past the threshold. Are you sure `dbms.tx_log.rotation.size` is not set?
A first thing to try can be to set `dbms.tx_log.rotation.size` with https://neo4j.com/docs/operations-manual/4.3/configuration/dynamic-settings/#dynamic-settings-procedure and doing a write transaction to see if that triggers the rotation.

**Comment by aleksanderlech** [comment]
Hey,
That's correct, unfortunately, the original log was deleted by admins to save space when it was running out :(
I am sure that this rotation.size setting was not there as I did not even know about it before.

After restarting the database and recovery being done it did not delete the file even after forcing checkpoint. After some time it was pruned though - maybe it's not the checkpoint but some transaction caused by the query I wrote caused the prune but it's still a mystery for me.

**Comment by emmaholmbergohlsson** [comment]
Log pruning is triggered by checkpointing, but no logs would be pruned if there only existed 2 transaction log files. A minimum of two files are kept, so log pruning would only happen after log rotation had created a third transaction log file. A write transaction can trigger log rotation. So I would guess a transaction triggered log rotation and then the oldest transaction log file was deleted after the next checkpoint.

Is the log rotation working correctly now after the restart so you are getting transaction log files of about 250 MB?
Without logs or a way to reproduce the issue I don't think we'll be able to find the root cause to the problem you saw.

**Comment by aleksanderlech** [comment]
I agree that it might be hard to reproduce that so I don't mind closing and reopening when it happens again.
It was set to default so it should and does maintain files of maximum size of 250MB when I checked the last time.

**Comment by emmaholmbergohlsson** [comment]
Okay, lets go with that, please reopen if it happens again
