### ISSUE TITLE
operator associativity

### ISSUE THREAD

**Issue by czpmango** [neo4j/neo4j#12815]
**Environment**
- Neo4j version: 4.2.4
- Operating system: macOS
- API/Driver: cypher-shell

**Steps to reproduce**
- Expected behavior
```
neo4j@neo4j> return 1=1=true;
+----------+
| 1=1=true |
+----------+
| TRUE     |
+----------+

neo4j@neo4j> return (1=1)=true;
+------------+
| (1=1)=true |
+------------+
| TRUE       |
+------------+
```
- Actual behavior
```
neo4j@neo4j> return 1=1=true;
+----------+
| 1=1=true |
+----------+
| FALSE    |
+----------+

neo4j@neo4j> return (1=1)=true;
+------------+
| (1=1)=true |
+------------+
| TRUE       |
+------------+
```

**Comment by czpmango** [comment]
If the operator priorities are the same, shouldn't the default operator associativity be left-first?

**Comment by tobias-johansson** [comment]
Hi, @czpmango 
This is actually the expected behavior. Chains of `=` and `<>` are treated [in a special way](https://neo4j.com/docs/cypher-manual/current/syntax/operators/#cypher-operations-chaining) in Cypher.

This means that  `1=1=true` is equivalent to `1=1 AND 1=true` and not `(1=1)=true` nor `1=(1=true)`

**Comment by czpmango** [comment]
> Hi, @czpmango This is actually the expected behavior. Chains of `=` and `<>` are treated [in a special way](https://neo4j.com/docs/cypher-manual/current/syntax/operators/#cypher-operations-chaining) in Cypher.
> 
> This means that `1=1=true` is equivalent to `1=1 AND 1=true` and not `(1=1)=true` nor `1=(1=true)`

ACK and thanks for reply!
