### ISSUE TITLE
Different results for UNWIND with and without inner CALL

### ISSUE THREAD

**Issue by stanislav-a-frolov** [neo4j/neo4j#12828]
- Neo4j version: 4.3.3; official docker image
- API/Driver: Neo4j Browser

Hi, 

Steps to reproduce:
Run query on **empty** database:

```
UNWIND [1, 2, 3] as a
OPTIONAL MATCH (matched:Asd {v: a-1})
CREATE (created:Asd {v: a})
RETURN a, created.v, matched.v
```

Return values: 
```
a	created.v	matched.v
1	1		null
2	2		null
3	3		null
```
Then, run this query on **empty** database (query is the same, but actions are inside CALL):
```
UNWIND [1, 2, 3] as a
CALL {
    WITH a
    OPTIONAL MATCH  (matched:Asd {v: a-1})
    CREATE (created:Asd {v: a})
    RETURN created, matched
}
RETURN a, created.v, matched.v
```
Return values: 
```
a	created.v	matched.v
1	1		null
2	2		1
3	3		2
```

The latter is an expected behaviour for me after reading docs.

**Comment by HannesSandberg** [comment]
Thanks for the report. We'll take a look and get back to you.

**Comment by arnefischereit** [comment]
Hi there,

Thank you for your raising this issue.

The difference in the results that you observed stems from different semantics on how these two queries are executed.

In general, Cypher behaves as if each of the clauses is (fully) executed one after the other. That is,
- we first produce three rows with column `a`,
- then for each row we execute the optional match, finding nothing,
- then for each row we create nodes and
- then we return.

The semantics of a sub-query is different: Here all the clauses in the body of the subquery are executed in sequence for one incoming row. Therefore, the `OPTIONAL MATCH` in the second iteration can observe the changes made by the `CREATE` from the first iteration.

In fact: Cypher is usually executed in a rather lazy manner, trying to execute as few rows as possible before returning the first results to the user. Therefore, if you put `EXPLAIN` in front of your first query, you will see that the plan produced contains an operator called `Eager` that is placed there because the planner has recognized that there is a potential conflict between the `MATCH` and the `CREATE` and that at this point, we cannot execute the query lazily:
```
+--------------------------+-----------------------------------------------------------+----------------+---------------------+
| Operator                 | Details                                                   | Estimated Rows | Other               |
+--------------------------+-----------------------------------------------------------+----------------+---------------------+
| +ProduceResults@neo4j    | a, `created.v`, `matched.v`                               |             10 | Fused in Pipeline 3 |
| |                        +-----------------------------------------------------------+----------------+---------------------+
| +Projection@neo4j        | created.v AS `created.v`, cache[matched.v] AS `matched.v` |             10 | Fused in Pipeline 3 |
| |                        +-----------------------------------------------------------+----------------+---------------------+
| +Create@neo4j            | (created:Asd {v: a})                                      |             10 | Fused in Pipeline 3 |
| |                        +-----------------------------------------------------------+----------------+---------------------+
| +Eager@neo4j             |                                                           |             10 | Fused in Pipeline 3 |
| |                        +-----------------------------------------------------------+----------------+---------------------+
| +Apply@neo4j             |                                                           |             10 |                     |
| |\                       +-----------------------------------------------------------+----------------+---------------------+
| | +Optional@neo4j        | a                                                         |             10 | In Pipeline 2       |
| | |                      +-----------------------------------------------------------+----------------+---------------------+
| | +Filter@neo4j          | cache[matched.v] = a - $autoint_1                         |              5 | Fused in Pipeline 1 |
| | |                      +-----------------------------------------------------------+----------------+---------------------+
| | +NodeByLabelScan@neo4j | matched:Asd                                               |            100 | Fused in Pipeline 1 |
| |                        +-----------------------------------------------------------+----------------+---------------------+
| +Unwind@neo4j            | $autolist_0 AS a                                          |             10 | Fused in Pipeline 0 |
+--------------------------+-----------------------------------------------------------+----------------+---------------------+
```

This is done in order to preserve the semantics described earlier.

If you want to know more about the `Eager` operator, you can read [this blog post from Jennifer Reif](https://community.neo4j.com/t/cypher-sleuthing-the-eager-operator/10730) or have a look at [the operator's documentation](https://neo4j.com/docs/cypher-manual/current/execution-plans/operators/#query-plan-eager). We plan on making this behaviour more clear from the [call subquery documentation](https://neo4j.com/docs/cypher-manual/current/clauses/call-subquery/) page.

Let me know if you have any more questions.

**Comment by arnefischereit** [comment]
I will close this issue for now. If you do not think this is resolved, please comment here or open a new issue, referencing this case.
