### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by soda92** [neo4j/neo4j#12899]
CI: https://github.com/soda92/neo4j/runs/6962505386?check_suite_focus=true

I use the solution here: https://github.com/neo4j/neo4j/issues/12875#issuecomment-1114712763

but it doesn't work.

**Comment by klaren** [comment]
Hello,

According to the log, you are running `mvn -Dlicensing.skip --no-transfer-progress install`.
Maven expects the second argument to be a goal, so you have to specify `install` first.

E.g.
```
mvn install -Dlicensing.skip --no-transfer-progress
```

**Comment by soda92** [comment]
No.
https://github.com/soda92/neo4j/runs/8016016097?check_suite_focus=true

**Comment by klaren** [comment]
Alright, appears to be an issue with PowerShell: https://stackoverflow.com/questions/31166828/how-to-handle-dots-in-powershell-commands

**Comment by soda92** [comment]
It finally runs, but failed.
https://github.com/soda92/neo4j/actions/runs/2933586723
It always fails... How do **You** build it? Is it fully open source? Or you release a BUGGED VERSION?

**Comment by klaren** [comment]
@soda92 There are a couple of test failures, which are flaky and will most likely pass the next run. We are trying to address all flaky tests but there will always be a few out of our 100000+ tests that will sporadically fail.

If you just want to build it you can run it with `-DskipTests`. This should always work.

Our internal pipeline looks like this:
1. Build the whole project with `mvn package -DskipTests -T2C`, abort if something does not compile.
2. Exeture all the tests with `mvn surefire:test failsafe:integration-test -Dlicense.skip -Dlicensing.skip -Dmaven.test.failure.ignore`. Note that we ignore test failures here.
3. Collect failing tests and generate a report. And as I said before, there will probably be a few that fail due to the nature of our tests.

**Comment by soda92** [comment]
OK. Thanks.
