### ISSUE TITLE
Need help with this apoc.load.json error

### ISSUE THREAD

**Issue by aditya113141** [neo4j/neo4j#12894]
Apologies if this isn't the right platform to ask this question. I am getting the error - 

 Neo.ClientError.Procedure.ProcedureCallFailed: Failed to invoke procedure `apoc.load.json`: Caused by: java.lang.NoSuchMethodError: 'com.fasterxml.jackson.core.util.JacksonFeatureSet com.fasterxml.jackson.core.JsonParser.getReadCapabilities()'

while importing a file using apoc.load.json()

I had saved the json file in the import folder of DBMS.
![WhatsApp Image 2022-06-08 at 1 20 16 AM](https://user-images.githubusercontent.com/56213335/172471417-c3978b04-8ec6-4338-8d94-cdec847401d1.jpeg)

**Comment by HannesSandberg** [comment]
Hi, thanks for the report. We will investigate and come back to you!

**Comment by Lojjs** [comment]
@aditya113141 APOC is a separate Github repo (although parts of it is shipped with Neo4j). There is a report about the same issue there https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2861. Can you check if what is written there solves the issue for you and otherwise add a comment to that one instead?

**Comment by Frenchiest-Fry** [comment]
Uninstalling Neosemantics (n10s) plugins resolves the issue.
