### ISSUE TITLE
Inconsistency with unary arithmetic operations

### ISSUE THREAD

**Issue by SeboCode** [neo4j/neo4j#12900]
I discovered an inconsistency with unary arithmetic operations. I'm not sure if it is a bug or not, but the behavior is nonetheless very unintuitive.

**Neo4j Version:** 4.4.8
**Operating System:** Arch Linux 5.18.3
**API:** Java

### Steps to reproduce
The following query returns the value `1` as expected.
```
RETURN --1
```
However, the query
```
RETURN ++1
```
results in an exception (same for combinations of unary arithmetic operations, such as `RETURN -+-+1`). Using parenthesis, i.e. `RETURN (+(+1))`, would mitigate the issue.

### Expected behavior
`RETURN ++1` returns the arithmetically correct value of `1`.

### Actual behavior
An exception is thrown.

**Comment by HannesSandberg** [comment]
Thank you for the report. We will investigate and report back to you.

**Comment by gem-neo4j** [comment]
Hi there! Thank you for writing this in to us, we took a look and whilst it does seem strange, this is intentional behaviour. We decided to not allow the chaining of unary operators e.g ---+++-+-+---++2 which leads us to only allow one unary operator (+ or -). However, it is still possible to invert a number using a minus sign. This leads us to allow a unary operator and the minus sign e.g —1 or +-1. From standard mathematical notation, there is not a plus operator, so a positive number is represented as one without the a sign. Parenthesizing the expression works as well as this supports the top-level expression inside, allowing any form of repetition. Hope this helps :)
