### ISSUE TITLE
load big csv file return error: connection reset

### ISSUE THREAD

**Issue by kasicWu** [neo4j/neo4j#12907]
- Neo4j version: 4.1.3 community
- Operating system: redhat7.6
- API/Driver: Python driver v4.2.1

neo4j config:
heap.max_size: 32g
heap.init_size: 32g
pagesize: 16g

existing data volume:
number of nodes: about 300 thousand
number of relationships: more then 400 million

load remote big csv file return connection reset error
csv size: 235m,more than 4 million lines
have index:NODE(ip)

use python api execute cypher:
load csv from 'http://***' as line
match (s:NODE {ip:line[0]}),(t:NODE {ip:line[1])
merge (s)-[r:ACCESS]->(t)
on create set r.create_time = timestamp()
on match set r.update_time = timestamp()

when the execution exceeds 3 minutes, an error is reported: Connection reset

the neo4j debug.log:
![07f06862c16ca32c1e7c596b9eb8a36](https://user-images.githubusercontent.com/48946767/179022928-f87bea31-38b0-48b9-a2ae-c666333540d3.jpg)
![d86d54f1445081866f6392c949f35d5](https://user-images.githubusercontent.com/48946767/179022969-f14c27dc-af88-43db-aa85-1ca52d08b999.jpg)
![1f6c11f1736f30e3b90697fe1ccdc59](https://user-images.githubusercontent.com/48946767/179022989-86e7c9b9-ac97-49f0-86f1-72faaa1a0682.jpg)

**Comment by mnd999** [comment]
Unfortunately Neo4j 4.1 is no longer supported, so we suggest you upgrade to a supported version. 
The issue is likely the transaction size is getting to large, please see the documentation for `USING PERIODIC COMMIT` [here](https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/#load-csv-importing-large-amounts-of-data) to batch your transactions. 

Generally we prefer to answer these types of questions in [our community forums](https://community.neo4j.com/) or on our [discord](https://discord.gg/neo4j) and you will likely get a faster response there. Github is more setup for bug reports in the product.

**Comment by kasicWu** [comment]
Thank you for your answer! @mnd999 
I tried to use "using periodic commit", but it was still the same error

Today, I want to clean up invalid data and find that a node cannot be deleted and its relationship cannot be deleted
Executing the delete statement of this node does not return results, and it has been blocked for several hours without returning
Is there a deadlock? Where can I find the lock?

Now, what should I do

**Comment by kasicWu** [comment]
open

**Comment by kasicWu** [comment]
Recover after restarting the database
I think the data should be deleted while importing the data, resulting in a deadlock.
There is no error when executing cypher program, and the lock is not released when the execution is finished.
