### ISSUE TITLE
Multiple database in community edition

### ISSUE THREAD

**Issue by alexgarel** [neo4j/neo4j#12920]
We start to use neo4j for an open source project where we will import graph, work on them, and dump them. We will have different graphs for each iteration and different iteration in parallel (those are taxonomies).

We begun working on the project with neo4j, it's cool, it match our requirements perfectly.
I was planning to have one database per taxonomy at a certain version.

But today I realized community edition only support one database ! That sounds crazy to me.
I know I can use Labels wisely to let all my separates graph live in the same database, but never the less it sound really strange.

I understand neo4j editor should be able to pay their bills and their employees, but I think having clustering, user management and so on in enterprises edition is already attractive enough for companies. Having just one database really makes it difficult to consider Neo4j CE for a production project. I speak about an open-source project.

**Describe the solution you'd like**
Make multiple database management available in community edition (just this feature). That is commands listed on https://neo4j.com/docs/cypher-manual/current/databases/

**Describe alternatives you've considered**
See above: yes I can use labels to have distinct graph. But I have no clear separation of data in this case.
Alternatively I should consider going for postgres + hierarchical query or another graph database… I suppose ! (but that would be a shame, neo4j looks like a very good match to our problem).

**Additional context**

**Comment by alexgarel** [comment]
Adding some less emotional explanations ;-)

[The project](https://github.com/openfoodfacts/taxonomy-editor/) is open source and needs to be reusable freely. That's why I don't want the project to depend on non open source feature of neo4j.

Really it's about pushing just a bit the cursor of functionality towards the community edition, at a level that seems reasonable to me and may help adoption (but of course I'm not the owner !).

If it was a feature in an AGPL version of neo4j it would be ok for me.

**Comment by jmsuhy** [comment]
I plan on releasing a plug-in that turns on multi database functionality in core (along with other ee features).  Of course if they do it in community,  then even better!

**Comment by jimwebber** [comment]
Hi @alexgarel,

Presently there are no plans to move the multi-DB feature into community edition. Usually that feature is used by SaaS customers who are Enterprise users. There's good product-market fit there.

In your case, I see that you've discounted using labels, so I think you have perhaps two choices (at least):

1. Dockerise neo4j and treat it as container-per-user.
2. Script Neo4j so that you can switch between databases in under /data

Or you could wait until @jmsuhy releases his planned plugin and hope that works for you. Neo4j welcomes community members contributing, but we won't be able to support them if they don't meet expectations.

**Comment by alexgarel** [comment]
Hi @jimwebber I'm a bit sad for your answer of course.

Dockerizing per database seem too complex too me. I don't have a per user scenario but more "per version", the idea in this project is that you do a round of edition on the graph, then submit it, and the edition is collaborative. So it would mean launching instance "on demand" which means letting the project control docker launch, thus crossing the container border, which I don't want (keep my project simple and containerized)

Thanks @jmsuhy for your offer, we will consider it.

Someone also points me to https://github.com/apache/age which might also be a good alternative for me (we are quite found of postgresql)

**Comment by bradenmacdonald** [comment]
Hey @alexgarel We have built a multi-tenant semantic knowledge base platform on top of a single Neo4j database, and it actually includes a taxonomy editor and a feature like "pull requests" where you can discuss changes to the taxonomy or data before they go live. See www.neolace.com . It's not yet completely open source, but we're planning to release the code soon. If you're still interested in this problem, I'd love to chat with you about what you're doing and could also tell you how we went about building multi-tenancy on top of a single DB; you can reach me at braden@neolace.com . (Although we use Neo4j Enterprise in production, we have carefully made sure that our platform doesn't depend on any enterprise features so that anyone can run it as a developer and contribute.)

**Comment by alireza-heidarii** [comment]
try my repo https://github.com/Alirezahr75/Multi-Instance-Neo4j-Manager 
[](https://github.com/Alirezahr75/Multi-Instance-Neo4j-Manager)

**Comment by jmsuhy** [comment]
Here are the links relating to my comment on this thread.   https://dozerdb.org and  https://github.com/dozerdb

Essentially it is an open source bootstrapping plugin (GPL) which adds multi database functionality among other features to Neo4j Community 4.4.x and 5.x.   First Alpha release is out for feedback.

**Comment by Trismegiste** [comment]
> Usually that feature is used by SaaS customers who are Enterprise users

Any single project needs at least 3 environments to work with, therefore 3 databases : `development`, `test` and `production` and I'm not going to add 'Dev', 'Test' and 'Prod' labels in the vertices, it would be a non-sense.

Too bad. After playing with neo4j for a week, it seems a good product.
