### ISSUE TITLE
[Fabric] id of node different if returned from inside or outside of subquery

### ISSUE THREAD

**Issue by ikwattro** [neo4j/neo4j#12940]
Scenario with the standard movie graph.

Take the following query  : 

```
CALL {
    USE movies
    MATCH (n) WHERE id(n) = 1
    RETURN id(n) AS id
}
RETURN id

╒════╕
│"id"│
╞════╡
│1   │
└────┘
```

However, move the `id(n)` to the last return clause

```
CALL {
    USE movies
    MATCH (n) WHERE id(n) = 1
    RETURN n
}
RETURN id(n)

╒════════════════╕
│"id(n)"         │
╞════════════════╡
│3377699720527873│
└────────────────┘
```

**Neo4j Version:** 4.4.11
**Operating System:** OS X
**API:** Docker

### Expected behaviour

Node ids should be the same independently from where they're returned

**Comment by michael-simons** [comment]
👀

**Comment by tobias-johansson** [comment]
Hi @ikwattro 
This is a known limitation in Neo4j Fabric. We've since updated the documentation of the [`id()`](https://neo4j.com/docs/cypher-manual/4.4/functions/scalar/#functions-id) function with a notice about this behavior.

In Neo4j 5 the [`id()`](https://neo4j.com/docs/cypher-manual/5/functions/scalar/#functions-id) function is deprecated in favor of the new function [`elementId()`](https://neo4j.com/docs/cypher-manual/5/functions/scalar/#functions-elementid), which does not suffer from the same limitations.

**Comment by ikwattro** [comment]
Thanks @tobias-johansson , yes I already started implementing elementId() with composite dbs. Thanks for replying.
