### ISSUE TITLE
Apache Commons Text Security vulnerabilities

### ISSUE THREAD

**Issue by verydemo** [neo4j/neo4j#12961]
![image](https://user-images.githubusercontent.com/29354679/197957359-8bfa0c70-fcfc-42c5-8fed-c201e11178df.png)
Hi, Apache Commons Text package needs to be updated, Thanks

**Comment by LukasRasmussen** [comment]
Any progress? A bit suprised that there's updates on the Docker image but no fix yet.

**Comment by klaren** [comment]
Hello, the fix is in neo4j 4.4.14, https://github.com/neo4j/neo4j/wiki/Neo4j-4.4-changelog#4414

We do not use the affected `StringSubstitutor` class from Apache Commons Text, so we are not vulnerable to the security issue.

**Comment by kixxalot** [comment]
@klaren  : 

> Hello, the fix is in neo4j 4.4.14, https://github.com/neo4j/neo4j/wiki/Neo4j-4.4-changelog#4414
> 
> We do not use the affected `StringSubstitutor` class from Apache Commons Text, so we are not vulnerable to the security issue.

1. Note that the most recent offline Neo4j Desktop (1.5.2) ships with Neo 5.1.0, which still comes with commons-text-1.9.jar 

2. Can you be more specific about this: "Updates Apoc dependencies so that transitive dependency to commons-text does not get flagged as problematic for CVE-2022-42889." - is commons-text-1.9.jar still used, and if so: how does it not get flagged as problematic anymore? Or has it been updated to 1.10?

3.  Is a workaround for us to just delete commons-text-1.9.jar from the lib folder, and put commons-text-1.10.0.jar there instead (with correct permissions obviously)?

**Comment by klaren** [comment]
1. Since we are not affected by this issue we will only update LTS releases, the current one is 4.4.
2. APOC is using commons-text, so there was a new release of APOC that used commons-text 1.10. The changelog refer to neo4j updating the bundled APOC version to the new release that uses 1.10.
3. You don't need to do anything. We do not use the vulnerable code so it's safe to ignore this warning. That being said, common-text 1.9 and 1.10 should be compatible so your suggestion of just replacing it should work.
