### ISSUE TITLE
round(-3.141592, 3, 'HALF_UP') = round(-3.141592, 3, 'HALF_DOWN') ?

### ISSUE THREAD

**Issue by jinhui-lai** [neo4j/neo4j#12972]
Neo4j Browser version: [5.0.0](https://github.com/neo4j/neo4j-browser/releases/tag/5.0.0)
Neo4j Server version: [4.4.5](https://github.com/neo4j/neo4j/wiki/Neo4j-4.4-changelog#445) (enterprise)
Build date: 2022/10/4
Operating System: win 11

The [document](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-numeric/#functions-round2) in neo4j website descripes as follows.

- HALF_DOWN:  Round towards closest value of given precision, with half-values always being rounded down.
- HALF_UP:  Round towards closest value of given precision, with half-values always being rounded up.

But when i use these two different models, it returns the same results.
```
RETURN round(-3.141592, 3, 'HALF_UP')
-3.142
```

```
RETURN round(-3.141592, 3, 'HALF_DOWN')
-3.142
```

I think it's a bug. It shoud be fixed. Thank you!

**Comment by HannesSandberg** [comment]
Thanks! We will look into this!

**Comment by Lojjs** [comment]
@jhIai This is actually not a bug, but our documentation could be clearer. We follow Java's rounding modes where a more accurate description of them can be found [here](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/RoundingMode.html). Both 'HALF_DOWN' and 'HALF_UP' means rounding to the nearest number of the given precision, unless there's a tie, when they round DOWN (towards zero) and UP (away from zero), respectively.

For -3.141592, there isn't any tie, but -3.142 is the closest number of precision 3, so that is the correct answer in both cases. 

On the other hand, for -3.1415, we do have a tie, why

```
RETURN round(-3.1415, 3, 'HALF_UP')
-3.142
```

```
RETURN round(-3.1415, 3, 'HALF_DOWN')
-3.141
```

I will improve the documentation with clearer descriptions (the one for FLOOR is actually wrong) and some more examples.

**Comment by jhIai** [comment]
Thank you!

**Comment by jhIai** [comment]
> @jhIai This is actually not a bug, but our documentation could be clearer. We follow Java's rounding modes where a more accurate description of them can be found [here](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/RoundingMode.html). Both 'HALF_DOWN' and 'HALF_UP' means rounding to the nearest number of the given precision, unless there's a tie, when they round DOWN (towards zero) and UP (away from zero), respectively.
> 
> For -3.141592, there isn't any tie, but -3.142 is the closest number of precision 3, so that is the correct answer in both cases.
> 
> On the other hand, for -3.1415, we do have a tie, why
> 
> ```
> RETURN round(-3.1415, 3, 'HALF_UP')
> -3.142
> ```
> 
> ```
> RETURN round(-3.1415, 3, 'HALF_DOWN')
> -3.141
> ```
> 
> I will improve the documentation with clearer descriptions (the one for FLOOR is actually wrong) and some more examples.

Thank you!
