### ISSUE TITLE
Correct query outputs `Type mismatch`

### ISSUE THREAD

**Issue by YuanchengJiang** [neo4j/neo4j#12990]
Neo4j version: 5.1.0
Operating system: Ubuntu 20.04
API/Driver: Cypher
Dataset: Recommendations, https://github.com/neo4j-graph-examples/recommendations

The following query is problematic: 
**`MATCH shortestPath((a:Person)-[b:DIRECTED]-(c:Movie)) WHERE id(b)>=100 RETURN b LIMIT 1`**

```
neo4j@neo4j> MATCH shortestPath((a:Person)-[b:DIRECTED]-(c:Movie)) WHERE id(b)>=100 RETURN b LIMIT 1;
Type mismatch: expected Node or Relationship but was List<Relationship> (line 1, column 64 (offset: 63))
"MATCH shortestPath((a:Person)-[b:DIRECTED]-(c:Movie)) WHERE id(b)>=100 RETURN b LIMIT 1"
                                                                ^
```
It somehow embeds the edge with a list and I need to use b[0]:
```
neo4j@neo4j> MATCH shortestPath((a:Person)-[b:DIRECTED]-(c:Movie)) WHERE id(b[0])>=100 RETURN b LIMIT 1;
+-------------------------------------------------------------------+
| b                                                                 |
+-------------------------------------------------------------------+
| [[:DIRECTED {role: "Commercial Chorus #1 (voice) (uncredited)"}]] |
+-------------------------------------------------------------------+

1 row
ready to start consuming query after 4 ms, results consumed after another 54 ms
```

**Comment by InverseFalcon** [comment]
In a shortestPath() pattern, you should be using variable-length relationships in the pattern, like:

```
MATCH shortestPath((a:Person)-[b:DIRECTED*]-(c:Movie))
```

Note the `*` here to indicate more than one relationship in the path. And in that case, `b` would refer to a list of relationships, not a single relationship, and it looks like `shortestPath()` is automatically treating it as var-length relationship such as `*..1`, mostly because it doesn't make sense to use shortestPath() for a pattern that isn't using a variable-length relationship. 

So while you ran into this strange situation, I'd point out that the query itself is wrong. You likely forgot to include the `*` to make this a variable-length relationship, or, if you wanted this to only be one relationship in the path, it's a misuse to use `shortestPath()` for this, as the path can only be of length 1, if it exists. 

If you removed `shortestPath()` then `b` would indeed refer to only one relationship, and your original predicate in the WHERE clause would have succeeded.

**Comment by YuanchengJiang** [comment]
Thanks for your reply. It makes sense to me. I will close this issue.
