### ISSUE TITLE
Grouped eager aggregation does return rows on 0-cardinality input 

### ISSUE THREAD

**Issue by fickludd** [neo4j/neo4j#13000]
- Neo4j version: 4.4.11
### Steps to reproduce
```
WITH 1 AS x
UNWIND [] AS r
RETURN x, collect(r) AS c
```

### Expected behavior
Single row with `x=1, c=[]`

### Actual behavior
No rows

This seems to be consistent if replacing UNWIND with MATCH without matches for example. The query 
```
WITH 1 AS x
UNWIND [] AS r
RETURN collect(r) AS c
```
returns a single row with `c=[]` as expected.

Submitting bug-reports is fun!

**Comment by fickludd** [comment]
Wait, is this intended behaviour? That's really confusing in that case!

**Comment by fickludd** [comment]
workaround would be
```
WITH 1 AS x
CALL {
  UNWIND [] AS r
  RETURN collect(r) AS c
}
RETURN x, c
```

**Comment by InverseFalcon** [comment]
It is intended behavior, and there are three principles that are a little obscure that make up what you're observing.

1. An UNWIND of a list yields a row per list element, so an UNWIND of an empty list means there are no rows. As such, any data on the input row is lost.
2. An aggregation, on its own with no grouping key (no other non-aggregation variables) will work on 0 rows to return a 1-row result that makes sense for the zero rows processed (a count() of 0, a collect() to an empty list, an avg() of 0, etc).
3. When a grouping key (non-aggregation term) is present when aggregating on zero rows, rows remain at zero and you get no rows as a result. This is because aggregation with a grouping key is like "per each distinct grouping key, return the aggregation across the rows with that grouping key value". As such, there are no rows to perform grouping upon.

The workaround, as you noted, allows you to get the results you want because the input rows from outside the subquery only get affected by the returned rows of the subquery. As such, the row doesn't get wiped out when rows go to 0 within the subquery, and the collect() on 0 rows ensures 1 row remains, and then this is returned from the subquery, and so 1 input row x 1 subquery output row = 1 resulting row. 

If the aggregation had not been there to bring rows back to 1, and the subquery had ended with `RETURN r` instead, then the input row would have been wiped out upon the 0-row return.

**Comment by fickludd** [comment]
Thanks @InverseFalcon,

I think I'm mostly annoyed because the language does not help me discover this subtlety because of the sneaky way that the WITH changes meaning. This started with a quite involved 25 row cypher query where I had need of the equivalent of `x` after the aggregation, though I could easily add it as a group key, and then the query stopped working. 

Please note that I spent 4 years implementing the `slotted`, `compiled` and `pipelined` runtimes, so the fact that I tripped on this really speaks against the language semantics.

**Comment by HannesSandberg** [comment]
Hello, @fickludd are you happy with the response above and should I close this issue?

**Comment by InverseFalcon** [comment]
Note that we do have a knowledge base article that goes into more depth into this with aggregating on 0 rows here:

https://neo4j.com/developer/kb/understanding-aggregations-on-zero-rows/

However it has not yet been updated to account for 4.x's subqueries, I can update that accordingly.

Personally I think the behavior is correct (as noted in the article, defaulting to `null` would lead to more problems), but also that it is unintuitive. Perhaps the official docs need a warning when it comes to aggregation with grouping keys from 0 input rows, maybe with a link to the article for the more in-depth explanation.

**Comment by fickludd** [comment]
I agree that the current semantic is the only sane one as long a `WITH` has so many functions.

I would rather encourage an eventual Cypher 2 to rework the `WITH`-clause into multiple clauses that reduce the risk for such subtle bugs (ping @boggle). Let's close the issue.
