### ISSUE TITLE
Find only indexed nodes

### ISSUE THREAD

**Issue by ns-92** [neo4j/neo4j#13024]
According to the documentation (Java embedded), the function `findNodes(...)` will look for online indexes and if there is none, it will scan all nodes with the given label(s) and property. This is convenient but will sometimes lead to slow runtime due to non-indexed nodes being searched. It would be therefore more convenient if there is a possibility to search only for indexed nodes and ignore non-indexed ones. Apologies if this feature already exists or has been asked before, in which case I would be grateful if you can give me a pointer to that. Thanks.

**Comment by burqen** [comment]
Hello @ns-92 , thank you for reaching out!
The idea with the embedded Java API (and with Cypher) is that having an index or not on your data should not change the result. E.g. if you ask for all nodes with label `Person` and name `John` then all the nodes that fit those criteria should be returned.

In the case of `findNodes(...)` you will never have a case where only parts of the result is part of the index and the rest needs to be searched. So if you have an index that fits what you are looking for with `findNodes(...)` you should be fine and no search for non-indexed nodes is needed.

If you are unsure about if you have an index that corresponds to what you are looking for with `findNodes(...)`, then let me give an example to try and make it more clear: If I want to do `findNodes(Label.label("Person"), "name", "John")` you will need an index like this:
```
CREATE INDEX
FOR (n:Person)
ON (n.name)
```

Does this help you?

**Comment by ns-92** [comment]
Dear @burqen, thanks for the response! In my use case I have to for example create and process all nodes `Person` first from the first `Village`, then create and process all nodes `Person` from the second `Village`. During these steps I sometimes need to find nodes `Person` of the current `Village` based on their `name`. Since these two partitions are similarly structured, this is what I did:

```
1. Create an index on `Person.name`
2. Create nodes `Person` from the first `Village`
3. Search for nodes `Person` with `name = John`
-> here the returned nodes are always from the first `Village`, since we only have one `Village` for now
4. Drop the index
5. Create an index again on `Person.name`
6. Create nodes `Person` from the second `Village`
7. Search for nodes `Person` with `name = John`
-> here the returned nodes are BOTH from the first and second `Village`
```

How do we make sure that in the last step only `John` from the second `Village` is returned? The current function `findNodes(...)` always returns nodes `John` from both `Villages`.

A workaround for this is to add an additional label such as `Village1` and `Village2` to each `Village` and create two separate indexes based on these labels. But this also means that every node of each `Village` must also have these exact additional labels, which is not efficient especially if we have a large number of nodes, labels and indexes.

I thought therefore it would be practical if we could also have an additional overloaded function such as:
```
findNodes(index, Label.label("Person"), "name", "John")
```
to find nodes that are indexed by `index`.

I hope my (extremely simplified) example above is clear enough.

Thanks!

EDIT: My current understanding is that indexes in neo4j only apply to nodes created after their creation. If an index is initiated after all nodes have been created, will it index all these existing nodes? If that is the case then I guess only the workaround with additional labels works for this example.

**Comment by burqen** [comment]
Hi @ns-92 I think I understand you a bit better now.

Let me first explain a little deeper how the neo4j indexes work.

An index will contain all nodes (or relationship if you are indexing relationships) with the given label and property that exist. As the index is created it will be populated with all existing data and as new changes come in (additions, deletes or updates) the index will be updated. So the index is a perfect mirror of what exists in the store at all times. So the concept of an index only containing parts of the data simply doesn't exist.

Now, about your specific domain.

If I understand you correctly you want to model Persons that in some way belong to Villages. Each Person belong to a single Village and a Village can have multiple Persons. I would model that data by having separate Person nodes and Village nodes and then have a relationship that connects each Person to their respective Village. Something like this as a simple example:
```
CREATE (v1:Village {someUniqueIdentifierForVillage:1})
CREATE (v2:Village {someUniqueIdentifierForVillage:2})
CREATE (:Person {name:"John"})-[:BELONG_TO]->(v1)
CREATE (:Person {name:"Karen"})-[:BELONG_TO]->(v1)
CREATE (:Person {name:"Ali"})-[:BELONG_TO]->(v1)
CREATE (:Person {name:"John"})-[:BELONG_TO]->(v2)
CREATE (:Person {name:"burqen"})-[:BELONG_TO]->(v2)
CREATE (:Person {name:"ns-92"})-[:BELONG_TO]->(v2)
... etc
```
Using Cypher you can then find all of the Persons belonging to a certain village using something like
```
MATCH (p:Person {name:"John"})-[:BELONG_TO]->(v:Village {someUniqueIdentifierForVillage:1})
RETURN p
```
Depending on your data and what indexes are available, Cypher will construct the optimal query plan for you and find only the Persons that belong to Village 1. Cypher queries can be passed through the embedded Java API using `tx.execute("...")`.

You could do the same thing manually with `findNodes(...)` by doing something like:
```
1. findNodes(Person, "name", "John")
2. for each found node, find all the BELONG_TO relationships: node.getRelationships(RelationshipType.withName("BELONG_TO")
3. for each of those relationships, getOtherNode(...) to get the Village
4. If the Village is the correct one, return the person node
```
You can ofc also start by finding the `Village` node and expand the other way to then filter on the name of the `Person` node. You would then probably want an index on `Village` and `someUniqueIdentifierForVillage`.

Good luck!

**Comment by ns-92** [comment]
Dear @burqen, thank you very much for your answer and explanation. Yes, I also came up with your suggestion regarding traversing the nodes after calling `findNodes(...)` but it's often not efficient and may lead to an endless loop without a proper handling of cycles in the graph. It's generally convenient that the planner will automatically find an optimal plan to find nodes based on available indexes but since I'm using Java embedded, I would like to have a better control over and overview of how nodes and relationships can be found using indexes in neo4j (if possible). 

I guess my questions boil down to:

1. Given a node, can we determine easily if it is indexed?
2. Given an index, can we easily find the list of nodes indexed by it?

I believe in the past neo4j used to allow such functionalities but somehow not anymore?

**Comment by burqen** [comment]
Hi @ns-92 , thank you for explaining.

Let me share my thoughts it :)

### Java API vs Cypher
The recommended way to use Neo4j is Cypher and the Java API should only be used when you have very specific and performance critical workloads that you cannot make work well enough through Cypher. The endless loop problem is also taken care of by Cypher.

What is your reason for using the Java API rather than Cypher? Note that both surfaces can be used with Neo4j embedded in your application.

### What is the problem you are trying to solve?
I can sympathise with wanting to have better control and overview over your system, but if it is not a means to an end it sounds like it is blocking you from making progress.

### It sounds like the problem you are dealing with is a graph modelling problem
Graph data modelling is an art; there is no “one right model” but a good model anticipates what the most common queries will be, and supports them in a performant & easy way. With that in mind, if you have a good data model, it should never arise that you have an important query and questions/concerns that it would run over un-indexed nodes.
Here are some useful guides for graph data modelling.
The "Graph Modeling" and "Graph Data Modeling" articles here: https://medium.com/@david.allen_3172 Specifically those two sounds relevant for your case https://medium.com/neo4j/graph-modeling-labels-71775ff7d121, https://medium.com/neo4j/graph-data-modeling-categorical-variables-dd8a2845d5e0

### And lastly, to answer your questions:
1. Given a node, can we determine easily if it is indexed? _Yes. If it has the label and property that matches an index, then it is indexed._
2. Given an index, can we easily find the list of nodes indexed by it? _`MATCH (n:Label) WHERE n.indexedProperty IS NOT NULL` will give you all nodes in the index for Label+indexedProperty. There is no easy way on the embedded API_

Back in Neo4j 3.x days and earlier there was another type of indexing that the user was responsible for maintaining themselves. The user would query those indexes themselves and Cypher wouldn't utilise them. Those indexes were removed in Neo4j 4.0.

**Comment by ns-92** [comment]
Dear @burqen, thank you for your answer and the helpful insight. The articles you mentioned are also very helpful.
