### ISSUE TITLE
Unexpected inconsistent results about UNWIND

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13067]
I execute two queries on my neo4j database ,and they are supposed to output same results but not.

Neo4j version:  4.4.5  Enterprise
operating system:  windows 10
API：Cypher version 9
query:   MATCH (n0) WHERE n0.id=0 UNWIND [1] as m MATCH (n1:L4),()-[r0:T4]->(),(n2) WHERE (n1)-[r0]->(n2) OPTIONAL MATCH (n0),()-[r1:T2]->(),(n3),(n2)<-[r2 :T3]-(n4 :L3) WHERE (n0)-[r1]->(n3) RETURN count(1)

The result of the above query is five,but when I remove the UNWIND clause,the result becomes one. And in theory, the UNWIND clause should not change the result.

There are my graph data:
create (:L4)-[:T4]->()<-[:T3]-(:L3);
create ({id:0})-[:T2]->(:L3);

**Comment by HannesSandberg** [comment]
Thank you! We will look into this.

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

Thank you very much for reporting this problem.

Investigating it, this seems to be a [known issue](https://github.com/neo4j/neo4j/issues/12836) on 4.4 with `OuterHashJoin`s, that has been fixed in [4.4.9](https://github.com/neo4j/neo4j/wiki/Neo4j-4.4-changelog#449).

Can you please verify whether an upgrade to a later version of 4.4.x or 5.x solves your problem?

Regards,

Arne

**Comment by ljhhuxiaoba** [comment]
Thanks very much!The problem hae been solved.
