### ISSUE TITLE
How can I view the contents of neo4j's transaction log files (neostore.transaction.db.*) (text format)

### ISSUE THREAD

**Issue by Rich-billions** [neo4j/neo4j#13088]
and understanding how transaction log files are organized

**Comment by InverseFalcon** [comment]
Just to note, these are not meant to be human readable, they aren't "logs" in the same sense as debug and query logs. They are instructions to Neo4j on how to apply transactional changes to the store files, in commit order. They won't include the cypher (if applicable) that was executed to generate the transactional changes. 

You may be better served by looking at query logs instead.

**Comment by klaren** [comment]
Hello @Rich-billions and sorry for the late reply.

There was a tool back in neo4j 3.4 that would do the thing you want: https://github.com/neo4j/neo4j/blob/3.4/tools/src/main/java/org/neo4j/tools/dump/DumpLogicalLog.java

To use it you have to build it from source. The transaction logs have not changed significantly since so looking at 3.4 databases should give you a good idea of how everything is organized.
