### ISSUE TITLE
Missing node in OPTIONAL MATCH

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13083]
I execute a query on my neo4j database ,and it is supposed to output a node as result but not.

Neo4j version: 5.5.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: MATCH (n0{id:0}) MATCH (n1)-[:T0]->(n3 :L0 :L3) OPTIONAL MATCH (n0)<-[]-(n1),()-[r1:T1]->(),(n5) WHERE (n1)-[r1]->(n5:L3) RETURN n5.id

The result of the above query is null,but there is really a path (n1)-[r1]->(n5:L3) where n5.id is 3 in my graph and I think the node n5 should be found.

There are my graph data:
create (n0:L1{id:0})<-[:T0]-(n1:L1{id:1})<-[:T1]-(n2{id:2})-[:T1]->(:L3{id:3});
match (n{id:2}) create (n)-[:T0]->(:L0:L3{id:4});

**Comment by InverseFalcon** [comment]
The query results are correct.

If we refer to the nodes by their id, then after the first two matches:

n0 is node 0 (matched by its id)
n3 is node 4 (it is the only node with labels :L0:L3 )
n1 is node 2 (it is the only node with a :TO relationship to node 4)

You can confirm this by only executing the first two MATCHes and returning n0, n1, and n3, and check their id properties in the table result view.

The very first subpattern of your OPTIONAL MATCH is: `OPTIONAL MATCH (n0)<-[]-(n1)` , but n1 (node 2) does not have any relationships to node 0. This is why the OPTIONAL MATCH fails; it doesn't even need to evaluate the other subpatterns or the WHERE clause. Since the OPTIONAL MATCH failed to find a matching pattern in the graph, all newly introduced variables from the OPTIONAL MATCH are set to null (r1 and n5 are the new variables in the OPTIONAL MATCH), which is why `n5.id` is null in the RETURN

__________

If instead of using one OPTIONAL MATCH you used 2 of them, and put the non-matching pattern in the first and the remaining parts of the pattern in the second, then you would get results back for n5:

```
MATCH (n0{id:0}) MATCH (n1)-[:T0]->(n3 :L0 :L3) 
OPTIONAL MATCH (n0)<-[]-(n1)
OPTIONAL MATCH ()-[r1:T1]->(),(n5) 
WHERE (n1)-[r1]->(n5:L3) 
RETURN n5.id
```

By doing this, the first OPTIONAL MATCH would find no such pattern in the graph, but no new variables are introduced so there is no change to the interim results. The second OPTIONAL MATCH would find its pattern in the graph, and return `3` for the value of n5.id.

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation and I can see the logic here!
