### ISSUE TITLE
Unexpected SyntaxError:Type mismatch: expected String or List<T> but was Integer

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13103]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.5.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: RETURN 1 ORDER BY size(length(null))
error message:
Type mismatch: expected String or List<T> but was Integer (line 1, column 24 (offset: 23))
"RETURN 1 ORDER BY size(length(null))"
I think the query  is syntactically correct and should return 1 as result.

**Comment by InverseFalcon** [comment]
The syntax is not correct, because the argument to the `size()` function must either be a string or a list, but instead you gave it an integer, since the output of the `length()` function is an integer.

We can use a more simple example to better demonstrate it:

```
RETURN 1 ORDER BY size(2)
```

This will give the same error.

What it comes down to is that it is a mistake to use `size(length())`, that is not syntactically correct.

**Comment by ljhhuxiaoba** [comment]
Thank you very much for explanation!
