### ISSUE TITLE
RuntimeUnsupportedError:Did not find `b` in the slot configuration

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13120]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: create (b),(n{a:count{match (b) return 1}}) return b,n
error message:
Neo.ClientError.Statement.RuntimeUnsupportedError
Did not find `b` in the slot configuration

And if I replace "count" with "exists",the same error will happen again.

Expected behavior:
The query should run successfully and two nodes are created.

Actual behavior:
The query failed.

**Comment by InverseFalcon** [comment]
A few things here.

First, you're trying to do too much simultaneously. Not only is that going to be confusing for anyone reading this query, it's also not going to work. 

You are trying to use the `b` variable (`match (b)`) in the same `create` clause in which you define it, so that won't succeed. 

That said, separating them out into separate CREATE statements also does not succeed, so there does seem to be a bug here. This SHOULD work, but does not:

```
create (b)
create (n{a:count{match (b)}}) 
return b,n
```

So that probably needs looking into.

Best practice however is to handle most non-trivial mutations or aggregations on values in WITH clauses instead of trying to execute them and use them at the same time.

Best practice for this query would be this, which succeeds:

```
create (b)
with b, count{match (b) return 1} as bCount
create (n {a:bCount}) 
return b,n
```

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation and I wonder if this problem will be fixed.

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba,

Thank you for reporting the issue. I agree with Andrew that seems problematic. I have submitted the issue with the appropriate team and hope that they will get back to you shortly ([private ticket](https://trello.com/c/t10wk5Zy)).

All the best,

**Comment by arnefischereit** [comment]
Hi @ljhhuxiaoba,

The issue you reported is in fact the same as #13216 and for the same reasons as mentioned there, we will leave the product as is for the 5.x cycle and forbid cross-references in Neo4j 6.x.

I hope that clarifies the current behaviour. I will close the issue but if you disagree, please feel free to comment and/or open a new issue on this.

Again, thanks for reporting these issues.

Regards,

Arne
