### ISSUE TITLE
Wrong result in `FOREACH`

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13121]
I found a discrepancy when running two semantically equivalent queries against an empty database:

---
1:
```cypher
FOREACH ( n0 IN [0, 0] | 
	CREATE ()
//	MERGE ()
	CREATE (:A)
)
RETURN COUNT {(:A)} AS n
```
Produces:
```
╒═══╕
│"n"│
╞═══╡
│2  │
└───┘
```

---
2:
```cypher
FOREACH ( n0 IN [0, 0] | 
	CREATE ()
	MERGE ()
	CREATE (:A)
)
RETURN COUNT {(:A)} AS n
```
Produces:
```
╒═══╕
│"n"│
╞═══╡
│4  │
└───┘
```
---

I believe the `MERGE` statement here should have no influence on the result of the query, especially on nodes that aren't referenced in its clause.

I encountered this issue when testing queries against the **Neo4j 5.6.0 community version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the aforementioned, semantically equivalent, queries against an empty database and observe that their results differ.

### Expected behavior
The queries should result in the same behavior.

### Actual behavior
The first query results in the creation of two nodes with the label `A`, whereas the second query creates four.

**Comment by InverseFalcon** [comment]
This is closed, but just to add a note: the behavior is correct, and this is because MERGE() is matching upon nodes in the graph and changing the row cardinality, resulting in multiplying out the number of rows the CREATE (:A) is acting upon.

In the first iteration of the foreach:

1. CREATE () creates one node - 1 node total ; 1 row cardinality
2. MERGE () matches to that one node  - 1 node total; 1 row cardinality
3. CREATE (:A) executes once for that single row - 2 nodes total; 1 :A node

On the next iteration of foreach:

1. CREATE () creates one node - 3 nodes total; 1 row cardinality
2. MERGE () matches to the 3 nodes - 3 nodes total; 3 row cardinality
3. CREATE (:A) executes for each of those 3 input rows - 6 nodes total; 4 :A nodes

**Comment by CelineWuest** [comment]
Noticed it an hour after submitting the issue :P 
My bad!

**Comment by InverseFalcon** [comment]
All good, I figured as much, I just wanted to annotate with an explanation for any future reference.
