### ISSUE TITLE
Variable from the outer scope in foreach is shadowed incorrectly

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13122]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: create (b{age:1}) foreach (a in [1]|create (b) delete (b) create ({age:b.age})) return 1
error message:
Neo.ClientError.Statement.EntityNotFound
Node with id 69 has been deleted in this transaction

But if I execute another query:create (b{age:1}) create (b) delete (b) create ({age:b.age}) return 1,then there is an error that Variable `b` already declared.I think the same error should appear in the first query to avoid the shadow of variable b from the outer scope.

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba 

Thank you for reporting another issue. Are you working on some kind of testing framework you would like to share with us? 😄 I have submitted the issue to the appropriate team ([private link](https://trello.com/c/VZsl6FFt)).

All the best,

**Comment by ljhhuxiaoba** [comment]
I haven't finished my work yet, so I can't share it for the time being. I'm really sorry.

**Comment by sherfert** [comment]
Hello @ljhhuxiaoba 

The errors from both queries are expected.

1. `create (b{age:1}) foreach (a in [1]|create (b) delete (b) create ({age:b.age})) return 1`
  * It is allowed to shadow variables in `foreach`. This should not lead to an error. There are only some subquery constructs that explicitly forbid shadowing, e.g. [COUNT](https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#count-subquery-with-with)
  * The `Node with id 69 has been deleted in this transaction` error is expected. It occurs because `b.age` is referenced after `b` was deleted. Any operations on deleted entities can lead to this exception.
2. `create (b{age:1}) create (b) delete (b) create ({age:b.age}) return 1`
  * `b` in the 2nd `create` is a variable declaration. but there is already an existing node with that name. Thus the error `Variable b already declared`

I hope this explanation helps. Let me know if you have any further questions.

**Comment by ljhhuxiaoba** [comment]
I see the difference here, which is that only the user can avoid variable overwriting problems like the one in the first query, and foreach does not prohibit this behavior.
