### ISSUE TITLE
Unexpected variable shadowing about reduce() in subquery

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13131]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query: create (a{k:count{return reduce(a=1,b in []|1)}}) return a
error message:
Neo.ClientError.Statement.SyntaxError
The variable `a` is shadowing a variable with the same name from the outer scope and needs to be renamed (line 1, column 33 (offset: 32))
"create (a{k:count{return reduce(a=1,b in []|1)}}) return a"

The same error also occurs in exists{} subquery.
But if I execute another query:create (a{k:reduce(a=1,b in []|1)}) return a,then it can run successfully.And I think the two queries are equivalent.

Steps to reproduce:
create (a{k:count{return reduce(a=1,b in []|1)}}) return a

Expected behavior:
The query should run successfully and return the node.

Actual behavior:
The query failed.

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba,
 
I will create a ticket for the relevant team to look at this issue. In this case, I think the issue is probably that our documentation is not good enough and needs improving ([Private tracker](https://trello.com/c/Tyiq4fDo)). The relevant team should be getting back to you shortly.

Warm thanks,

**Comment by AzuObs** [comment]
Hi @ljhhuxiaoba 

Thanks for the report. The two queries you posted are not semantically equivalent because one is a subquery, and these are executed slightly differently and are also subject to different scoping rules. I have let the appropriate team know about this however, because I think there is room for improvement and also because this might still be categorised as a bug.

The team should get back to you shortly ([private link](https://trello.com/c/EcI5d9NJ)).

Warm thanks,

**Comment by sherfert** [comment]
Hi @ljhhuxiaoba 

This is expected.
* `reduce` allows shadowing of existing variables. This is the default in Cypher, unless explicitly forbidden.
* `EXISTS`/`COUNT` forbid shadowing of existing variables. This is for example documented [here](https://neo4j.com/docs/cypher-manual/current/syntax/expressions/#count-subquery-with-with). This applies to any clause inside the `EXISTS`/`COUNT`, even to a `reduce`.

I hope this explanation helps. Let me know if you have any further questions.

**Comment by ljhhuxiaoba** [comment]
Thank you for your explanation. I can see the difference here.
