### ISSUE TITLE
Unexpected order about "case when"

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13167]
I execute a query on my neo4j database and get wrong result.

Neo4j version: 5.6.0 Enterprise
operating system: windows 10
API：Cypher version 9
query:  unwind [null,true] as a return a order by case when a then true end
result:
true
null

But if I execute query such as "unwind [null,true] as a return a order by null" or "unwind [null,true] as a return a order by true",then the result will be:
null
true

Expected behavior:
The query should not change the order of elements in list.

Actual behavior:
The query changes the order.

**Comment by loveleif** [comment]
Hello again @ljhhuxiaoba, and again thanks for your tireless work!

From [the documentation](https://neo4j.com/docs/cypher-manual/current/clauses/order-by/#order-null):

> When sorting the result set, null will always come at the end of the result set for ascending sorting, and first when doing descending sort.

We can modify your query slightly to see what we're actually sorting on: 

```
neo4j@neo4j> unwind [null,true] as a return a, case when a then true end as sortOn order by case when a then true end;
+---------------+
| a    | sortOn |
+---------------+
| TRUE | TRUE   |
| NULL | NULL   |
+---------------+
```

This seems to be in line with the expected behaviour based on the documentation.

**Comment by ljhhuxiaoba** [comment]
I can understand the case above,but I still don't understand the order here.
Query "unwind [null,true] as a return a order by a" returns true first and null last,because it is ordered by a itself and null should behind true.
And query "unwind [null,true] as a return a order by true" or "unwind [null,true] as a return a order by null" returns null first and true last,because "order by true" and "order by null" don't change the order.
But in this case "unwind [null,true] as a return a order by case when a then true end",when a=null,"case when a then true end" is null,thus it is ordered by null(without influence),because "order by null" doesn't change the order.Then a=true,the situation is similar.So the result is null first and true last(no change). 
I don't know if I made that clear and where I am wrong.

**Comment by loveleif** [comment]
Keep in mind "null will always come at the end of the result set", we can rewrite the query `unwind [null,true] as a return a order by case when a then true end` into one with the same expected result:

```
neo4j@neo4j> unwind [null,true] as a 
             with a, case when a then true end as sortBy 
             return a, sortBy 
             order by sortBy;
+---------------+
| a    | sortBy |
+---------------+
| TRUE | TRUE   |
| NULL | NULL   |
+---------------+
```

We are basically sorting on `a`, because `a` and `sortBy` have the same values. And as we know, nulls comes last, which is also what we see.

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation.
