### ISSUE TITLE
Operator "CONTAINS" should not work on lists

### ISSUE THREAD

**Issue by tomocesnik** [neo4j/neo4j#13195]
It is easy to mistakenly use "CONTAINS" operator in case of checking if a list "contains" an element. 

## Steps to reproduce
1. Add some data:
`WITH range(1,10) AS lst
UNWIND lst AS l
CREATE (n:Test {id: l})
`
2. Try to query it in a wrong way:
`MATCH (n:Test) WHERE labels(n) CONTAINS "Test" RETURN n`
`MATCH (n:Test) WHERE NOT labels(n) CONTAINS "Test" RETURN n`

## Expected behavior
Syntax error is thrown.

## Actual behavior
Both queries silently succeed but not returning any data.

## Affected versions
I have confirmed that this problem happens on Neo4j versions 4.4.20 and 5.7.0.
It does not happen on Neo4j version 4.3.23, where the actual behavior is the same as expected behavior.

**Comment by arnefischereit** [comment]
Hi @tomocesnik,

Thank you for filing this bug report.

This change in behaviour was a conscious decision we made for the 4.4.0 release, for all the string comparison operators to be more forgiving.

Instead of throwing an exception, we now return `NULL`, which we do in a number of cases (e.g. `[1][1]`). In the end this is a language design decision to make.

I hope this answers your question. Otherwise, please comment below and re-open the issue if necessary.

---

[Link for internal reference](https://trello.com/c/MK5qKAZ7/)
