### ISSUE TITLE
SyntaxError about aggregation expression

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13200]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:with 0 as b return collect(1)[b]
error message:
Neo.ClientError.Statement.SyntaxError
Aggregation column contains implicit grouping expressions. For example, in 'RETURN n.a, n.a + n.b + count(*)' the aggregation expression 'n.a + n.b + count(*)' includes the implicit grouping key 'n.b'. It may be possible to rewrite the query by extracting these grouping/aggregation expressions into a preceding WITH clause. Illegal expression(s): b (line 1, column 31 (offset: 30))
"with 0 as b return collect(1)[b]"
                               ^

I think this query is semantically correct and should run successfully.
When I execute another query such as "with 0 as b return collect(1)[0]",then it can run successfully and no error occurs.

Expected behavior:
The query should run successfully and return 1.

Actual behavior:
The query failed.

**Comment by InverseFalcon** [comment]
The query erroring out is correct behavior, as is the error message.

When you aggregate (such as with `collect()`), you aggregate with respect to something: either across the entire result set (when there or is no grouping key), or with respect to the grouping key, which are the non-aggregation variables present on the row with the aggregation (explicit grouping key), or otherwise even if not explicit, what variables are forced to be the grouping key in order to be applied in operations on the aggregation result (implicit grouping key, as in your example). 

Implicit grouping keys are tricky because it may not be obvious that a variable is acting as the grouping key for an aggregation, and so in 5.x implicit grouping keys are no longer supported. You can read about this in more detail in the 5.x additions and deprecations section of the docs:

https://neo4j.com/docs/cypher-manual/current/deprecations-additions-removals-compatibility/#cypher-deprecations-additions-removals-5.0

> Implied grouping keys are no longer supported. Only expressions that do not contain aggregations are still considered grouping keys. 

_______

To explain further, your original example was:

```
with 0 as b 
return collect(1)[b]
```

In order to use the variable `b` to get the value at the given index, it MUST be used as a grouping key when you perform the aggregations, since when you aggregate there are only variables aliased on the results of the aggregation, or variables used in the grouping key, and since you do not have `b` as an explicit grouping key, it must be implicit, which is no longer allowed.

An expression using an explicit grouping key would be: `return b, collect(1)[b]`, so we would know the collect() aggregation is done with respect to `b`, which is the only way the `b` variable can survive the aggregation and still be present in order to finish the remaining operations on the aggregation result.

This may be more apparent if you remember that variables may address more than one input row, like so:

```
UNWIND [1,2,3,4,5] as b 
RETURN collect(1)[b]
```

Now you can more clearly see the ambiguity. This isn't a standalone collect() without a grouping key. In order for the `b` to make sense where it's used, it must be part of the grouping key, and the explicit form would be:

```
UNWIND [1,2,3,4,5] as b 
RETURN b, collect(1)[b]
```

making it clear that we are collecting with respect to `b` as the grouping key, that we will get (in this example) 5 rows of results, where the `b` on each row is different.

______________

The reason why your alternate query did not trigger an error was because `0` is a literal, not a variable, and does not have the potential to represent different values across multiple input rows, so in that aggregation there is no grouping key. Likewise, parameters have a fixed value after they are passed into a query, and also cannot represent different values across multiple input rows.

**Comment by ljhhuxiaoba** [comment]
I now have a better understanding of the use of aggregate functions and thank you for your patience in explaining them!
