### ISSUE TITLE
Inconsistent results about the count() function

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13219]
I execute two queries on my neo4j database and get inconsistent results.

Neo4j version: 5.8.0 Community
operating system: windows 10
API：Cypher version 9
query:
match (c) return count(c{k:1})
match (c{k:1}) return count(c)

I think the above two queries are equivalent.
But the result of the first query is 2 and the second is 1.And I think the result 1 is right.

To create the database:
create (),({k:1})

**Comment by InverseFalcon** [comment]
The count() aggregation function does not work as a filter. 

You can use it on properties to count only non-null values, like `count(c.foo)`, or non-null variables, but no actual filtering will be done within the expression you give it, which is why it's giving a return of `2`, it's behavior is the same as `count(c)`.

If anything, I would expect the first query to error out, as it doesn't look like it should be valid syntax.

The `count{}` subquery, however, is different, and would execute per input row (there would be 2 rows of results), and per row it would filter, and get the count of the result. If your intent is to filter something and get its count, the `count{}` subquery is the tool you should be using instead.

**Comment by ljhhuxiaoba** [comment]
Thank  you very much.
