### ISSUE TITLE
In MATCH clause, duplicated path patterns cause incorrect behaviors

### ISSUE THREAD

**Issue by joyemang33** [neo4j/neo4j#13225]
- Neo4j version: 5.8.0-enterprise
- Operating system: Ubuntu 20.04
- API/Driver: Cypher
- **Steps to reproduce**

Hello! While testing Neo4j in the movie graph, I came across an issue related to duplicated path patterns. Allow me to explain in a clearer manner:

In the second query, the expected result should be 506. This is because all pairs (n0, n1) in the first query, satisfy the pattern defined in the second query.

Similarly, in the third query, the expected result should also be 506. However, currently, it returns 64, which is the number of pairs (n0, n1) that have at least two edges in the movie graph. 
The issue here is that there is no constraint requiring the two relationships to be identical, and thus the expected result should still be 506.

While I am uncertain if this behavior is a bug in Neo4j, it is worth noting that other graph databases (such as Memgraph) attempt to address this by returning an exception ```Redeclaring variable: r1``` for the second query.

Would it is possible for you to further confirm and investigate this issue?
One possible solution to address this issue is to implement a step during query compilation that removes duplicated path patterns for each pattern, and another solution is to throw an exception like other GDBs when encountering a redeclared variable for relation.

```cypher
//:play movie-graph
MATCH (n0)-[r1]-(n1) RETURN COUNT (*)
=> 506
MATCH (n0)-[r1]-(n1), (n1)-[r1]-(n0) RETURN COUNT (*)
=> 0
MATCH (n0)-[]-(n1), (n1)-[]-(n0) RETURN COUNT (*)
=>64
```
- Expected behavior
```cypher
MATCH (n0)-[r1]-(n1), (n1)-[r1]-(n0) RETURN COUNT (*)
=> 506
MATCH (n0)-[]-(n1), (n1)-[]-(n0) RETURN COUNT (*)
=> 506
```
or
```cypher
MATCH (n0)-[r1]-(n1), (n1)-[r1]-(n0) RETURN COUNT (*)
=> Exception: Redeclaring variable: r1.
MATCH (n0)-[]-(n1), (n1)-[]-(n0) RETURN COUNT (*)
=> 506
```

**Comment by sherfert** [comment]
Hi @joyemang33 and thanks for your issue report.

This is expected behavior. Let me explain why:

In a graph pattern (everything you write after a `MATCH` for example), any actual relationship in the graph can only be traversed once. See the documentation for more details: https://neo4j.com/docs/cypher-manual/current/patterns/reference/#graph-patterns-rules-relationship-uniqueness


This means that your queries search for slightly different things:
* `MATCH (n0)-[r1]-(n1) RETURN COUNT (*)` => Count all relationships in the graph, matched in any direction. This will be equal to `2 * count of relationships in the graph`.
* `MATCH (n0)-[r1]-(n1), (n1)-[r1]-(n0) RETURN COUNT (*)` => Count all patterns where two nodes are connected with two relationships, but traversing the same relationship twice. Since this is disallowed, 0 results match this query.
* `MATCH (n0)-[]-(n1), (n1)-[]-(n0) RETURN COUNT (*)` => Count all patterns where two nodes are connected with two relationships. This is different from the first query, which does not put any restriction on the nodes being connected with 2 relationships between them.

I hope this clears up the issue, let me know if there are further questions.

**Comment by joyemang33** [comment]
@sherfert Many thanks for your elaborated explanation! I have understood the first query and the third query. 

But I think the second the zero in the second query. According to the provided documents, It looks like duplicated variable assigned to relationship (e.g., r1 for the query) is also an undefined behavior. In some complex query, user may type duplicated relationship-variables, and the they can not aware it by the result 0. In my opinion, an exception will be better here for the undefined behavior rather than a normal result zero, which may be confused. Could you add an exception for this in the future version, it would be highly appreciated.

**Comment by sherfert** [comment]
@joyemang33 
I agree with your sentiment. This can easily be overlooked and an error would make this more obvious than 0 results.
Actually, we had this behavior in previous versions of neo4j.

The reason we changed it, is to prepare the product for different "match modes". For example, there is a match mode upcoming in a future release that would allow traversing the same relationship multiple times in a `MATCH` clause.

To still warn the user in the cases where they will get 0 results, we decided to compromise and issue a warning instead of an error. The warnings reads:

"A relationship is referenced more than once in the query, which leads to no results because relationships must not occur more than once in each result. (Relationship `r1` was repeated)"

You can see this warning for example in neo4j browser when typing your query prepended with `EXPLAIN`.

**Comment by joyemang33** [comment]
@sherfert Many thanks for your help and I think warning is also OK for users. 

BTW, the upcoming match mode looks like very cool. I am looking forward to the new functionality, and maybe in the future, our testing approach can help you detect some logic and performance issues in the new mode🥹

Best regards,
Joye
