### ISSUE TITLE
Unexpected EntityNotFound Error 

### ISSUE THREAD

**Issue by ljhhuxiaoba** [neo4j/neo4j#13254]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.9.0 Community
operating system: windows 10
API：Cypher version 9

To create the graph:
[graph.txt](https://github.com/neo4j/neo4j/files/12039809/graph.txt)

To reproduce:
OPTIONAL MATCH ( :L4)-[r0]-(n0), (n1 :L4)-[r1]-() DETACH DELETE case when n1.k26 then n1 end RETURN 1;

error message:
Neo.ClientError.Statement.EntityNotFound
Node with id 307694 has been deleted in this transaction

Expected behavior:
The query should run successfully.

Actual behavior:
The query failed.

**Comment by smietana** [comment]
Thank you! We will investigate this.

**Comment by erik-leffler** [comment]
Hi, this is expected behaviour. The match clause will match all pairs of node, and a given pair with `k26: true` will be present as `n1` in many `n0, n1` pairs and thus be deleted many times.

**Comment by erik-leffler** [comment]
Hi, I believe this to be expected behaviour. 

The node with `id: 3` that has `k26: true` will match the pattern bound to the `n1` variable in more than one way. This means that it will be passed to the `DETACH DELETE` multiple times. It will be deleted the first time, and the second time we expect an exception as we are reading the `.k26` property of a deleted entity. 

To remedy this we could extract the property using a WITH clause like so `OPTIONAL MATCH (:L4)-[r0]-(n0), (n1 :L4)-[r1]-() WITH n1, n1.k26 as k26 DETACH DELETE case when k26 then n1 end RETURN 1;`

**Comment by ljhhuxiaoba** [comment]
Thanks for your explanation.
