### ISSUE TITLE
Task exceeded maximum timeout 

### ISSUE THREAD

**Issue by amindadgar** [neo4j/neo4j#13271]
## System information
- Neo4j version: 5.9.0
- Operating system: Ubuntu 22.04
- API/Driver: Python driver 5.8.0

## Example bug report

I discovered that when I'm doing a `session.excute_write` using python driver I'm experiencing an error with `Task exceeded maximum timeout value (1800 seconds)` exception. What I'm exactly doing is I have broke down my queries into an array of query and then I'm doing the `session.excute_write` for each query inside one session. In case of having about less than 60K queries it is working well and is inserting data in neo4j but when the query count exceeds the 60K count it would produce an exception defined above for task exceed timeout. I also tried to close the session after 30K of queries and create another but still got no success.

I know the task can take a bit of time (maybe more than 1800s for big data), but how to handle it in our case? (I did broke down the queries with the purpose of not taking much memory)

**Neo4j Version:** 5.9.0
**Operating System:** Ubuntu 22.04
**API:** Docker

### Expected behavior
The data got fully inserted with no exception of task exceeded error.

### Actual behavior
Getting the error `Task exceeded maximum timeout value (1800 seconds)` after 60K of small query insertions.

**Comment by robsdedude** [comment]
Hi and thanks for reaching out. I've tried to reproduce the issue, but was not able to.

Can you please provide more details?
 * Can you post the full exception with stack trace?
 * What Python version are you using?
 * Are you using the async driver or the synchronous one?
 
Here's the Python snipped that I tried to assemble from your description and I don't get any errors:
```python
import neo4j


URL = "neo4j://localhost:7687"
AUTH = ("neo4j", "pass")


def work(tx, query, **params):
    return list(tx.run(query, **params))


def test(driver: neo4j.Driver):
    query = "CREATE (n:TestLabel {num: $i}) RETURN n"

    with driver.session(database="neo4j") as session:
        i = 0
        while True:
            session.execute_write(work, query, i=i)
            i += 1
            print(i)


def main():
    with neo4j.GraphDatabase.driver(URL, auth=AUTH) as driver:
        test(driver)


if __name__ == "__main__":
    main()
```

Maybe you can adjust the code to be closer to what you're doing and maybe even so that it causes the same error. If not, please post a minimal example of your code that still exposes the issue.

**Comment by amindadgar** [comment]
Thanks for the response. the problem was for another part of the project which we had limited the job timeout in reddis queue, so It is fully resolved by increasing our background job timeout. closing the issue now.
