### ISSUE TITLE
Neo4j and embedded mode

### ISSUE THREAD

**Issue by rickardoberg** [neo4j/neo4j#13273]
I have been using Neo4j in embedded mode for a long time, but it is becoming more difficult with every release, to the point that I'm not sure if being able to embed Neo4j in Java applications is something that is supported.

There are two main issues I'm facing currently:
1) With every release more split packages are introduced in the jars, making it difficult to reference Neo4j from modular artifacts. (5.10.0 made this MUCH worse)
2) To start up Neo4j in embedded mode you have to reference org.neo4j:neo4j, which includes many non-embedded elements such as Jetty/Jersey/Bolt

The workaround for 1) is to create our own shaded Neo4j, to fix your problems by simply lumping it all into one jar. The Automatic Module Name included in MANIFEST.MF makes it worse, not better, by telling the module system that the jar should be complying with module rules, and yet they do not because of split packages (and it gets WORSE, not better, with every release).

The workaround for 2) is to have a really long "exclude dependency" list in Maven POM, and hope that it works. The real fix is to have a modular approach where the web parts are not required to start an embedded database, but that seems like wishful thinking at this point.

Ultimately the question becomes: do you intend to support having Neo4j embedded in Java applications going forward? Why is embedded mode getting worse and worse with every release? It would be good to have an official answer to this.

**Comment by mauvo** [comment]
Hi Rickard,

I'm a product manager for the database. I haven't had my eye on embedded mode for recent releases, sorry for the frustration we're causing you.

Please bear with me while I talk to my colleagues and figure out what's happened and the options available.

Best wishes,
David

**Comment by mauvo** [comment]
Hi Rickard,

This issue has come about due to moving to monthly releases alongside our LTS version. The monthly releases allow us to get new features and capabilities into your hands sooner. But you have observed one of the side effects, at this pace we can't also keep embedding consistent from month to month.

For embedding applications, it might be possible (or even desirable) to stick to a single Neo4j v5 release rather than take the latest update each month. This would immediately cut the work you need to do to package Neo4j for your application.

Thanks,
David
