### ISSUE TITLE
Logic Inconsistency Caused by Query Partitioning

### ISSUE THREAD

**Issue by joyemang33** [neo4j/neo4j#13276]
**Neo4j Version:** 5.9.0
**Operating System:** Ubuntu 20.04
**API:** Cypher

Hi! During our testing, we found that there is a logic inconsistency when partitioning a bi-direction relationship with a label expression into two individual ones. 
I am not sure whether they are expected behaviors since I am not an expert on Cypher. Could you further help me confirm and investigate it? It would be highly appreciated.

```Cypher
MATCH (n1:((%)))-[r1:(!T4&!T6&!!T5)]-(n2:(!L5|!!!L1|(L1))) RETURN COUNT(*)
=> 27
```
```Cypher
MATCH (n1:((%)))-[r1:(!T4&!T6&!!T5)]->(n2:(!L5|!!!L1|(L1))) RETURN COUNT(*)
=> 15
```
```Cypher
MATCH (n1:((%)))<-[r1:(!T4&!T6&!!T5)]-(n2:(!L5|!!!L1|(L1))) RETURN COUNT(*)
=> 15
```

The result of the first query should match the sum of other ones, while 27 $\neq$ 15 + 15.

Notably, during our previous test without label expressions, there is no inconsistency caused by such a partitioning approach. Therefore, I think it may indicate a potential bug in Neo4j about handling label expressions in ```MATCH```.

### Steps to reproduce
The Graph data can be created by the following statements:
[1691633902.2462535.log](https://github.com/neo4j/neo4j/files/12318372/1691633902.2462535.log)

Best regards,
Joye

**Comment by erik-leffler** [comment]
Hi, thank you for the repport! We will investigate this.

**Comment by erik-leffler** [comment]
Hi @joyemang33, when I try to replicate this locally on a 5.9 db I get a count of 12 for outgoing, 13 for incoming, and 25 for undirected. Are you sure that there hasn't been any other nodes/relationships created since executing the provided file?

Also, the sum of the two directed counts need not be the undirected count. If for example we had a loop in the database which has the same source and target node like `(x)-[r]->(x)`, then an undirected pattern `MATCH (n1)-[]-(n2)` will match the loop only once, whilst both an outgoing pattern `MATCH (n1)-[]->(n2)` and an incoming pattern `MATCH (n1)<-[]-(n2)` will match the loop.

**Comment by joyemang33** [comment]
Hi @erik-leffler! Many thanks for your response and pointing out the fact that this test oracle will not hold when there are loops. After the investigation, we found that I uploaded the wrong file for creating, and we will upload the correct one ASAP. Sorry for any inconvenience caused by that.

Closed until uploading new test cases
