### ISSUE TITLE
Different result of the example in opencypher

### ISSUE THREAD

**Issue by Lincyaw** [neo4j/neo4j#13292]
Neo4j: 5.9.0
Version: Docker

Hello, in this feature

https://github.com/opencypher/openCypher/blob/master/tck/features/clauses/match/Match8.feature

```
 Scenario: [2] Counting rows after MATCH, MERGE, OPTIONAL MATCH
    Given an empty graph
    And having executed:
      """
      CREATE (a:A), (b:B)
      CREATE (a)-[:T1]->(b),
             (b)-[:T2]->(a)
      """
    When executing query:
      """
      MATCH (a)
      MERGE (b)
      WITH *
      OPTIONAL MATCH (a)--(b)
      RETURN count(*)
      """
    Then the result should be, in any order:
      | count(*) |
      | 6        |
    And no side effects
```

After executing the example, I got a different result. Does it correct?

<img width="1579" alt="image" src="https://github.com/neo4j/neo4j/assets/53161583/568fde0c-b57b-4c9e-903e-65042770715e">

**Comment by hedengran** [comment]
Hi, thank you for the report! The behavior you are seeing when executing the example is expected, and both scenarios are behaving correctly. 

In [Match8.feature](https://github.com/opencypher/openCypher/blob/master/tck/features/clauses/match/Match8.feature), the two create clauses are executed as one query:

```
CREATE (a:A), (b:B)
CREATE (a)-[:T1]->(b),
       (b)-[:T2]->(a);
```

First node `a` and node `b` are created. Since `a` and `b` are already bound, the next create clause will only create a relationship between the already exisiting `a` and `b`.

In your example, the `CREATE` clauses are separated by a semicolon:

```
CREATE (a:A), (b:B);   //  <- semicolon
CREATE (a)-[:T1]->(b),
       (b)-[:T2]->(a);
```

This means that the two create clauses will be treated as two separate queries. The first one will create an `a` and a `b` node.  The second `CREATE`, treated as a new query, will not have `a` or `b` bound. As such, it will create two new nodes, `a` and `b`, and then create two relationships between these two new nodes. 

As such the semicolon significantly alters the meaning of your query.

Hope that helps!
