### ISSUE TITLE
neo4j-admin backup restore does not respect configured data and transaction folders and --to-path-data options

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j#13306]
**Neo4j Version:** 5.11.0
**Operating System:** Amazon Linux 2

On my AWS EC2 instance, here are some relevant folder locations:
- neo4j `bin` and `lib` directories are under `/usr/share/neo4j/`
- the `data` folder is configured in neo4j.conf to be at `/data`.
- the `transaction` folder is configured in neo4j.conf to be at `/transactions` (which is totally separate from `/data`).

The DBMS is working totally fine normally with this setup.

But `neo4j-admin database restore` seems to be ignoring the configured `data` and `transaction` folder locations, and also only partially respects the `--to-path-data` option. That is, it behaves as if the `data` folder sits right beside the `bin` folder, and the `transaction` folder sits under that(wrong) `data` folder location. Even if I try to counteract some of this behavior by specifying the `--to-path-data=/data` option, it still puts a lot of files in `/usr/share/neo4j/data/databases/xxx` and a smaller number of files in `/data/databases/xxx.

### Steps to reproduce

Sample command line:

`sudo -u neo4j /usr/share/neo4j/bin/neo4j-admin database restore --from-path=/data/backups/ekg/ekg-2023-09-19T19-00-50.backup --to-path-data=/data/databases ekg-sam`

### Expected behavior

1. A new `ekg-sam` folder should be under `/data/databases`.
2. A new `ekg-sam` folder should be under `/transactions`.
3. A new `ekg-sam` folder should be under `/data/scripts`

### Actual behavior

1. A new `ekg-sam` folder is under `/data/databases` and `/usr/share/neo4j/data/databases`. Also, the latter folder seems to be complete, whereas the former has much fewer contents.
2. A new `ekg-sam` folder is under `/usr/share/neo4j/data/transactions`.
3. A new `ekg-sam` folder is under `/usr/share/neo4j/data/scripts`.

**Comment by klaren** [comment]
Hello and thanks for reporting,

Are you using the tarball or rpm installation?

**Comment by docrozza** [comment]
Hi - thanks for reporting and the detailed steps to reproduce!

Unfortunately I was unable to reproduce the errors you saw - at least on my latest 5.13 runtime. The steps I tried were:
- install server at `/Testing/neo4j`
- update the `neo4j.conf` with the following
```
server.backup.enabled=true
server.directories.data=/Testing/backupRestore/server/data
server.directories.transaction.logs.root=/Testing/backupRestore/server/transactions
```
- start and add some data
- observe that the DB resides in `/Testing/backupRestore/server/data/databases/neo4j`
- observe that the Tx logs resides in `/Testing/backupRestore/server/transactions/neo4j`
- run the backup command
```
/Testing/neo4j/bin/neo4j-admin database backup --to-path=/Testing/backupRestore --from=localhost:6362
```
- run the restore command
```
/Testing/neo4/bin/neo4j-admin database restore \
   --from-path=/Testing/backupRestore/neo4j-2023-10-13T15-37-05.backup \
   ekg-sam
```

With these steps, it all worked as expected:
- no content was added to /Testing/neo4/data
- the restored DB was in /Testing/backupRestore/server/data/databases/ekg-sam
- the restored logs were in /Testing/backupRestore/server/transactions/ekg-sam
- the cypher was in /Testing/backupRestore/server/data/scripts/ekg-sam

There was a change in 5.12 around the restore command (_Moving file instead of copying when restoring a backup_) that may have also fixed the issue you are observing - is it possible for you to give it a go on the latest version?

If it is still failing, it might also be worth running the restore command with the `--verbose` option for some further details and maybe checking the file permissions in the relevant directories to ensure nothin is amiss there too.

**Comment by docrozza** [comment]
Please open a new card if you continue to observe the problems in the restore command and we'll take another look at it
