### ISSUE TITLE
[Bug] java.lang.IllegalArgumentException: Unrecognized setting. No declared setting with name: server.directories.neo4j_home. Cleanup the config or disable 'server.config.strict_validation.enabled' to continue.

### ISSUE THREAD

**Issue by tyousyuka** [neo4j/neo4j#13329]
I used this neo4j embedding api
![image](https://github.com/neo4j/neo4j/assets/5753432/e138601e-f6e8-4a4d-b11a-9dbf9cf650f8)

when I run it in the IntelliJ IDEA 2023.2.4, it is ok；

but when I pack the programma as a jar, it occur an error, like this :
![image](https://github.com/neo4j/neo4j/assets/5753432/703103a1-9aeb-406c-b4dc-e84fe51500d8)

what can I do ?what is the reason?
Thank you!!!
@MishaDemianenko

**Comment by Roxling** [comment]
@tyousyuka Hello
Neo4j stores its settings in jars. When you pack your program into a jar you need to ensure all of the dependencies are included in that jar, or added to the classpath, or it will never work. This exception just happens to be the first thing that does not work when only some parts of neo4j are available. This is **not** a bug in neo4j, but how the java/jvm works. When you run inside intellij it probably works because your classpath is different from when you run it as a single jar.

See https://en.wikipedia.org/wiki/Classpath
If you want to package everything into one single fat-jar, see e.g https://maven.apache.org/plugins/maven-shade-plugin/
