### ISSUE TITLE
Text Indexes (2.0) on neo4j 5.12 massive negative impact on query planning - may only be when using "call"

### ISSUE THREAD

**Issue by jrsperry** [neo4j/neo4j#13326]
Docker Image: neo4j:5.12

I've experienced this a variety of times with Neo4j 5 where indexing has large negative impacts on query planning, which has actually held me back from switching to neo4j 5. Sometimes the indexes work great, other times not so much. I've been using the new text index (2.0). Here's an example with 2 query plans where I removed indexes that led to better performance. The bad query plans are a result of expanding every possible relationship in the db rather than using the node that it's attached to (in this example, the sentence node, the good plan uses the 10 requested, the bad one expands all relationships). 

All I did to get an actually good query plan was remove 2 indexes, on the Word.lemma and EventRole.eventLemma. These are the 2 main properties used in the query. On the good plan without indexes in the db it appears to fetch the nodes in the vicinity rather than starting from scratch, which is what appears to happen with the bad plan. 

I've attached the query plans (with the query pasted within) as txt files. The bad query plan has decided to not use the 10 "sentence" nodes for it's expansion, leading to over 1 million db hits, where as the other one doesn't look at all possible relationships in the db. I'm baffled as to why this is happening. This leads to 2.4 million db hits, as opposed to 2800 db hits. 

As a strange added note, this seems to only happen when using "call". If I end the query before the call and return just "sentence.text" then everything looks great on the query plans.

### Steps to reproduce
Unsure to be honest. It makes absolute 0 sense what is going on with query plans. 

### Expected behavior
Query Plans would be better with indexing, rather than almost 1000 times worse. 

### Actual behavior
1 query plan rocks, the other does not. 

Query: 

cypher replan=force
profile  MATCH (sentence:`Sentence`)
WHERE sentence:`Sentence`
MATCH (sentence)-[:`HAS_WORDS`]->(Word0:`Word`)
WHERE Word0.lemma = 'have'
MATCH (sentence)
WHERE EXISTS {
  MATCH (sentence)-[:`HAS_WORDS`]->(Word0)
  WHERE (NOT (EXISTS {
      MATCH (Word0)<-[:`HAS_WORDS`]-(EventRole1:`EventRole`)
      WHERE EventRole1.eventLemma = 'something'
    })
    AND Word0.lemma = 'have')
}
WITH DISTINCT sentence limit 10
CALL {
  WITH sentence
  MATCH (sentence)-[:`HAS_WORDS`]->(Word10:`Word`)
  WHERE (NOT (EXISTS {
      MATCH (Word10)<-[:`HAS_WORDS`]-(EventRole10:`EventRole`)
      WHERE EventRole10.eventLemma = 'something'
    })
    AND Word10.lemma = 'have')
  RETURN collect(Word10 {
    evidence: Word10.evidence
  }) AS Word30
}
RETURN apoc.convert.toJson(sentence {
  sentenceId: sentence.sentenceId,
  beginOffsets: sentence.beginOffsets,
  text: sentence.text,
  `Word-AUTO-2`: Word30
}) AS sentence skip 0 

Note: These are auto-generated query plans and are a sample, i'm aware that there are some redundancies in the logic and that it doesn't make perfect sense. 

[bad_query_all_indexes.txt](https://github.com/neo4j/neo4j/files/12920688/bad_query_all_indexes.txt)
[bad_query_no_eventrole_eventlemma.txt](https://github.com/neo4j/neo4j/files/12920690/bad_query_no_eventrole_eventlemma.txt)
[good_query_no_eventrole_eventlemma_no_word_lemma_indexes.txt](https://github.com/neo4j/neo4j/files/12920694/good_query_no_eventrole_eventlemma_no_word_lemma_indexes.txt)

**Comment by jrsperry** [comment]
I just removed the text index and replaced it with a range index, the query plans fine with a range index. It appears that the text index (2.0) is the offender here. 

If I have a range and a text index on the word.lemma property then query plans are very fast and efficient (only 1500 db hits). Additionally, if I change the "=" operator to be a "contains" operator then the planning goes as expected. I know there are some potential limitations with equality checks on strings though I wouldn't expect to see that in this kind of query. 

Leads me to only want to use range indexes though.

**Comment by arnefischereit** [comment]
Hi @jrsperry,

Sorry to learn that you have such difficulties with the planner utilising the indexes to their full potential. Generally, `TEXT` indexes are meant to speed up queries containing `CONTAINS` or `ENDS WITH` predicates. If all you have are equality predicates, then you are probably better off with a `RANGE` index.

Looking at the plans, it looks to me that the culprit is that we highly underestimate the number of times that the pattern

```Cypher
  MATCH (sentence)-[:HAS_WORDS]->(Word0 {lemma: 'have'})
  WHERE NOT EXISTS {
      MATCH (Word0)<-[:HAS_WORDS]-(EventRole1:EventRole)
      WHERE EventRole1.eventLemma = 'something'
    }
  }
```
is present.

For me to investigate this further, I would need the graph counts of the database that you are querying, preferably with all `RANGE` indexes that you have activated.

You can obtain the graph counts via
```
CALL db.stats.retrieve('GRAPH COUNTS')
```

Regards,

Arne

**Comment by jrsperry** [comment]
Ya I solved my problems by switching to a range index, and understand they are preferred to a TEXT index in most scenarios. Is it recommended to have both indexes then if you are doing queries with both equality/starts with checks and contains/ends with predicates? Using TEXT index alone is completely unusable and slow when doing any other kind of predicate check.

**Comment by arnefischereit** [comment]
Generally, TEXT indexes should be able to answer most predicates with adequate performance. What happened in your case was that the plan was changed altogether. That is probably because RANGE indexes can provide us with a tad more information than TEXT indexes.

That is, if you have both kinds of predicates: Start with TEXT indexes. If the performance for equality is not good enough, add RANGE indexes.

I will close this issue now as it seems that your questions are answered. Please let me know if that is not the case or we should investigate your case further.
