### ISSUE TITLE
Question for Open-Cypher Specification

### ISSUE THREAD

**Issue by ddaa2000** [neo4j/neo4j#13332]
I find that the Open-Cypher Specification for the WITH clause is a little unclear. Specifically, I'm not sure how the WITH clause deals with the result set of the previous clause if the WITH clause is a "WITH a as expr" (expr is not an aggregation function).
Specifically, for the empty result set from the previous clause. Should "WITH a as 1" return a line of 1, or no line, or this is an undefined behavior?

Thanks a lot!

**Comment by hvub** [comment]
### Meta remark

This question would be better suited for the openCypher repo, because it is about openCypher artifact and not about artifact homed in this repository, here. Please, post openCypher related question on the [openCypher repo](https://github.com/opencypher/openCypher) in the future. Thanks.

### General remark in the vicinity of the question

Not everything allowed by a grammar is valid syntax. Every language complex enough to be interesting has additional rules that further restrict the syntax generateable by the grammar. 

Simple example: `1 / "a"` is allowed by the oC grammar. Still, it is not valid syntax.

In fact, there are many different pairs of grammar and rules that effectively specify the same language, i.e., the same amount of valid syntax. Behavior (or rather semantics) is usually only specified for valid syntax.

### To the question specifically

`WITH a AS _expr_` is not valid oC syntax and it is not even allowed by the oC grammar.

The syntax of projection items of a WITH clause are defined by the grammar [production "ProjectionItem"](https://raw.githack.com/openCypher/openCypher/master/tools/grammar-production-links/grammarLink.html?p=ProjectionItem), which read as follows:

```xml
  <production name="ProjectionItem" rr:inline="true">
    <alt> <seq>&expr; &SP; AS &SP; &var;</seq> &expr; </alt>
  </production>
```

`<alt> ... </alt>` specifies an alternative between all it direct children. In this particular case, there are two direct children:

1. `<seq>&expr; &SP; AS &SP; &var;</seq>`
2. `&expr;`

None of these can generate `a AS 1`.

The Railroad diagrams (generated from the grammar) may be more illuminating. Here [ProjectionItem](https://s3.amazonaws.com/artifacts.opencypher.org/M23/railroad/ProjectionBody.html) is shown as

```
ProjectionItem = (Expression, SP, (A,S), SP, Variable)
               | Expression
               ;
Variable = SymbolicName ;
```

Clearly, the keyword `AS` cannot be followed by an expression, but only by whitespace and a symbolic name (which cannot start with a numeral).

Given that `WITH a AS 1` is not valid syntax, we do not have to debate its semantics — it does not have any. 

In any case, the semantics of the WITH clause without aggregation functions is "Project each row in the driving table with the given projection items." Consequently, the WITH clause without aggregation functions cannot change the cardinality of the driving table. Any empty driving table always remains empty after WITH clause without aggregation functions.

An empty driving table can be repopulated by WITH clause _with_ aggregation functions, such as `WITH COUNT(*) AS x` which will turn an empty driving table into a driving table with single row `{ x: 0 }`.

Hope that helps.

**Comment by ddaa2000** [comment]
Sorry that I mistakenly wrote "WITH 1 as a" to "WITH a as 1". Anyway, I will post it to the OpenCypher Repo. Thanks a lot.
