### ISSUE TITLE
Variable not found in slot configuration of Aggregation

### ISSUE THREAD

**Issue by CelineWuest** [neo4j/neo4j#13338]
When running the following query:
```cypher
CREATE (x), ({a1:EXISTS { RETURN COUNT(0) AS a2, keys(x) AS a4 }})
```

I encountered the following error:
```
Neo4jError: Neo.ClientError.Statement.RuntimeUnsupportedError (Did not find `x` in the slot configuration of Aggregation (Id(4)))
```

I believe the query mentioned above is semantically and syntactically correct and thus no error should be thrown here.

I encountered this issue when testing queries against the **Neo4j 5.13.0 enterprise version** in a Docker container running **alpine v.3**.

### Steps to reproduce
Run the following queries and observe it throws an error:
```cypher
CREATE (x), ({a1:EXISTS { RETURN COUNT(0) AS a2, keys(x) AS a4 }})
```

### Expected behavior
The query should run successfully

### Actual behavior
The query fails with the error message ``Neo4jError: Neo.ClientError.Statement.RuntimeUnsupportedError (Did not find `x` in the slot configuration of Aggregation (Id(4)))``

**Comment by PetrJanouch** [comment]
Hi @DominicWuest ,

thanks for reporting this. This looks very similar to https://github.com/neo4j/neo4j/issues/13339 . Until we know otherwise, we will treat this as another occurrence of that issue.

**Comment by sherfert** [comment]
Hi @DominicWuest 

The query is deprecated, and it will not be possible to run it in the next mayor version of neo4j.

The warnings generated by the query reads like this:
`'Creating an entity (x) and referencing that entity in a property definition in the same CREATE is deprecated.'`

Unfortunately, the warning is not visible straight away, because neo4j fails to generate a plan for this query. To see the warning, you have to run the queries like this: `EXPLAIN CYPHER runtime=legacy ...`.

The deprecation is because allowing these cross-references in the same CREATE can easily lead to cyclic references and it is unclear in which order elements should be created.

To fix the warning, and the error, change your queries like this:

```
CREATE (x)
CREATE ({a1:EXISTS { RETURN COUNT(0) AS a2, keys(x) AS a4 }})
```

Note that this is the same issue as #13216 and #13316
