### ISSUE TITLE
Performance issue after upgrade from 3.5 to 4.4

### ISSUE THREAD

**Issue by tomswinkels** [neo4j/neo4j#13354]
Since we have update from Neo4j 3.5 to 4.4 we have some performance issues.

We think there is a problem in the query planner, used the wrong index.
Is makes the whole database slowdown.

- Neo4j version: 4.4.28
- Operating system:  Ubuntu 23.10

Query:

```
PROFILE MATCH (hour:Hour{Hash: "31138173/2022/12/27/09"})
WITH hour
MATCH (prev:Hour{TimeTree: "31138173"})
WHERE prev.HourInDay < hour.HourInDay
WITH prev, hour
ORDER BY prev.HourInDay DESC LIMIT 1
MERGE (prev)-[:NEXT]->(hour)
```

Run on Neo4j 3.5:

![plan](https://github.com/neo4j/neo4j/assets/9036151/91bfff40-0f5e-4b13-9563-083baba6b65b)

Run on Neo4j 4.4.28:

![plan (1)](https://github.com/neo4j/neo4j/assets/9036151/2889cb86-2881-4fc7-9323-46ef1156a896)

When we change the query:

```
PROFILE MATCH (hour:Hour{Hash: "31138173/2022/12/27/09"})
WITH hour, hour.HourInDay as notInUsed
MATCH (prev:Hour{TimeTree: "31138173"})
WHERE prev.HourInDay < hour.HourInDay
WITH prev, hour
ORDER BY prev.HourInDay DESC LIMIT 1
MERGE (prev)-[:NEXT]->(hour)
```

Then the query is so mutch better and faster, (same as 3.5):

![plan (2)](https://github.com/neo4j/neo4j/assets/9036151/4126c100-a259-4592-bb34-01112cdaab8d)

**Comment by tomswinkels** [comment]
We have tested it on Neo4j 5.14.0.

There is the same problem.

First query:

![plan (3)](https://github.com/neo4j/neo4j/assets/9036151/3d88a3d3-dfd8-443c-bfcd-a1981415f0c2)

`Cypher version: , planner: COST, runtime: PIPELINED. 100782520 total db hits in 33281 ms.`

Second query:

![plan (4)](https://github.com/neo4j/neo4j/assets/9036151/54403f40-860f-4834-b7fe-4d09669749a3)

`Cypher version: , planner: COST, runtime: PIPELINED. 178000 total db hits in 185 ms.`

**Comment by jexp** [comment]
What happens if you prefix your query with `cypher runtime=slotted`?

**Comment by tomswinkels** [comment]
@jexp Also using the wrong index.

See the result:

```
cypher runtime=slotted

PROFILE MATCH (hour:Hour{Hash: "31138173/2022/12/27/09"})
WITH hour
MATCH (prev:Hour{TimeTree: "31138173"})
WHERE prev.HourInDay < hour.HourInDay
WITH prev, hour
ORDER BY prev.HourInDay DESC LIMIT 1
MERGE (prev)-[:NEXT]->(hour)
```

`Cypher version: CYPHER 4.4, planner: COST, runtime: SLOTTED. 67188592 total db hits in 86440 ms.`

![plan (5)](https://github.com/neo4j/neo4j/assets/9036151/5b5bcbc8-aeb0-4a81-9c87-7f15cd9d925e)

**Comment by inmost-light** [comment]
@tomswinkels 

Thank you for reporting, a fix has been implemented and should make it into 4.4.29 and 5.16.

Until then you'll need a workaround, like your `WITH hour, hour.HourInDay as notInUsed` or `WITH hour SKIP 0`.

**Comment by tomswinkels** [comment]
@inmost-light good to hear! When will that versions released?

**Comment by inmost-light** [comment]
@tomswinkels I don't know exactly, probably early January for 4.4.29 and a few weeks later for 5.16.

**Comment by tim-hanssen** [comment]
@inmost-light can you tell when the bug started? Is it possible to maybe go back to .27?

**Comment by inmost-light** [comment]
@tim-hanssen It was introduced in 4.3.0.

**Comment by tomswinkels** [comment]
@inmost-light Can you tell something more about the impact of this fix? We have a lot of performance issues after upgrading to Neo4j 4. So we are curious of the bug are close all us problems.

**Comment by inmost-light** [comment]
@tomswinkels 

Affected queries must have:
1. A MATCH clause with multiple components (i.e. comma-separated patterns without a connecting relationship). `MATCH (hour:Hour), (prev:Hour)`  would be an example, but `MATCH (hour:Hour) MATCH (prev:Hour)` and `MATCH (hour:Hour) WITH hour MATCH (prev:Hour)` are also equivalent from the planner perspective, so they also fit. Using one of the previously mentioned workarounds invalidates this condition.
2. Multiple index-compatible predicates like `prev.TimeTree = "31138173" AND prev.HourInDay < hour.HourInDay`.
3. At least one of these predicates must depend on a variable from the other component (`hour` in this case).

Given these conditions, planner currently relies on a heuristic that always chooses to use an index that solves the predicate with dependency (`prev.HourInDay < hour.HourInDay`) over alternatives.

The fix is to consider all index options and choose the one that is optimal according to our cardinality-cost model instead of using a heuristic.

**Comment by tomswinkels** [comment]
Thnx @inmost-light !

**Comment by inmost-light** [comment]
@tomswinkels Hey, have you had the chance to try out the new 4.4 version?

**Comment by tomswinkels** [comment]
@inmost-light Hi, the change fixed this issue. Thanks!
