### ISSUE TITLE
The query returned an incorrect result

### ISSUE THREAD

**Issue by 17318584151** [neo4j/neo4j#13372]
match (c:analyzer) where c.id = "9625d5ae8b97425597a104d104cdd87a" return c
<img width="1082" alt="image" src="https://github.com/neo4j/neo4j/assets/155518083/36e6d8cc-7ade-4082-9ee8-3d2e7e7e63b9">
The version I'm using is 4.2.9
I don't know how to reproduce it, but can I provide my data directory

**Comment by 17318584151** [comment]
<img width="1226" alt="image" src="https://github.com/neo4j/neo4j/assets/155518083/fd490dcc-2077-494c-a9c6-5a1e04671c6a">

return c.id is correct

**Comment by gem-neo4j** [comment]
Hi there! Thanks for writing in, unfortunately 4.2 is no longer supported by us, and I would suggest updating to a supported version, as this issue may have already been fixed by us at some other point.

One thing you can try is to run a consistency check to see if there is anything wrong with the store. See [here](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/consistency-checker/) for more info.

If the query is using an index, a possible fix is to drop and rebuild it.

If you find this problem persists in supported versions, feel free to reopen this ticket! Hope this helps.
