### ISSUE TITLE
neo4j admin import incorrectly reports fault-tolerance parameter on failed import.

### ISSUE THREAD

**Issue by paulBloomreach** [neo4j/neo4j#13378]
On Neo4j Community 5.15.0

When I have a failed import, it tells me:

"We recommend that data should be cleaned before importing. The fault-tolerance can be increased using –fault-tolerance=<num>, however this will dramatically affect the tool’s performance."

However there is no parameter called: - fault-tolerance. The correct message should read:

"We recommend that data should be cleaned before importing. The fault-tolerance can be increased using  --bad-tolerance=<num>, however this will dramatically affect the tool’s performance."

**Comment by emmaholmbergohlsson** [comment]
Hey @paulBloomreach. Thank you for reporting it, you are completely right. I have merged a fix now that will be included in the next release (5.17)
I'll close this issue since there is nothing more to do here. Don't hesitate to raise a new one if you run into any more problems. Thank you for the help :star:
