### ISSUE TITLE
Failed to create node property type constraint: Invalid property type `STRING NOT NULL`.

### ISSUE THREAD

**Issue by pksunkara** [neo4j/neo4j#13407]
## Guidelines

- Neo4j version: 5.17 enterprise
- Operating system:  Arch Linux
- API/Driver: cypher-shell & browser

####  **Steps to reproduce**

* New database with nothing in it.
* Run the following:

```cypher
CREATE CONSTRAINT person_type_email
FOR (n:Person)
REQUIRE n.email IS :: STRING!;
```

#### Expected behavior

It should work in creating a property type constraint of `STRING NOT NULL`

According to the following text in https://neo4j.com/docs/cypher-manual/current/values-and-types/property-structural-constructed/#types-synonyms

> All Cypher types contain the `null` value. To make them not nullable, `NOT NULL` can be appended to the end of the type (e.g. `BOOLEAN NOT NULL`, `LIST<FLOAT NOT NULL>`). A shorthand syntax equivalent, introduced in Neo4j 5.14, for `NOT NULL` is to use an exclamation mark `!` (e.g. `INTEGER!`, `LIST<STRING!>`).

#### Actual behavior

Getting the following error:

```
Failed to create node property type constraint: Invalid property type `STRING NOT NULL`. (line 3, column 20 (offset: 67))
"REQUIRE n.email IS :: STRING!"
                       ^
```

**Comment by Hunterness** [comment]
This is actually the expected behaviour, even if it might not be that intuitive.

The property type constraints cannot handle all types but only a subset of them as given by the [constraint documentation](https://neo4j.com/docs/cypher-manual/current/constraints/examples/#constraints-examples-node-property-type) (picture below). At the moment that does not include the `NOT NULL` variants as existence/not null has its own separate [constraint `IS NOT NULL`](https://neo4j.com/docs/cypher-manual/current/constraints/examples/#constraints-examples-node-property-existence) which pre-dates the property type ones. 

![image](https://github.com/neo4j/neo4j/assets/7591575/0c8a9acc-778f-4771-8b72-04c44ca241ef)

**Comment by pksunkara** [comment]
That makes sense. But I think the line immediately under it that says

> For all available Cypher® types, see the section on [types and their synonyms](https://neo4j.com/docs/cypher-manual/current/values-and-types/property-structural-constructed/#types-synonyms).

kinda confused me and thought any type is supported.

**Comment by Hunterness** [comment]
That is more to see syntax variations and remaining (but not allowed) types, could maybe be better formulated though. But the top of the list does say that these are the ones supported by the constraints 🤷‍♀️

**Comment by pksunkara** [comment]
Yup, can definitely be better worded. Thanks for the help.
