### ISSUE TITLE
No label was specified for the node index in xyz:ID(xyz-id-space)

### ISSUE THREAD

**Issue by zxbayne** [neo4j/neo4j#13411]
I am trying to do an incremental import from neo4j-admin import option by running the following command:

bin/neo4j-admin database import incremental --force --stage=ALL --nodes person.csv --skip-duplicate-nodes mdm

similiar to #13224 
I get the following stacktrace as error:

- Neo4j version: 5.17.0
- Operating system: Ubuntu 16.04 (Using docker to deploy neo4j )
- API/Driver: Neo4j-Admin Command
- Expected behavior: Import to be done successfully
- Actual behavior: The stack trace shown as above
- 
![image](https://github.com/neo4j/neo4j/assets/52626036/085267c9-1426-4e7e-841b-d6e83aa7dad8)

![image](https://github.com/neo4j/neo4j/assets/52626036/1079f41e-2fb1-4ada-bae7-0c585e11c891)

**Comment by zxbayne** [comment]
Using the same data set, the full import is successful. But it failed after changing the command to incremental import.

**Comment by 0x66656c6978** [comment]
Im facing the same Issue. Doing a full import on the first batch works, but running an incremental import on the same nodes and relationships results in this error.

In my case the labels and IDs are separate. The header for the node ID is `id:ID` and the header for the labels is `:LABEL`

**Comment by tinwelint** [comment]
Hi all, have you had a look at https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/#import-tool-incremental ? Specifically see the note for incremental import in https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/#import-tool-header-format

**Comment by 0x66656c6978** [comment]
Hey, thanks for your helpful reply!

No that constraint is new to me. So the nodes have to be in individual files where each file has to have the same labels?

The main reason I used the incremental import is because the full import was taking ~15 minutes for 100k entities, for a dataset with 90 million entities and 700 million relationships with the following command (the machine has 32 cores and ~100gb of ram and a fast SSD).
Each file has a header with 1703 properties, and most of these values are empty, because the entities have very different properties.

```
neo4j-admin database import full \
    --nodes 'import/entity/\d+\.csv' \
    --relationships 'import/relationship/\d+\.csv' \
    --array-delimiter=";" \
    --delimiter="\t" \
    --overwrite-destination \
    --skip-duplicate-nodes=true \
    --skip-bad-relationships=true \
    --bad-tolerance=10000000 \
    --max-off-heap-memory=60G \
    --verbose \
    mydb
```

I read online that people sped up their imports by chunking their import files so that smaller number of entities will be imported with only the relationships to these nodes and the nodes created prior.

And I definitely noticed a speed up increase when I split the import into multiple files. Importing 100k entities with their relationships only took 5 minutes.

Now is there no way to keep these files as chunks and import them with neo4j, without making sure each file only has nodes with the same labels?

**Comment by tinwelint** [comment]
@0x66656c6978 For incremental import within a file group (one or more files that are logically one stream) nodes can have different labels, but they all at least need to share that label that the backing constraint has, and which its header specifies. They can have other labels in additional to that.

**Comment by 0x66656c6978** [comment]
@tinwelint great, thank you for your reply! So I assume I could add a generic label, for example `Entity` to all my nodes and add this label to the header.

**Comment by tinwelint** [comment]
@0x66656c6978 Hmm are there any relationships in the incremental data that refers to existing nodes? I'd guess the user experience is a bit cumbersome if you're just adding new nodes and new relationships only for these new nodes since the main idea is to be able to create new relationships for existing nodes as well.

**Comment by 0x66656c6978** [comment]
No, there are no existing nodes, but I don't think we're going to need the incremental import anymore since we figured out the main bottleneck: the main performance problem is that each node has a unique label. We are trying to normalize them and group them. We've seen a tremendous improvement in speed when using the same label for all nodes. So we are probably just going to use the full import.


Thanks again for your help!

**Comment by Asriel31** [comment]
Hello,
May be someone have an idea about this WARN message ?
WARN: file group with header file test.csv specifies no node labels, which could be a mistake 
That message is raised for each node load via full import without relationship header : user_id:ID,name,gender, :LABEL  instance 65649, "Ivanka Bonova", "Female", USER ?
by advance thks a lot :)

**Comment by samarthps29** [comment]
I think this should resolve the issue - https://neo4j.com/docs/operations-manual/current/import/#import-tool-header-format

![Image](https://github.com/user-attachments/assets/9a61ac74-1599-4dc7-9248-7c9da520266e)
