### ISSUE TITLE
Failed to invoke function `genai.vector.encode`: Caused by: java.net.ConnectException: Connection timed out: connect

### ISSUE THREAD

**Issue by 3mpt** [neo4j/neo4j#13420]
我用neo4j 5.17版本，想进行genai的实验，然而一直出现这个错误，我在官方notebook上可以成功运行，在本地报错，我觉得是我的网络问题，有人遇到相同的情况吗？怎么解决这个问题。

**Comment by parnmatt** [comment]
Hi @3mpt sorry I don't speak Mandarin, but Google Translate has helped :smile: 

I'm sorry you've had some issues using the GenAI plugin.
This exception indicates issues connecting to the vector provider service you have chosen, from the Neo4j instance you are running. Usually, something is blacklisting these providers at some level.

The server(s) running the instance might be configured to blacklist, for example in `/etc/hosts`; or some other local firewall.
The router itself may have been configured to restrict access to certain domains.
Your internet service provider could also be blocking your traffic. They may be required to do so based on the local laws of your region or country.

For example, here is the list of [supported countries for OpenAI](https://platform.openai.com/docs/supported-countries). You can check if your country is listed there. If that domain is blocked, your country likely won't be listed. Other supported providers may have similar lists.

The GenAI plugin supports OpenAI, VertexAI, and Bedrock. Azure Open AI is also supported on Aura and also packaged with Neo4j 5.18 Enterprise Edition. Hopefully one of those works for you on-prem; if not, we are exploring the possibility of making it easy to provide your custom providers on-prem.

If you believe you are in a supported region and have confirmed that your internet service provider, network configuration, or firewalls are not blocking the request; please update us with more detailed information of your situation.

**Comment by 3mpt** [comment]
> 嗨，对不起，我不会说普通话，但谷歌翻译有帮助 😄
> 
> 很抱歉，您在使用 GenAI 插件时遇到了一些问题。此异常表示从您正在运行的 Neo4j 实例连接到您选择的矢量提供程序服务时出现问题。通常，某些东西在某种程度上将这些提供商列入黑名单。
> 
> 运行实例的服务器可能配置为黑名单，例如;或其他一些本地防火墙。路由器本身可能已配置为限制对某些域的访问。您的互联网服务提供商也可能阻止您的流量。根据您所在地区或国家/地区的当地法律，他们可能需要这样做。`/etc/hosts`
> 
> 例如，这里是 [OpenAI 支持的国家/地区](https://platform.openai.com/docs/supported-countries)列表。您可以检查您的国家/地区是否列在那里。如果该域名被屏蔽，您所在的国家/地区可能不会被列出。其他受支持的提供程序可能具有类似的列表。
> 
> GenAI 插件支持 OpenAI、VertexAI 和 Bedrock。Azure Open AI 在 Aura 上也受支持，并且还与 Neo4j 5.18 Enterprise Edition 打包在一起。希望其中之一适合您在本地使用;如果没有，我们正在探索使在本地提供自定义提供程序变得容易的可能性。
> 
> 如果您认为自己位于受支持的区域，并已确认您的互联网服务提供商、网络配置或防火墙未阻止该请求;请向我们提供您情况的更多详细信息。

谢谢你的回复，我的地区并不在这里但是我可以在本地的代理上访问openai，但是我无法让neo4j桌面版本也用同样的方式访问。

**Comment by parnmatt** [comment]
If your region is not listed there, then OpenAI is likely being blacklisted by your internet service provider. That is something out of our control.

You've mentioned using a proxy with Neo4j Desktop. To my knowledge, you can configure Neo4j Desktop to [use a proxy](https://neo4j.com/docs/desktop-manual/current/installation/advanced-installation/#_proxy_setup), but I believe that is for Desktop itself, rather than the instances running.

Proxies can be configured with an allow-list, block-list, or a non-proxy-list.
Thus the proxy itself could be blocking the call, or allowing the connection directly rather than via the proxy. Ensure the proxy is setup correctly for your use case.

You can set up your system networking to have a global proxy, and all network traffic goes via that proxy.
However, you should be able to configure a Java-based application to [use a specific proxy](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html).

In this case you would want to set the Java system properties `https.proxyHost`, and `https.proxyPort`.

These can be added to your [`neo4j.conf`](https://neo4j.com/docs/operations-manual/current/configuration/file-locations/#neo4j-config) using [`server.jvm.additional`](https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/#config_server.jvm.additional)

```ini
server.jvm.additional=-Dhttps.proxyHost=example.proxy.host.com
server.jvm.additional=-Dhttps.proxyPort=443
```
(replace with your proxy settings)
Restart the DBMS to enable the new settings.

Hopefully that might help.

**Comment by parnmatt** [comment]
I hope we have found the underlying issue and the potential use of a proxy, or alternative provider has aided in using the feature. As we've not heard anything back for the last month therefore I will be closing this issue.
If you feel this particular issue has not been resolved, feel free to reach back out.
