### ISSUE TITLE
One possible performance issue

### ISSUE THREAD

**Issue by salted-yu** [neo4j/neo4j#13438]
- Neo4j version: 5.18.1 community
- Operating system: Ubuntu 22.04
- API/Driver:  Cypher 
- **Steps to reproduce**
1. Use the https://github.com/neo4j-graph-examples/twitter-v2 database.
2. Execute the following query
3. query 1 with 88 ms
```cypher
MATCH (n0:User)<-[e1:MENTIONS]-(n1)<-[e2:POSTS]-(n2:User)<-[e3:FOLLOWS]-(n3:Me)-[e4:POSTS]->(n4),(n2:User) RETURN count(n2) as n
```
![image](https://github.com/neo4j/neo4j/assets/61446801/ae7409c8-4635-4a35-bc0b-4013f3fbd2cc)

4. query 2 with 3319 ms
```cypher
MATCH (n0:User)<-[e1:MENTIONS]-(n1:Tweet)<-[e2:POSTS]-(n2:User)<-[e3:FOLLOWS]-(n3:Me)-[e4:POSTS]->(n4:Tweet),(n2:User) RETURN count(n2) as n
```
![image](https://github.com/neo4j/neo4j/assets/61446801/9e2f4bad-7237-4f7d-b458-9648d1477bfc)

- Expected behavior
The two query should spend similar time.
- Actual behavior
query 2 with more label information much slower than query 1

There are the profile results for the queries.
**query 1**
![plan1](https://github.com/neo4j/neo4j/assets/61446801/3a984a0b-23b5-4ceb-9314-8e198dad921e)
**query 2**
![plan2](https://github.com/neo4j/neo4j/assets/61446801/d408733b-a115-4426-9222-2fd21bfa6061)

**Comment by alexaverbuch** [comment]
Thank you @salted-yu we'll take a look at this.
You are correct to assume that adding more schema information _tends_ to result in better plans, and therefore better performance.

However, there is no guaranty that it will always work this way.
When there are too few reliable statistics to work with (as is the case with this query) the planner sometimes gets "lucky" with its guess. In other words, it just so happened the planner made a very lucky guess for your first query.

**Comment by arnefischereit** [comment]
Hi @salted-yu,

Thank you for the interesting issue.

There are several layers to this problem.

## Filters are not for free

Let's start with the overall question, why adding a label can lead to a worse plan: Adding a label is not for free, as we do not have a guarantee in Neo4j in terms of a schema that all `-[:POSTS]->` relationships end in a node with label `:Tweet`. Having an optional schema is on the roadmap but until then we need to plan an additional `Filter` operator, which incurs cost.

Let's have a look at the decision point between the two plans when a `:Tweet` label is specified.

```
	0: Plan #0x7ae77e13 [winner] 
		.nodeHashJoin("n3") // cost 39387.5, cardinality 1213867.5999999999
		.|.filter("n2:User") // cost 10149.0, cardinality 10124.0
		.|.expandAll("(n3)-[e3:FOLLOWS]->(n2)") // cost 25.0, cardinality 10124.0
		.|.nodeByLabelScan("n3", "Me", IndexOrderNone) // cost 10.0, cardinality 10.0
		.filter("n4:Tweet") // cost 1224.0, cardinality 1199.0
		.expandAll("(n3)-[e4:POSTS]->(n4)") // cost 25.0, cardinality 1199.0
		.nodeByLabelScan("n3", "Me", IndexOrderNone) // cost 10.0, cardinality 10.0
		(hints: 0, heuristic: 0)

[...]

	3: Plan #0xf69c6018 
		.filter("n4:Tweet") // cost 1239202.6, cardinality 1213867.6
		.expandAll("(n3)-[e4:POSTS]->(n4)") // cost 25335.0, cardinality 1213867.6
		.filter("n2:User") // cost 10149.0, cardinality 10124.0
		.expandAll("(n3)-[e3:FOLLOWS]->(n2)") // cost 25.0, cardinality 10124.0
		.nodeByLabelScan("n3", "Me", IndexOrderNone) // cost 10.0, cardinality 10.0
		(hints: 0, heuristic: 0)
```

Plan 0 is assigned a cost of 39387, as it only needs to evaluate `n4:Tweet` on part of the result set (1199 nodes). Whereas plan 3 is evaluating it on all 1,218,867 rows, which is far more costly. (These are estimation, mind you.) Therefore, we choose plan 0 (cost 39,387) instead of plan 3 (cost 1,239,202).

If we subtract the cost of the `Filter`, we would have chosen plan 3 instead
```
(1,239,202 - 1,213,867) = 25,335 < 38,188 = (39,387 - 1,199)
```
## An egocentric dataset

So, if the `Filter` on `:Tweet` costs so much, why is the first plan faster then?

Well, this comes down to us making some bad estimation on how many results are returned by parts of the pattern (the cardinality). This is due to the fact that we generally assume an even distribution of statistics over the graph.

You can test this yourself by running
```cypher
MATCH (u:User)
RETURN
  COUNT {(u)<-[:FOLLOWS]-()} AS followers,
  COUNT {(u)-[:POSTS]->()}   AS posts
```
Plotting/analysing the results shows that in the case of the twitter dataset, there is one user (`:Me`) out of 38,986 users accounting for 56% of all `:POSTS` relationships and for 77% of all `:FOLLOWS` relationships. We could call this a very *egocentric* dataset. This skews our estimates such that we completely underestimate the number of rows for pattern `(n2)<-[e3:FOLLOWS]-(n3)-[e4:POSTS]->(n4)` which we need to deal with at the decision point mentioned in the previous paragraph.

I hope this makes some sense to you and gave you a fun tour around the decision making in the Cypher Planner.

Let me know if you have any more questions regarding this. Otherwise, I will close this issue.

**Comment by salted-yu** [comment]
Thank you for your detailed explanation!
I have no problem and will close this issue.
