### ISSUE TITLE
Neo4j cypher ：query directed relationships

### ISSUE THREAD

**Issue by zyh20011** [neo4j/neo4j#13449]
To help us understand your issue, please specify important details, primarily:

- Neo4j Desktop version: 1.5.9
- Operating system:  Windows 11

I found that when using the Cypher statement to query the directional relationship between two nodes, the graph view and other views display differently. All other views can display A ->B results well, but the graph view still displays the relationship between A ->B and B ->A, without displaying the directional relationship.

graph view
![定向关系graph视图](https://github.com/neo4j/neo4j/assets/125949405/09ddc1b4-a3c9-41d9-adaa-dc3141e279b0)

Is there a problem with my cypher statement？

**Comment by InverseFalcon** [comment]
Hello,

Your Cypher is fine. The Neo4j Browser has a default behavior (which can be disabled in the settings tab) that will additionally query and show any relationships in the graph between any of the nodes returned from a query, even if you didn't ask for them or return them. The purpose is to see a more complete view of the segment of the graph you are viewing, but it can be confusing when you are only looking to display some relationships instead of others, or no relationships at all.

Note that these extra relationships (queried under the hood), if they exist, only show up on the graphical result view, and not the tabular or textual results view.

Here's an answer provided for a similar question, which includes a screenshot showing where to find the `Connect result nodes` checkbox:
https://community.neo4j.com/t/query-results-different-in-neo4j-browser-versus-bloom-neodash/59839/2

**Comment by zyh20011** [comment]
Thanks！I solved it！
