### ISSUE TITLE
Critical CVE in container image

### ISSUE THREAD

**Issue by sebastianvoss** [neo4j/neo4j#13448]
According to a recent scan there are critical CVEs in the container image `neo4j:5.19.0-enterprise`:

- CVE-2019-8457
- CVE-2023-45853

```
Total: 2 (CRITICAL: 2)

┌──────────┬────────────────┬──────────┬──────────────┬─────────────────────────┬───────────────┬────────────────────────────────────────────────────────┐
│ Library  │ Vulnerability  │ Severity │    Status    │    Installed Version    │ Fixed Version │                         Title                          │
├──────────┼────────────────┼──────────┼──────────────┼─────────────────────────┼───────────────┼────────────────────────────────────────────────────────┤
│ libdb5.3 │ CVE-2019-8457  │ CRITICAL │ affected     │ 5.3.28+dfsg1-0.8        │               │ sqlite: heap out-of-bound read in function rtreenode() │
│          │                │          │              │                         │               │ https://avd.aquasec.com/nvd/cve-2019-8457              │
├──────────┼────────────────┤          ├──────────────┼─────────────────────────┼───────────────┼────────────────────────────────────────────────────────┤
│ zlib1g   │ CVE-2023-45853 │          │ will_not_fix │ 1:1.2.11.dfsg-2+deb11u2 │               │ zlib: integer overflow and resultant heap-based buffer │
│          │                │          │              │                         │               │ overflow in zipOpenNewFileInZip4_6                     │
│          │                │          │              │                         │               │ https://avd.aquasec.com/nvd/cve-2023-45853             │
└──────────┴────────────────┴──────────┴──────────────┴─────────────────────────┴───────────────┴────────────────────────────────────────────────────────┘
```

Are there already plans to resolve those?

**Comment by jennyowen** [comment]
Both of those CVEs are from the `debian:bullseye-slim` base image as essential linux packages, rather than from Neo4j. If debian fixes their image it will automatically be updated, by docker, into our latest images. 
There is nothing we can do about them in Neo4j because they are not coming from our part of the image.

Also, for what it's worth, the security scan on docker hub for `neo4j:5.19.0-enterprise` does not report any critical severity CVEs in `neo4j:5.19.0-enterprise` or `debian:bullseye-slim`:
https://hub.docker.com/layers/library/neo4j/enterprise-bullseye/images/sha256-8c1e19ad0b1e883111bb89141d19fecfc6e281bca8973c46251e430cab68840b?context=explore

Since you have an enterprise license you can always ask Neo4j support these and any future questions about CVEs. They are usually much faster to respond.
