### ISSUE TITLE
toInteger and toFloat can't handle strings with common thousands delimiters

### ISSUE THREAD

**Issue by mdfrenchman** [neo4j/neo4j#13442]
Not sure if this is a bug or a feature request, but for most languages it's a bug.
CAVEAT: I understand `,` is a decimal separator in some cultures, but considering strings often have those type of values, it should operate off the culture variant setting for the server instead of returning null.

- Neo4j version: 5.18.1
- Operating system: All
- API/Driver: Cypher
- **Steps to reproduce**
`RETURN toInteger("1,000") as x`
`RETURN reduce (total = 0, x in ["1,000","100","200"] | total + toInteger(x)) as thisErrors`
- Expected behavior
x returns as 1000
thisErrors returns as 1300
- Actual behavior
x returns as null
thisErrors fails with **Can't add 'Long' to 'NO_VALUE'**

**Comment by LinneaAndersson** [comment]
@mdfrenchmanThanks for reaching out to us. The`,` is currently not supported. I will put it as a feature request and get back to you once I have more information.

**Comment by pontusmelke** [comment]
Hi @mdfrenchman 
Thanks for reporting. As you allude to it is not straight forward to add a decimal in the way you suggest since it will depend on the locale of your server. In Sweden where I live "1,000" would be interpreted as "1.0" for example. 

We will most probably not add support for using decimal in this way however in 5.x we do support using an underscore as a delimiter, so in your example you could use 
```
RETURN 1_000 as x
```

It is not exactly what you asked for but hopefully it could still be helpful. However, toInteger doesn't seem to support underscores. We will make sure to look into that! 

Best regards
Pontus
