### ISSUE TITLE
Version 5.19.0 and 5.20.0 releases

### ISSUE THREAD

**Issue by gongomgra** [neo4j/neo4j#13453]
Hello!

I have seen the branch 5.19 in the repo for some time, but a release for that version was not tagged in this repository. Do you have any estimation on when the open source version will be released?

**Comment by kr-0-n** [comment]
I am missing the neo4j/neo4j-admin:5.19.0 release on dockerhub, which might be related to this

**Comment by jmsuhy** [comment]
Until Neo4j gets this resolved,  If you want access to version 5.19.0 that the DozerDB team compiled - you can access it on docker hub or direct download.   It is Neo4j Community 5.19 branch +  DozerDB plugin pre-configured.   Links are on site : https://dozerdb.org/       

You can also compile Neo4j community yourself from the 5.19 branch in this repo.

I am curious what is going on as well.

**Comment by gongomgra** [comment]
Any update on this? I see version 5.20.0 has been released for the APOC procedures asset yet the Neo4j version has not been released.

**Comment by jmsuhy** [comment]
Looks like Neo4j is playing games again.  Version 5.20.0 is available for download on their website but since the source code is not available they may be violating the GPLv3 license.  Keep in mind the free software foundation recently forced Neo4j to remove all AGPL licenses that had commons clause and infringed on FSF’s AGPL copyright.   

Under the GNU General Public License version 3 (GPLv3), if you distribute software that is based on GPL-licensed code, you are required to make the source code available to the recipients of the software. This means that anyone who receives the binary or executable version of your software must also have access to the corresponding source code.

**Comment by jmsuhy** [comment]
All code for 5.20.0 was published.   Thank you.

**Comment by ericsporre** [comment]
Hi!

Sorry about the missing tags. This has been corrected and both 5.19 and 5.20 are tagged and all source code is available.
