### ISSUE TITLE
Introduce methods for specific Entity properties

### ISSUE THREAD

**Issue by TomVanWemmel** [neo4j/neo4j#13477]
For the implementation of custom code like user-defined procedures, it's not unlikely that you need to read or modify node properties. Unfortunately, the Entity interface only defines a handful of methods and the values are all of the type Object. 

It would be convenient if there was a way to indicate what type of Object is expected. 
Perhaps a method which has a generic type or, since the properties are all Value objects in origin, a method that returns (a copy of) the Value.

**Comment by VishalMCF** [comment]
You mean like <T extends SomeCustomBaseObject>??

**Comment by parnmatt** [comment]
@TomVanWemmel can you please provide an example of what you mean.

`Entity::getProperty` indeed returns an `Object`, because that is the _most specialised type_ that they all share.
It _is_ a copy of the underlying data in a _normal_ Java class. It will be a `String`, or a `double[]` or a `Long` (primitives would be boxed).

Having a generic getter would, at best, be the cast you'd do yourself.
```java
(String) person.getProperty("name");
// vs
person.<String>getTypedProperty("name"); // which would effectively do the same unchecked cast

// though in some cases, can be inferred to be String, thus
person.getTypedProperty("name");
```
The latter can have _some_ benefit in some interfaces and use cases where the `<String>` can fully be inferred.
I'm not seeing a strong reason to expand the current public interface.

You are welcome to write your own helper functions and use those getters instead, thus taking advantage of the places which can infer the type by the interface.
```java
public <T> T getPropertyFrom(Entity entity, String propKey) {
    return (T) entity.getProperty(propKey);
}

public <T, V extends T> T getPropertyFrom(Entity entity, String propKey, V defaultValue) {
    return (T) entity.getProperty(propKey, defaultValue);
}
```
---

It's important to stress these are in the normal Java type system (or public interface), not our internal `Value` types. It returns a `String`, not a `StringValue` (or some other `TextValue`); a `double[]`, not a `DoubleArray`; a `Long`, not a `LongValue`.
Though internally we handle things as `Value`, a copy in a more native Java type is always returned to the user in the public API (where possible) or an interface (such as `PointValue` to `Point`).
The `Value` types are not part of the public API, but some interfaces are.

**Comment by parnmatt** [comment]
Hi @TomVanWemmel it's been months since your last activity on this issue.
I presume you've found a workaround that works for you.
As noted above, without some pointed examples I do not see a strong reason to expand our public interface in this area to do the unchecked cast on behalf of the user.
I will be closing this issue for the time being; however, please feel free to reopen it if you wish to further discuss.
