### ISSUE TITLE
Error trying to create embeddings on graph entities - 'vectorDimension' must be between 1 and 0 inclusively

### ISSUE THREAD

**Issue by liadlevy-pando** [neo4j/neo4j#13470]
## Overview

When I run the code from the [blog](https://neo4j.com/developer-blog/knowledge-graph-rag-application/
) all work well, but when trying to run it on my neo4j database data I get this error.

```python 
neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `db.index.vector.createNodeIndex`: Caused by: java.lang.IllegalArgumentException: 'vectorDimension' must be between 1 and 0 inclusively}
```
On some entities I can get it work but on others I don't. Cloudn't find the pattern why it happens.

## neo4j.config
Added to default config
```bash
dbms.security.procedures.allowlist=apoc.coll.*,apoc.load.*,gds.*,apoc.*
dbms.security.procedures.unrestricted=apoc.*, gds.*, jwt.security.*
```

## Dependencies:
- Neo4j version: 5.18.1/5.19/5.20 - Enterprise Version
- Operating system: Windows (Docker) / Linux AMI AWS
- Python: 3.11
### Packages
- langchain-community==0.2.2
- neo4j==5.18.0/5.19.0/5.20.0
- langchain==0.2.2
- langchain-core==0.2.4
- langchain-openai==0.1.8

## Steps to reproduce
Using this blog code on my Data
https://neo4j.com/developer-blog/knowledge-graph-rag-application/

Code:
```python

from langchain_community.vectorstores.neo4j_vector import Neo4jVector
from langchain_openai import AzureOpenAIEmbeddings, AzureChatOpenAI
from langchain.chains import RetrievalQA, GraphCypherQAChain
from langchain.agents import create_openai_functions_agent, Tool, AgentExecutor
from langchain import hub
from dotenv import load_dotenv
from langchain_community.graphs import Neo4jGraph


load_dotenv()

neo4j_uri = "bolt://localhost:7687"
neo4j_user = "<...>"
neo4j_password = "<...>"

graph = Neo4jGraph(
    url=neo4j_uri,
    username=neo4j_user,
    password=neo4j_password,
    database="<...>",
    enhanced_schema=True,
)

vector_index = Neo4jVector.from_existing_graph(
    AzureOpenAIEmbeddings(
        azure_deployment='<...>',
        azure_endpoint='<...>',
        openai_api_key='<...>',
        model='text-embedding-3-large',
    ),
    url=neo4j_uri,
    username=neo4j_user,
    password=neo4j_password,
    database="<...>",
    index_name='<...>',
    node_label="<...>",
    text_node_properties=['<...>'],
    embedding_node_property='<...>',
)

# Query the vector index
response = vector_index.similarity_search(
    "Give me all <...>"
)
print(response[0].page_content)
```

**Comment by parnmatt** [comment]
Hi, yes this is a known edge case issue that surfaced in Neo4j 5.18, when using a database from before Neo4j 5.11, and using the old procedure to create a node vector index, rather than the native cypher.

The quickest and simplest way forward is to write something to the database with a version of Neo4j 5.11 or newer.
This can be a simple creation of a new node, or changing a property value. These changes can be reverted in a _different_ transaction if they are not wanted. We just need a valid commited write to the store.

I would add that it is best if you populate the database with the vectors before creating the index.

---

This occurs when using a database in which the last write operation was done on a version before Neo4j 5.11 (before vector indexes were added).

Normally the first write when on a later version will automatically upgrade the internal database version to that new version.
However, if the _first_ write happens to be the creation of a vector index using the old `db.index.vector.createNodeIndex` procedure, this will be blocked in Neo4j 5.18 onwards, as it explicitly does a version check to know what is allowed, but it's checking the current version rather than the version it could be after upgrading due to a write.
For Neo4j 5.20, we have at least improved the exception message returned to the user, but this particular edge case bug has not been fixed.

---

Though this older procedure is not "officially" deprecated; it should loosely be considered as such, and from Neo4j 5.15 onwards users should use the `CREATE VECTOR INDEX...` cypher syntax (and Neo4j 5.18 onwards for relationship vector index).

It seems LangChain is using the older procedure rather than the new native cypher commands; which is odd as a quick search through the codebase, it has support for relationship vector indexes with Neo4j, thus should require at least Neo4j 5.18. 
Arguably this is an issue with the implementation of LangChain's Neo4j wrapper, and should be taken up with them to use the newer preferred native cypher.

However, this _is_ an edge case bug we are aware of. Thanks for reaching out.

**Comment by liadlevy-pando** [comment]
@parnmatt Works thanks!
I ran this and it did the trick. 

```sql
CREATE VECTOR INDEX `xxxx`
FOR (n:`xxxx`) ON (n.`embedding`)
OPTIONS {indexConfig: {`vector.dimensions`: 3072,`vector.similarity_function`: 'cosine'}, indexProvider: 'vector-2.0'}
```

**Comment by parnmatt** [comment]
@liadlevy-pando glad you got it working, indeed manually running the cypher would also work well.

---
As an aside, I see the 3072 dimensional vectors, I presume you're using `text-embedding-3-large` embeddings from OpenAI.

These are really quite interesting as these gen3 embeddings have ordered their dimension elements by importance. Which gives it a unique ability to be shortened. When interacting with OpenAI you can specifically ask for that (thus be sent the smaller vectors), however you can also it yourself.

_this assumption cannot be made for any arbitrary embedding model_

I mention this as `text-embedding-3-large` 3072 dimensional vectors shortened to the first 512 dimensions is _much_ smaller on disk, at a relatively small cost of accuracy, but _still_ should be better than the previous generation `text-embedding-ada-002` 1536 dimensional vectors.

Vectors are not small objects, and if you use, store, and index a great number of them; safely reducing their dimensionality can save a lot on space, and possibly compute time.

Just something to consider as you explore this space. :smile:
