### ISSUE TITLE
neo4j-admin import demo data error

### ISSUE THREAD

**Issue by Ming-Lei** [neo4j/neo4j#13492]
In Neo4j Community 5.21.2, use the neo4j-admin import tool to create demo data based on the [documentation](https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin/neo4j-admin-import/), and run the following command:

`neo4j-admin database import full --nodes ./movies_header.csv,movies.csv --nodes ./actors_header.csv,actors.csv --relationships ./roles_header.csv,roles.csv --trim-strings=true movies`

Then run the `CREATE DATABASE movies` command in the browser and return Unsupported administration command: CREATE DATABASE movies

Change initial.dbms.default_database to movies, and the status will be offline after restarting the service

What should I do to use the data I just imported?

**Comment by parnmatt** [comment]
Neo4j Community does not have multi-db, that is an Enterprise feature. You will only have the one database called `neo4j` by default (though controlled via that setting name that was provided to you).

The command should be fine; however, rather than the output database `movies` at the end, you would need `neo4j`.
Considering that would already exist, you would also need to add the option `--overwrite-destination=true`.

You should not need to use `CREATE DATABASE neo4j` for it already exists, you've just overwritten the (hopefully empty) db that was there.

**Comment by parnmatt** [comment]
Hi @Ming-Lei it's been about a month and I've not heard back. I hope you were able make progress, either from my comment, further exploration of the docs, or figuring it out yourself.
If you do have further questions about this, please feel free to reach out to the community.
