### ISSUE TITLE
Neo4j PARALLEL runtime for transactions that modify data

### ISSUE THREAD

**Issue by alexanoid** [neo4j/neo4j#13529]
As far as I know, in the current version of Neo4j, we can use the PARALLEL runtime only for read-only transactions. 

I very often need, for example, to first read data from the database and then update it with another query within the same transaction. Currently, I cannot execute the first query using the PARALLEL runtime.

Please allow the PARALLEL runtime to be used in transactions that not only read data but also modify it.

**Comment by PetrJanouch** [comment]
Hello @alexanoid,

not allowing using parallel runtime for write queries is not an artificial restriction that we introduced on a whim.
The way how neo4j does writes (and handles transaction state) is extremely hard to combine with parallel query execution.
We might do something about it in the future, but it will be a considerable engineering effort that, as far as I am aware, is not planned in near future.

**Comment by henriknyman** [comment]
@alexanoid However, you should be able to execute read-only queries with parallel runtime BEFORE any write queries, in the same transaction. Only once the transaction has accumulated an uncommitted transaction state from a write query it is no longer allowed to execute queries with parallel runtime. 
(Note that due to Neo4j's read-committed isolation level it would not provide any additional benefits over executing the read and write queries in separate transactions, apart from it perhaps being more practical in the current structure of your application code)

> Currently, I cannot execute the first query using the PARALLEL runtime.

How did you run? Can you provide us with the query and error message as this is expected to work?

**Comment by henriknyman** [comment]
Executing a read-only query with parallel runtime AFTER a write query, in the same transaction, is not allowed. This is not supported because the transaction state is currently not thread-safe.

**Comment by henriknyman** [comment]
We are working on support for `CALL { ... } IN CONCURRENT TRANSACTIONS` with parallel runtime, which would allow parallel execution with writes performed in batches in separate transactions. This could be used for updates where transaction atomicity is not required.

**Comment by alexanoid** [comment]
@henriknyman Sorry for my late response. I am currently tied up with renewing my Neo4j startup license. As soon as I extend it, I'll get back to this issue

**Comment by henriknyman** [comment]
@alexanoid I closed this, but you can just reopen it if you still have a problem when you are ready.
