### ISSUE TITLE
When will ISO-GQL be supported

### ISSUE THREAD

**Issue by zhiqix** [neo4j/neo4j#13545]
When will ISO-GQL be supported

**Comment by malencv** [comment]
Neo4j began working on making Cypher GQL conformant early on and has been incrementally releasing GQL features since version 4.4 in 2021. Due to the strong similarities between Cypher and GQL, achieving full conformance is well underway. 

Neo4j publishes detailed conformance documentation (see [here](https://neo4j.com/docs/cypher-manual/current/appendix/gql-conformance/)), updated with each release. 
As an aside, a published conformance statement is the only reliable (and mandatory) way of comparing GQL conformance across implementations. Generic declarations of 'full conformance' are only useful for marketing purposes.
