### ISSUE TITLE
ExecutionFailed about NULL When Using Index

### ISSUE THREAD

**Issue by bluejunhao** [neo4j/neo4j#13559]
I execute a query on my neo4j database ,and an error occurs.

Neo4j version: 5.22.0 Community
operating system: windows 10
API：Cypher version 9
**query**:_MATCH (n:L{k:NULL}) USING POINT INDEX n:L(k) RETURN 1;_

**error message**:
Neo.DatabaseError.Statement.ExecutionFailed
Failed to fulfil the hints of the query.
Could not solve these hints: `USING POINT INDEX n:L(k)`

Plan .produceResults("1")
.projection("$`  AUTOINT0` AS 1")
.nodeIndexOperator("n:L(k = NULL)", indexOrder = IndexOrderNone, argumentIds = Set(), getValue = Map("k" -> CanGetValue), unique = false, indexType = IndexType.RANGE, supportPartitionedScan = true)
.build()

**To reproduce**:
CREATE (n:L{k:point({longitude:1, latitude:1})});
CREATE POINT INDEX p FOR (n:L) ON (n.k);

**Comment by InverseFalcon** [comment]
This is not a bug.

Rather, there are some principles you are missing that explain why this index hint cannot be used.

1. While `null` may be a valid value within a map literal, when it comes to node/relationship properties, `null` is not a value, and instead means "non-existence". As in, setting a property to `null` is the same as removing it, and a filter on a property using `IS NULL` means that the node/relationship does not have the property at all.
2. Indexes in Neo4j only include the node in the index if it has a property value. So if you create a blank `:Person` node with only an `id` property, and you have an index on `:Person(name)`, that node is not going to be included in the index, because it has no `name` property.
3. Per the above, any attempt to lookup a node by a null property cannot use the null property for index lookup.

Because of the above, an attempt to force usage of an index using a hint will fail, if you're trying to pass `null` as the indexed property value in your MATCH pattern. Since `null` is not a value when it comes to node properties, and because only nodes/relationships with non-null indexed properties populate indexes, such an attempt, even if it did not error out and actually attempted to use the index, would never return you any results.
