### ISSUE TITLE
Tap to paste not supported on Safari Mobile / Chrome

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1663]
From @albertoperdomo

Hi,

a user of GrapheneDB has reported an issue. He can't paste content. I've double checked and it doesn't work.

The tap event seems to be blocked and the paste option does not show up.

Not really sure this is really a bug, but I wanted to report it just in case.
I've tested with 2.0.0-M06 on iPad, iOS 6 with Safari Mobile and Chrome.

**Comment by apcj** [comment]
Hi @albertoperdomo. Sadly it doesn't look like we'll be able to fix this because the library we depend on (CodeMirror) doesn't support this feature: https://github.com/codemirror/CodeMirror/issues/60

There are alternatives we could look into (e.g. Ace) but the support doesn't seem much better there either.
