### ISSUE TITLE
Pan and zoom

### ISSUE THREAD

**Issue by jakewins** [neo4j/neo4j#1672]
From @redapple

It would be nice to navigate in the graph like a web map, think google maps, bing maps etc, using the wheel scrool to zoom in/out and mouse-drag to navigate in the graph plane up/down/left/right

I sometimes have to zoom out my browser view and drag "hidden" nodes to the top-left corner and zoom again to interact with them.
![neo4j__panzoom100](https://f.cloud.github.com/assets/886296/1419246/0578d7aa-3fc7-11e3-8ac5-583df7418d05.png)
![neo4j__panzoomout](https://f.cloud.github.com/assets/886296/1419249/0c3f9d08-3fc7-11e3-99fd-b1a7a1dcc97a.png)

**Comment by ambition-consulting** [comment]
This feature is useless without zooming out to get a complete view. You basically expect the user to pan around towards the invisible boundaries to find the hidden nodes. The intention of a visualizing tool should be showing information, not hiding it.

**Comment by akollegger** [comment]
Thanks for your thoughts @amb-it-ion ,

We're glad that you find the built-in visualization compelling enough to ask for more features. We're pretty interested in improving these capabilities of Neo4j Browser because it is so convenient to have basic visualization available. As you can tell from the timeline here, this is a longstanding request which we look forward to resolving when we can. 

Until then, you can find more visualization capabilities using tools from from Linkurious, Keylines or Tom Sawyer. For more information, check out http://neo4j.com/developer/guide-data-visualization/

Cheers,
Andreas

**Comment by trevithj** [comment]
As a work-around, it is possible to manually zoom using the developer console or similar.

Select the background of the graph, and inspect this element: it should be an SVG:rect.
The next element below it should be an SVG:g element `<g>`

Edit the attributes of the `<g>` element to something like `<g transform="scale(0.5)">` to control zooming, or `<g transform="translate(-10, 30)">` to control panning.
Or both - eg: `<g transform="translate(-100,-40) scale(.0.75)">`

This is clunky, but not being able to zoom is a pain.
