### ISSUE TITLE
Cypher (lack of) optimization on variable length path with WHERE NONE(...)

### ISSUE THREAD

**Issue by aseemk** [neo4j/neo4j#1961]
Not sure if you guys would consider this a bug or feature request =), but I was surprised to discover that a `MATCH ... -[rels*]- ...` + `WHERE NONE(rel IN rels WHERE ...)` query doesn't short-circuit the traversal the moment the first match fails. This is the only way I've been able to write a query to return the "first" matching relationship, as described here:

http://stackoverflow.com/questions/21746893/neo4j-cypher-find-first-matching-relationship-in-a-linked-list

Let me know if I can provide more info beyond that post. Thanks for the consideration!

**Comment by jakewins** [comment]
After two years of deep consideration, we have now decided this is a feature request ;)

**Comment by camertron** [comment]
Any update on this?

**Comment by jexp** [comment]
At least for shortest-path we pull in now predicates that are resolvable, @craigtaverner can tell you more. See: http://neo4j.com/docs/3.0.0-SNAPSHOT/query-shortestpath-planning.html

**Comment by craigtaverner** [comment]
This looks like it was fixed by the work we did last year in https://github.com/neo4j/neo4j/commit/2c5c3dd. This is similar to, but not the same work that we did for shortestPath the year before. The concept is that if we have `all()` or `none()` functions that apply to the relationships traversed in the varlength pattern, we can extract the inner predicate and apply it during traversal, with dramatic performance improvements. The commit comment describes this in more detail. It looks like it came out in Neo4j 3.0.3.
