### ISSUE TITLE
Support multiple databases in Neo4j Server

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#266]
@tomasmuller: 'Added `-i PATH` option for `./bin/neo4j` and `./bin/neo4j-coordinator` scripts.

This option override the default value of NEO4J_INSTANCE, which is NEO4J_HOME.

So, to use this flag, the PATH must point to a directory with `/conf` and `/data` folders and files, and all existing path entries in configuration files must be updated to this new location.
'

**Comment by AndrewBryson** [comment]
Are there plans to support multiple databases within a single Neo4j instance?  Having to manage separate instances and the related network configuration for each new port is annoying.  I know the Neo4j licensing model is per-instance so there may not be a great commercial push to support this feature, but I don't know of any other database which doesn't.  Supporting modern day SaaS and multi-tenant scenario would be a lot easier with this feature in place.

**Comment by cleishm** [comment]
Hey @AndrewBryson,

Having multiple databases in a single instance is definitely something we're aware of the desire for, and we will be considering how to add it in future. Part of the history of Neo4j as an embedded application, where the database handles its own resources, has lead to the server hosting a single graph. We're working toward a future where we've got more flexibility and can host several separate databases in a single server, that share resources. Neo4j 2.2 will be a first step in that direction, and more will follow (although we don't have a firm timeline yet).

Meanwhile, one of the advantages of the graph model, is the ability to store multiple disconnected graphs within a single database. Many users do this, using authorisation controls implemented in their applications to ensure separation. So you could certainly consider that approach for now.

Cheers,
Chris

**Comment by AndrewBryson** [comment]
Thanks @cleishm.

**Comment by ceefour** [comment]
:+1: for this.

Even if we can store multiple graphs in one database, import/export (aka backup/restore) is a problem. As it's no longer trivial to restore just a single graph which is partial database. The time taken is also much longer.

**Comment by gilbert** [comment]
Is this feature now supported by neo4j 3.0? If so, how do we take advantage of it?

**Comment by chrisvest** [comment]
@mindeavor True multi-tenancy is not in 3.0. The file layout has been changed to support multiple active databases, but in 3.0 you can still only have one database active at a time: http://neo4j.com/docs/operations-manual/current/#config_dbms.active_database

**Comment by rationalism** [comment]
+1

**Comment by ospaarmann** [comment]
Any updates on this?

**Comment by gilescope** [comment]
+1

**Comment by ospaarmann** [comment]
Just a quick comment. If you want to run tests you can always use Docker. It doesn't take too long to set up locally. Just make sure to mount a host directory as a data volume if you want to keep the data. Otherwise everything will be gone when you kill the container (which shouldn't be an issue for testing).

`docker run --rm -p 7687:7687 -e 'NEO4J_AUTH=none' neo4j:3.0.6`

**Comment by jcontesse** [comment]
+1

**Comment by apomp** [comment]
+1

**Comment by sergiofigueras** [comment]
Well, since 2012 and no support for that have been made yet. I'm afraid that I'll get retired of software development one day and this issue will remain as open here. Added it to my favorites to check if it is still not supported when I get retired.

**Comment by abayob** [comment]
+1

**Comment by janekdb** [comment]
+1 for supporting multiple databases without resorting to multiple instances of neo4j running.

**Comment by algarsi3** [comment]
+1

**Comment by captain-http** [comment]
+1

**Comment by penguinkang** [comment]
+1

**Comment by rajendrag** [comment]
+1

**Comment by ben-tazulev** [comment]
+1

**Comment by Clooney24** [comment]
+1

**Comment by glebiuskv** [comment]
+1

**Comment by vimishor** [comment]
Guys, this +1 spam its getting annoying. Please stop it.

If you are interested on a subject discussed in a issue (_any issue, from any project, not just this one_), just subscribe to the issue and you will get your updates, without forcing an email to be sent to all the people which are subscribed to that particular issue.

**Comment by DeltaBravo** [comment]
@vimishor If you no longer want to receive notifications feel free to unsubscribe. As for the rest of us we will continue to "+1" in order to send the message to Neo4j that the lack of multi-tenancy is a glaring omission which needs to be addressed. 

Some of us are using Neo4j for our SaaS Web applications. We need multiple databases per instance, not simply multiple instances per server. We need it for security. We need it for backup and restoration of individual datasets.

+1

btw, if you feel GitHub should have an integrated 'upvote' feature so we are no longer limited to leaving "+1" comments perhaps you should [contact them](https://github.com/contact) instead of polluting this thread.

**Comment by vimishor** [comment]
> btw, if you feel GitHub should have an integrated 'upvote' feature so we are no longer limited to leaving "+1" comments perhaps you should contact them 

https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

> instead of polluting this thread.

Ah, my bad. I will take my common sense and I'll show myself to the door.

**Comment by DeltaBravo** [comment]
..before you leave let me say you were right! 

There is no need for anyone to spam "+1" when GitHub has an 'upvote' feature. It really is too bad that--as the many "+1" posts show--the feature is so 'hidden'. Of course it is in plain site but instead of a universal upward-pointing-arrow or thumbs-up icon they chose to misuse the emoji icon. None the less, that is the fault of GitHub UI staff and not you. 

Perhaps next time, instead of telling us we are wrong, tell us how we can do things better.

+1 to you : P

**Comment by Herndl** [comment]
Any updates on this?

**Comment by ceefour** [comment]
@deltabravo agreed. GitHub should have an upvote button instead, and allow issues to be sorted (easily, not hidden) based on upvotes... StackOverflow style.

There's a very big difference between "the feature is there" vs "user's intention". I suggest “How Technology is Hijacking Your Mind — from a Former Insider” @tristanharris https://journal.thriveglobal.com/how-technology-hijacks-peoples-minds-from-a-magician-and-google-s-design-ethicist-56d62ef5edf3 for some mindblowing read.

(Sorry out of topic)

**Comment by cyrilchapon** [comment]
Interesting discussion happening here

**Comment by Alexyyek** [comment]
Six years, interesting team.

**Comment by alastai** [comment]
This issue is under active discussion in Neo4j product management/engineering. There are three overlapping approaches being examined, all of which are desirable in our view, but there are pluses and minuses for each, both in terms of features and cost of implementation. 

It would be helpful to get views from the community on relative priorities, as additional comments on this issue. If anyone would prefer to mail or talk privately please feel free to contact alastair DOT green AT neo4j.com.

1) **Multiple clusters**. As part of our roadmap towards a horizontally-scalable sharded Neo4j database, we plan to introduce an addition to our Causal Cluster architecture. This will enable a group of Neo4j clusters to form a single administrative unit. Each cluster within the group will manage a separate database "image". A client will be able to connect to any server in any cluster, and get routed (load balanced) to a server belonging to an identified cluster within the group, where the cluster identity will probably be expressed via a bolt:// URI. Each cluster will be capable of independent administration (backup/restore, cluster config etc). Over time we intend to allow the target state of the cluster group or "multi-cluster" to be expressed as a single, master configuration. This will facilitate/automate the application deployment pattern of having multiple separate database instances for (manual) application "partitions" of the database, and will also prepare the administrative deployment/routing framework for automatic load distribution across a single graph that is partitioned automatically, where each shard or group of shards is managed/replicated by a separate cluster. The first steps of this roadmap will be released in 2018 on current plans.

2) **Multiple graphs**. There are many use cases where system support for identified discrete graphs would be helpful for data modelling and application design purposes. As Chris pointed out a couple of years ago on this thread, you can view discrete, disconnected components within the current single, default graph managed by a Neo4j server as independent graphs. However, at the moment this requires application tagging, which is error-prone, and pollutes predicate expressions in Cypher queries. The openCypher project has been working (in line with other initiatives like the LDBC research query language G-CORE, and with expressed needs/directions from other Cypher implementers like SAP, and the designers of the Oracle PGQL language) to add multiple named graph support to openCypher, along with true graph query compositionality (allowing graphs to be input to and output from queries, which in turn permits composition -- both `andThen()`-style query chaining, and `compose()` style sub-query support). These capabilities would be supplemented by graph set operations like union and difference. There are valuable outgrowths such as support for graph views (named queries) that would result. These features are already beginning to see the light of day in the [Cypher for Apache Spark project](https://github.com/opencypher/cypher-for-apache-spark), which is under very active development. We also plan to extend these new language features to the core Neo4j database server, at least starting that work in 2018.

3) **Multiple databases or "schemas"**. This is not necessarily distinct from item 2). One of the possible architectures for support for multiple graphs in Neo4j Server is that persistent graphs (as opposed to transient view graphs) are fully discrete (no node or relationship sharing between graphs). That in turn could enable some kind of id/storage partitioning, which could enable independent graphs/databases to be backed up and restored independently. 

All of these ways of incarnating multiple independent graphs that can be named and located independently would allow the named graph (or named query = view = graph) to become an object of access control (a resource).

**Comment by ceefour** [comment]
@alastai My hunch is most of the people in this bug, including myself, want no.3.

But even in no.3 you mentioned ambiguous term, "databases" or "schemas", if you're borrowing from SQL terminology, these are different terms. "Databases" is more like it, they're pretty much separate from each other, sometimes in the filesystem level. In both PostgreSQL and MongoDB, a cluster is a collection of databases. It's possible backup a database, multiple databases, or entire cluster.

In my experience schemas are more about convenience/shortcuts rather than a fundamental operational concern. In many ways it's possible to replace "." with "_" and it's essentially what a schema does. It's not always possible to backup and restore independently because it may refer to objects in other schemas and vice versa. I think your no.2 is closer to the "schema" concept.

**Comment by DeltaBravo** [comment]
Some of the technical terms are beyond my realm of clear understanding so I will respond with my use case. I think what I need is option three but aspects of option two sound very attractive (chaining, sub-queries, and multiple named graph support for example).

I have a SAAS product. I have multiple clients and all data is being stored in a single graph. **Backup and restore of a single client's data is a requirement.** Having a graph for each client seems to me the obvious solution.

From a security stand point I do not want a rogue query to be able to reach data from another client (graph). Queries which touched multiple graphs would need to be specified intentionally. That is, not simply following a variable length relationship but rather nodes or query segments would need to specify the graph(s) to search.

I also want to be able to 'copy' a query result (from one graph to another or to itself). I believe this would be accomplished with sub-queries. In SQL I can pass a SELECT query to a INSERT query for example. The issue of unique constraints would then need to be addressed. As it stands I query the database, modify the results in PHP, and insert the 'copy' back into the database. Slow.

**Comment by alastai** [comment]
@ceefour @DeltaBravo Thanks for the comments. Very useful.

**Comment by petermo13** [comment]
Obviously, there is a Giant Demand to this Concurrent Multiple Active DB/Schema Feature. This feature would be Extremely helpful in every way. So Yes, +1 !

**Comment by kewball** [comment]
No. 1, the **Multiple Clusters** sounds like an architectural plan. The other two seem more like after-thoughts.

**Comment by dmikov** [comment]
My interest in this is rather small but painful, we need multiple databases to create and drop them on demand during testing, integration and user. Polluting main database or managing instances with security and network is just too big of a chore. Not to mention is forcing us to run tests one at a time to clean it up.
 As such, our requirement is to have droppable database specified by connection (url), not parts of query.

**Comment by KernelPryanic** [comment]
Definitely the most necessary feature, how can it be in open state so far???

**Comment by and1truong** [comment]
I have multiple applications running on neo4j, but I can't guarantee that application X have a bug that DELETE ALL NODES in graph.

Separated database is very nature & common in programming. Please make (3) happen.

Launch multiple docker instances maybe an option, but each of them use ~1GB RAM, which makes no sense to us.

**Comment by michaelahlers** [comment]
This is a frustrating limitation of Neo4j, for sure. Perhaps it matters less in production, but for integration testing it's a huge problem.

**Comment by alastai** [comment]
We are actively pursuing plans for No. 3, and No. 1 is on the way very soon, in upcoming 3.4 release. Your feedback has been consistent, and we are paying attention. Thanks very much indeed.

**Comment by majerr** [comment]
Really great to hear there is active development on this, thank you.

**Comment by be-rock** [comment]
3.4.7 is out now.  Can someone confirm if this feature now exists?  If so, can you refer us all to the appropriate Neo4j documentation?

And maybe most importantly is it or will it be included in the _Community Edition_?

Thanks.

**Comment by chrisvest** [comment]
@be-rock Causal Clustering, which Multi-clustering relies on, is only available in the Enterprise Edition:
https://neo4j.com/docs/operations-manual/current/clustering/multi-clustering/

**Comment by cyrilchapon** [comment]
That moment where you feel so good contributing with issues, ideas, software and product design on an open source project, and the feature is released in a commercial licensed edition.

**Comment by sebastienjust** [comment]
So it's been 6 years we ask for that in workshops, emails, phone and still nothing. This is really annoying. 
In our use case, we need to have one database per customer, for safety and legal reasons (GPRD). We need to deal with that kind of deployment now : deploying one instance per customer and making some weird things to allocate sets of ports per customer, trying to put as much as databases as we can on the same host. Imagine the nightmare for backups, maintenance, database upgrades, creating new customers, etc.
We've been waiting too long for that basic feature. Any database system can manage multiple "databases" in one host. This is basic feature. 

But, the biggest problem is that every year we hear that it's said to be a priority and still nothing happens. 
If some help is requested to make it happen, ask for help. There is a community (and developers) ready to help including us.
Please be clear on that question, give a date and do it (or ask for help), or say that this will never happen. 
We need the feature as well as a clear position on that.

**Comment by NanisTe** [comment]
> So it's been 6 years we ask for that in workshops, emails, phone and still nothing. This is really annoying.
> In our use case, we need to have one database per customer, for safety and legal reasons (GPRD). We need to deal with that kind of deployment now : deploying one instance per customer and making some weird things to allocate sets of ports per customer, trying to put as much as databases as we can on the same host. Imagine the nightmare for backups, maintenance, database upgrades, creating new customers, etc.
> We've been waiting too long for that basic feature. Any database system can manage multiple "databases" in one host. This is basic feature.
> 
> But, the biggest problem is that every year we hear that it's said to be a priority and still nothing happens.
> If some help is requested to make it happen, ask for help. There is a community (and developers) ready to help including us.
> Please be clear on that question, give a date and do it (or ask for help), or say that this will never happen.
> We need the feature as well as a clear position on that.

I definitely agree with your comment @sebastienjust .

**Comment by cyrilchapon** [comment]
@sebastienjust, they released it under commercial license on enterprise edition, which basically proves the work is already done, choices are already made and nothing is gonna happen in this issue.

That joky project would deserve anyone to fork the whole stuff and implement it faster and better than them, à la io.js

**Comment by cleishm** [comment]
@cyrilchapon I don't believe "Multi-Clustering", which is the feature in the enterprise version, allows one to "manage multiple 'databases' in one host", as @sebastienjust (and this PR) is requesting.

**Comment by cyrilchapon** [comment]
Oh Well. Ok then I agree with his PoV

**Comment by flavianmissi** [comment]
parachuting in here but have we considered proposing this feature on [the ONgDB fork](https://github.com/GraphFoundation/ongdb) instead?
not sure what are their plans regarding features which are absent from the original code base, but might be worth the try anyway. this is such a basic feature.

**Comment by farlofayle** [comment]
I'm making recommendations for a customer and the fact that Neo4j is still missing this feature after 6 years is pretty surprising and somewhat disappointing. I wonder if it's a business/revenue decision that is blocking this as opposed to a technical one? This is such a critical feature for multi-tenant installations where you want to keep the graphs completely isolated

**Comment by stuartsimpson** [comment]
@cleishm - First off i would like to say I love working with Neo4j.  From my 20+ years as a Data Architect and Applications designer perspective, it is one of the more exciting data repositories out there.  With that said, this request has more activity on it than any other feature request and it has been on the list for over 6 years.  Why has there been no progress on this feature?  I keep running into situations where I need to have multiple instances of Neo4j running on a server.  Creating multiple copies of the source code, as many have pointed out, is painful and not practical in large configurations where a requirement for separation of concerns, as multi tenant or regulatory separations of data is required.  I know I am not qualified to contribute code base on this endeavor but I have worked with and managed many database in development environments through out my career.  This feature would go a long way towards expanding how Neo4j could be use in an enterprise deployment.  I love using the product in a personal or local install. However, this missing feature makes it hard to use it in advanced enterprise deployments.  This is my two cents.

**Comment by DeltaBravo** [comment]
This is the point at which conspiracy theories begin to develop because the reality of the situation is just too difficult to comprehend or accept. 

An otherwise seemingly professional database with no multi-tenancy, no (official) PHP support, mediocre documentation (it's really close to being good...but isn't), etc. It seems to me that Neo4j is content to cater to large enterprises and is not at all concerned about typical developers or common use cases (such as the Web...). 

This product could be useful as a 'regular' database not only as big-data analysis tool.

**Comment by jmsuhy** [comment]
Multiple databases will be in ONgDB 4.   You will be able to switch dbs, etc.

**Comment by martinfurmanski** [comment]
With the release of 4.0 which includes both multi-database and fabric support I think it is safe to call this issue finally resolved. Note that these are enterprise features. Please see https://neo4j.com/blog/neo4j-graph-database-4-0-ga-release/ for an in-depth discussion.

**Comment by kayrus** [comment]
> Note that these are enterprise features

time to switch to orientdb https://orientdb.com/orientdb-vs-neo4j/

**Comment by DeltaBravo** [comment]
Yeah, Neo4j seems to have abandoned FOSS--just early days PR to get the business going. They are chasing 'big data' and big money. It's a shame as graph databases are such a good fit for Web development today.
I invested four years into Neo4j and built a business and a product on top of it. : (
I am currently looking into TerminusDB.
