### ISSUE TITLE
afterRollback not always called when TX tolls back

### ISSUE THREAD

**Issue by bachmanm** [neo4j/neo4j#2660]
When a transaction rolls back due to constraint violations, afterRollback() on TransactionEventHandler is called, as illustrated by this passing test:

```
@Test
public void afterRollbackShouldBeCalledOnHandlers() {
    GraphDatabaseService database = new TestGraphDatabaseFactory().newImpermanentDatabase();

    try (Transaction tx = database.beginTx()) {
        Node node1 = database.createNode();
        Node node2 = database.createNode();
        node1.createRelationshipTo(node2, DynamicRelationshipType.withName("TEST"));
        tx.success();
    }

    final AtomicBoolean called = new AtomicBoolean(false);

    database.registerTransactionEventHandler(new TransactionEventHandler.Adapter<Void>() {
        @Override
        public void afterRollback(TransactionData data, Void state) {
            called.set(true);
        }
    });

    try {
        try (Transaction tx = database.beginTx()) {
            database.getNodeById(0).delete();
            tx.success();
        }

        fail("This tx should not succeed");
    } catch (RuntimeException e) {
        //ok
    }

    assertTrue("Handler wasn't called!", called.get());
}
```

However, when the client code throws a RuntimeException in the middle of a transaction or in beforeCommit(), afterRollback() isn't called, although the transaction is rolled back. Illustrated by the following failing test:

```
@Test
public void afterRollbackShouldBeCalledOnHandlers2() {
    GraphDatabaseService database = new TestGraphDatabaseFactory().newImpermanentDatabase();

    final AtomicBoolean called = new AtomicBoolean(false);

    database.registerTransactionEventHandler(new TransactionEventHandler.Adapter<Void>() {
        @Override
        public Void beforeCommit(TransactionData data) throws Exception {
            throw new RuntimeException();
        }

        @Override
        public void afterRollback(TransactionData data, Void state) {
            called.set(true);
        }
    });

    try {
        try (Transaction tx = database.beginTx()) {
            database.createNode();
            tx.success();
        }

        fail("This tx should not succeed");
    } catch (RuntimeException e) {
        //ok
    }

    assertTrue("Handler wasn't called!", called.get());
}
```

Neo4j 2.1.2

**Comment by tinwelint** [comment]
The javadoc of `TransactionEventHandler` states that:

`Any {@link TransactionData} being passed in to this method is guaranteed to first have been called with {@link #beforeCommit(TransactionData)}.`

This sort of implies that a failed `beforeCommit` cannot produce a value to pass into this method. The javadoc isn't clear on this matter though. I can still see a value in having `afterRollback` called in this case though, because as you say: the transaction is actually rolled back.

What would be a good idea here, to pass in `null` state? Also there's a TODO in the source saying that it may be useful passing in the exception cause to `afterRollback`, if any (which in this case there would be).

**Comment by bachmanm** [comment]
I'd say passing a `null` state would be sensible.
