### ISSUE TITLE
node_auto_index 500 error on query after initial install

### ISSUE THREAD

**Issue by cicomputing** [neo4j/neo4j#295]
For full discussion see:  https://groups.google.com/forum/?hl=en&fromgroups=#!topic/neo4j/07itKJmRsbI

We have a script that does a fresh install of neo4j for development. After we do this, our web app makes an initial query for nodes that match a certain attribute. This always fails with a 500 error until we manually create an index called "node_auto_index"

Here is a slightly modified version of the query from our logs (forgive any punctuation mistakes, the query does work when there is an index):

```
START nodes=node:node_auto_index('email_indexed:email1@example.net OR other.email_indexed:email1@example.net OR other2.email_indexed:email1@example.net')
RETURN nodes
```

The response body:

```
   body:
    { message: 'Index `node_auto_index` does not exist',
      exception: 'MissingIndexException',
      stacktrace:
       [ 'org.neo4j.cypher.internal.executionplan.builders.IndexQueryBuilder.checkNodeIndex(IndexQueryBuilder.scala:53)',
         'org.neo4j.cypher.internal.executionplan.builders.IndexQueryBuilder.createStartPipe(IndexQueryBuilder.scala:80)',
         'org.neo4j.cypher.internal.executionplan.builders.IndexQueryBuilder.apply(IndexQueryBuilder.scala:37)',
         'org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.prepareExecutionPlan(ExecutionPlanImpl.scala:46)',
         'org.neo4j.cypher.internal.executionplan.ExecutionPlanImpl.<init>(ExecutionPlanImpl.scala:32)',
         'org.neo4j.cypher.ExecutionEngine$$anonfun$prepare$1.apply(ExecutionEngine.scala:61)',
         'org.neo4j.cypher.ExecutionEngine$$anonfun$prepare$1.apply(ExecutionEngine.scala:61)',
         'org.neo4j.cypher.internal.LRUCache.getOrElseUpdate(LRUCache.scala:31)',
         'org.neo4j.cypher.ExecutionEngine.prepare(ExecutionEngine.scala:61)',
         'org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:55)',
         'org.neo4j.cypher.ExecutionEngine.execute(ExecutionEngine.scala:58)',
         'org.neo4j.cypher.javacompat.ExecutionEngine.execute(ExecutionEngine.java:86)',
         'org.neo4j.server.rest.web.CypherService.cypher(CypherService.java:79)',
         'java.lang.reflect.Method.invoke(Method.java:597)' ] } }
```

From Michael Hunger:

I think the issue is from a change in the neo4j internals that don't cause indexes to be created by default (without anything stored in them) before the first getIndex() is called, and as cypher checks upfront if the index is there ....

I think for the auto-indexes that they should be created at db-startup even if there is nothing in there.

I hit the same issue with the console.

A workaround is to add an indexed property to (for instance the root node, and remove it again).

start n=node(0)  
set n.name='foo' 
delete n.name 
return n

**Comment by craigtaverner** [comment]
Tested on 2.3.11 and 3.2.3

In 2.3 added lines to conf/neo4j.properties:

```
node_auto_indexing=true
node_keys_indexable=name,email
```

Then ran commands:

```
START nodes=node:node_auto_index('email:email1@example.net') RETURN nodes
```
Got a 201 error with message `Index 'node_auto_index' does not exist`, which seems the correct response.

```
CREATE ({email:'email1@example.net'})
```

Succeeded. And then repeating the above `START` query also succeeded and returned one node.

In 3.2.3 edited the conf/neo4j.conf file and added:

```
dbms.auto_index.nodes.enabled=true                     
dbms.auto_index.nodes.keys=name,email
```

Then ran the same sequence of commands above, the `START`, `CREATE`, `START` sequence, and got identical behaviour with the error `Index 'node_auto_index' does not exist` on the first query, but success on the last.

This matches the expected behaviour of the node auto index, which is to only create the index on demand. Michael Hungers advice above then still applies. This behaviour will not be changed, especially since the auto index has been deprecated since 2.0, which was in 2014.
