### ISSUE TITLE
FEATURE REQUEST: display final cypher query for parameterized queries as debug output

### ISSUE THREAD

**Issue by henry74** [neo4j/neo4j#3232]
It would be very helpful to be able to copy/paste the final parameterized cypher query into the Neo4j browser or cli to test whether queries are correct.  Currently, parameters and the query are passed separately and there is no simple way to get the final cypher query.

Initially my workflow would involve writing a non-parameterized query, then when it was validated to be working switch it into a parameterized query for performance improvements.

Because the query and parameters are passed into Neo4j and combined within the Cypher engine, it wouldn't make a lot of sense to put it into the interface (e.g. neography gem) as that would just involve a bunch of text substitution to get the final query and it would be redundant with what the Cypher engine is already doing.

Thoughts?

**Comment by clintmod** [comment]
Would really love to see this feature added.

**Comment by oskarhane** [comment]
On the roadmap of neo4j-browser we do have an auto-detecting param's UI that will resolve / fulfill this feature request.
However, we have extracted neo4j-browser's codebase from neo4j's since this issue was posted and we must have missed to transfer this to the new repo.
Since we have this tracked already and this is the wrong repo now, I'm going to close this.
Feel free to open it in https://github.com/neo4j/neo4j-browser if you want @henry74, but this feature will come.
