### ISSUE TITLE
shortestPath ignores specified properties

### ISSUE THREAD

**Issue by shesek** [neo4j/neo4j#3388]
It appears like `shortestPath` and `allShortestPaths` ignores properties specified for filtering relationships, as in `shortestPath(src-[:KNOWS {foo:'bar'}]->dest)`.

Can be reproduced here: http://console.neo4j.org/r/329cf3

I currently have to resort to finding all paths normally, then sort by their length to find the shortest ones, which is significantly slower.

**Comment by sherfert** [comment]
We do not support this and give the error message `shortestPath(...) contains properties MapExpression(List((PropertyKeyName(a),StringLiteral(b)))). This is currently not supported.`

**Comment by craigtaverner** [comment]
I should clarify further. The syntax as described in the original report is indeed not supported, but since 3.0 we have supported predices in shortestPath. Instead of writing `shortestPath(src-[:KNOWS {foo:'bar'}]->dest)` you should write:

```
p=shortestPath((src)-[:KNOWS*]->(dst))
WHERE ALL(r in relationships(p) WHERE r.foo = 'bar')
```

So, while relationship type predicates are supported inline in the shortestPath expression, any other predicates, like property value, need to be in a separate WHERE clause with `ALL()` or `NONE()` functions. These functions will be unwrapped, and the inner predicate, eg. `r.foo = 'bar'` injected into the shortestPath algorithm. Note that if you do not use ALL or NONE, but use any predicate that requires testing complete paths, like ANY, then this does not work, and the predicate is applied after the shortestPath is run. See the docs for more details.

https://neo4j.com/docs/developer-manual/current/cypher/execution-plans/shortestpath-planning/
