### ISSUE TITLE
ConsistencyCheckTool outputs progress to stderr instead of stdout

### ISSUE THREAD

**Issue by bradnussbaum** [neo4j/neo4j#3466]
Why does the ConsistencyCheckTool output to stderr?

org.neo4j.consistency.ConsistencyCheckTool.java (49)

ConsistencyCheckTool tool = new ConsistencyCheckTool( new ConsistencyCheckService(), System.err );

I would like to submit a pull request to update this to stdout but wanted to get some feedback here first.

Is there a reason for this being stderr by default?

For reference, the BackupTool uses stdout by default:
org.neo4j.backup.BackupTool (87)
BackupTool tool = new BackupTool( new BackupService( new DefaultFileSystemAbstraction() ), System.out );

**Comment by MikeBenza** [comment]
I'd go so far as to say the consistency check tool has output swapped.  Normal program output showing progress is outputted on stderr.  When there's an error it's outputted on stdout.

Also, the consistency checker tool should exit non-zero if there’s a consistency problem.  It’d be much easier to check the exit code than to see if there’s an error than analyzing stdout (or stderr).

**Comment by jakewins** [comment]
@thobe I think I agree with the above. I assume is uses stderr with the thought being that it is outputting an error report - but the purpose of the tool is to output that report, I'd expect stuff on stderr to be errors in the tool itself. WDYT?

**Comment by thobe** [comment]
The way I designed it way-back-when was to output _progress indication_ on `stderr` and to output the _result_ (the found inconsistencies) on `stdout`, this made it easy to pipe the report to something else in the shell, while still getting seeing the progress report, and seemed consistent with other tools such as `curl` did.

I don't know if that is still how it works.

The writing to `stdout` might not be as useful as it once was either, since we now always write a report file as well. It might be better to only write to the report file, and only have the progress report and summary printed to `stdout` or `stderr`.

I don't quite understand what is being suggested here. But I think writing the found inconsistencies to `stderr` would be wrong. 

I definitely agree that the tool should exit non-zero if any inconsistencies were found.

**Comment by jotomo** [comment]
Here's a stab at communicating found inconsistencies via exit code: https://gist.github.com/jotomo/5003e4932339eb09fe7efbba88319ed0
If this is still relevant and somebody is willing to address the PR I'll open one for it.

**Comment by jakewins** [comment]
@benbc I think @jotomo's diff above seems like a nice improvement, but have no idea of the plans for this stuff anymore - WDYT, will you take a PR for that?

**Comment by klaren** [comment]
`ConsistencyCheckTool` is deprecated in favor of `neo4j-admin check-consistency` which exits with non-zero on inconsistencies. Writing progress to `stderr` can be avoided by checking `System.console()` before outputting the progress bar, it will return `null` if either `stdin` or `stdout` is redirected with a pipe.  I've created a PR that will be here momentarily. Thanks for the feedback!

**Comment by kenahoo** [comment]
FWIW, and I know this is an old thread, but I think the way @thobe designed it in the first place is correct.  The output of the tool is shown on `stdout` and status/alerts to the person running it are shown on `stderr`.  It just so happens that the purpose of this tool is to find "inconsistencies", i.e. "errors", but that doesn't mean its output should be on `stderr`.

**Comment by MikeBenza** [comment]
The purpose of the tool is to check the consistency of the data store.
Errors should go to stderr.
