### ISSUE TITLE
`MATCH` / `OPTIONAL MATCH` queries are much slower when `WHERE` is specified after `OPTIONAL MATCH`

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4j/neo4j#3827]
Maybe this isn't a priority, but here's my query:

    MATCH (neo_ded1031412:`DED`)<-[rel0:`IN`]-(townland_street:`TownlandStreet`)<-[rel1:`IN`]-(node3:`House`)<-[rel2:`LIVES_IN`]-(resident:`Resident`)
    OPTIONAL MATCH resident-[i:identified_as]-(:Resident)
    WHERE ID(neo_ded1031412)= 1031412
    RETURN townland_street, count(i), count(resident) LIMIT 10

It's a bit funky because it's coming out of the Neo4j.rb QueryProxy API (I actually even still cleaned it up a little bit to make it easier for you to read).

The point is that this query times out (I have a 60 second timeout on my server), but if I move the `WHERE` before the `OPTIONAL MATCH` it takes 421 ms.  I can kind of understand why this might not be easy for the cypher parser to detect, but it could save somebody confusion.  Also, as I said this comes out of the Neo4j.rb API, so it's not something that can be fixed without fixing the internals, and even then it would probably be tricky to appropriately split up that `WHERE` clause

**Comment by cleishm** [comment]
Hi @cheerfulstoic,

Please be aware that the `WHERE` always relates to the immediately preceding `MATCH` _or `OPTIONAL MATCH`. So, in your example, it's applying to the `OPTIONAL MATCH` only and not to the first `MATCH`.

Due to the way you're query is written, the result in either case will be the same. However it will match all possible examples of the pattern _without using the `WHERE`_, and then filter them back down again when applying the `WHERE` during the `OPTIONAL MATCH`. We'll look at improving the optimizer in future to detect this kind of thing, and automatically apply it earlier. For now, always use the `WHERE` along with the `MATCH` that you want it to apply to.

Cheers,
Chris

**Comment by Davidmylove** [comment]
Sure wil
