### ISSUE TITLE
Space between CSV header values causes second value to return NULL

### ISSUE THREAD

**Issue by sheldonkreger** [neo4j/neo4j#3871]
Using Neo4J community 2.1.6.

Assume a CSV with a space after the first header value's comma:
`user1, user2`
`1, 2`

The following query returns NULL for u2:

    LOAD CSV WITH HEADERS FROM "file:///x/edges1.csv" AS csvLine
    MATCH (u1:User)
    WHERE u1.id = toInt(csvLine.user1)
    RETURN u1.id, toInt(csvLine.user2);

`toInt(csvLine.user2)` returns NULL.

Removing the space in the CSV file returns the value expected. You do not have to remove the spaces from between the values themselves, just in the header.

**Comment by jexp** [comment]
I think you either have to clean up your CSV, or use `toInt(trim(csvLine.user2))`.

Can you try `return csvLIne.user2` ?

Good question about toInt ignoring whitespace.

**Comment by jakewins** [comment]
I'm not sure we should clean up lines automatically this way, even if it is in the header. Instead, I suggest the fix is to either clean the header line up, or to refer to the exact header string using backticks: 

```
csvLine.` user2`
```

Closing this as a wontfix, but happy to have a discussion if there are compelling arguments for reopening.
