### ISSUE TITLE
Submitting multiple semi-colon separated Cypher statements through Neo4j Browser

### ISSUE THREAD

**Issue by kdekooter** [neo4j/neo4j#3908]
See http://stackoverflow.com/questions/20420042/submitting-multiple-semi-colon-separated-cypher-statements-through-neo4j-browser for details.

**Comment by cleishm** [comment]
Hi Kees,

This isn't a bug, but rather the expected behaviour (currently).

The Neo4j Browser runs each command entered as a single query, and displays the results of that query. It does not support multiple queries (or the implied multiple sets of results!). However, it's certainly something we'll be thinking about how to provide for in future.

Note that it is possible to use neo4j shell to run multiple queries, as you're trying to do. The results of each individual command will be written to stdout. Examples are in the documentation: http://neo4j.com/docs/stable/shell-sample-session.html

Cheers,
Chris

**Comment by kdekooter** [comment]
Thanks Chris, consider this a feature request then ;-).
