### ISSUE TITLE
Network not created correctly when first node is created separately

### ISSUE THREAD

**Issue by krystofa** [neo4j/neo4j#4043]
I opened a question on Stack overflow here: http://stackoverflow.com/questions/28496913/finding-the-root-of-a-dag-in-neo4j

In this the respondent sent me a simple DAG to demonstrate a query:

create (a:Node {name:'A'})
create (b:Node {name:'B'})
create (c:Node {name:'C'})
create (d:Node {name:'D'})
create (e:Node {name:'E'})
create (f:Node {name:'F'})
create (g:Node {name:'G'})
create (h:Node {name:'H'})
create a-[:POINTS]->b
create a-[:POINTS]->c
create c-[:POINTS]->d
create c-[:POINTS]->e
create c-[:POINTS]->f
create f-[:POINTS]->g
create f-[:POINTS]->h

However when testing this I found that if I pasted the first line into the console separately and then pasted all the other lines in one go I ended up with a broken graph (see the screen shot).  This did not happen when I pasted all the items into the console in one go:

![broken dag](https://cloud.githubusercontent.com/assets/7046482/6284577/482a4d9e-b8e9-11e4-9fe7-79c4090d0766.PNG)

When querying this to find the root node using:

match (r:Node)-->() 
where not ( ()-->r ) 
return r

Nothing was returned.

I'm happy to provide sample database files for both the working version and the broken version but cannot see an easy way of uploading them here.

Neo4j version: neo4j-community-2.2.0-M03
OS: Centos 7
Browser Chrome 40.0.2214.111 (64-bit)
Java version: 1.7.0_75

**Comment by apcj** [comment]
Hi Christopher,

Remember that identifiers (a, b, c, etc. in your query) are just arbitrary names that you can assign and use within a single query. So if you use `a` in one query, and then use `a` again in another query, it won't refer to the same thing.

If you execute this one line query on its own, you will create a node labelled `Node` with property `name` = 'A':

```
create (a:Node {name:'A'})
```

The query is binding the new node the identifier `a` but you are not doing anything with that identifier, you might as well have written:

```
create (:Node {name:'A'})
```

If you execute another query and also use an identifier `a`, Neo4j won't have anything bound to `a`. For example:

```
create a-[:POINTS]->b
create a-[:POINTS]->c
```

Since you are in a `CREATE` statement, Neo4j assumes that you want to create a new node, so it will create a one for you and bind it to `a`. This query doesn't specify a label or any properties for this new node, so the node is created without either.

This unlabelled and property-less node is the node that shows up grey in the visualisation.

You can adapt your root-finding query to find this unlabelled node if you just remove the label restriction:

```
match (r)-->() 
where not ( ()-->r ) 
return r
```

As a side note, if you really want to split up your query into two parts, you'll need to find the node you created in the first query using `CREATE` or `MERGE` before you try to attach relationships to it.

**Comment by krystofa** [comment]
Ahh yes!  That makes perfect sense.  Thanks
