### ISSUE TITLE
Not sure if bug: No help text or log on browser UI on 2.2

### ISSUE THREAD

**Issue by whatSocks** [neo4j/neo4j#4187]
Old versions had logo and help text:
![46_open_the_browser_chrome](https://cloud.githubusercontent.com/assets/2731744/6612386/de329e64-c851-11e4-8e05-a2d3625907d2.png)

2.2 has no logo or help text:
![screenshot 2015-03-12 00 50 27](https://cloud.githubusercontent.com/assets/2731744/6612388/f1848054-c851-11e4-86ba-74493a1e1c3d.png)

**Comment by apcj** [comment]
Hi there, I think this might a stale browser cache problem - where you previously looked at an old version of Neo4j in your browser. We've addressed this if the previous version was 2.2.0-RC1 or later, but you might have to do one more force refresh, since your previous version is going to be older than 2.2.0-RC1. Can you give that a go? Cmd-shift-R or similar.

**Comment by whatSocks** [comment]
I'm using chrome incognito mode with a hard refresh just in case - no help text visible.

**Comment by akollegger** [comment]
Hi @whatSocks 

Thanks for noticing these changes. The watermark and clever-quote in the background were intentionally dropped. The help text in the editor bar, "Use <shift-return> to...", is being reconsidered. We're working through design approaches for hints+tips as a general facility, rather than co-opting the placeholder text. 

In the previous versions, did you find that approach reasonable, and the content helpful?

Cheers,
Andreas

**Comment by whatSocks** [comment]
@akollegger,
I remember the help text being helpful in the transition from writing "START blah blah" to the current syntax. Unlike the tutorial things in the query results or "helpful hints" popups in other applications, all I have to do to make it go away is start using the application, so it's hard for the help text to be annoying or intrusive.

I like the watermark, but keeping it / removing it is more of a UI decision than a UX decision.

**Comment by akollegger** [comment]
That's really helpful to hear. Thanks! 

We are keen to provide useful, appropriate, and timely hints and assistance that is sensitive to what a user is currently doing and aware of their previous experience. For now, we'll leave the Browser as is while we work on that. 

Thanks,
Andreas
