### ISSUE TITLE
Please provide support for language collation rules when using ORDER BY

### ISSUE THREAD

**Issue by vince-bickers** [neo4j/neo4j#4211]
The ORDER BY clause does not appear to honour the JVM parameters for user.language and user.country, if they are set in neo4j-wrapper.properties. In other words

given neo4j-wrapper.conf
````
wrapper.java.additional=-Duser.country=SK
wrapper.java.additional=-Duser.language=sk
````

and the following CYPHER
````
create (p:Person {name:"Adam"})
create (p:Person {name:"Ábel"})
create (p:Person {name:"Boris"})
match (p:Person) return p order by p.name
````
then "Boris" should be returned last. Instead "Ábel" is returned last.

**Comment by cleishm** [comment]
Hi @vince-bickers,

Having the ability to control collation of values in Cypher is certainly something we've discussed in the past, and is on our roadmap. Unfortunately I can't give a timeframe on that, as our priorities are often in flux and there's a lot of thinking to be done on this topic.

Most likely, however, we will implement collation in the database itself (and exposed via the Cypher language), rather than using preferences set in the JVM on which Neo4j runs. That will give us more flexibility to define when and where different collation rules apply, as well as providing a more consistent experience vis-a-vis other databases.

Thanks for raising this though, and it's great to know that people are interested in this topic. And thanks for being a great part of our community!

Cheers,
Chris

PS. I'm closing this issue, but don't worry: it's definitely on our backlog and plans.

**Comment by tdzienniak** [comment]
Hey,

any new info on ETA for this feature?

**Comment by SimplyComple0x78** [comment]
Hey @cleishm,
is this topic still on your roadmap for like 6 years?
In my case all uppercase-letters are sorted before the lowercase ones and the Umlauts are at the very end. That can't be an open issue since 2015, right? Have I missed some update or option?

**Comment by fadesibert** [comment]
Same here - even for things like simple case insensitivity (let along latin-1 collations or utf-8) - would be good to get a view on what the plan is with this...

**Comment by cleishm** [comment]
> Hey @cleishm,
> 
> is this topic still on your roadmap for like 6 years?
> 

I haven't worked with Neo4j for about 6 years or more, so you may like to reach out to them directly.
