### ISSUE TITLE
Neo4j 2.2 - Web interface shows blank results panel in Firefox on Ubuntu

### ISSUE THREAD

**Issue by bunkat** [neo4j/neo4j#4287]
I'm using FireFox 30.0 on Ubuntu 14.04 and I no longer see any results from my queries.  In the console I see a lot of 'no element found' log entries.  The same query in Chromium on the same machine works as expected.

![image](https://cloud.githubusercontent.com/assets/665885/6836030/03975e10-d2fc-11e4-9602-86d58dd6d87f.png)

**Comment by cleishm** [comment]
Hi @bunkat,

This is likely a cache issue in your browser, rather than a bug with Neo4j. Please try doing a shift-reload of the page, or clear the cache as described here: https://support.mozilla.org/en-US/kb/how-clear-firefox-cache#w_clear-the-cache

If that doesn't work, then please feel free to provide more details.

Cheers,
Chris
