### ISSUE TITLE
URI as CSS class doesn't work

### ISSUE THREAD

**Issue by boferri** [neo4j/neo4j#4413]
In our project we write RDF into neo4j. We utilise RDF types as labels in neo4j. All RDF types are URIs. Since neo4j 2.2.0 the graph rendering in the web interface changed a bit, i.e., now you are fully utilising the labels as CSS classes, but, e.g.,

```
node.http://d-nb.info/standards/elementset/gnd#Gods
```

doesn't work, i.e., now I cannot manipulate the displaying node caption anymore, since I do not produce valid CSS with URIs as CSS classes. The URI grammar (syntax; https://tools.ietf.org/html/rfc3986) is not valid to the CSS class grammar (syntax; http://dev.w3.org/csswg/css2/syndata.html).

**Comment by apcj** [comment]
Hi @zazi, thanks for the very helpful feedback.

What if we changed the syntax so that you can escape labels using back-ticks, like you can in Cypher? e.g.

```
node.`http://d-nb.info/standards/elementset/gnd#Gods`
```

Would that work for your use-case?

That still doesn't conform to the [CSS spec](http://dev.w3.org/csswg/css2/syndata.html#characters). However, after having GraSS out in the wild for a while now, it looks like it would be best to move the syntax further from CSS and closer to Cypher. In particular, we bent the meaning of CSS selectors to work with a property graph model, but it's not going to be pretty if we want more advanced selector expressions. For example if we want to have a rule that targets a specific property value of even a graph pattern, it's going to be easier to use Cypher syntax to express that than trying to borrow more features from CSS. Does that make sense?

**Comment by boferri** [comment]
Hi @apcj This makes absolutely sense and should fulfil my intention to display the node identifiers (which are URIs as well). So +1 for implementing this GraSS enhancement.

**Comment by oskarhane** [comment]
This issue was moved to neo4j/neo4j-browser#137
