### ISSUE TITLE
add dynamic registration of callbacks to Ronja?

### ISSUE THREAD

**Issue by RichMorin** [neo4j/neo4j#4553]
Ronja, Neo4j's new [Cypher Query Optimizer](http://neo4j.com/blog/introducing-new-cypher-query-optimizer), divides query handling into several steps:
1. Convert the input query string into an abstract syntax tree (AST)
2. Optimize and normalize the AST
3. Create a query graph from the normalized AST
4. Create a logical plan from X
5. Rewrite the logical plan
6. Create an execution plan from the logical plan
7. Execute the query using the execution plan

I would like to be able to register callback functions for execution (before step 1, between steps,
and after step 6). These functions could be used to retrieve intermediate data structures, provide macro processing, and much more.

Ideally, callback registration would be dynamic, allowing any JVM-based program (e.g., a Clojure or Elixir REPL) to insert its code into the pipeline.

**Comment by cleishm** [comment]
Hey Rich,

That's an interesting idea. I'm not sure what you'd plan to use it for, but it does sound intriguing.

It's a lot of work to do that, and there would need to be some serious thinking about what these callbacks would be able to do, what the interfaces look like, how they'd be registered, etc. Given it's not something we require ourselves at this time, I don't think we could possibly commit to doing any of that work right now. We'd certainly be happy for the community to think on it though! Let us know if you spend any time coming up with a plan and, preferably, a spiked implementation?

Cheers,
Chris

**Comment by RichMorin** [comment]
> That's an interesting idea. I'm not sure what you'd plan to use it for, but it does sound intriguing.

See the Neo4j mailing list thread [Getting an AST for a Cypher query](https://groups.google.com/forum/#!topic/neo4j/VB-JQnR00Qk) for some use cases.
Other use cases would certainly emerge, if a plugin facility existed.

> It's a lot of work to do that, and there would need to be some serious thinking about what these callbacks would be able to do, what the interfaces look like, how they'd be registered, etc.

I'm not a Java programmer, let alone a Neo4j internals wizard. However, I'd be happy to work with others to help specify and/or document the interfaces.

-r

**Comment by cleishm** [comment]
Hey Rich,

Glad to see you've raised it on the mailing list already - that's where I was going to point you next anyway! That's honestly the best place for these kind of feature requests, as this issue tracker is primarily used for issues rather than feature requests and especially not big picture things like this. This idea will definitely need some community support to rally around it, so you can find some people to help with the design and spiking.

Cheers,
Chris

**Comment by chrisvest** [comment]
The openCypher project is building tools for building parsers and ASTs. These APIs are not something I think makes sense in a database product, but it might make sense in the space of the openCypher project, so I suggest you open an issue (or otherwise start a discussion) over there: https://github.com/opencypher/openCypher/
