### ISSUE TITLE
SyntaxException when escaping dot in v2.1.5

### ISSUE THREAD

**Issue by brian-gates** [neo4j/neo4j#4617]
```
neo4j-sh (?)$ match (n) where n.name =~ ".*\..*" return n limit 1;
SyntaxException: Invalid input '.': expected '\', ''', '"', 'b', 'f', 'n', 'r', 't' or Unicode (line 1, column 31)
"match (n) where n.name =~ ".*\..*" return n limit 1"
                               ^
```

Seems this should work as per http://neo4j.com/docs/2.1.8/query-where.html#where-escaping-in-regular-expressions

**Comment by collin** [comment]
Here is the output for the same query in 2.2.1

```
Invalid input '.': expected '\', ''', '"', 'b', 'f', 'n', 'r', 't', UTF16 or UTF32 (line 1, column 31 (offset: 30))
"match (n) where n.name =~ ".*\..*" return n limit 1;"
                               ^
```

**Comment by brian-gates** [comment]
A workaround we found is

```
neo4j-sh (?)$ match (n) where n.name =~ ".*[.].*" return n limit 1;
```

**Comment by jexp** [comment]
It seems the example you cited @brian-gates is for escaping special characters like backspaces, newlines, tabs etc.

For your example either two or four slashes would be imho needed. But I tested it with one, two, three and four slashes and couldn't get it to work.

**Ok, actually two slashes work but only for dots. Not for normal letters :)**

`match (n) where n.name =~ ".*\\..*" return n limit 1;`

Could that be some double escaping due to json strings or such?

Did you try to use parameters instead for the regexp?

**Comment by brian-gates** [comment]
I can't use params since this is via the console.  Perhaps I should have specified that from the start.

**Comment by sherfert** [comment]
This is a documentation error. In Cypher, a backslash must be escaped ( https://neo4j.com/docs/developer-manual/current/cypher/syntax/expressions/ ) because it is a special character. If you want your regular expression to match against a slash, the correct version is "\\/" and whatever comes before and after that. Everything else is not supposed to work. We will fix the documentation example!
