### ISSUE TITLE
Query no longer working in 2.2+ (used to work in 2.1.x)

### ISSUE THREAD

**Issue by cskardon** [neo4j/neo4j#4665]
So - I have a query that has been working in 2.1.x (in fact, I'm pretty sure it was working back in 1.6, maybe even before) but has stopped working in 2.2+ databases.

Create Data:

`Create (n:Test {val:"n"})-[:CONNECTION]->(o:Test {val:"o"})-[:CONNECTION]->(p:Test {val:"p"})`

which creates:

`(n)-CONNECTION->(o)-CONNECTION->(p)`

Match Data:

```
MATCH (n:Test)-[:CONNECTION*1..2]-(p:Test),(p)-[:CONNECTION*1..2]-(o:Test)
Where(n.val = 'n') and(o.val = 'o') and(p.val = 'p')
return n,o,p
```

In 2.1.x this returns data, in 2.2+ (I've tested in 2.3 as well - same issue) - the query returns no data. 

On StackOverflow there is a workaround query I can use but it's going to involve a huge rewrite of my codebase to use a 2.2+ database (which being lazy - I'm loath to do). 

It looks to me like the cypher compiler has changed how it parses the `Match` statement - Has this been changed purposely? and is/was my initial query invalid?

The stack overflow for this is: http://stackoverflow.com/questions/30350265/ability-to-jump-back-and-forth-in-a-query-no-longer-in-2-2

**Comment by cleishm** [comment]
Hi @cskardon,

Thanks for raising this. We'll make sure to look into it asap.

Cheers,
Chris

**Comment by cleishm** [comment]
Hi @cskardon,

After a quick look into this, I think the behavior in Neo4j 2.2 (and later) is correct.

The first part of your `MATCH` pattern is `(n:Test)-[:CONNECTION*1..2]-(p:Test)` (with the relevant conditions `n.val='n'` and `p.val='p'`), which means that the only way to match the pattern is to use both of the relationships that were created.

Because a `MATCH` pattern in Cypher will never match the same relationship twice, the second part of the pattern, `(p)-[:CONNECTION*1..2]-(o:Test)` can never match as there are no relationships left it can use.

As noted on stackoverflow, the way to achieve what you're trying to do, is to use two separate `MATCH` clauses, as separate matches can, naturally, cover the same relationships. So this would be quite valid:

```
MATCH (n:Test)-[:CONNECTION*1..2]-(p:Test)
WHERE (n.val = 'n') and (p.val = 'p')
MATCH (p)-[:CONNECTION*1..2]-(o:Test)
WHERE o.val = 'o'
return n,o,p
```

Cheers,
Chris
- Matching relationships once only is important for avoiding loops and other unexpected cases.

**Comment by cskardon** [comment]
Do I presume that it working in all versions prior to 2.2 was a bug in itself? And it shouldn't have worked?

**Comment by cleishm** [comment]
@cskardon: right - it should never have worked, but it seems there was a bug in those variable length paths that meant it did allow relationship re-use in some cases. That was inadvertently fixed in 2.2, due to a bunch of other changes.

We could possibly go back and patch it in the older releases, but it's probably not worthwhile.

**Comment by cleishm** [comment]
PS. You can see this yourself - the following query also returns no rows in 2.1.8, yet it should be equivalent to your query in what it matches:

```
MATCH (n:Test)-[:CONNECTION]-()-[:CONNECTION]-(p:Test), (p)-[:CONNECTION]-(o:Test)
WHERE (n.val = 'n') and (o.val = 'o') and (p.val = 'p')
RETURN n,o,p
```

**Comment by cskardon** [comment]
I feel a re-write coming up then :)
