### ISSUE TITLE
How to recover from EntityNotFound Error

### ISSUE THREAD

**Issue by mboedigh** [neo4j/neo4j#4751]
I am experimenting with a large database with SNP annotations (among other things) and was going to change my desgin.  I wanted to delete all data from the :SNP nodes. The database had 100s of millions of nodes and I was forced to delete small segments at a time in a somewhat painful attempt to keep the database from crashing. I had queries like this:
match (s:SNP)-[r]-() where s.name< 'rs01' delete r, s
match (s:SNP)-[r]-() where s.name< 'rs02' delete r, s
etc. 
But sometimes the database would crash anyway. Cypher front end thought the database was unplugged. (funny for awhile). And the Neo4j Community app was non-responsive. 
Eventually I got into a state where
match (s:SNP)-[r]-() where s.name > 'rs55' delete r, s
Node with id 15244864
Neo.ClientError.Statement.EntityNotFound

OR
match (s:SNP)-[r]-() where s.name< 'rs55' delete r, s
Node with id 15244864
Neo.ClientError.Statement.EntityNotFound

OR even 
match (s:SNP) return count(s)
Node with id 15244864
Neo.ClientError.Statement.EntityNotFound

I'm note sure what is wrong but if anyone has suggestions to either delete all SNPs or otherwise recover please let me know. There is still a lot of data in the database that I'd like to keep

**Comment by jakewins** [comment]
Which version of Neo4j are you running?

**Comment by mboedigh** [comment]
Thanks for getting back to me! I was running 2.2. I can probably look up the exact version if you are interested in pursuing this further.
From my end, I have since rebuilt the database from scratch on Neo4j 2.3 M2. I am still curious if there is a general approach to recovering.

Mike

**Comment by jakewins** [comment]
The entity not found exceptions you are seeing _might_ be caused by a corrupted index. Depending on which patch version of 2.2 you were running. If you want, you can force the database to rebuild its indexes. Make sure you have a backup of the store before doing this, and that the database is shut down cleanly (eg you started it and stopped it in a normal fashion).

With that done, go to the database folder, and delete the 'schema' folder. Start the database back up, and it will rebuild its indexes. This may take a long time if you had a big database.

**Comment by klaren** [comment]
As previously stated this is most likely due to a corrupt index. An online alternative would be to drop the index and create it anew. This does not work for the error reported in this issue which relates to the schema index that can't be dropped, but the drop-create approach work for other indexes you create through cypher.
