### ISSUE TITLE
Windows Desktop UI: remember the last database location

### ISSUE THREAD

**Issue by sheymann** [neo4j/neo4j#4806]
Hello folks,

I use the Windows Desktop every day and I usually work on the same database. I've got frustrated because the database location is reset each time I close the UI or reboot the computer, and got to browse the same location again and again...

Can we remember the database location?

**Comment by ADTC** [comment]
I browsed the code and found that this should affect all platforms, including Mac OS X and Linux. The culprit is here:

https://github.com/neo4j/neo4j/blob/3.1/packaging/neo4j-desktop/src/main/java/org/neo4j/desktop/config/portable/PortableInstallation.java#L36

If there's a way remember the last used database location and restore it in this method, only falling back to the hardcoded default when nothing was remembered, that will be great!

Even better if the text box was a drop down and I could choose one of the many recently used databases.

**Comment by ADTC** [comment]
@sheymann as a workaround, you could create a junction to your database at the default database location:

```
cd "C:\Users\ <your user name> \Documents\Neo4j\"
rename default.graphdb old.default.graphdb
mklink /J default.graphdb "C:\path\to\your\database.graphdb"
```

This way, you can just start up the default database, and it will be your favorite database.

If you have several databases that you switch between, you could build a batch script to present you with a list of your favorite databases, and create the junction to the selected one, before you run Neo4j. Or, have several one-click scripts - one for each database.

**Comment by oskarhane** [comment]
As this refers to our old Neo4j Desktop and the new version shouldn't have this issue, I'm closing this.
