### ISSUE TITLE
CORS headers prohibit AJAX requests

### ISSUE THREAD

**Issue by lericson** [neo4j/neo4j#4835]
It turns out that if an `XmlHttpRequest` specifies an authorization header, the `Access-Control-Allow-Origin` _must not_ be the wildcard, `*`, which Neo4j sets unconditionally in `community/server/src/main/java/org/neo4j/server/rest/web/AllowAjaxFilter.java`.

One solution might be to allow specifying this header's value, with a default value of `*` to preserve current behaviors for existing installations.

**Comment by jakewins** [comment]
Hey, @lericson, thanks for reporting this.

There's been some discussion around this. The current CORS behavior has survived from earlier times when we used a separate port for the web GUI, it is technically not part of our official feature set.

Looking over it now, it feels somewhat uncomfortable to expand it to continue working in the authenticated case, since this significantly increases the databases attack surface and the complexity of security code paths.

Could you expand on what you are using the CORS headers for?

**Comment by lericson** [comment]
Upon further reflection I will have decided not to use this feature I told him, and instead use a proxy in some kind of a web app.
- Ludvig (phone)

**Comment by lericson** [comment]
Sorry for the somewhat incoherent response, seems speech-to-text isn't quite there yet. :smile: I was trying to say that I don't use it in anymore. The idea was to query Neo4j from the client side of a web app, but it turned out to be a bad idea for many reasons -- not the least of which is security concerns.

**Comment by lericson** [comment]
That said, perhaps it would be better to remove the CORS headers altogether.

**Comment by jakewins** [comment]
@lericson +1, I'm adding an internal backlog task to deprecate+remove
