### ISSUE TITLE
Is Order By still not recomended?

### ISSUE THREAD

**Issue by vinerz** [neo4j/neo4j#5078]
Hello everyone! First of all, thank you for this great tool.

I am still diving into the world of neo4j and I am planning to do a quite complex user feed with interests and friends. To do so I need a pagination system that I will do with order by date property of nodes and a limit 20. 

I was reading some articles from a year or earlier that this is not recommended due to performance issues and I saw a post regarding linked lists.

This may not be the best solution because I will have lots of writes of small activities (liked, commented, watched) and these users can have a couple thousand followers. Linked lists would burn the server having to rewrite every single follower feed on every single popular user activity.

However, in those articles some developers of neo4j mentioned that you guys were working on a better indexing system for order by. Is it already implemented?

Thanks again for this wonderful piece of binary data,
Vinicius

**Comment by jexp** [comment]
Hi,

with Neo4j 2.3 there will be index supported range scans so that you can do: 

`WHERE post.date > time() - 5*day`

and it will use an index. If you are starting with your feature now, grab the next milestone release (prob. 2.3.RC1) and give it a try.

Otherwise performance for reading long linked lists also got way better with 2.2 and the COST planner.
