### ISSUE TITLE
PowerShell scripts should return non-zero when commands fail

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#5246]
Currently, a command can fail and the only way to know is to parse stdout/ stderr. It would be much easier for users to first query the exit status for whether the command worked, and then subsequently try parsing stderr for a detailed explanation.

**Comment by lassewesth** [comment]
@glennsarti Ping.

**Comment by glennsarti** [comment]
@lassewesth

This is an interesting issue.  It's not specifically a problem with the powershell code for Neo4j, but how powershell deals with errors in general.  As powershell has both terminating and non-terminating issues it just pumps them all out to STDERR and lets the caller deal with it.  I see a few options how to deal with this.

1 Do nothing
Let the caller decide whether there was an error or not based on STDERR and STDOUT

2 Provide guidance
The code on the neo4j repo is not modified but instead guidance is provided by Neo4j on how to call these functions and return the appropriate exit code e.g.

```
try { <some code>; Exit 0 } catch { Exit 1 }
```

3 Change all functions that could expose errors to additionaly modify the exit code
This gets tricky as any function could be used and what actually defines an error e.g. is a missing configuration parameter an error or expected behaviour?

4 Provide a generic wrapper function that takes in a script block and pushes a 1 or 0 exit code based on its success e.g.

```
Invoke-Neo4jWithExitCode  { Start-Neo4jServer -Console -Wait }
```

What do you think?

**Comment by lassewesth** [comment]
@glennsarti I do not like 1), but that _is_ the workaround I have in place currently for our automated testing.

I'd prefer 3). As in, do enough input checking to catch user errors early and fail fast with non-zero exit codes. Then call whatever business method is needed, and return whatever exit code that gave, black box stylee. Sort of like I'd expect things to work on Linux.

But then, I was hoping you could tell me what the canonical Powershell way of doing things is.

**Comment by glennsarti** [comment]
@lassewesth Errors within Powershell are an array of Error Objects.  They are far more expressive and complex than an integer.  But I think what we're talking about is what the ExitCode of the powershell.exe process is, as opposed to how errors are tracked internally in the scripts i.e. The error trapping in Java is expressive but java.exe still returns integer process exit codes.

In that case, it's up to the PS script to set the exit code.  As far as PS.exe is concerned it succesfully loaded, parsed and executed the supplied script i.e. Exit Code 0 (Success).  Whether the script itself had errors is irrelevant.

Personally I prefer 4.  This means the PS functions retain all of the expressive nature of PS Error Objects and users can still choose whether errors are terminal or not.  

Even a basic wrapper that just returns the number of errors encountered during the script execution would yield the behaviour you're after (`Exit $error.count()`)

**Comment by craigtaverner** [comment]
This issue seems to have gone stale, and appears more like a discussion than a real bug report. I will close it for now, but if this is causing actual problems, please feel free to re-open it with a description of the problem (ie. failing test).

**Comment by mdealer** [comment]
Why reinvent the wheel? We're already under .Net, so why can't exceptions be used or something for all the details. The top process should return a simple integer because that's like 99% of how the subsystem error handling works. Things like this are just another reason to never use PS.
