### ISSUE TITLE
PowerShell scripts should not list optional parameters as required

### ISSUE THREAD

**Issue by lassewesth** [neo4j/neo4j#5247]
Several scripts list e.g. `UseHost` and `UsePort` as required when they really are not.

**Comment by lassewesth** [comment]
@glennsarti Ping.

**Comment by lassewesth** [comment]
Also `FromPipeline` in Start-Neo4jImport

**Comment by glennsarti** [comment]
@lassewesth This is by design. The examples you've given are used to determine which parameter set is used. Parameter sets are like method signatures in Java, i.e. A function has different ways of being called  depending on which parameters are used. 

Use get-help on the function you're interested in and you'll notice multiple ways to invoke it.

If you have any further examples can you list them here, otherwise we can close this issue.

**Comment by lassewesth** [comment]
@glennsarti I guess documenting them as required is fine since there is no elegant way to express conditionally-required. Closing.
