### ISSUE TITLE
neo4j csv import "hangs" in version v2.2.4

### ISSUE THREAD

**Issue by zukomgwili** [neo4j/neo4j#5261]
We have created an application that imports csv files into neo4j using neo4jshell scripts. We have been experiencing problems with importing in the latest version (v2.2.4) of neo4j. 
Neo4j “hangs” after importing  approximately 130 csv files. In previous versions of neo4j (v2.1.5) we did not experience this problem, only in the latest version has this issue surfaced. Our neo4j server has 128GB of memory (the entire graph is in memory).
We have been able to resolve the issue by changing the PERIODIC COMMIT size in our shell scripts to 10000 (from the default 1000). This is a cause of concern for us because in our production environment (neo4j 2.1.5), the default value 1000 has worked since we went live without any issues.

We have created a pack with data for reproducing the problem. Please can we have a private email address to send relevant instructions(for reproducing the issue) and links to the data.

**Comment by jexp** [comment]
if you have a customer account with neo technology, please raise the ticket there.

Otherwise you can send the scripts and data examples to me (michael at neo4j.com)

Please make sure to add the server configuration directory (if you run shell against neo4j-server) and detailed explanations on how you run the workload (concurrent/non-concurrent) and a sample db that you import into (with the right constraints etc. set)

**Comment by zukomgwili** [comment]
Thank you Michael for your response. I have sent you an email.

**Comment by jakewins** [comment]
@jexp @zukomgwili was this resolved?

**Comment by jjaderberg** [comment]
No response for over a year, closing.
