### ISSUE TITLE
Neo4j RPM repo defaults to non-working version...

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#5388]
Why does the repo default to an unsupported, pre-release version? This should not happen when installing according to the directions at http://yum.neo4j.org/. When you follow those directions, you should get the latest, greatest stable version...

**Comment by wcooley** [comment]
I was wondering that myself; fortunately we're at an older version so I've got the yum "versionlock" plugin enabled and did not get it automatically.

**Comment by jakewins** [comment]
Hey Alan!

This is part of how we work - the branch where the bulk of development takes place is the main github branch. If you want stable releases, have a look at http://neo4j.com or check out the tag for the stable release you want.

Cheers
Jake

**Comment by jakewins** [comment]
Wait, sorry, I completely misunderstood your complaint - I thought you were talking about this github repo.

I'm not sure why the Yum repo is defaulting to unstable releases. @benbc do you know anything about that?

/j

**Comment by Alan-R** [comment]
This is a broken way to work. Period.

Your DEFAULT, DESCRIBED way of installing on Red Hat should NOT be to 
install broken cruft. In fact, even a development release shouldn't be 
as broken as this one is (like it won't even start for anyone).

I'm hoping you don't know how updates through repositories work - 
because otherwise what you said makes no sense... The purpose of a repo 
is to provide continual updates of working products. Not to provide 
clearly brain-dead broken versions of development products. If you want 
a development repo, you should have a separate repo for that.

But the way you're doing it means that a customer would either have to
     (a) freeze the version - and avoid picking up (and be completely 
unaware of) critical bug fixes for your code
     (b) avoid using a repo for updates altogether.

People use repos to keep their software up to date. This is what 
professionals do. They do not redownload from a web page. Downloading 
from a web page is for trying software, not maintaining it. That's not 
how the world works.

Developers and people doing trials do that, but not professional system 
administrators...

**Comment by jakewins** [comment]
@Alan-R please see my second comment, we are talking about two different things.

**Comment by benbc** [comment]
Hi @Alan-R. You are right that our Yum repo is broken. I'm sorry.

The confusion of pre-release and release versions in the repo is a problem that we are aware of but have not yet had the time to address.

In our (admittedly feeble) defence, the page that you point to also says:

> This is experimental and not considered safe for production. You have been warned.

As you are aware there is workaround: freezing the version that you're using. If you are keen to use our Yum repo then I recommend doing that for now.

-Ben

**Comment by Alan-R** [comment]
Thanks to both of you.  This is the main way RPM-based customers _should_ be installing it. This is how the world works.

Please change the text on that page to state that it is known to have this (unfortunate) property along with the suggested workaround and a pointer to the github issue which has now been reopened.

My apologies to @jakewins for the tone of my reply. I didn't realize that we had a misunderstanding about the issue I was raising.

Thanks for reopening the issue.

**Comment by benbc** [comment]
@Alan-R We have now updated the note on http://yum.neo4j.org/ to warn about the pre-release versions in the repo.

**Comment by wcooley** [comment]
> @Alan-R We have now updated the note on http://yum.neo4j.org/ to warn about the pre-release versions in the repo.

@benbc Seriously, this is @neo4j's response? Not having a reliable, supported Yum repository does not exactly make for a good user experience for enterprise deployments.

**Comment by Alan-R** [comment]
@wcooley I certainly agree with you. There is another item which they probably should have referred to here: https://github.com/neo4j/neo4j/issues/5484. To quote @benbc from that item:

`Thanks for raising these points, @Alan-R and @vargok. We're hoping to rework the RPM soon and we'll make sure to cover the things you've raised.`

I understand that to mean that they're going to rework their RPM creation mechanism to fix the "issues we'd raised". I certainly hope that he means this issue too. But I'll point back to this one and make sure that they know that's what I expect - and what @wcooley expects too ;-). I'm sure that @vargok feels the same way.

**Comment by benbc** [comment]
@wcooley The RPM package available at http://yum.neo4j.org/ is documented there as experimental and not suitable for production use. I understand that even given that limitation it is surprising to find pre-release and released packages in the same repo, so I've interpreted this issue as a request to alleviate that surprise.

I understand that some people will want to use the experimental package in production because it's easier than creating their own or converting our official Debian packages with `alien`. It's the kind of thing I've done in the past with other packages. But if that's what you choose to do, I think it's reasonable to expect to negotiate some bumps in the road.

We want to publish an official RPM package but we have not had the resources to do so yet. I hope you appreciate that moving a package from experimental to official status is not simply a question of fixing a couple of problems and rearranging the repo. We need to integrate the package into our automated build, test and release processes; we need to ensure that we have then capacity to respond to future issues and to maintain the repo.

In the meantime it's extremely helpful to get reports of problems that you and others run into when using the package -- thank you. They'll help us make sure that the official package is as good as possible. But please be patient and cut us a bit of slack, given that you've chosen to use an experimental package.
