### ISSUE TITLE
please drop your scala dependency or offer cross builds

### ISSUE THREAD

**Issue by fommil** [neo4j/neo4j#5802]
in e.g. the cypher parser. It means that the parser (and I hope nothing more) is effectively unusable by Scala developers as it ties you to one binary format.

**Comment by fommil** [comment]
related to https://github.com/neo4j/neo4j/pull/4551

**Comment by fommil** [comment]
in the scala world, all artefacts are published under a `name_scalaVersion` naming convention. Until you do this, uptake by scala applications is going to be extremely limited.

I'm just lost a full day fighting JVM, Lucene and Scala versions to try and do a PoC and now I have to call it quits on neo4j.

A very appropriate trial for Halloween.

**Comment by cleishm** [comment]
Hi @fommil,

You might find it better to use Neo4j as a database server, which is the predominant approach to deployment. This allows you to isolate it as an entirely separate concern from your own application, and frees you from any concern with dependency conflict. Neo4j, as a fully fledged database system, has many dependencies.

That said _there is cross builds of the cypher compiler using Scala 2.10 and Scala 2.11_. These are available for Neo4j 2.2 and you can find these on maven central: https://maven-repository.com/artifact/org.neo4j/neo4j-cypher-compiler-2.2/ and https://maven-repository.com/artifact/org.neo4j/neo4j-cypher-compiler-2.2_2.11/ respectively.

Additionally, if you're looking to do a PoC with neo4j, then by all means send me an email so we can discuss how we at Neo4j can help you put something compelling together.

Cheers,
Chris

**Comment by fommil** [comment]
@cleishm Part of the spec is that we need it to be embedded. We also need a version which works on Java 6 as this is for scala tooling (the official JDK still being 1.6 for both scala 2.10 and 2.11).

PoC is https://github.com/ensime/ensime-server/issues/1133

I was able to compile your 1.9.9 code without changes just by copying and pasting it, it is good to hear that you have a similar thing for recent releases. I am tempted to create and publish my own GPL artefacts for 1.9.9 and then swap out for a different implementation later.

By using scala you are also limiting our ability to upgrade to scala 2.12 (if I'd known this in advance I may not have started down this alley). So we'd need to get you into the scala community build. No doubt you have some form of commercial arrangement with TypeSafe so you may wish to proceed with that through those channels just so that there are no surprises for you when new versions of scala are released. I won't get involved in that, it's much easier for me just to use an alternative graph database https://github.com/scala/community-builds

**Comment by fommil** [comment]
is there no chance you could just publish some normalised artefacts for scala 2.10 and 2.11?

**Comment by boggle** [comment]
Hello, our current policy is that a public ("GA") version of Neo4j supports a recent, stable, major version of scala. Minor versions of that GA release continuously upgrade that major version of scala to the latest minor version. Neo4j GA releases always allow you to use the latest Cypher compiler from the previous GA release as well as from the previews point GA release (i.e. 2.x supports 1.9) using binary dependencies. Hence these depended on Cypher compilers are also available in the same scala version used by the GA release as separate maven artifacts. You should not depend on these artifacts in any other way, they are brought in as dependencies by the mainline product.

Going forward, a future GA release will at some point upgrade to scala 2.12 once it has become stable (that may not happen immediately when scala 2.12.0 is release but soon after), i.e. we will provide an upgrade path.

The Cypher execution engine is larger than just the cypher compiler modules and part of the core database product. Hence the scala version used is tied to the current version of Neo4j. Making the scala version a configurable aspect of a GA release is difficult: We need to double our testing effort and ensure everything works with both versions, we have to write the code such that it compiles on both versions (not a biggie but still), and it will complicate our project setup and build infrastructure to the point where we would have to publish different packages of Neo4j that depend on different versions of scala, at least to maven central. We currently do not want to take this overhead since it has only been requested rarely, i.e. if you'd like to use Neo4j in embedded mode, please target the scala version of the Neo4j GA version you are using. 

Given that Neo4j 2.3 GA supports scala 2.11.7 (which is stable) and scala 2.12 only has pushed milestone releases so far and we will upgrade to it in a reasonable time frame, in which way is this limiting you?

**Comment by boggle** [comment]
Please also note that Neo4j 2.3 targets Java 7, not Java 6 (which is end of life).

**Comment by boggle** [comment]
Regarding accessing the Cypher parser, we are working towards releasing it separately as part of the http://www.opencypher.org effort.

**Comment by fommil** [comment]
I'm writing tooling, so we need to support cross-scala versions. Your answer simply means we can't use neo4j :cry: Also, we need to be able to support 2.12 far ahead of it being considered "stable" (many 2.12 developers use our tooling).

We also need to support Java 6, which is end of life only in name. The vast majority of corporates are still using it in production.

It is good to hear that you are separating out cypher. If this is all your Scala code, it might mean that we can come back to neo4j at a future date.

**Comment by boggle** [comment]
That is sad to hear. Couldn't you target different versions of Neo4j depending on the setup used? From how I look at it, the combination of java and scala used just determines the latest version of Neo4j available to you. Shouldn't a cross version build be able to take that into account?

**Comment by fommil** [comment]
no, because you broke Java 6 compatibility in the version that supports Scala 2.11, and I don't know what your release cycle is for Scala 2.12. We need to wait for you to separate out your internal, non-standard, Scala components and offer cross builds of your modules.

**Comment by fommil** [comment]
Also, you have additional Lucene version requirements, which we also use, so that's another branch of code that we'd have to maintain.

**Comment by chrisvest** [comment]
It is possible to use the `neo4j-kernel` without the Cypher and Lucene dependencies, but then you don't get the Cypher or indexing features.

**Comment by fommil** [comment]
is it possible to use neo4j-kernel 1.9.9 with gremlin v2 or does gremlin use cypher and lucene under the hood?

**Comment by fommil** [comment]
(actually, if we're using 1.9.9 we're ok with your version of Lucene... in fact I'd like to integrate them)

**Comment by boggle** [comment]
No Neo4j version since 2.0 has officially supported Java 6. The underlying issue sounds like you'd like to be able to upgrade arbitrary dependencies of third party products, I'm surprised that works for other larger components at all and perhaps is best addressed by using OSGI and/or project jigsaw. Perhaps we can improve the situation as part of opencypher and/or when transitioning to Java 9.

**Comment by fommil** [comment]
You're overcomplicating it. The fundamental problem here is your internal dependency on a fixed version of scala, which is not at all evident by pulling in your top level framework. If all your scala code is moved into opencypher and it is cross-built, then the problem goes away.

As a workaround for v1.9.9 (i.e. Java 6), publishing a separate _2.11 jar for the cypher module would do it.

**Comment by chrisvest** [comment]
The gremlin-plugin in 1.9.9 depends on Lucene and Cypher because it depends on the server. I'm not familiar with how it's otherwise integrated into the product.

**Comment by boggle** [comment]
Any code that depends on the cypher compiler modules depends on internal, non-public, unsupported Neo4j APIs. What do you really need? If this is about getting access to the parser, opencypher really is the right answer and will deliver that.

**Comment by fommil** [comment]
To use neo4j 1.9.9 (i.e. for our Java 6 requirement) I need you to publish separate `cypher_2.10` and `cypher_2.11` jars, not one that pretends to be a Java library called `cypher`.

To use neo4j 2.x on Java 7+, we need the same for your more recent releases. If you choose to do that via `opencypher`, then that works well.

**Comment by jakewins** [comment]
@fommil could you expand on what it is that drives a hard requirement to embed the database engine itself in the JVM - is it that you yourselves are running as an embedded library and don't want to force your users to manage a separate database?

If so, would you be open to an option where Neo4j has a thin client driver in the JVM which then runs Neo4j itself in a separate process "under the hood"?

**Comment by fommil** [comment]
I am pretty sure I gave all this detail above and in the feature ticket that I linked to. Absolutely must be embedded, anything else would dramatically complicate our release pipeline. I'm using OrientDB instead, but I would really love to have the option of using neo4j in the future.

**Comment by jakewins** [comment]
I did read through that, but I must be missing something; the requirements seem to me to revolve around:
- Must not conflict with application dependencies
- Must be addable to application through simple single dependency and nothing more

Eg; I don't understand where the requirement of "must run in the same OS process" comes from. 

While we won't be able to accommodate your request to either drop all our external dependencies or to handle the combinatorial complexity of supporting all versions of those dependencies, we absolutely want a smooth integration into JVM libraries. Thus, there are two options:

Either our embedded dependency launches its Neo4j instance in a separate process, or it loads Neo4j into an isolated class loader. My preference is for the former option, as this also isolates heap access. 

The latter option is useful, assuming it works with Scala, because you should be able to do that on your own - simply bundle Neo4j jars as resources in your jars, and then load them into their own classloader at runtime.

**Comment by fommil** [comment]
@jakewins I'm not asking you to drop all your external dependencies. Just to use standard publishing conventions for your scala jars.

**Comment by jakewins** [comment]
I want to give some background to why we are pushing back here:

Today, we maintain five versions of Neo4j, three editions of each, across five operating systems and four JVMs. In total, we test 300 combinations. 

These combinations are tested by over 30,000 unit and component tests, four multi-hour fuzz test suites, three performance testing suites and three multi-week production scenario suites as well as being subject to extensive manual testing. 

Adding a single additional Scala version to support would add 300 additional combinations for us to test in that pipeline - that is simply cost prohibitive, we cannot officially support multiple versions of Scala unless there was a major financial aspect that could pay for the cost of it. 

Now - there may be a way in Scala around this somehow. However, while it is for you, this problem is not Scala specific for us. We get these same requests for Lucene and other dependencies.

We benefit massively from being able to use third-party dependencies, we will not stop doing that. We also cannot support multiple versions of each dependency, unless the exponential increase in testing complexity pays for itself, as it does for software like operating systems and JVMs.

**Alternatives**

Given this, there are three alternatives: 
- Someone could release an unsupported version of Neo4j with mixed Scala support
- JVM applications load Neo4j into its own classloader
- General applications run Neo4j in a separate process

All of these could be done in a way where they would appear the same to application developers: you add Neo4j as a dependency, instantiate it in your program and it "just works". The first option means no commercial support, which is a no-go for many. The second is nice, but JVM-specific. The third one is cross-language and gives Neo4j its own heap.

Would any of the options above solve your problem?

**Comment by fommil** [comment]
I'm not asking you to change your external dependencies, I'm just asking you to use an industry standard packaging convention for scala jars. If you were even able to rename the artefact of cypher to cypher_2.10 then that would assist greatly in use from scala because somebody else could publish the cypher_2.11/cypher_2.12 whatever jars.

In any case, I thought cypher was being split off as a separate project as discussed above. Which, in itself, would fix this.

**Comment by jakewins** [comment]
When you said "I need you to publish separate cypher_2.10 and cypher_2.11 jars" and "We need to wait for you to [..] offer cross builds of your modules.", I thought you were saying you wanted us to offer cross-built Cypher jars for Scala 2.10 and 2.11, that's my bad for misunderstanding.

OpenCypher is a language specification - Neo4j will still ship with an implementation of Cypher, for obvious reasons. 

If separating out the query engine is an acceptable solution to you, then just stop depending on Cypher. You can do this either by excluding the Cypher dependency, or by depending on Neo4j internal components directly - although of course that voids any warranty. Simply depend on the Neo4j kernel if you want the database without a query language: http://search.maven.org/#artifactdetails%7Corg.neo4j%7Cneo4j-kernel%7C2.3.1%7Cjar

If that is not an acceptable solution, then I recommend you look into OSGi or loading Neo4j through a separate class loader as outlined above.

Assuming this ticket is then entirely about the naming of our internal artifacts, I'll forward your feedback to the Cypher team, and we will take the embedded use case you raised here into consideration as we develop our new surface layer. Thanks so much for your time!

**Comment by fommil** [comment]
Yes that is all that is needed. It is extremely bizarre to publish scala jars without following cross build conventions. If unofficial builds for 2.11 (for the older release that I'm using) were to be made available under GPL only, then that would be great and covers you from a warranty POV.

Since you have closed this ticket, where should I watch the be informed of progress in this area?

**Comment by jakewins** [comment]
Github will send you a notification if the Cypher team decides to reopen this ticket and change the naming of our internal jars.

**Comment by fommil** [comment]
OK cool, glad the request is going where it needs to go.
