### ISSUE TITLE
All identifiers become unbound after UNWIND of [ ] or NULL

### ISSUE THREAD

**Issue by cybersam** [neo4j/neo4j#5851]
This bug is a special case of https://github.com/neo4j/neo4j/issues/4315, which has been marked fixed.

In this special case, if a query unwinds an empty collection or a `NULL` value, then all identifiers become unbound.

[Here is a console](http://console.neo4j.org/?id=fyt931) that show this bug when unwinding a `NULL`.

This is a serious bug. For instance, it would cause queries that UNWIND a collection obtained from an OPTIONAL MATCH to become unreliable -- as sometimes the collection may be `NULL`, and all identifiers would become unbound.

**Comment by ikwattro** [comment]
@cybersam  `UNWIND` expands a collection into a seq of rows.

NULL is neither a collection and an empty collection will just have as behavior to return nothing because the RETURN is bound to the expanded rows.

**Comment by cybersam** [comment]
The problem is, even if we try to return other identifiers, they are all gone.

**Comment by ikwattro** [comment]
Sorry you're right. You should have replied before I deleted my silly comment.

Thanks for the report btw.

**Comment by systay** [comment]
Hi @cybersam!

Not sure what you mean by "all identifiers become unbound.". What the console link shows is a query that returns no rows, which is the expected result when `UNWIND`ing a null/empty collection. What are you proposing should happen instead?

**Comment by cybersam** [comment]
I expect `fred` and `ethel` to retain their values.

**Comment by cybersam** [comment]
The accepted answer to [this SO question](http://stackoverflow.com/questions/33549833/how-to-get-all-nodes-in-a-disjointed-sub-graph-neo4j-py2neo/33559217#33559217) shows a somewhat real-world example of where this (alleged) bug presents a problem.

**Comment by henriknyman** [comment]
Hi @cybersam,
If the UNWIND produces no rows you do not get any identifiers. You can achieve what you want with OPTIONAL MATCH by making sure you get the start node in the collection, like this:

MATCH (n {name: "Neo"})
OPTIONAL MATCH p=(n)-[*]-(m)
WITH [n, NODES(p)] as nodes
UNWIND nodes as node
WITH node WHERE node IS NOT NULL
RETURN DISTINCT node

**Comment by MysterAitch** [comment]
I have arrived here after coming across this issue personally (Neo4j v3.0.7), therefore hope to be able to offer some insight into this issue. 

My observation is that where a MATCH followed by OPTIONAL MATCH, unwinding on a field which may have null values causes the OPTIONAL MATCH to act as a MATCH (i.e. stripping all paths which do not meet the optional match). 

In my use case, I am unwinding on a collection of dates which may be empty (a scenario analogous to a set of products and dates of sales). Unfortunately, the behaviour above means that, in the sales scenario, any products with nil sales yet are excluded from the search results.

What I would like to happen is that if UNWIND is passed a null value, it will will return null too (as opposed to stripping the row from the results).

Whether this is expected behaviour and/or whether I am misusing UNWIND is something I was hoping to find within search results, and will follow up if any additional detail is discovered.

Update: This [StackOverflow question](http://stackoverflow.com/questions/29840801/cypher-use-unwind-with-potentially-empty-collection) is precisely what I describe above, with [this answer](http://stackoverflow.com/a/32545006) being a functional workaround in my particular case.

**Comment by igorclark** [comment]
This just bit me pretty hard. If I pass in e.g. 

```
:params data => {
    one: [ { a: 1 }, { b: 2 } ],
    two: [  ],
    three: {
        four: [ 1, 2, 3 ],
        five: [ { six: 7, eight: 9 } ]
    }
}
```

and then try to do anything with `UNWIND $data.one`, it'll work fine right up 'til when I subsequently try to do something with `UNWIND $data.two`. At that point the rest of the entire query will fail because all the identifier and parameter bindings have been dropped, not because there was an `OPTIONAL MATCH` but because a particular nested component was an intentionally empty list.

Maybe people don't pass in that kind of data structure but it's super helpful for me. It lets me provide an API in my code where other devs can just pass me the appropriate structure, I can check it for validity, pass it in to a Cypher query and convert to the appropriate nodes & relationships. Which means, when dealing with a nested structure that maps to a quite different structure in the graph, the app developers don't have to deal with that at all, and I can reconstruct the same nested structure on the way back out, making it super transparent. The ability to pass in nested structures as parameters makes this really nice; the fact that everything will get forgotten after one of the elements is `[]` or `NULL` means I end up having to split it up into multiple queries, which in some cases is fine, but others much less so as I'd like to have everything happening in one transactional request.

So I'd like to second @MysterAitch's suggestion of `UNWIND` returning `NULL` instead of stripping the row or otherwise losing the bindings.

Cheers.

**Comment by InverseFalcon** [comment]
I don't believe the Cypher team considers the current behavior a bug, even though this is surely a common pitfall.

At the least we could consider an OPTIONAL UNWIND which leaves a null result and doesn't filter out rows, providing desired functionality without changing the behavior of the original UNWIND.
