### ISSUE TITLE
transaction  sleep all the time

### ISSUE THREAD

**Issue by xghrbc1001** [neo4j/neo4j#5955]
I found jstack sleeping there all the time.

```
"qtp1880519262-294" #294 prio=5 os_prio=0 tid=0x00007f746fb09800 nid=0x7795 sleeping[0x00007f71c5c99000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
    at java.lang.Thread.sleep(Native Method)
    at java.lang.Thread.sleep(Thread.java:340)
    at org.neo4j.kernel.impl.util.concurrent.LockWaitStrategies$3.apply(LockWaitStrategies.java:69)
```

LockWaitStrategies.java

```
Thread.sleep( 0, 500 );
```

but LockWaitStrategies.java was only sleep 500ns.

I found this loop in ForsetiClient.java

```
   // Apply the designated wait strategy
                waitStrategies[resourceType.typeId()].apply( tries++ );

```

what blocks my transaction? code like this in our plugins

```
try (Transaction beginTx = db.beginTx()) {
// do somthing,my throw exception
beginTx.success();
} catch(Exception ex){
}

```

whether we must call close() when exception thows? transaction is big

my neo4j about 5000 0000 nodes, also transaction is big in order to  update data by schedule.

**Comment by xghrbc1001** [comment]
I found this loop in ForsetiClient.java
```
   // Apply the designated wait strategy
                waitStrategies[resourceType.typeId()].apply( tries++ );

```
what blocks my transaction? code like this:
```
try (Transaction beginTx = db.beginTx()) {
// do somthing,my throw exception
beginTx.success();
}

```
whether we must call finish() if exception thows?

my neo4j about 5000 0000 nodes, also transaction is big in order to  update data by schedule.

**Comment by maxsumrall** [comment]
I'm sorry, your issue doesn't provide much detail about the situation. If you can better describe the problem or narrow the scope of issue, feel free to open a new one. Otherwise, your question might be a better fit for here: http://stackoverflow.com/questions/tagged/neo4j

Also, here is the standard java documentation about what happens in try with resources blocks. https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
