### ISSUE TITLE
Calling Transaction#terminate after close() causes the next Transaction to fail.

### ISSUE THREAD

**Issue by tkroman** [neo4j/neo4j#5996]
The problem is easy to reproduce:
- create a transaction
- close it
- wait till the next transaction with the same backing `KernelTransaction` is opened
- an exception is thrown saying that the transaction is already terminated.

I have a couple of deterministic tests that reproduce this issue using both the API and directly `KernelTransactionImplementation`: https://github.com/neo4j/neo4j/pull/5979/files#diff-bc0520c1d02de7734e4b39cfb4ee24b2R49

I had a PR (#5979) suggesting a fix, but @tinwelint argued that it might introduce some undesired side-effects. Moreover, the idea of KTI pooling might not be the best choice since it brings some complications to the codebase.

The PR contains more detailed problem description, which I'd like not to copy-paste here since it's already linked.

**Comment by lutovich** [comment]
Hello @tkroman,

Thanks for reporting this issue.
It should be fixed in 2.2 and 2.3 by this PR https://github.com/neo4j/neo4j/pull/6075 which makes pooling of `KernelTransactionImplementation`s safe.
And in 3.0 by this one https://github.com/neo4j/neo4j/pull/6058 which removes pooling of `KernelTransactionImplementation`s.

**Comment by tkroman** [comment]
Hi @lutovich . Nice to see a fast response to this. Thanks.
