### ISSUE TITLE
similarity computations For Recommendation

### ISSUE THREAD

**Issue by Hassankashi** [neo4j/neo4j#6073]
I am going to find a appropriate function in order to obtain accurate similarity between two persons according to their favourites. 

for instance persons are connected to tags and their desire to each tags will be kept on the edge of tag nodes. I want to recommend similar persons to each persons.

I have found two solutions: 
1. Cosine Similarity
   ![similarity](https://cloud.githubusercontent.com/assets/5254816/11719256/36b59ab6-9f5a-11e5-9210-ee310b27a0ee.jpg)
2. Pearson Correlation
   ![correlation](https://cloud.githubusercontent.com/assets/5254816/11726158/aa7de4bc-9f7d-11e5-8fa6-06b7cf0fa296.jpg)

When I was surfing on the net and your documentation I found:
http://neo4j.com/docs/stable/cypher-cookbook-similarity-calc.html#cookbook-calculate-similarities-by-complex-calculations

![neo4j](https://cloud.githubusercontent.com/assets/5254816/11726227/f9c950a6-9f7d-11e5-9c38-45bb9c7e44bc.jpg)

My question is what is your logic behind this formula?
What is difference between r and H?

Because at the first glance I think H1 or H2 are always equals one. Unless I should consider the rest of the graph.

Thank you in advanced for any helps.

**Comment by davidoliverSP2** [comment]
@mneedham Could you take a look at this question relating to Graph Algorithms?

**Comment by craigtaverner** [comment]
@Hassankashi This part of the Cypher documentation has been removed, and I see that this question was raised a long time ago, so I'm guessing it is no longer a priority. I will give a short answer and close the issue, but if you have followup questions or related ones, please feel free to re-open the issue or open new issues.

My view of why the equation uses both r1.times and H1, is because there are two ways of modelling the concept of 'number of times a user ate a particular food'. This can be modelled either as a property on the relationship which is incremented, so if r1.times = 5, it means the user ate the food 5 times. Likewise, it can be modelled by adding more relationships, so there could be 5 r1 relationships between a user and a particular food. The H1 and H2 parameters consider this, while the r1.times considers the other approach. I assume the author of this equation was combining the two approaches.
