### ISSUE TITLE
neo4j RPM repository has digital signature issues

### ISSUE THREAD

**Issue by Alan-R** [neo4j/neo4j#6143]
There is some issue with the repository which the "zypper" command (SuSE equivalent to yum) doesn't like about the repository. Apparently something either isn't signed, or isn't signed properly. The message looks like this:
`Warning: Ignoring failed signature verification for file 'repomd.xml' from repository 'neo4j'!
Double-check this is not caused by some malicious changes in the file!`

This is one of **many** issues with the RPM repository.

**Comment by spacecowboy** [comment]
Closing. I have verified that there is no signature issues on OpenSuse Leap 42.2. with the new RPM packages. Configured `yum.neo4j.org/stable` and the GPG key using Yast.

I should note that there is another bug which makes the package installation fail on Suse but that has been fixed in https://github.com/neo4j/neo4j/pull/8805 and will be appear as updates on the repo soon.
