### ISSUE TITLE
3.0.0 M04 - ResultCursor.size() throws NullPointerException when cursor is empty

### ISSUE THREAD

**Issue by hectorlf** [neo4j/neo4j#6497]
Neo4j Community 3.0.0 M04.

Calling size() on an empty ResultCursor throws a cryptic NullPointerException:

`Exception in thread "main" java.lang.NullPointerException
        at org.neo4j.driver.internal.InternalResultCursor.size(InternalResultCursor.java:234)
        at test.Neo4jTest.main(Neo4jTest.java:24)`

See the attached test case (run with "gradlew run"). Did not happen in M03.

[resultcursor-size-test.zip](https://github.com/neo4j/neo4j/files/142696/resultcursor-size-test.zip)

**Comment by jotomo** [comment]
@nigelsmall @boggle : Problem is with the java-driver, I think at https://github.com/neo4j/neo4j-java-driver/blob/1.0/driver/src/main/java/org/neo4j/driver/internal/InternalResultCursor.java#L234 it should read ```keys().size()``` (with parenthesis after _keys_). Since _keys()_ stopped simply returning _keys_ through a recent commit by @nigelsmall to _keys()_ (The streaming PR). _size()_ was added by @boggle when _keys()_ simply returned _keys_.
The naming (same name for a field and method) is IMHO a bit unfortunate (and inviting to such errors?). 
@boggle Don't confuse Scala & Java here: while in Scala fields and methods share the same namespace (so this wouldn't be legal) and parenthesis are frequently omitted on method calls, Java has separate namespaces for fields and methods, and methods strictly need parenthesis - though I'm sure you already know that :-)

**Comment by hectorlf** [comment]
Changes in the API for 3.0.0 RC1 made this issue irrelevant. I'm closing it. Thanks!!
