### ISSUE TITLE
Feature request: Native date/time type

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#6620]
Right now, I store dates and times as milliseconds-since-epoch, and convert back and forth to other in-memory formats with Joda-Time. But it would be convenient to have native support for a date/time type in neo4j, to save having to convert, stop possible mistakes when conversion is forgotten, enhance human readability, and so on.

From StackOverflow, it seems like this gets requested a lot, but I haven't yet found an existing issue for it. If there's an existing issue, of course, please just merge this with that one.

Some relevant StackOverflow threads:

http://stackoverflow.com/questions/29343767/howto-handle-dates-in-neo4j
http://stackoverflow.com/questions/9138857/in-neo4j-how-can-i-index-by-date-and-search-in-a-date-range
http://stackoverflow.com/questions/28088464/when-will-neo4j-support-dates-as-properties
http://stackoverflow.com/questions/21643896/neo4j-date-data-types
http://stackoverflow.com/questions/33120380/how-to-get-the-datetime-from-database-in-neo4j

**Comment by Mats-SX** [comment]
Hello @rationalism and thank you for contacting us!

Yes, we agree that it is unfortunate that we haven't yet gotten time to do proper temporal support in Neo4j. But it might encourage you to find that we have our eyes on it, and that there in fact is already a high-level specification for the Cypher types that will be supported, which you can find here: https://github.com/opencypher/openCypher/blob/master/cip/CIP2015-09-16-public-type-system-type-annotation.adoc

As to when this will become reality, we do not know, but it is reasonable to expect it to happen in the 3.x timeframe.

**Comment by astesin** [comment]
In case my vote matters. I think that neo4j rigorous approach to timekeeping (64-bit int millisecond timestamp) should stay forever. Why should a database care of whatever business logic of your timezone stays today? Or tomorrow?

**Comment by thobe** [comment]
@astesin our plan is to keep being as rigorous, while making time type safe and more user friendly.
In case you like reading long documents, our plans for how we think date and time handling should work is outlined in a [google document](https://docs.google.com/document/d/1UiFEGbGi4TviTlQDM-irFzfLJxERtSM7ElDYIiplUzw/edit?usp=sharing).

**Comment by kokoworld** [comment]
Any further on when this may be available?

**Comment by Mats-SX** [comment]
@kokoworld Not as of yet, no. It's in the plans, but not on the current list of priorities.

**Comment by blackjax99** [comment]
Any progress on putting this on the roadmap?

**Comment by Mats-SX** [comment]
@blackjax99 The latest news is that this is not likely going to be part of `3.2`.

**Comment by blackjax99** [comment]
I really don't understand why this is not a top priority there.  This is a blocker for organizations wanting to adopt you for serious work.  This feature literally forced us to go buy from OrientDB instead of Neo4J, which we would have preferred to do.  You lost tens of thousands of dollars just on us.

**Comment by manonthemat** [comment]
@blackjax99 
I personally don't understand how storing dates as a long or even a string is such a blocker, that you rather trow out a graph database for a graph/document-hybrid.

Please explain your use-case that this is such a big deal. In my experience, the Neo4j team has many good ears when explaining (not just demanding) a feature request and why it is important for them. If it's so important for you, maybe it's also important for other companies - they just don't know it yet. If that's the case, I'm sure the effort to get this feature in will pick up. Also, if you have some tens of thousands of dollars to spare, you could also move some of the resources to build this feature yourself. Or am I totally missing the point here?

Your comment 3.5 weeks ago didn't indicate that this is such a big deal. If it was, I'm sure you personally talked to someone at Neo Technologies. For anyone just reading that and your most recent comment a few hours ago, this behavior seems a little bit unprofessional and the mildest reaction you might get is a raised eyebrow - just like your avatar pictures.

**Comment by blackjax99** [comment]
I spoke to folks from Neo4J in person about 2-2.5 years ago and with account reps on the phone about 18 months ago.  In the first case I was told it was on the roadmap but not in the immediate term, and in the latter case they tried to convince me that it was a 'feature' not a design flaw.  I don't have tens of thousands of dollars to spare, I have them to spend on licensing the technologies I need to publish the applications my company charges our customers for, just as the Neo folks do for this application they have built their business around.

If you don't see why native date/time support in queries and in the functions provided by the platform are an issue I am not sure I can help you, it is intuitively obvious to anyone whose usecases involve a major component of modelling time.  Sure you can hack workarounds, but who wants to base their whole architecture on top of something that they know from the start they have to hack workarounds for?

Perhaps you have usecases where time is a minor thing and the hacks will be adequate in the few cases where you need to factor it in, for us it will be a constraint on practically all queries.

Why it is a problem for Neo to support a core feature that practically any other DB considers a core feature (because most users of databases also do) is a mystery.

Jon

**Comment by simoami** [comment]
👍  Not sure how this was missed as a core data type from the beginning. Can't wait to see it incorporated.

**Comment by Murilo-Perrone** [comment]
@blackjax99 and @simoami, from what I've seen, Neo4j drivers already map language specific types to Neo4j's primitive types. I'm happily using Date types from GORM in groovy/grails, which get automatically converted behind the scenes to Unix time (a long integer as the number of milliseconds since epoch - 1/1/1970). What is your programming language and what exactly are you missing? Is it about adding date manipulation function in Cypher ?

IMHO, dates and times are intrinsically just a set of culture-oriented conventions to represent time, not in strict units of physics, but in units of astronomy, reflecting our knowledge of earth and moon's orbits. For instance, some cultures convey to extend some years to 13 month. That explains the high complexity of  the google doc pointed by @thobe . Hence I don't think it is conceptually correct to hard-code a specific date convention into Neo4j or any other database management system.

I understand it would be time consuming to migrate into Neo4j a system using lots of date functions, such as the MONTH() function of SQL, but that's not a good solution anyway, as it is requires a mathematically inefficient calculation which must be done individually. Replicating this feature in Cypher would encourage the replication of the same poor architecture. Instead, the performance-effective choice would be to store the individual date/time parts that your business logic requires as your application uses them. If you need to query over the month, then you may store year, month and days separately, ignoring the time, for example.

So instead of sticking to date conventions, I think Neo4j's should just expose a pluggable interface for date mapping classes in Java (Neo4j's native language). Those would hold the logic to store a composite structure composed of multiple Neo4j primitive types representing the required date/time parts, and also map that structure to your programming language specific types, providing any missing features such as time-zones. As a bonus, each part of such structure would also be readable within cypher queries with the best performance and intuitive syntax, such as "MATCH (n) WHERE n.date.month = $m RETURN n".

Such pluggable solution allows the community to take care of developing the many different implementations for most common use cases, even dates from a Chinese calendar.

**Comment by jkaster** [comment]
For me, the main issue is support for tooling around date/time manipulation. For example, [Looker](https://looker.com) has very rich date/time querying and analysis capability. As a fan of Neo4j before I started working at Looker, I would like to attempt to support Neo4j with Looker. Without a standard date/time approach, date/time queries for whatever might be used as date/time format via Cypher are impractical.

**Comment by Lojjs** [comment]
Update from the Cypher Team:
We are aware that this is highly requested and useful feature. Right now we are in a planning phase for coming Cypher versions and this is one of our prioritized features. As of today I have no certain timing to give yo, but I will try to keep you updated.

Thanks for your patience!

**Comment by thobe** [comment]
For those who might be following this issue. This feature has been implemented in Neo4j 3.4 which is in the process of being released.
