### ISSUE TITLE
ACTUAL id-type parameter in import memory needs

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#6677]
Hi there!
I'm importing CSVs with neo4j-import

```
IMPORT DONE in 6s 201ms. Imported:
  622638 nodes
  427978 relationships
  1245276 properties
```

IDs are very sparse and big in number , eg `21457000101005334643`.
This breaks (``bad.log` file created) the import, so i imported same data in with id-type STRING, but query performance dramatically dropped.
So, i tryed `--id-type ACTUAL`, but this broke my r3.8xLarge instance memory (**244 GB**).

Uncompressed csv files are 29_MB_ total.
Imported (ad id-type INTEGER)  database is somewhere around 80_MB_.

What is happening? :-)

**Comment by cosimosimeoneTR** [comment]
Sorry, forgot:
2.3.1 - COMMUNITY

**Comment by chrisvest** [comment]
@cosimosimeoneTR Our store format in 2.3.1 does not support that many nodes or relationships, so `--id-type ACTUAL` cannot work for IDs that big. And even if it did, it would make our store files just as sparse as your IDs, which would be a very inefficient way of storing your graph. It sounds like `--id-type INTEGER` is the right option for your case.

Our records are not just a rearrangement of the CSV data. Records have points to each other to support traversal, so that's probably where the extra space usage is going.

**Comment by cosimosimeoneTR** [comment]
Hey there!
Thanks for reply!
But still, integer is not big enough with IDs like `21457000101005334643` ...

**Comment by chrisvest** [comment]
Right… `INTEGER` uses 64-bit longs for storing the IDs, but you need at least 65 bits for a number such as `21457000101005334643`. If you can't do anything about the magnitude of those numbers, then I guess you have to use strings.

**Comment by jexp** [comment]
@cosimosimeoneTR what kind of query performance did you see drop? 
It shouldn't matter a lot which id-type you use for queries. Except if you have no constraint on the id when trying to look it up.

**Comment by chrisvest** [comment]
Closing because it looks like the original question got answered.
