### ISSUE TITLE
Import relationship CSV refering to second label does not work

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#6910]
As from your example in
http://alpha.neohq.net/docs/server-manual/import-tool-examples.html#import-tool-id-handling
i would like to ba able to create a `roles7.csv` like this

```
:START_ID(Actor),role,:END_ID(Movie)
1,"Neo",1
2,"Morpheus",1
3,"Trinity",1
```

and a `roles7Seq.csv`like

```
:START_ID(Actor),role,:END_ID(Sequel)
1,"Neo",2
1,"Neo",3
2,"Morpheus",2
2,"Morpheus",3
3,"Trinity",2
3,"Trinity",3
```

without getting the 

```
There were bad entries which were skipped and logged into /mnt/databaseDisk/CosTEST/bad.log
```

error

**Comment by spacecowboy** [comment]
To clarify, do you mean that it doesn't work because you specify `Sequel` as the node type, instead of `Movie`?

**Comment by cosimosimeoneTR** [comment]
Exaclty :)

**Comment by maxsumrall** [comment]
The problem is a misunderstanding of what `END_ID(Sequel)` implies. In the movies7.csv file, if you imported it according to the manual, you used the header: `movieId:ID(Movie),title,year:int,:LABEL`. This creates an ID space (In this case, `Movie`) for nodes imported in that file. This ID space called `Movie` is unrelated to the nodes having a label `Movie`. 

In your import header for sequels, you are stating that you want to make relationships between nodes from the `Actor` ID space and nodes in the `Sequel` ID space. The problem is the nodes were imported using a different ID space. When this step is executed, it fails to find any nodes imported in the ID space `Sequel`. This is working as intended, and you should change `Sequel` to whatever ID space was used for the nodes.

For example, you could do something like:

```
movieId:ID(Foo),title,year:int,:LABEL
1,"The Matrix",1999,Movie
2,"The Matrix Reloaded",2003,Movie;Sequel
3,"The Matrix Revolutions",2003,Movie;Sequel
```

```
:START_ID(Actor),role,:END_ID(Foo)
1,"Neo",1
2,"Morpheus",1
3,"Trinity",1
```

```
:START_ID(Actor),role,:END_ID(Foo)
1,"Neo",2
1,"Neo",3
2,"Morpheus",2
2,"Morpheus",3
3,"Trinity",2
3,"Trinity",3
```

**Comment by cosimosimeoneTR** [comment]
Well... No... :-)
It's not a workaround or a technical trick i need.
I need to load data with correct labels, and refer to those data for what they mean at business logic level.
Foo might be the answer in IT point of view, is _not_ in terms of Business view.

I have to say, disappointing answer.

**Comment by maxsumrall** [comment]
This will load nodes with the labels Movie and Sequel, as specified in the first file. The `Foo` is only used internally during import to know what nodes you are referring to in the relationship import step. 

If you want separate nodes for Movies and Sequels, then can you give an example of how you would like the data to look after the import? The example I gave results in this: 
![untitled](https://cloud.githubusercontent.com/assets/628843/14605163/9da9dfe2-0577-11e6-979c-9a319d770409.jpg)

**Comment by spacecowboy** [comment]
It's neither a workaround, nor a technical trick.

Just clarifying, Foo has nothing to do with your business logic. The ID space is only meant as a way to avoid ID collisions in your csv files during import. It has nothing to do with the labels of your nodes.

In the manual, there are two ID spaces defined: `Actor` and `Movie`. This allows for two sets of nodes with the same IDs.

In the example given by @maxsumrall , the `Movie` namespace was renamed to `Foo` to illustrate that it is completely separated from the labels. The term `Foo` is only used during import to avoid collisions and to make sure the relationships point to the correct nodes.

Can you explain what it is that you actually need to do? And why naming the ID space to anything you want does not solve it?
