### ISSUE TITLE
Neo4J Community Edition Server different answers on restart!

### ISSUE THREAD

**Issue by Nithanaroy** [neo4j/neo4j#6923]
- Neo4j version: 2.3.3
- Operating system: OS X 10.9.5
- API/Driver: Cypher
- Expected behavior: Consistency is the result is expected on restarting the server
- Actual behavior: Different answers for the same query on restart. Fixes on re-install!
### Steps to reproduce
1. Download data from https://dl.dropboxusercontent.com/u/95923404/georeach.zip. Please note that this graph is created from [Yelp Dataset Challenge](https://www.yelp.com/dataset_challenge)
2. Do a fresh install of Neo4J community edition 2.3.3
3. Start the server
4. Start a shell in terminal using `neo4j-shell`
5. Issue this query, `match (b:Person) return count(b);` and note the result
6. Now quit the shell, stop the server and close the server application
7. Start the server again
8. Issue the same query and note the different result!

Check the screen recording I did - https://dl.dropboxusercontent.com/u/95923404/Neo4JIssueScreenRecording.mov
### Expected behavior

On restarting the server, the result shown in step 5 should be the same. The result we saw the first time we ran in the step 5 is correct. On restarting the server application gives wrong result! Surprisingly it gives the same wrong result every time. To fix it, just reinstall Neo4J Community edition again!
### Actual behavior

On restarting the server application, the result for query shown in step 5 is different.
## Resources

The screenshot below summarizes the issue. The same query issued twice before and after restarting the server application.
![screen shot 2016-04-12 at 11 16 45 am](https://cloud.githubusercontent.com/assets/670556/14470858/93222af6-00a0-11e6-9820-bcf0f09bd3c6.png)

**Comment by jexp** [comment]
Thanks a lot for this superb reporting ! Really helpful.
Could you provide us with the two databases **before** and then **after** the first restart, i.e. when it started to show the different counts.

**Comment by Nithanaroy** [comment]
@jexp Glad it helped. Here you go. Would you mind saving them to a shared location and updating the links for the datasets so that I can delete from my (limited capacity) Dropbox.

After a fresh install (when we see right results): https://dl.dropboxusercontent.com/u/95923404/fresh_on_install.zip
After server application restart (when we start seeing wrong results): https://dl.dropboxusercontent.com/u/95923404/after_restart.zip

**Comment by jexp** [comment]
I got them, you can delete them from your dropbox. Thank YOU !

**Comment by jexp** [comment]
Tried to reproduce it but couldn't:

```
unzip fresh_on_install.zip 
Archive:  fresh_on_install.zip
   creating: georeach/
...

$ ~/Downloads/neo4j-enterprise-2.3.3/bin/neo4j-shell -path georeach/

neo4j-sh (?)$ match (b:Person) return count(b);
+----------+
| count(b) |
+----------+
| 552339   |
+----------+
1 row
3429 ms
neo4j-sh (?)$ quit
$ ~/Downloads/neo4j-enterprise-2.3.3/bin/neo4j-shell -path georeach/

neo4j-sh (?)$ match (b:Person) return count(b);
+----------+
| count(b) |
+----------+
| 552339   |
+----------+
1 row
2537 ms

```

even the after-restart.zip shows the same count ....

```
rm -rf georeach/
$ unzip after_restart.zip 
Archive:  after_restart.zip
   creating: georeach/
...

$ ~/Downloads/neo4j-enterprise-2.3.3/bin/neo4j-shell -path georeach/

neo4j-sh (?)$ match (b:Person) return count(b);
+----------+
| count(b) |
+----------+
| 552339   |
+----------+
1 row
3209 ms
neo4j-sh (?)$ quit

$ ~/Downloads/neo4j-enterprise-2.3.3/bin/neo4j-shell -path georeach/

neo4j-sh (?)$ match (b:Person) return count(b);
+----------+
| count(b) |
+----------+
| 552339   |
+----------+
1 row
2511 ms
```

**Comment by jexp** [comment]
As your shell connects to a running server, are you sure there were not transactions ongoing that added those additional people? An import or some process writing data to it?

**Comment by Nithanaroy** [comment]
I am the only person using the server and I was careful not to open two connections at a time. Also, I see you are using `neo4j-enterprise-2.3.3`, I am working on `/Applications/Neo4j Community Edition.app/Contents/Resources/app/bin/neo4j-shell` and v2.3.3

**Comment by jexp** [comment]
As you only quit shell, the server keeps running, so the results shouldn't change at all.

Did you by chance have a second server running, that the other shell might have connected to?

Can you verify the wrong results in the web-interface?

**Comment by Nithanaroy** [comment]
The results change once I quit the server application, not just the shell. Sorry, if I was unclear before; please check the video screencast attached here (this is the same one used in the original issue).

I made sure that I was running only one server at a time. The surprising part as I mentioned before is that, the incorrect answer is always the same!

Also attached the web interface screenshot. 552339 is the correct answer.

![Web Interface Screenshot](https://cloud.githubusercontent.com/assets/670556/14504439/b3090064-0169-11e6-96d3-7fddc7e04b7d.png)

[Neo4JIssueScreenRecording.zip](https://github.com/neo4j/neo4j/files/217714/Neo4JIssueScreenRecording.zip)

**Comment by maxsumrall** [comment]
Hi @Nithanaroy, I'm trying to figure out what's causing your problem. Thanks for reporting it!

I have found a problem that I am able to repeat locally, but I'd like to see what happens when you do it in your environment and report back. 

Can you do exactly what you did in your last screen recording, but after each time that you issue the query, can you also execute the command `dbinfo -g Kernel`. So that the Kernel info is shown after each restart.

Then outline of the actions to do would then be (edited from your first post):
1. Download data from https://dl.dropboxusercontent.com/u/95923404/georeach.zip. Please note that this graph is created from Yelp Dataset Challenge
2. Do a fresh install of Neo4J community edition 2.3.3
3. Start the server
4. Start a shell in terminal using neo4j-shell
5. Issue this query, match (b:Person) return count(b); and note the result
6. Issue this query, dbinfo -g Kernel and note the result
7. Now quit the shell, stop the server and close the server application
8. Start the server again
9. Issue the same querys and note the different result!

I think there is a problem with the desktop app/packaging and the db path it uses on restart.

**Comment by maxsumrall** [comment]
Hi @Nithanaroy, I hope this has fixed your issue.

Given that you seem to be extensively using Neo4j and other tools, I would recommend using the tarfile of the release rather than the desktop packaging. Here is the link to the [2.3.3 tarfile](http://info.neotechnology.com/download-thanks.html?edition=community&release=2.3.3&flavour=unix&_ga=1.223182491.1012287939.1444921526) 

I'd really like to know the outcome of trying the above actions and whether this is indeed a serious bug or a problem with the Desktop packaging.

**Comment by Nithanaroy** [comment]
@maxsumrall This is a great catch! Yes its a UI bug and not kernel or packaging. Though the UI shows the right directory, it is using the default graph on server restart. You can raise a bug on UI side :) Thanks for helping me.
