### ISSUE TITLE
FOREACH DELETE query is broken on v2.3.3

### ISSUE THREAD

**Issue by s101d1** [neo4j/neo4j#6956]
I just upgraded neo4j from v2.3.1 to v2.3.3, I found out this query doesn't work anymore:

```
match (a:Person {id: "1"})-[r:ACTED_IN]->(m:Movie)
with (case when a.id = "1" then [r] else [] end) as rr
foreach (r in rr | delete r);
```

I got error:
`MatchError: Any (of class org.neo4j.cypher.internal.frontend.v2_3.symbols.AnyType$$anon$1)`

Note: the node data doesn't need to be exist to produce the error.

It seems same thing happened too with neo4j v2.2.x: https://github.com/neo4j/neo4j/issues/6876

**Comment by ehx-v1** [comment]
just looking around whether I can help somewhere out of what I understood, as far as I get it the query is way too complicated, the `case` in `with` will hit `when` upon each node, also instead of building a collection you then use `foreach` on you could directly operate on (in this case `delete`) the relationship in the same query part, all in all it would just be:
`match (:Person {id:"1"})-[r:ACTED_IN]->(:Movie)
delete r`
where r would hit every ACTED_IN relationship from any Person with id property(!) 1 to any Movie
also why I inserted the exclamation mark: there's a difference between `{id: <some_value>}` (searches for a property called id and compares it to the value) and `{#id: <some_value>}` (compares the internal node ID to the value), there is a chance you actually want the second one
EDIT: I think it was `#id`, I'm not sure though, perhaps it's a different prefix

**Comment by s101d1** [comment]
err, it's just an example query to trigger the bug, no logic issue concerned here. 

Here is the more concise way to trigger the bug:

```
match (a)
with (case when null then [a] else [] end) as bb
foreach (b in bb | delete b);
```

**Comment by ehx-v1** [comment]
ah ok but that's a completely different situation, above the case clause condition always evaluates to true, null however evaluates to unknown, which is interpreted as false as far as I get it, so one time you always get a collection with r and one time always an empty collection
EDIT: ahh now I'm getting it, in the initial post you meant the match MUST result in an empty collection, so the collection out of with is empty too
then foreach on empty throws MatchError, which means foreach simply doesn't get along with empty, I think it always tries to find at least one element in the queue, then it's probably rather a contra-intuitive implementation than a bug, because foreach doesn't behave like Java or C++ for each loop but expects at least one element instead

**Comment by s101d1** [comment]
It doesn't matter whether the condition is true or false. And please don't derail the thread.

**Comment by craigtaverner** [comment]
This is a real bug. We have a fix for it which should come out in the next 2.3.x release whenever that will be. Thanks for reporting it. The fix itself can be seen in https://github.com/neo4j/neo4j/pull/6896/commits/1a2001cc1df59511057286180c11a166a4cfd3c2 and affect the RULE planner in 2.2 and above.

**Comment by ehx-v1** [comment]
ok I seem to completely misunderstand this, so this is my last comment on this issue

**Comment by craigtaverner** [comment]
Fixed in https://github.com/neo4j/neo4j/pull/6896
