### ISSUE TITLE
not able to store NAN, minus infinity and positive infinity in a array of double

### ISSUE THREAD

**Issue by MEngher** [neo4j/neo4j#696]
here is the message:
{
  "from": "/node",
  "body": null,
  "status": 400,
  "message": "Invalid JSON array in POST body: {\"NodeId\":\"http://localhost:7474/db/data/node/1\",\"seriesId\":\"M_series_0\",\"Descriptor\":\"time series:M_series_0\",\"OValues\":[0.0,1.0,2.0,3.0,4.0,\"NaN\",\"Infinity\",\"-Infinity\",8.0,9.0,10.0]}"
}

**Comment by cmorgner** [comment]
Hi, I just stumbled upon this issue while porting the Structr Database Driver to the Bolt protocol. Is there any update?

I can store NaN values in a (remote) database using Bolt, but I can not query for them using Cypher..

![nan1](https://cloud.githubusercontent.com/assets/311577/17591916/8120011c-5fe0-11e6-8fdc-1e7dc11027cb.png)
![nan2](https://cloud.githubusercontent.com/assets/311577/17591922/85785b1a-5fe0-11e6-9ed9-6ce363d84ede.png)

**Comment by chrisvest** [comment]
NaN never compares equal to anything, not even itself. What is needed for querying is an `isNaN` function or predicate operator.

/cc @systay

**Comment by mullinger** [comment]
The issue of "infinity" being rendered as null just hit me in a bug that cost me several hours of time:
https://github.com/neo4j-contrib/neo4j-graph-algorithms/issues/256

**Comment by mmeloni** [comment]
I'm using neo4j spatial plugin that uses array(bbox) to rapresents objects in space. I'm also using a library that communicate with batch api rest with neo4j 3.1.4 (neo4j-php-ogm).

I think that is related to this issue.

`curl -X POST -H "Content-Type: application/json" -d '{"method":"PUT","to":"\/node\/47593\/properties","body":{"bbox":[126,-2.08333,126,-2.08333]},"id":8}' 127.0.0.1:7474/db/data/batch
`
`
  "message" : "**Invalid JSON array in POST body**: {\"bbox\":[126,-2.08333,126,-2.08333]
  "exception" : "BatchOperationFailedException",
  "fullname" : "org.neo4j.server.rest.domain.BatchOperationFailedException"
`

**Comment by sherfert** [comment]
I just tried with neo4j 3.5.13 to run the following through the browser:

```
CREATE (n:Test {a: 0.0/0.0, b: 1.0/0.0, c:-1.0/0.0, d:[0.0/0.0, 1.0/0.0, -1.0/0.0]})
MATCH (n:Test) RETURN n
```

There is a text output error in the browser that shows `NaN` as `null` in the tabular view, but otherwise this worked. I reported that error to our browser team.

So it is possible to store `NaN`, and infinities in arrays of doubles, at least in neo4j 3.5.13.
There is no constant for these values, i.e. `Double.NaN`, so one has to resort to `0.0/0.0` or `1.0/0.0`. Also there is no way to query for such values, i.e. no `isNaN` function.

I am going to close this issue, since the original problem has been fixed. Please feel free to open new issues to highlight your interest in getting these constants and the function.
