### ISSUE TITLE
neo4j-shell not recognising read from stdin with option "-file -"

### ISSUE THREAD

**Issue by jimmux** [neo4j/neo4j#7056]
I just updated from v3.0.0-RC1 to v3.0.0, running on Linux Mint 17.3, and one of my convenience scripts broke on a call to neo4j-shell.

After a bit of testing, it seems that the documented `-file -` to pipe from stdin is no longer an option. For example, when I run:

`neo4j-shell -v -file - < foo.cql`

I get error:

`
ERROR (-v for expanded information):
    File to execute does not exist: /path/to/neo4j/-
org.neo4j.shell.ShellException: File to execute does not exist: /path/to/neo4j/-
    at org.neo4j.shell.StartClient.grabPromptOrJustExecuteCommand(StartClient.java:402)
    at org.neo4j.shell.StartClient.startRemote(StartClient.java:364)
    at org.neo4j.shell.StartClient.start(StartClient.java:229)
    at org.neo4j.shell.StartClient.main(StartClient.java:147)
`

This worked on the previous release.

It will work if I drop the -file option completely, e.g.:

`neo4j-shell -v < foo.cql`

so it's easy to work around. If this is a deliberate change, it seems the documentation (--help) needs an update.

**Neo4j Version:** 3.0.0
**Operating System:** Linux Mint 17.3
### Steps to reproduce

Use the neo4j-shell option to read from stdin: `neo4j-shell -file -`
### Expected behavior

Accept input from stdin, don't throw an error.
### Actual behavior

Throws an error

**Comment by spacecowboy** [comment]
Thanks for the report. This was an unintentional change.

**Comment by jotomo** [comment]
@srbaker FYI: The _neo4j-shell_ script [resolves](https://github.com/neo4j/neo4j/blame/0044e527c208211cc9050d663d82cfb2683ccb5f/packaging/standalone/src/main/distribution/shell-scripts/bin/neo4j-shell#L37) the _-_ argument to an absolute path, which then fails in Java code, since the check there looks for just the _-_. (Just passing by, being curious how this broke, since I've contributed the _stdin_ handling bit many moons ago ;-) ).
