### ISSUE TITLE
Can not start neo4j 3.0.0 (brewed) from inside tmux session on Mac OS X

### ISSUE THREAD

**Issue by manonthemat** [neo4j/neo4j#7138]
I discovered, that Neo4j 3.0.0 (brewed version) can not be started from within a tmux session.
- Neo4j version: 3.0.0 (installed via homebrew)
- Operating system: Mac OS X 10.11.4
- tmux version: 2.1
- shell: zsh 5.2 (x86_64-apple-darwin15.0.0)
### Steps to reproduce
1. Open a terminal, install or upgrade neo4j and tmux via homebrew: `brew update && brew install neo4j tmux`
2. Start a tmux session: `tmux`
3. Try to start neo4j: `neo4j start`
### Expected behavior

Neo4j should be successfully started.
### Actual behavior

Neo4j (/usr/local/bin/neo4j) will not start from within a tmux session.
The contents of `/usr/local/Cellar/neo4j/3.0.0/libexec/logs/neo4j.log`:

> nohup: can't detach from console: Inappropriate ioctl for device

`neo4j status` and `neo4j stop` work as expected from inside a tmux session. Starting the service however is not working with this version.

**Comment by chrisvest** [comment]
This is a problem with OS X and tmux, and screen and nohup. There's a long explanation about this weirdness here: https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard

I'm not sure it's possible to fix in our scripts. As a work-around, since you are using tmux, you can dedicate a pane to Neo4j and use `neo4j console`.

**Comment by jonpacker** [comment]
This is causing problems for me in tmux too. In addition, I get the same message if trying to launch neo4j from, for example, node.js. I maintain a small development package that automatically starts/stops/cleans a neo4j database for testing purposes, and I can't get it to work with neo4j 3 because I can't seem to launch neo4j from node. Is there any workaround (apart from `neo4j console`)?
