### ISSUE TITLE
Support file-based parameter input for neo4j-import and neo4j-shell parameters

### ISSUE THREAD

**Issue by jkaster** [neo4j/neo4j#7333]
## Support longer parameter lists for neo4j-import and neo4j-shell

Passing parameters only via the command-line to neo4j-import is limiting and awkward. I want to be able to pass dozens, and possibly hundreds, of CSV files to the import. This will exceed the capabilities of the command-line.

The same request for neo4j-shell is mainly for consistency, but I can see scenarios where it would be just as useful there.

**Neo4j Version:** 3.0.2
**Operating System:** Windows
**API:** `neo4j-import` and `neo4j-shell`
### Suggested usage

Some syntax options for using a parameter file:
`neo4j-import --params params.txt`
`neo4j-import --args params.txt`
`neo4j-import @params.txt`
`neo4j-import < params.txt`

where params.txt would be something like the following. Note that multiple parameters can be specified on the same line or multiple lines (all white space is skipped the same way):

```
--into /data/folder 
--db-config "/config/neo4j.properties" 
--nodes:Endpoint Endpoint_Header.csv,Endpoint.csv --nodes:Registry Registry_Header.csv,Registry.csv
--nodes:Process Process_Header.csv,Process.csv
--relationships:REGISTRYHOST RegistryHost_linkheader.csv,RegistryHost_link.csv --relationships:PROCESSHOST ProcessHost_linkheader.csv,ProcessHost_link.csv
--relationships:PROCESSREGISTRY ProcessRegistry_linkheader.csv,ProcessRegistry_link.csv
```

This is related to #7307

**Comment by benbc** [comment]
Hello @jkaster. Thank you for this suggestion. Can you give us an idea of your use case for this?

**Comment by jkaster** [comment]
On 6/8/2016 10:12 AM, Ben Butler-Cole wrote:

> Hello @jkaster https://github.com/jkaster. Thank you for this 
> suggestion. Can you give us an idea of your use case for this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> https://github.com/neo4j/neo4j/issues/7333#issuecomment-224661547, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AF0TAlHIcgqVvmYJ8E4_5AXFzWtCKZcsks5qJvfogaJpZM4IwG9e.
> 
> I already put it in the request: "I want to be able to pass dozens, and 
> possibly hundreds, of CSV files to the import"

We produce multiple gigabytes of data daily. After extensive 
experimentation and communication with neo4j engineers, we've determined 
the only way to update the graph database in a timely fashion with the 
latest data results is to use neo4j-import. LOAD CSV is too slow for 
updating an existing database in a timely fashion, so we use CSV files 
as our "one true source" and are using the bulk importer to create new 
databases, then switch to those databases when they are complete. We 
have a service that collects the desired CSV files and creates the batch 
command to load them via neo4j-import .. but neo4j-import is too limited 
in the length of the parameters it can take via the command line.

**Comment by benbc** [comment]
Thanks @jkaster, that's helpful. We'll look into this, but I can't give you a date for when it's likely to be implemented.

**Comment by tinwelint** [comment]
As seen in https://neo4j.com/docs/operations-manual/3.4/tools/import/options/ this is now supported for the `neo4j-admin import` (even the deprecated `neo4j-import` surface). The `neo4j-shell` (also deprecated in favor of the cypher shell) has a `--file` argument for a similar feature.

**Comment by praveenag** [comment]
We haven't added this option to cypher-shell because it does not have a similar usecase. cypher-shell does not take a lot of parameters wherein it would make sense to accept parameters from a file.

**Comment by stuarteberg** [comment]
In his message [above](https://github.com/neo4j/neo4j/issues/7333#issuecomment-391655045), @tinwelint pointed out that in neo4j 3.4, the admin tool offers the `--f` option, which allows all arguments to be passed via file instead of the command line.

But the `--f` option seems to have been dropped in neo4j v4 and v5.  Is that correct?  Has it been renamed or superseded by a different option?

---

### My use case:

We use neo4j to represent synaptic connections in the brain of a small animal.  There are hundreds of millions of them, and each one has a handful of properties.

Unfortunately, the exact property names for each synapse can vary.  Therefore, if I were to include them all in a single file, the file would have MANY columns, but on any given row most of the columns would be empty.  This would lead to a single very large CSV file that was mostly empty.  Those columns might be mostly empty, but they still slow down the neo4j ingestion -- prohibitively so.

Instead of doing that, I can generate a _sequence_ of CSV files, with rows grouped according to their non-empty columns (properties). The advantage of that approach is that it requires fewer CSV items to be processed overall.  The disadvantage is that it requires many files -- so many that the shell script fails with `Argument list too long`.

**Comment by tinwelint** [comment]
@stuarteberg in neo4j v4 and v5 the CLI tools make use of PicoCLI, which has this built-in, i.e. all commands supports this. What you do is e.g.

`neo4j-admin database import @/path/to/my-args.txt`

which contains all arguments. You can even have multiple arg files I think. See more at https://picocli.info/#AtFiles

**Comment by stuarteberg** [comment]
@tinwelint Just to follow up: Thank you!  That made my day.  Using the syntax you showed, I'm able to load all of my data.  Without that feature, I was unable to do so.
