### ISSUE TITLE
Expose socket timeouts for .NET Bolt driver

### ISSUE THREAD

**Issue by OlivierLebra** [neo4j/neo4j#7344]
Please provide a way to set hard timeouts to the sockets used by the Neo4j .NET Bolt driver.

**Comment by zhenlineo** [comment]
Could you explain more on this card. 

Do you want to generally let the server to kill driver socket connections after a certain Idle time? Or do you want .NET driver to terminate the connection with the server after certain idle timeout? 

If it is a .NET driver specific request, then I would suggest for further questions, it is faster if you make the issue under [.NET driver repo](https://github.com/neo4j/neo4j-dotnet-driver)

Besides all above, why do you want to timeout the connection? Could you give me a usecase?
Thanks in advance.

**Comment by OlivierLebra** [comment]
I want the equivalent of HTTP clients' connection timeout (maximum time that you allow the connection to the server to take) and operation timeouts (maximum time that you allow the whole operation to take). Needed in case the network is slow or unreachable, or the server request is slow, that would cause the client to hang.

**Comment by lutovich** [comment]
Hi @didlybom,

Sorry for the late follow-up on this issue! I'd like to clarify couple things.

Do you suggest to make following two timeouts configurable:
1) socket connection timeout. i.e. smth like `socket.connect(<configured_timeout>)`
2) socket receive timeout. i.e. https://msdn.microsoft.com/en-us/library/system.net.sockets.socket.receivetimeout(v=vs.110).aspx

?

I'm just a bit unsure what "operation timeouts" means. Is this max query or transaction time? If so you could use `dbms.transaction.timeout` in combination with `dbms.lock.acquisition.timeout` Neo4j database settings since 3.1.0 to limit execution time.

**Comment by OlivierLebra** [comment]
@lutovich, yes, 1. and 2. exactly like you said. I needed a client side timeout, so that if for any reason the server is abnormally slow or not responding, the client would time out. dbms.*.timeout settings would ensure the server cannot hold a connection forever because of neo4j, but let's say something else than neo4j brings the server to a crawl, the client needs the ability to time out.

**Comment by lutovich** [comment]
@didlybom makes sense. I'll create cards for us to add these timeouts. We'll keep this issue open and updated. Thanks for your input!

**Comment by lutovich** [comment]
Hi @didlybom, here is a PR for connection timeout: https://github.com/neo4j/neo4j-dotnet-driver/pull/134

**Comment by zhenlineo** [comment]
Hi @didlybom We have release 1.1.0-rc1 on .net driver which includes the connection timeout.

**Comment by MinhNguyenDev** [comment]
Hi guys, if I'm not mistaken, we have the feature to allow connection timeout but not query time out, is that correct ? I need the client to time out when running a slow query i.e more than 5 seconds, something like:
using (var session = Driver.Session(TimeSpan.FromSeconds(5))) (Set the time out so any RunAsync, ToListAsync function would time out after 5 seconds)

Please let me know if it's possible, thanks a lot ?

**Comment by zhenlineo** [comment]
We've added connection acquisition timeout, connection life timeout to address this problem. Pls update to the latest .net driver to use these features. More information can be find in neo4j documentations.

@MinhNguyenDev We've have tx timeout on the server side. also you can config this on the driver side since 1.7 driver series too.
