### ISSUE TITLE
Methods needing transactions should be more cleanly documented

### ISSUE THREAD

**Issue by ehx-v1** [neo4j/neo4j#7381]
This is basically a combination of a question and a related documentation request.
In the GraphDatabaseService class, it is stated that all the methods require a transactional environment. However, I know that e.g. `shutdown()` doesn't need one. There are other methods, like `index()` or `traversalDescription()` where I have no idea whether they need a transaction or not, because both would make sense.
Additionally, there is no clue about whether a transactional context is needed for any methods of Node or Relationship. Personally I see this as a substantial gap in the documentation. Besides being personally interested in which methods need a transactional environment, and especially for which methods an auto-commit styled environment (which is what I'm setting up) would make sense, I would like this to be more clearly documented, especially the Node/Relationship part which lacks any documentation about this.

**Comment by mariascharin** [comment]
This issue was raised two and a half years ago so I will assume the question is outdated. Apologies for this. 

In any case, here is the answer I've got for the functionality in the upcoming release: 
In 4.0 the API for the database service and transaction is changed in a way that all methods that require transaction are actually invoked on the transaction object itself. All methods that are left are transaction independent.
