### ISSUE TITLE
Make "neo4j start" message more useful 

### ISSUE THREAD

**Issue by mjmare** [neo4j/neo4j#7522]
Currently (neo4j 3.0.2 community) says something like this on startup:

> Starting Neo4j.
> Started neo4j (pid 1156). By default, it is available at http://localhost:7474/
> There may be a short delay until the server is ready.
> See /Users/mjm/Dropbox/Devel/_Experiments/Neo4j/neo4j-community-3.0.2/logs/neo4j.log for current status.

Why not mention the _actual_ port instead of the default one? Even better, mention all ports: http, https, bolt. 
Also it might also be helpful getting a message when the server is actually available, instead of "There may be a short delay".

All this might be helpful when troubleshooting and also when one fires up more than one neo4j instance. 

TIA

**Comment by zhenlineo** [comment]
This could be an improvement to the usability of our product. However I think there is no reliable way to know when the server will be available. The only way to know is to continuously ping the port until a connection can be established. We've discussed this before and decided that it is an application concern to perform this ping rather than the database server itself. 

For printing the real ports, it should be straightforward to read from config file and print it here. It looks like that we've already reading the log location from the config files, so it shall be easy(?) to support reading other configs too. But note the changes need both in our linux and windows start up script.

**Comment by technige** [comment]
As per @zhenlineo's reply, I'm closing this as a _wontfix_. While the output could arguably be improved in places, this particular script is not intended to provide structured output for consumption by another process, nor is it intended to block until the server - or indeed the entire cluster - is ready (for some definition of "ready"). In many real-world cases, this script actually executes as part of a startup sequence.

For testing and development, the recommendation is to construct a test harness that repeatedly polls the relevant socket addresses until a connection can be made.

**Comment by mjmare** [comment]
My point was not to indicate that the server is available for connections but that the port mentioned (7474) may not the actual port when changed in the config. So IMO it would be nicer to (new) users to indicate the actual port used (helpful diagnostics) or mention more clearly that the port might have been changed in the config. 

Just like the helpful "There may be a short delay until the server is ready." message. Not strictly necessary but nice.
