### ISSUE TITLE
[Feature Request] When importing, generate ".bad" file, regardless of --bad-tolerance value

### ISSUE THREAD

**Issue by cosimosimeoneTR** [neo4j/neo4j#7575]
Produce a file with raw content of **all** rows rejected in the import process.

Please read
https://docs.oracle.com/cd/B19306_01/server.102/b14215/ldr_concepts.htm#i1004846

At the moment, neo4j produces `not-imported.bad` just when _one and only one_ row fails.
https://neo4j.com/docs/operations-manual/current/
or (with default --bad-tolerance) just logs in `debug.log` the 1001th row with error, all previous rows are just counted, not detailed.

**Comment by spacecowboy** [comment]
Sounds like a reasonable feature request

**Comment by cosimosimeoneTR** [comment]
Any prevision on how/when/if you are going to implement this? :-)

**Comment by spacecowboy** [comment]
Not really :(

**Comment by cosimosimeoneTR** [comment]
Uhm.. Ok.
Shall i leave this tkt open as a placeholder/reminder, or you want me to close it?

**Comment by spacecowboy** [comment]
Please leave it open, we should be able to get to it at some point

**Comment by tinwelint** [comment]
In 3.5 there are two surfaces of the importer:

- the deprecated `neo4j-import` surface where by default the `--bad-tolerance` is 1000. The first 1000 bad entries will be logged and the 1001th will fail the import. Bad logging can be skipped completely with `--skip-bad-entries-logging`.
- the `neo4j-admin import` surface where by default it fails on first bad entry, but if configuring it to not fail on bad entries it will log those into `import.report`.

I don't think it works how you suggest, that it logs only one row and then nothing else, or the "last" row. Perhaps it used to do that, but not since at least 3.4 or so. In short, all bad entries that are skipped _are_ logged, unless explicitly configured to not do that.
