### ISSUE TITLE
Unexpected attempt to cast to GraphDatabaseAPI on GlobalGraphOperations

### ISSUE THREAD

**Issue by ehx-v1** [neo4j/neo4j#7635]
Steps to reproduce:
1. Make a graph database class **directly** implementing `GraphDatabaseService`.
2. Try to run `GlobalGraphOperations` on it.
Expected behavior: Works.
Actual behavior: Fails with `ClassCastException` after... trying to cast to `GraphDatabaseAPI`???

Further background: I have some wrapper graph databases in my library built upon Neo4j (not yet in a publishable state). These inherit from an abstract `GraphDatabaseWrapper` class that directly implements `GraphDatabaseService`. You will most probably agree that, for wrapper databases, the standard `GraphDatabaseFacadeFactory` way makes little sense. However, `GlobalGraphOperations` seems to assume that all `GraphDatabaseService` classes are built this way...

I'm trying to fix this particular case, but you should still think about whether the assumption makes sense in general, especially given that, from all I found, it's not even documented.

**Comment by chrisvest** [comment]
`GlobalGraphOperations` expects to get the "real" `GraphDatabaseService` implementation. It needs to access database internals. Your custom wrappers are not supported. `GraphDatabaseFacadeFactory` is also internal API, so using that is also not supported.

You can upgrade to 3.0 where `GGO` is gone and its methods have moved to the `GDS` interface, making it easy for you to wrap. Or you can continue using internal APIs and implement `GraphDatabaseAPI` instead of `GDS`, but be aware that our internal APIs can change in incompatible ways between releases.

**Comment by ehx-v1** [comment]
I'll set off a PR anyway, in terms of wrapper interaction, so in 2.3 this will clean out up to some point. As for FacadeFactory, making custom FacadeFactories is the official way according to the Javadoc, that's why I mentioned it.

**Comment by ehx-v1** [comment]
Also, I already managed to work around this, but it's always the same pattern, reducing wrappers to the wrapped databases until there are none. That's why I'll try to include this scheme in Neo4j 2.3 - at least if I make it to clone the repo past the proxy.

**Comment by ehx-v1** [comment]
You know what, I think this fix doesn't need a related issue.

**Comment by chrisvest** [comment]
> making custom FacadeFactories is the official way according to the Javadoc

Can you point me to where the javadocs say this?

**Comment by ehx-v1** [comment]
Documentation of `GraphDatabaseFacade`.

> To make a custom `GraphDatabaseFacade`, the best option is to subclass an existing `GraphDatabaseFacadeFactory`.

Not being marked as deprecated, it makes me assume that `GraphDatabaseFacade` is not internal, as all internal stuff seems to be marked as deprecated in Neo4j.

**Comment by tkroman** [comment]
> all internal stuff seems to be marked as deprecated in Neo4j

No, it does not.

FWIW:
There was a time when I thought that I should try and make my own `GDS`/whatever implementation, but that time is long gone and I would suggest you to review your options, since I'm 99% sure that a single person couldn't tweak the database consistently and in such a fashion that nothing falls apart. No, really. I give you 99% that you'll later admit that you wasted your time if you'll chose to go down that road.

**Comment by chrisvest** [comment]
Sorry, but `GraphDatabaseFacade` is not in our published javadocs: https://neo4j.com/docs/2.3.6/javadocs/ – that means it's not part of our public API.
