### ISSUE TITLE
Allow REDUCE to work with maps

### ISSUE THREAD

**Issue by rickardoberg** [neo4j/neo4j#7764]
I would like Cypher REDUCE to work with a map as an accumulator. As input I have a list of tuples (key,value) which I want to convert into a map.

Something like this:
REDUCE(map={}, row IN coll | SET map[row.key]=row.value)

**Comment by jexp** [comment]
I'd prefer 

```
REDUCE(map={}, row IN coll | map + { (row.key) : row.value})
```

**Comment by swayam18** [comment]
any updates on this issue?

**Comment by freeeve** [comment]
apoc helps these days:

```
with [{a:1, x:'y'}, {b:2, y:'z'}] as coll
return reduce(acc={}, x in coll | apoc.map.merge(acc, x))
```

**Comment by sherfert** [comment]
Reduce works with any accumulator, what is missing from Cypher is a way to to merge maps. For this I refer to this feature request: https://github.com/neo4j/neo4j/issues/4470

But, since [APOC](https://neo4j-contrib.github.io/neo4j-apoc-procedures/#map-functions) already provides such functions:

apoc.map.merge(base, patch)
apoc.map.updateTree(tree, key, value)

we currently don't consider adding these functions into Neo4j.
