### ISSUE TITLE
Node by Id seek not called as expected

### ISSUE THREAD

**Issue by adi** [neo4j/neo4j#7933]
**Neo4j Version:** 3.0.4
**Operating System:** Any
### Steps to reproduce
1. Create a node with label Test and return its id
2. Run 'profile match (m:Test) where id(m)=15 return m;' where you replace 15 by your returned id
### Expected behaviour

According to http://neo4j.com/docs/stable/execution-plans-starting-query.html#query-plan-directed-relationship-by-id-seek the method called should always be a seek by id
### Actual behaviour

If the number of Test labeled nodes is low (under 15) the method called is a full scan by the Test label while when is high (over 14) the method called is a seek by id

**Comment by spacecowboy** [comment]
Thanks for the report.

@systay do you consider this a bug?

**Comment by Mats-SX** [comment]
Hello @adi and thanks for reaching out to us.

The documentation you are referring to is old; it's the 2.3 manual. The corresponding section in the 3.0 Developer Manual is found here: http://neo4j.com/docs/developer-manual/current/cypher/#match-node-by-id

The constants with which the cost planner estimates which planning operators to use are updated regularly as the kernel changes. Due to the nature of cost estimation, the behaviour of the planner is not always deterministic, and that's why you're seeing some variance here. There's also our legacy `rule` planner which you can invoke by prepending your query like so:

```
CYPHER planner=rule
MATCH (m:Test) 
  WHERE id(m) = ... 
RETURN m
```

This will give you deterministic planning, but is generally not as good as the default cost planner.

To conclude, it _is_ expected that the `NodeByIdSeek` is chosen only after a certain number of nodes with the given label has been created (thus increasing the cardinality and cost of the `NodeByLabelScan`).

All the best
Mats
