### ISSUE TITLE
Neo4j hard crashes when out of memory

### ISSUE THREAD

**Issue by rationalism** [neo4j/neo4j#7984]
- Neo4j version: 3.0.5 Enterprise
- Operating system: Ubuntu 14.04.4 LTS
- API/Driver: neo4j-java-driver 1.0.5

I'm not really sure what caused this, other than just running high QPS on a mid-range machine, since Neo4j's debug.log has no errors, warnings or diagnostic information at the time of the crash. The system logging daemon returned this much:

OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fbed2674000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fbec4237000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00007fbec4136000, 12288, 0) failed; error='Cannot allocate memory' (errno=12)
[4417076.751195] init: neo4j main process (19281) terminated with status 1
[4417076.751213] init: neo4j main process ended, respawning

If it helps, here's some information about the memory settings from debug.log during Neo4j startup:

https://gist.github.com/rationalism/c489a1d8e6151e387f216c13b769f2e5

**Comment by chrisvest** [comment]
Your computer is too starved for memory to be able to allocate enough for our Java process. Since you say Neo4j crashed, you might find something about the oom-killer attacking a Java process in your `dmesg` log.

Also note this:

```
[o.n.k.i.DiagnosticsManager] Total Physical memory: 7.80 GB
[o.n.k.i.DiagnosticsManager] Free Physical memory: 2.42 GB
```

When Neo4j starts up, your system has only 2.42 GiB of memory available. That's not a lot. And Java expects that it can grab 1.95 GiB for the heap, but the heap is not all that we'll allocate.

I suggest you look into what's using up all the memory on the machine, and free some up. Or configure a much smaller heap. Also explicitly configure the page cache size, instead of relying on heuristics. They don't work so well when the system isn't dedicated entirely to running Neo4j.

I'm closing this. Feel free to reopen if you still feel their's a problem with Neo4j.
