### ISSUE TITLE
Request - Noe4j Master-Slave in CE?

### ISSUE THREAD

**Issue by sd2302** [neo4j/neo4j#8248]
Hi Community,
Is it possible to request Master-Slave replication feature in the Community Edition?

We understand Master Slave replication is available only in paid Enterprise Edition from Neo4j.com

**Comment by prathle** [comment]
Hi @sd2302. If you're using Neo4j in a free open source application, whose source code you plan to contribute to the OSS community, then you can use Neo4j Enterprise Edition under the APGL v3 as outlined here https://neo4j.com/licensing/ (look towards the bottom under "Neo4j Loves Open Source"). 

If you are building a closed-source application, then you can always license Neo4j Enterprise. Depending on what you are doing, you may qualify for a other ways to use Neo4j Enterprise without a financial or free open source commitment. One is the Startup Program, where qualifying startups can use Neo4j Enterprise without paying, even if their software is closed source. The link posted above includes a list of the different options.

As to the reasoning behind all of this... Neo4j (both Community & Enterprise Editions) gets designed/built/tested by a large team of full-time salaried employees. We love offering code up to the world, and supporting others who share that mission. We also love that people find value in using Neo4j Enterprise with closed-source applications, because that provides the funds for the project to improve & evolve. We call this philosophy "fair trade". Community Edition has few strings attached. Enterprise Edition takes lots of extra effort to build & maintain (not that Community Edition doesn't!) And so excluding special cases like startups who are trying to get off the ground, we offer it up in exchange for either making the world a better place by contributing your application code (tit for tat), or signing up for a commercial subscription, which includes not just access to the Enterprise Edition, but commercial support and a variety of services in relation to support (consulting, training, etc).

I hope that helps!
