### ISSUE TITLE
Counts are too slow when they include relations

### ISSUE THREAD

**Issue by mvinas1977** [neo4j/neo4j#8544]
I have a db with the following nodes

3 Companies
2201139 Employees

If I do

MATCH (n:Employee) WHERE n.administrative = true RETURN COUNT(*) AS Count

It is slow but acceptable it takes 700ms to respond

But if I include the relationship to company it takes 6.5s to respond, I tried several queries and all are taking about same time. I have indexes for both Company.name and Employee.administrative

MATCH (n:Employee) WHERE n.administrative = true WITH n AS n MATCH (n)-[r1:company]->(n1:Employee) WHERE n1.name IN ['companyA', 'companyB'] WITH n AS n, n1 AS n1, r1 AS r1 RETURN COUNT(*) AS Count

MATCH (n1:Company) WHERE n1.name IN ['companyA', 'companyB']  WITH n1 as n1 MATCH (n1)<-[r1:company]-(n:Employee) WHERE n.administrative = true WITH n AS n, n1 AS n1, r1 AS r1 RETURN COUNT(*) AS Count

MATCH (n1:Company)<-[r1:company]-(n:Employee) WHERE n1.name IN ['companyA', 'companyB'] AND n.administrative = true RETURN COUNT(*) AS Count

**Comment by mvinas1977** [comment]
I have a db with the following nodes

3             Companies
2201139 Employees

If I do 

MATCH (n:`Employee`) WHERE n.`administrative` = true RETURN COUNT(*) AS `Count` 

It is slow but acceptable it takes 700ms to respond

But if I include the relationship to company it takes 6.5s to respond, I tried several queries and all are taking about same time. I have indexes for both Company.name and Employee.administrative


MATCH (n:`Employee`) WHERE n.`administrative` = true WITH n AS n MATCH (n)-[r1:company]->(n1:`Employee`) WHERE n1.`name` IN ['companyA', 'companyB'] WITH n AS n, n1 AS n1, r1 AS r1 RETURN COUNT(*) AS `Count`

MATCH (n1:`Company`) WHERE n1.`name` IN ['companyA', 'companyB']  WITH n1 as n1 MATCH (n1)<-[r1:company]-(n:`Employee`) WHERE n.`administrative` = true WITH n AS n, n1 AS n1, r1 AS r1 RETURN COUNT(*) AS `Count`

MATCH (n1:`Company`)<-[r1:company]-(n:`Employee`) WHERE n1.`name` IN ['companyA', 'companyB'] AND n.`administrative` = true RETURN COUNT(*) AS `Count`

**Comment by chrisvest** [comment]
What version of Neo4j are you using, and what do the explain plans look like for the various queries?

**Comment by mvinas1977** [comment]
I'm using neo4j 3.1.0

![captura de pantalla de 2016-12-23 12-24-20](https://cloud.githubusercontent.com/assets/22802651/21457027/df65030e-c934-11e6-9824-d87816a28a29.png)
![captura de pantalla de 2016-12-23 12-24-43](https://cloud.githubusercontent.com/assets/22802651/21457025/df63a8ec-c934-11e6-830f-b393a411cedc.png)
![captura de pantalla de 2016-12-23 12-25-18](https://cloud.githubusercontent.com/assets/22802651/21457026/df645724-c934-11e6-8fb3-34a0ed39991c.png)

**Comment by craigtaverner** [comment]
This looks like an issue with the data model. Or to put it another way, with this model the query will hit about 50% of the node records and 50% of the relationship records (assuming administrative=true/false is evenly split). If we had a `PROFILE` instead of `EXPLAIN` we could see better if that is the case.

So if you want to optimize a query that asks something about 50% of the data you need to think about re-structuring the model to hit less data. There are many options, and I suggest two here:

* A non-graph option is to save this as property fields on Employee and index them (so for pre-3.2 make a property called admin_company with values like 'true-CompanyA'. Then your query would be something like `MATCH (n:Employee) WHERE n.admin_company IN ['true-CompanyA','true-CompanyB'] RETURN count(*)`. This should hit the index only and be much faster (two index queries).
* A graph option is to create an intermediate node so you have something like (:Company)<-[:IN]-(:Role)<-[:HAS]-(:Employee). A query like `MATCH (c:Company)<-[:IN]-(r:Role)<-[e:HAS]-() WHERE c.name in ['CompanyA','CompanyB'] AND r.admin = true RETURN count(e)` should do two very fast index lookups on Company (or LabelScan+Filter since there are only 3 companies), a fast Expand to the Roles (very few relationships) and a fast filter of the few roles, and finally the expensive part will be cheap because you are essentially asking for the degree of the incoming :HAS relationships, which is optimized in recent versions of Neo4j.

**Comment by craigtaverner** [comment]
I decided to try this out myself, using something like the graphy solution I proposed in the previous comment. First I made a model like yours be repeating the following query 3 times to make about 900k employees in 3 companies:

```
UNWIND ['A','B','C'] as suffix WITH suffix
MERGE (c:Company {name:'Company'+suffix}) WITH c, suffix
UNWIND Range(0,100000) as i WITH i, CASE i%2 WHEN 0 THEN true ELSE false END as admin, c, suffix
CREATE (e:Employee {name: 'Employee-'+suffix+'-'+i, administrative: admin})
CREATE (e)-[:company]->(c)
RETURN count(e)
```
Then I ran the following query:

```
PROFILE MATCH (n1:Company) WHERE n1.name IN ['CompanyA', 'CompanyB'] MATCH (n1)<-[r1:company]-(n:Employee) WHERE n.administrative = true RETURN count(*) As Count
```

It took about 600ms returned a count of 300k and a profile showing it hit 600k records from the relationship store. This reflects the slow performance you report. It is only faster than your case because I have a smaller model, of 900k employees instead of 2M.

Now to refactor the model to enable a much faster query, I want to make the intermediate node `:Role`:

```
MATCH (c:Company)<-[r:company]-(e:Employee) WITH c, r, e LIMIT 100000 DELETE r with c, e MERGE (c)<-[:IN]-(role:Role {administrative:e.administrative}) WITH c, e, role MERGE (e)-[:HAS]->(role) RETURN count (e)
```
This query refactors 100k of the employees onto the new model, deleting the old `:company` relationships and creating the new `:Role` intermediate node. This is a little like making a join table in SQL. The reason I only do 100k, not the entire 900k is that this query is eager and can take a lot of memory, so I simply repeat this query 10 times and all the graph will be refactored. This took a little time, and in fact there are probably ways to optimise this (including build the model from scratch). But for the purpose of this answer, this is good enough.

So, how much faster is the new model for counting the stats you want? I decided to write a new query that gives you the number you want, plus a few more (in effect giving you counts for all combinations of company and administrative true/false). In the old model that would touch every node and relationship in the graph, making it very slow. In the new model we can get an answer from touching only 9 nodes and 6 relationships like this:

```
MATCH (c:Company)<-[:IN]-(r:Role) RETURN c.name, r.administrative, size((r)<-[:HAS]-())
```

This time the query took less than a millisecond to produce the table:

```
╒══════════╤══════════════════╤══════════════════════╕
│"c.name"  │"r.administrative"│"size((r)<-[:HAS]-())"│
╞══════════╪══════════════════╪══════════════════════╡
│"CompanyA"│false             │150000                │
├──────────┼──────────────────┼──────────────────────┤
│"CompanyA"│true              │150003                │
├──────────┼──────────────────┼──────────────────────┤
│"CompanyB"│false             │150000                │
├──────────┼──────────────────┼──────────────────────┤
│"CompanyB"│true              │150003                │
├──────────┼──────────────────┼──────────────────────┤
│"CompanyC"│false             │150000                │
├──────────┼──────────────────┼──────────────────────┤
│"CompanyC"│true              │150003                │
└──────────┴──────────────────┴──────────────────────┘
```

This is very much faster than the original 600ms, at least 600x faster.

**Comment by craigtaverner** [comment]
I believe the answers above satisfy the original question, so I will close this issue. If you feel they do not, please reopen it with a clarification of what more you would like answers to.
