### ISSUE TITLE
Any scale out solution?

### ISSUE THREAD

**Issue by mqliang** [neo4j/neo4j#8773]
Read the document the neo4j, it seems neo4j only support matsre-slave cluster?

 In our use case, we need a  graph DB to store all HTTP call chain in a cluster, in other words, the relationship of two nodes a list of historical HTTP call information (url, header, code, etc) as properties. Since HTTP call is frequent, relationship properties will grow over time and becomes really huge eventually. 

Hence, we need a scale out solution, for example, is it possible config neo4j using HBase as an alternative storage backend, or is neo4j itself horizonal scalable?

**Comment by spacecowboy** [comment]
@mqliang if I understand your question correctly, you are asking if neo4j supports sharding?

The answer is no, and no we do not support any other storage backends.

That said, people often think they need sharding when they don't. Almost no one has a graph big enough to warrant it (because neo4j is fast). So I'd recommend you give it a try anyway.
