### ISSUE TITLE
1) .Net graphical result of a queries, 2) graphical CRUD functionality

### ISSUE THREAD

**Issue by mhelal** [neo4j/neo4j#8852]
Hi, 

I am wondering if there are any code (APIs) or packages that perform these two functionalities already in .Net C# Visual Studio project:

1) the same graphical query result I see in the 7474 port browser, can I have it displayed in a windows C# form?

2) Is there any C# code that enable graphical CRUD functions (create, read, update and delete), such that you can right click a node or an edge to edit/delete/add to its labels and properties? have a toolbox from which you can drag a node or an edge to add to the existing database, or create an edge by selecting two nodes or dragging from one to the other? 

I appreciate if you can reply with options that can save me from re-inventing the wheel

thank you very much, 

Manal

**Comment by jexp** [comment]
From @cskardon

I don't know of any off hand, 

1) If it's a WinForms/WPF project I would hunt out a control to see if someone has done it already - quickly something like http://www.yworks.com/products/yfiles-net seems to cover it - but the I think it's probably not cheap. You could render d3.js in a browser control I guess, which would be the same as the browser, but would make (2) tricky. There might be other controls, but I've not found anything that looks similar.

2) This kind of goes hand in hand with (1) - If the control displaying a node has a decent set of events/commands and can pass that data on to a backend - I see no reason you wouldn't be able to do it, but you're always going to have to roll-your-own for this - 

Otherwise feel free to join neo4j.com/slack for more discussion as this here is an issue tracker
