### ISSUE TITLE
Properties() function is not present on cypher refcard

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j#8946]
The [cypher refcard](http://neo4j.com/docs/cypher-refcard/current/) has no references to the `properties()` function. From glancing through refcards from earlier versions, I don't think it's ever been included.

**Comment by petraselmer** [comment]
In the interests of keeping the Cypher refcard short and succinct, ideally, the refcard only contains a subset of the functions present in Cypher, rather than exhaustively listing everything. 

However, I think `properties()` absolutely ought to be included, as it is a very useful function. So, thanks for bringing this to our attention - I will ensure it gets added very soon.

**Comment by petraselmer** [comment]
I have added a commit - to be merged very soon - addressing this [here](https://github.com/neo4j/neo4j-documentation/pull/33/commits/b745dcf1c686a05d741f8ec8d2d715d37ebaa287) as part of this [PR](https://github.com/neo4j/neo4j-documentation/pull/33)
