### ISSUE TITLE
Security hole - browser indefinitely remains authenticated

### ISSUE THREAD

**Issue by benstevens48** [neo4j/neo4j#9278]
I have tried adding these two lines to my neo4j.conf file:
```
browser.credential_timeout=7200s
browser.retain_connection_credentials=false
```
I subsequently restated the neo4j service and also completely cleared my browser cache. I then logged in to the Neo4j browser. However, I am still authenticated several weeks later having shut down my PC many times during that period. 

So it seems like these settings are not working. This results is quite a big security hole since once someone has logged into the browser they remain authenticated on that web browser/device for ever. I've asked for help on StackOverflow but no-one could suggest anything, so I assume this is a bug. Also, any workarounds to improve security would be appreciated.

**Neo4j Version:** 3.1.3 Community
**Operating System:** Ubuntu 16.04  
**API:** Browser

### Steps to reproduce
Add these two lines to neo4j.conf:
```
browser.credential_timeout=7200s
browser.retain_connection_credentials=false
```

### Expected behavior
Browser authentication should at least time out after 7200s of inactivity. I assume also `browser.retain_connection_credentials=false` should prevent it from remaining authenticated across multiple sessions.

### Actual behavior
Browser remains authenticated.

In case it makes any difference (I'm not sure why it should) I am running Neo4j behind an nginx proxy and have ticked 'do not use bolt' in the browser settings.

**Comment by klaren** [comment]
It's not stated in the documentation but the following settings is only part of the enterprise edition:
```
browser.credential_timeout
browser.retain_connection_credentials
browser.remote_content_hostname_whitelist
browser.allow_outgoing_connections
```

Credentials are stored in the browser's local storage, not considered to be part of the cache. So in order to clear them, you would need to find out how to clear the local storage of your browser. In Chrome, you can open the DevTools console, `Ctrl+Shift+J` (Windows / Linux) or `Cmd+Opt+J` (Mac), and type `localStorage.removeItem("neo4j.connections")` in the console to clear that particular login. It can be saved as a bookmarklet as well so you don't need to remember it.

Thanks for reporting! Documentation will be updated accordingly.

Feel free to reopen if you have additional questions.

**Comment by benstevens48** [comment]
Ok, thanks for updating the docs. 

Unfortunately at the moment whilst our editing and visualisation interface is being developed I need to give access to the Neo4j browser to some semi-technical team members, so the interface is currently available over the internet. This is not ideal. I was hoping to be able to time out credentials in case people log in via someone else's PC to demo it or they leave their device lying around something.

As a workaround, perhaps I can change the username every so often...
