### ISSUE TITLE
Unable to use multiple index hints in 3.2

### ISSUE THREAD

**Issue by InverseFalcon** [neo4j/neo4j#9435]
In Neo4j 3.1.x versions, I could use multiple index hints to match on both starting and end nodes, then perform match operations between them. This automatically changed the query planner to RULE.

In Neo4j 3.2, since the RULE planner has been removed, this approach is no longer possible, and errors out.

This example on the :Movies graph demonstrates a query that works on 3.1.x, but fails with error in 3.2:

```
match (k:Person {name: 'Keanu Reeves'}), (t:Person {name: 'Hugo Weaving'}) 
using index k:Person(name)
using index t:Person(name)
match p=(k)-[:ACTED_IN*0..5]-(t)
RETURN count(p)
```

Error is:

```
ERROR Neo.DatabaseError.Statement.ExecutionFailed
Failed to fulfil the hints of the query.
Could not solve these hints: `USING INDEX t:Person(name)
```

**Comment by systay** [comment]
Hi @InverseFalcon,

Thanks for reporting this. Fixing this in the cost planner is too risky in a patch release, so this is not something we will add support for in the Neo4j 3.2.x series. Instead, this will be fixed in Neo4j 3.3 (https://github.com/neo4j/neo4j/pull/9462).

For this particular problem, the workaround is to specifically ask for the rule planner, by prepending your query with `CYPHER planner=rule match...`
