### ISSUE TITLE
neo4j.connections.default

### ISSUE THREAD

**Issue by rmfwebmaster** [neo4j/neo4j#9675]
$ php bin/console
PHP Fatal error:  Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "schema" under "neo4j.connections.default" in /var/www/html/movies-symfony-php-bolt/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php:317

**Comment by eebus** [comment]
@rmfwebmaster 
I quite unsure what the problem seems to be could you submit a bit more information?

- Neo4j version: X.Y.Z
- Operating system: (for example Windows 95/Ubuntu 16.04)
- API/Driver: (for example Cypher/Java API/Python driver vX.Y.Z)
- **Steps to reproduce**
- Expected behavior
- Actual behavior

**Comment by angelov** [comment]
@rmfwebmaster if you use `neo4j/neo4j-bundle` v0.3+ you should change the `schema` key under `neo4j.connections.default` in your configuration to `scheme`. Check [this](https://github.com/neo4j-contrib/neo4j-symfony/pull/23).
